### ISSUE TITLE
RfE: Would like to get a direct link to a Toot

### ISSUE THREAD

**Issue by ascheman** [tootsuite/mastodon#8267] opened 2018-08-18 09:39 UTC
I would like to get a copy to the link location directly in the "..." lower right corner menu. There is already the "embed" item:
![image](https://user-images.githubusercontent.com/456000/44297995-383f2500-a2db-11e8-9f2a-e153a8aea270.png)

I can copy the link to the toot from the iframe but would rather like to see a new item to directly copy the link to the Toot to the clipboard (as it is possible with Twitter).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by connyduck** [comment] 2018-08-18 09:44
Just click on the timestamp of a toot

**Comment by ascheman** [comment] 2018-08-18 09:59
Thanks, but this is not very obvious. 

If you are aiming to make users move from Twitter to Mastodon it is probably a good idea to give them the same user experience.

**Comment by swedneck** [comment] 2018-08-18 10:28
I agree, having the timestamp be a link to the toot is really strange, i would honestly like a dedicated "permalink" button.
![2018-08-18_12-26-08](https://user-images.githubusercontent.com/40505480/44298372-1f863d80-a2e2-11e8-94f6-7b74fa8ec713.png)

**Comment by ThibG** [comment] 2018-08-18 11:03
Duplicate of #6848

**Closed by ThibG** 2018-08-18 11:03 UTC
