### ISSUE TITLE
Remote reply & boost buttons.

### ISSUE THREAD

**Issue by steelman** [tootsuite/mastodon#4843] opened 2017-09-07 19:49 UTC
Make it possible (if possible without following the author) to reply or boost a toot from a remote instance while viewing the author's TL.

I think solution is going to be similar to follow/share buttons from #4511 
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by springbov** [comment] 2017-11-01 20:40
This is a feature I would like to have as well.

**Comment by Cassolotl** [comment] 2018-02-26 23:38
I think this is possibly a duplicate of *Add ability to boost/favourite a tweet on a remote instance #916*.

**Comment by Gargron** [comment] 2018-11-07 15:42
This was implemented in 2.5

**Closed by Gargron** 2018-11-07 15:42 UTC
Labels: suggestion
