### ISSUE TITLE
Login with profile name fails

### ISSUE THREAD

**Issue by jacotec** [tootsuite/mastodon#11362] opened 2019-07-19 12:11 UTC
My instance greets my users to log in with the profile name or email:

![image](https://user-images.githubusercontent.com/3321655/61534008-b695d100-aa2e-11e9-9078-9e7df9bd8eb2.png)

Unfortunately the profile name doe not work, so users are quite worried. It's even more complicated:

- Users authenticating from LDAP can only log in with their profile name but not with their email

- Users with Mastodon-internal registration can only log in with their email address, but not with their profile name.

The expected behavior would be that it does what it says: Users can log in with their username or email address (should not be a problem as both is unique)

Mastodon 2.9.2

**Comment by ichi-i** [comment] 2019-07-26 13:29
The English version only shows "E-mail address". There is no profile name option when logging in.
Maybe this is a localization problem?

**Comment by jacotec** [comment] 2019-07-26 13:35
I think it changes when you have LDAP configured, as LDAP users log in with their username.
It's however highly worrying - and why shouldn't any account use the (unique) username as an option to the email address? It's much more convenient for the user to allow both.

**Comment by Gargron** [comment] 2019-08-05 09:08
Duplicate of #6976

**Closed by Gargron** 2019-08-05 09:08 UTC
Labels: partially a bug
