### ISSUE TITLE
Ability to open toots in current column instead of in Getting started column in web UI

### ISSUE THREAD

**Issue by Exagone313** [tootsuite/mastodon#3772] opened 2017-06-15 13:03 UTC
Hi,

Since v1.4.2, you can pin/unpin columns, but the _Getting started_ column is always in the most right position (changing this would be another suggestion I don't want to make).
If you pinned more columns that your screen can display, you may not able to see directly the toot you clicked on, it does not even scroll to the right.
My suggestion it to open a clicked toot in the column containing that toot.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2017-07-23 13:59
I believe this is a duplicate of #355 - "Open content in the same column as it was clicked in". This issue #3772 shows that the issue is now more urgent.

**Comment by wxcafe** [comment] 2017-09-26 01:12
Duplicate of #355 yeah

**Closed by wxcafe** 2017-09-26 01:12 UTC
Labels: enhancement
