### ISSUE TITLE
Suspending an account should not delete it

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#6954] opened 2018-03-29 11:49 UTC
Currently, suspending an account purges its contents completely, even though this is not clearly stated.

Account suspensions and content/following/followers purging should really be two very separate steps for reasons stated in https://octodon.social/@CobaltVelvet/99766921921908947

This feature requires displaying that an account is suspended, and a way to federate that information to other instances. To my knowledge, ActivityPub does not specify a way to do that.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment] 2018-03-29 11:54
:+1:

**Comment by ThibG** [comment] 2018-03-29 12:00
(Removed the “fit for beginners” tag as it clearly needs some work on the protocol side of things)

**Comment by wxcafe** [comment] 2018-03-29 12:02
hmm? I don't think so, it could be a simple fix in the admin panel?

**Comment by ThibG** [comment] 2018-03-29 12:08
That would only work locally, you have to federate that information. The information currently being federated on suspension in the complete deletion of the account.

**Comment by wxcafe** [comment] 2018-03-29 12:14
ah. yes.

**Comment by ThisIsMissEm** [comment] 2018-04-01 18:35
Yeah, we've gotten caught out on this with Switter, where we thought suspension just disabled a user, and were completely caught out when we found out it deleted everything straight away. I was thinking for account deletion we should publish out to the network that the account is deleted, but keep the information in the local instance database for some predefined time range, in case there was a malicious action taken by that user.

(We basically had this happen and then couldn't discuss afterwards what happened as all related content was completely gone)

**Comment by stephenburgess8** [comment] 2018-04-08 05:03
> The information currently being federated on suspension is the complete deletion of the account.

I believe it makes sense for the toots of a suspended user to show up as deleted, even if they are only soft deleted on the server. The most crucial part of this request is to not destroy the user data upon suspension, but to disable it (soft delete). This will allow the user’s data to be restored if a suspension is reversed. It will also allow admins to look back on what happened to trigger the suspension. If a user’s account is restored after suspension, other instances will have to go back to get the old toots. This is inconvenient, true. However the more important value right now is simply no longer deleting the content.

Here are a couple relevant parts of the code, which hopefully linking to will help someone else fix this functionality a little eaiser. I believe this solution will be in the Ruby, but maybe a flag needs to be set on the call from the HAML. I am not a Ruby dev so I am not able to provide a code solution for this one. I will be curious to see what the solution will be for this one. Thanks.

https://github.com/tootsuite/mastodon/blob/master/app/services/suspend_account_service.rb#L17

https://github.com/tootsuite/mastodon/blob/master/app/views/admin/accounts/show.html.haml#L116

https://github.com/tootsuite/mastodon/blob/master/app/controllers/admin/reports_controller.rb#L47

**Comment by ThisIsMissEm** [comment] 2018-04-08 06:45
I think at a high level we need:
- **soft delete**: remove content from public visibility (including counters), purge from remote servers, retained locally for a given timeframe for admin retrospective
- **hard delete**: current behaviour, this is the case for when you need to remove something in an entirely destructive manner (e.g., removing content that should've never been published)

Then for `statuses`, `accounts` or `users`, and `lists` (I think those are only three entry points into the data), we'd need to use some mechanism to check for soft deletion.

For accounts, we may wish to change `suspended` from a boolean to a `suspended_until` timestamp, such that we can do temporary suspensions (useful when dealing with flamewars or other cases where you just need to put a user or few on ice for a bit)

It'd be a fairly large change, touching pretty much the entirety of mastodon's code, because it affects all reads and deletes of data. 

Techwise, it would be possible to use the [discard gem](https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid) to perform soft-deletes of statuses and lists locally, for accounts, I'd go with splitting `suspended` from `deleted` whilst functionally they're pretty much the same, it'd show clearer intents.

We'd also need to deal with the counter caches, as the rails-native counter caches that we use at the moment don't work with `deleted_at` type columns. An alternative would be [Counter Culture](https://github.com/magnusvk/counter_culture).

The biggest benefit of enabling soft deletes for every delete is that we'd effectively be able to go back and look at bad interactions that lead to reports, such that we can effectively moderate content. Sure, it'd increase storage overheads, but it's worth it in my opinion for the safety and moderation aspects.

---

A short term fix would be to change the language: instead of saying "suspend" when what we really mean is "delete", we should say "delete" — this would just be a translations change pretty much, and would likely mitigate some of the damage that can be done accidentally.

**Comment by ThibG** [comment] 2018-04-08 09:12
@stephenburgess8 there are multiple issues with issuing a deletion to the federation:
- The account's toots will be erased from remote instances, thus making it appear “empty” if it is brought back online. Public/unlisted toots will get fetched again if someone interacts with them, though.
- Private toots/direct messages from that account are lost forever for remote instances, as there currently exist no mechanism to fetch them.
- Following/followed lists are going to be cleared on remote instances, leading to “shadow followers” and broken following relations. I don't think that can be easily fixed.

**Comment by ThisIsMissEm** [comment] 2018-04-08 10:49
@ThibG couldn't we just republish those events as if they'd happened in current time?

**Comment by ThibG** [comment] 2018-04-08 10:57
@ThisIsMissEm I don't think so… for following/followed, you will have to deal with manually-accepted follow requests. For previous toots, it could be a *lot*, it's unreasonable to re-push them. In all cases, re-publishing things is going to result in a lot of noise (traffic, notifications).

Or maybe I didn't understand your suggestion.

**Comment by ThibG** [comment] 2018-04-08 12:46
Yeah, that's why https://github.com/w3c/activitystreams/issues/466 has been opened. IIRC, it will be discussed on the next SocialCG meeting: https://www.w3.org/wiki/SocialCG/2018-04-11

**Comment by ThisIsMissEm** [comment] 2018-04-24 14:03
@ThibG Was there any follow up to this post the meeting on the 11th April?

**Comment by nightpool** [comment] 2018-04-24 14:06
It does not look like that issue got discussed at that meeting because
there was noone there to talk about it.

**Comment by nightpool** [comment] 2018-04-24 14:07
I'm tempted to mark this as a duplicate of #5760 because that's the real change we need here (with maybe a rake/sidekiq task to clean old stuff up if people want) and I don't think adding more complicated user-facing or protocol-facing behavior is the right way to go.

**Comment by ThibG** [comment] 2018-04-24 14:26
Ah, it's a shame that this hasn't been discussed during this meeting :/

@nightpool broadcasting the deletion of a suspended account will still break a lot of things, should that account be unsuspended in the future, cf. https://github.com/tootsuite/mastodon/issues/6954#issuecomment-379534349

I still think displaying such accounts as suspended (e.g. like twitter does) and federating that information is reasonable and way better than the broken and misleading behavior we currently have.

**Comment by nightpool** [comment] 2018-04-24 14:27
@ThibG 

> broadcasting the deletion of a suspended account will still break a lot of things, should that account be unsuspended in the future

This **is** an implementation detail. Whether remote servers choose to delete the account and refetch the content later (which there *is* a mechanism for, using HTTP signed requests, mastodon just doesn't use it) or keep the account around for some sort of "grace period" is not something I feel comfortable Mandating from a spec standpoint.

**Comment by ThibG** [comment] 2018-04-24 14:35
Re-fetching the follow relations? You could do that I guess, but you'll run into a lot of corner cases with “locked” accounts. Also, good luck figuring out the difference between a legitimate follow and something a malicious server would want you to add.

I don't think we are suggesting the introduction of a “grace period” into the protocol, but just an additional message that says “this account has been suspended”, indicating that interactions might fail, that statuses from this account should be hidden, and that this account might be unsuspended at a later date.

**Comment by rixx** [comment] 2018-05-29 15:00
A temp fix would be to rename the "suspend user" and "perform full suspension" buttons to "delete user" and maybe show a warning on hover that this will also delete all statuses posted by that user. Could we please have this? Even as a somewhat experienced admin I was just trusting the language of the button and was not aware that suspension == deletion of account and all toots until a few months ago.

(Also, making the button red would help a lot.)

**Comment by ThisIsMissEm** [comment] 2018-05-30 13:59
I agree with this change, although, wouldn't like to call it a temporary fix. Any action that results in a loss of data should be clearly indicated.

**Comment by deutrino** [comment] 2019-06-11 02:32
Part of the problem is that **the word "suspend" is the wrong word to describe a total scorched-earth wipe of everything related to the account.** This issue could be left open for another year or two with plenty of :thinking: over protocol details, or the function could be named something other than "suspend" (which implies an action which is undoable), and that would be an improvement.

**Comment by deutrino** [comment] 2019-10-26 23:19
This is still badly misworded.

**Closed** 2020-09-15 12:37 UTC
Labels: admin support, suggestion
