### ISSUE TITLE
Change uploaded photos order on web UI

### ISSUE THREAD

**Issue by Kjwon15** [tootsuite/mastodon#10855] opened 2019-05-27 07:11 UTC
### Pitch

Make uploaded photos on compose UI draggable to change it's order

### Motivation

Upload photos using multiple file select results unpredictable orders.
Like Facebook, Draggable photos to change it's order is very useful. Specifically on cartoon or something.

**Comment by Cassolotl** [comment] 2019-05-27 09:42
This is a duplicate of *[Feature request] Ability to reorder attached images after uploading but before posting #9635* - you could add your 👍 there?

**Comment by Gargron** [comment] 2019-05-27 22:30
Maybe we can add "order" attribute to attachments?

**Comment by Gargron** [comment] 2019-08-05 09:16
Duplicate of  #9635

**Closed by Gargron** 2019-08-05 09:16 UTC
Labels: suggestion
