### ISSUE TITLE
Recommendation, identity verification

### ISSUE THREAD

**Issue by xBladeTV** [tootsuite/mastodon#5396] opened 2017-10-14 22:41 UTC
![tick-160426_960_720](https://user-images.githubusercontent.com/32804219/31579926-ddf4a320-b106-11e7-8853-94064154fabe.png)

**Comment by ykzts** [comment] 2017-10-14 22:45
what?

**Comment by xBladeTV** [comment] 2017-10-14 23:02
This symbol next to the name, also that you can verify accounts that are helping with different parts of Mastodon

![b4bfxrccuaapswx](https://user-images.githubusercontent.com/32804219/31580024-c01daa1a-b109-11e7-8d10-0d0e7f0d2f0f.jpg)

**Comment by ykzts** [comment] 2017-10-14 23:09
duplicate of #3821

**Closed by ykzts** 2017-10-14 23:09 UTC
