### ISSUE TITLE
vanishing emoji in notifications

### ISSUE THREAD

**Issue by azbulutlu** [tootsuite/mastodon#2094] opened 2017-04-18 18:02 UTC
https://social.tchncs.de/@gertdebra/923395
The emoji in this toot wasn't visible in notifications column :) 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Wonderfall** [comment] 2017-04-18 19:03
Looks like it's a duplicate of https://github.com/tootsuite/mastodon/issues/2016

**Comment by azbulutlu** [comment] 2017-04-18 19:11
somehow skipped over that issue when searching, sorry for the duplicate

**Closed** 2017-04-20 01:05 UTC
Labels: duplicate
