### ISSUE TITLE
Add comment when boosting a toot

### ISSUE THREAD

**Issue by baby-gnu** [tootsuite/mastodon#3507] opened 2017-06-01 21:20 UTC
Hello.

When I boost a toot, I would like to add a comment to express my motivation of the boost.

Sometimes I boost a toot to disagree but I can't express it in the boost process:

* add a reply to the toot
* boost the toot

Users just reviewing their timelime may miss-interpret me.

I would like to make available a comment on top of the boosted toot, this way people will read my note and then the original toot.

Another point is that my comment should be in the replies of the boosted toot.

Regards.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Komic** [comment] 2017-06-01 23:20
related to https://github.com/tootsuite/mastodon/issues/309 & https://github.com/tootsuite/mastodon/issues/2719

**Comment by Gargron** [comment] 2017-07-02 14:23
Duplicate of #309

**Closed by Gargron** 2017-07-02 14:23 UTC
