### ISSUE TITLE
missing toots in Favourites column

### ISSUE THREAD

**Issue by abochmann** [tootsuite/mastodon#5682] opened 2017-11-13 21:31 UTC
When scrolling back several pages through the Favourites (/web/favourites) timeline, an effect similar to Issue #5379 appears: There's blank holes in the feed, with no toots being displayed.

My instance is running on Mastodon 2.0.0

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by sorin-davidoi** [comment] 2017-11-13 22:44
Duplicate of #5630.

**Closed by sorin-davidoi** 2017-11-13 22:44 UTC
