### ISSUE TITLE
Content area under new toot for announcements

### ISSUE THREAD

**Issue by xvilo** [tootsuite/mastodon#1762] opened 2017-04-14 12:10 UTC
It would be great to use the area under the "New Toot" section (first column) is a custom text area. This way an instance owner could add important messages there. 

I am not that well know with Ruby on Rails, so If there is anybody who could implement this? 
It would be great if the content area were positioned on the bottom of that section and just disappears on mobile or when the page isn't high enough. 

The image is a screenshot of what I mean;
![contentarea](https://cloud.githubusercontent.com/assets/390769/25042904/16ed8442-211c-11e7-9fff-a1ba69390d27.jpg)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment] 2017-04-14 12:24
Thats where the toot composer can be expanded out to though, so it's useful to keep that bit of space clean in case someone writes a really long toot.

**Comment by xvilo** [comment] 2017-04-14 12:38
Maybe it would be possible to let it disappear?

**Comment by tomfhowe** [comment] 2017-04-14 14:25
I might be wrong, but I think that's kind of what the bottom of the getting started column is for? That space definitely does look weird unused on big screens, but blank space is not always wasted space. I don't know.

**Comment by mjankowski** [comment] 2017-04-14 14:31
> This way an instance owner could add important messages there.

I'm curious about what sorts of things fit this description?

Would it be useful to visually highlight statuses from instance admins?

Would it be useful to have non-status instance-wide notifications available somewhere in the UI?

**Comment by wxcafe** [comment] 2017-04-15 00:00
This is a duplicate of #1209, please add your comment there if you want. Closing.

**Closed by wxcafe** 2017-04-15 00:00 UTC
Labels: duplicate
