### ISSUE TITLE
Cards not getting federated properly?

### ISSUE THREAD

**Issue by Kimik0** [tootsuite/mastodon#3396] opened 2017-05-28 16:33 UTC
Example: the associated card for https://mamot.fr/@artefr/1765496
Asking the originating instance for the card through https://mamot.fr/api/v1/statuses/1765496/card gives a card with all the fields listed in the API documentation as non-nullable.
Asking a different instance for the card, for example https://mastodon.social/api/v1/statuses/7389519/card gives a response that is missing the description (should be non-nullable) and image, and has a different title and url. https://mastodon.xyz/api/v1/statuses/3376619/card gives an empty response, as do https://framapiaf.org/api/v1/statuses/833796/card , https://oc.todon.fr/api/v1/statuses/1279125/card , and https://mastodon.cloud/api/v1/statuses/11241664/card . https://witches.town/api/v1/statuses/1864352/card gives the same mangled response as mastodon.social.

I'm not sure cards are all that important, but shouldn't the results at least be consistent?
* * * *
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by happycoloredbanana** [comment] 2017-06-12 18:20
Think I found the cause for this one: when a card is being generated, [current implementation uses the first non-local URL](https://github.com/tootsuite/mastodon/blob/37dbfa4cd7f97cfbab68d1bfd774aabf5ca2e0af/app/services/fetch_link_card_service.rb#L39) from the post. However, if the post contains hashtags, on the remote server, the hashtag link (in the above case - https://mamot.fr/tags/toutestvrai) will be interpreted as a non-local and will be used for card generation.
I will try to fix this.

**Comment by happycoloredbanana** [comment] 2017-06-13 20:00
Correction: current code knows how to deal with hashtag links if `rel="tag"` is present. I guess in this case it gets sanitized out somehow.

**Comment by happycoloredbanana** [comment] 2017-06-16 20:55
@Gargron any chance you could help with retrieving the raw content of https://mastodon.social/api/v1/statuses/7389519 as it's stored in the DB?

**Closed** 2018-04-08 18:59 UTC
Labels: bug
