### ISSUE TITLE
disable-auto-scroll option

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#1780] opened 2017-04-14 15:17 UTC
some users (like myself) do not want this auto-scroll functionality, and it does not make sense for it to act in this way when you are scrolled down and looking at posts of any particular amount of time in the past.

i presume the second is intended to not function like this, because it seems to make a concious effort to keep its positioning, and yet, it fails more often than not. this is touched on in #1306 however i believe an option should exist to keep your timelines from auto-scrolling at all. it would still show the blue "new posts above", presumably, and would allow you to scroll up on your own time to see new posts

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-14 15:19
would this be a duplicate of this #1538 ?

**Comment by hoodiek** [comment] 2017-04-14 15:20
it could be considered one, but i think that one is more about the act of posts being  loaded manually, like say, twitter proper, where it says X new posts at the top and you click it to "refresh" and load them

**Comment by Cassolotl** [comment] 2017-04-15 11:48
In the Twitter app for Mac there is a setting that stops auto-scrolling. It loads new tweets, but you have to scroll up manually to see them. That, for me, would be ideal.

The same as what happens when you scroll down a bit in the federated timeline - posts above it continue to load and the scrollbar adjusts itself, but to see the new posts you have to scroll.

**Comment by hoodiek** [comment] 2017-04-15 21:52
same @Cassolotl

**Comment by Maverynthia** [comment] 2017-06-05 12:24
Either way, I hate the auto-scroll. Mastodon should have had this feature.

**Comment by Gargron** [comment] 2017-06-29 22:15
Duplicate of #240

**Closed by Gargron** 2017-06-29 22:15 UTC
Labels: enhancement, priority - medium, ui
