### ISSUE TITLE
Feature request - Privacy lists

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#2425] opened 2017-04-25 03:38 UTC
With federated private toots now in production, seems like we need more granular privacy controls.

I'd like to see custom privacy lists so users can decide which followers their toots federate to. Could be a mechanism both of instance control ("I don't trust the instance") and user control ("I don't want to share this with this person"). This would make private toots more useful for generally public accounts.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2017-06-23 21:56
I ran into a need for this today. There's someone I don't mind following me, but also I want to toot privately and have them not see it.

Basically I want anyone to be able to follow me, but I want to be able to have a whitelist for who gets to see my private toots.

See also #422 - "lists, mutuals only, and eliminating the need for multiple accounts."

**Comment by wxcafe** [comment] 2017-09-26 01:20
yeah, duplicate of #422, closing

**Closed by wxcafe** 2017-09-26 01:20 UTC
Labels: enhancement, ui
