### ISSUE TITLE
Redirect after submitting a reply to a private toot results in a blank page

### ISSUE THREAD

**Issue by testingwithfire** [tootsuite/mastodon#10093] opened 2019-02-21 10:31 UTC
When I submit a reply to a private toot on Firefox for Linux, the redirect results in an empty page (https://kitty.town/web/timelines/direct)

### Expected behaviour

1. Submit a reply to a private toot
2. Get redirected to timeline

### Actual behaviour

The redirect (https://kitty.town/web/timelines/direct) results in an empty page. 

### Steps to reproduce the problem

Just reply to a private toot and you should see the issue.

### Specifications

I don't know the Mastodon version. I'm running Firefox 60.5.1esr on Debian 9.

**Comment by ThibG** [comment] 2019-02-21 21:51
Most likely a duplicate of #10068, closing.

**Closed by ThibG** 2019-02-21 21:51 UTC
