### ISSUE TITLE
Distinguish English US and English UK dialects for interface language

### ISSUE THREAD

**Issue by Phidica** [tootsuite/mastodon#8456] opened 2018-08-26 13:04 UTC
On the main page of web UI for a logged-in user, I see "favourites". In the preferences, I see "authorized". Mixing of dialects in this way looks odd. Can they be distinguished as interface languages?

**Comment by ykzts** [comment] 2018-08-26 14:03
You can add a new locale from [Weblate](https://weblate.joinmastodon.org/new-lang/mastodon/backend/).

**Comment by trwnh** [comment] 2018-08-26 14:59
duplicate of #8163

**Closed** 2018-08-26 21:03 UTC
