### ISSUE TITLE
Long posts blocks privacy setting options

### ISSUE THREAD

**Issue by ragingscholar** [tootsuite/mastodon#5421] opened 2017-10-16 17:49 UTC
![image1](https://user-images.githubusercontent.com/18600658/31626617-0596c688-b2dd-11e7-90a4-6ee38934bfa9.jpeg)

As shown in the picture above. This happens when replying to or posting a long post, the privacy setting options get blocked.

Tested with Chrome 61.0, screen resolution 1366*768

**Comment by Cassolotl** [comment] 2017-10-16 19:43
I think this is a duplicate of #5313?

**Comment by ragingscholar** [comment] 2017-10-17 17:05
Looks like a duplicate, really sorry about that. I made sure that I searched open issues...

**Closed** 2017-10-17 17:06 UTC

**Comment by Cassolotl** [comment] 2017-10-17 18:54
No worries! :) I only knew about the other one because I'd already read it!
