### ISSUE TITLE
Option to Auto-Delete Toots

### ISSUE THREAD

**Issue by kevquirk** [tootsuite/mastodon#13328] opened 2020-03-29 16:51 UTC
Quite simple really. Many people on Mastodon are privacy advocates. It would be great to have an option within user preferences where they could choose to auto-delete toots older than a set time.

Default would be to keep all toots, but if enabled, the user could set the number of days/weeks/months etc that toots older than should be deleted.

From an admin perspective it could also save server resources?

**Comment by trwnh** [comment] 2020-03-29 21:37
Duplicate of #1295

**Closed** 2020-03-30 00:28 UTC
