### ISSUE TITLE
Get Mastodon on TranslateWiki to simplify localisation work

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#1241] opened 2017-04-08 08:31 UTC
Everything is in the title really. It’s currently not so easy to keep track of the English version changes and additions, and to assure a consistent translation. Having a fitting interface to do so would be welcome.

[TranslateWiki](https://translatewiki.net/wiki/Translating:New_project) seems like the go-to place for free software projects, but there are probably solutions I haven’t heard of. Transifex is nice too but non-free.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by davidak** [comment] 2017-04-10 22:02
elementary OS just switched from Transifex to [Weblate](https://weblate.org/de/):

https://medium.com/elementaryos/adios-transifex-weve-gone-to-weblate-59870dea06b2

**Comment by nclm** [comment] 2017-04-11 19:58
Ah yes, Weblate sounds good too, and we could have our own server just for Mastodon (which would be more costly than Translate Wiki though). We just have to check if it’s compatible with Mastodon’s language files.

**Comment by jeroenpraat** [comment] 2017-04-17 21:57
+1

And I really don't care which translation tool is used. Now it is almost unworkable, especially with more people. And this will get worse.

**Comment by Artoria2e5** [comment] 2017-04-21 02:19
Personally I prefer Weblate too. They usually provide better plural checking and stuff than TWN does, but I am not quite sure about how these work out with Ruby i18n files. The current status is indeed unworkable.

**Comment by yookoala** [comment] 2017-04-21 04:58
Cool. TranslateWiki seems to support both Javascript and YAML.

One tricky thing is to actually reference the translation files. You still have to manually add the references in Ruby and Javascript when you add the language.

**Comment by ashfurrow** [comment] 2017-04-22 02:11
Crowdin was also suggested here: https://github.com/tootsuite/mastodon/issues/950

**Comment by Artoria2e5** [comment] 2017-04-22 04:37
I am expecting JSX files to be the biggest obstacle here, as most translation platforms don't and won't want to involve dealing with executable code. It may be possible to separate the localization object into a JSON file and do some preprocessor magic to include the JSON objects into JSX at build time though.

**Comment by thor-the-norseman** [comment] 2017-04-30 17:37
Related to #1742.

**Comment by thor-the-norseman** [comment] 2017-04-30 17:40
Related to #213.

**Comment by thor-the-norseman** [comment] 2017-05-01 09:40
Working on something here: https://github.com/thor-the-norseman/mastotran

**Comment by benediktg** [comment] 2017-05-04 07:57
> Ah yes, Weblate sounds good too, and we could have our own server just for Mastodon (which would be more costly than Translate Wiki though).

@nclm 
weblate.org also offers free hosting for Free Software projects at https://hosted.weblate.org/

I really would appreciate such a web based translation tool because it makes translation accessible to non-developers. Additionally it would prevent double work because two people translated the same strings. 😉

**Comment by LNDDYL** [comment] 2017-05-19 10:11
I created ["Mastodon Translation Team" on Slack](https://mastodon-translation.slack.com)).

![4a8ae28a548b7708](https://cloud.githubusercontent.com/assets/4318463/26243458/86f5bf80-3cbe-11e7-9d85-958f9f3bc896.png)

**Comment by LNDDYL** [comment] 2017-05-24 15:26
@nclm @davidak @benediktg @thor-the-norseman @Artoria2e5 @ashfurrow @yookoala @jeroenpraat
About [POEditor](https://poeditor.com)?

**Comment by davidak** [comment] 2017-05-24 15:36
@LNDDYL POEditor is no free software, so we would be dependent on them.

**Comment by bamstam** [comment] 2017-07-05 22:27
I would go for Weblate :-) I'm using it on a daily basis, for me a clear recommendation

**Comment by nightpool** [comment] 2017-07-06 18:33
weblate looks pretty good, and it should be pretty easy to set up a free account without doing too much work.

**Comment by saper** [comment] 2017-07-25 20:07
Isn't there something that is not a centralized, third-party service?

**Comment by Artoria2e5** [comment] 2017-07-25 21:09
Weblate can be hosted locally, but as a lazy person with an account on https://hosted.weblate.org/ I don't see many reasons to do that…

**Comment by nightpool** [comment] 2017-08-01 19:52
I'm going to look into setting up a weblate instance this week, and seeing what kind of configuration will work well for the mastodon project.

**Comment by gandaro** [comment] 2018-01-06 16:26
@nightpool What’s your status?

**Comment by jeroenpraat** [comment] 2018-01-06 16:53
I'm not @nightpool, but i can confirm that Weblate was deployed a while ago. Unfortunately it isn't updated anymore since Mastodon v2.1.0 with new strings and also not merged with the master anymore.

**Comment by gandaro** [comment] 2018-01-15 15:43
For your information, I will cease working on the German translation as long as this is not fixed.

**Comment by renatolond** [comment] 2018-01-17 16:55
I've been trying to merge the translations from time to time, I've merged after 2.1.0 when I noticed that the pt-br translations had not been picked up. It's been a few days since I merged, though, on #6228

**Comment by gandaro** [comment] 2018-01-17 23:12
Could a GitHub hook be implemented for this, please, so that Weblate automatically gets updated?

**Comment by nightpool** [comment] 2018-01-17 23:19
@gandaro the problem isn't the hooks, it's that weblate reformats all the source files and causes tons of conflicts with other translators.

**Comment by gandaro** [comment] 2018-01-17 23:33
Why does it cause conflicts with other translators? Because other translators don’t use Weblate? Are there other problems? It should be possible to tell translators to stop editing the translation files directly.

**Comment by gandaro** [comment] 2018-01-17 23:43
When I amended the German translation, I noticed the following.

For instance, a string called `hello:world` was added to the source file. A German translation was added, too. But later, the same string was changed in the source file. To check whether there is a translation for the source string, you cannot simply check if there is a string called "hello:world" in both files. You need to check the version history: when was the last time that the string was updated in the source file, and when was the last time that it was updated in the translation file?

Does Weblate correctly deprecate translation strings?

**Comment by Gargron** [comment] 2018-02-13 22:14
We've got weblate now: <https://weblate.joinmastodon.org>

**Closed by Gargron** 2018-02-13 22:14 UTC
Labels: internationalization

**Comment by wioxjk** [comment] 2020-05-18 12:52
What happened with the weblate?

**Comment by Gargron** [comment] 2020-05-19 05:34
We've got Crowdin now: https://crowdin.com/project/mastodon

(Weblate wasn't good)

**Comment by SuperSandro2000** [comment] 2020-05-19 10:10
What is not good about it?
