### ISSUE TITLE
Public toots from federated accounts posted prior to installation does not appear

### ISSUE THREAD

**Issue by clement-analogue** [tootsuite/mastodon#2621] opened 2017-04-29 14:05 UTC
On a freshly installed instance of Mastodon, when trying to look at toots of accounts from other servers, the toots posted prior to the creation of the instance does not appear.

**Comment by jbbdude** [comment] 2017-04-29 18:24
This is the expected behavior. Past toots from accounts on federated instances don't get pulled in except for specific cases (e.g. the URL of the toot is plugged into the search box).

This would be a feature request, but in the past this has been discussed as intended behavior.

**Comment by wolfteeth** [comment] 2017-04-29 23:29
+1 as a feature request. I'd like the federation experience to have fewer seams like this showing for users.

**Comment by schmittlauch** [comment] 2017-04-30 09:45
Wouldn't it be quite easy for an instance to just pull the users Atom feed, at least when having followed a user?
I can understand big instances may not want this overhead, but single-user instances would heavily profit from that.

**Comment by schmittlauch** [comment] 2017-04-30 09:55
I guess this can be seen as duplicate of good old #34

**Comment by Gargron** [comment] 2018-04-08 18:38
Not a bug

**Closed by Gargron** 2018-04-08 18:38 UTC
Labels: enhancement
