### ISSUE TITLE
"Muted users" only shows 40 items

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#8463] opened 2018-08-26 15:41 UTC
I'm assuming pagination got overlooked here -- "blocked users" loads more users properly once you reach the bottom of the list.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [2.5.0rc1](https://github.com/tootsuite/mastodon/releases) and not on `master`

**Comment by Gargron** [comment] 2018-08-26 15:52
Weird, blocks and mutes are equally hooked up to pagination logic.

**Comment by trwnh** [comment] 2018-08-26 16:23
I'm not sure if this is relevant, but could it have something to do with how many users total are muted/blocked? I think I've blocked about 60 and muted several hundreds, if that makes a difference.

**Comment by JMendyk** [comment] 2018-08-26 17:35
I compared `MuteController`'s and `BlocksController`'s source - they differ a bit and found that the issue is in:
https://github.com/tootsuite/mastodon/blob/da13fa50215c5153ee199eb8e70e7fa030523a00/app/controllers/api/v1/mutes_controller.rb#L49-L55

Later, I browsed history of `MuteController` and `BlocksController` and found similiar bug report but for blocks #5268 which was fixed by #5285, hence the difference in source codes.

@Gargron If it's okay, I can fix the issue, clean up `MuteController` to make it's source match `BlocksController` and I'll create a pull request.

**Comment by Gargron** [comment] 2018-08-26 18:52
@JMendyk Go ahead, I'll wait with the git tag then

**Closed** 2018-08-26 19:30 UTC
