### ISSUE TITLE
Show account.created_at in the web client

### ISSUE THREAD

**Issue by mkosler** [tootsuite/mastodon#5791] opened 2017-11-23 15:26 UTC
It's around time when users are celebrating their Mastodon anniversaries, but their account creation date doesn't seem to be exposed in the web client. That data is already visible in the Account entity (account.created_at), so it would be nice (and easy) to expose that somewhere in the client so people can know when their anniversary is.

Other clients, such as Twidere for Android, already expose this.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment] 2018-05-07 19:30
Duplicate of #5399

**Closed by ThibG** 2018-05-07 19:30 UTC
