### ISSUE TITLE
Link @user@twitter.com to There Respective Twitter Profiles.

### ISSUE THREAD

**Issue by mcb2003** [tootsuite/mastodon#8851] opened 2018-10-02 10:14 UTC
As is standard behaviour on Mastodon, whenever a user is mentioned from another instance, the reference to their profile looks like __@user@instance.domain.__ This then becomes a link to __@user's__ profile on __instance.domain.__ However, we could extend this to non-mastodon services as well, namely Twitter. Simply by typing __@user@twitter.com__ users on twitter could be mentioned in toots and could be linked to the user's profile on twitter. I've seen people do this already and I believe, although I could be wrong, that the [twitter mastodon crossposter](https://crossposter.masto.donte.com.br/) does this as well when posting tweats to mastodon, however, they don't show up as links.

Feel free to close this issue if it is a duplicate: I had a quick look but couldn't find anything related.

**Comment by ykzts** [comment] 2018-10-02 12:03
Duplicate of #1849

**Closed by ykzts** 2018-10-02 12:03 UTC
