### ISSUE TITLE
Group similar notifications in notification view

### ISSUE THREAD

**Issue by lutoma** [tootsuite/mastodon#1586] opened 2017-04-11 23:06 UTC
This is a low-prio UI thing: One of my toots was just boosted ~200 times, making my notification pane essentially useless because any other notifications became buried somewhere between hundreds of notifications concerning that one toot.

Similarly to how twitter does it, I think it would be very useful to group 'similar' notifications, so that you would instead get something like `xyz and 150 other people have boosted your toot` and `foo and 12 other people followed you` etc.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-12 17:05
duplicate of #1483

**Closed by wxcafe** 2017-04-12 17:05 UTC
Labels: duplicate
