### ISSUE TITLE
Feature request: Please allow me to mute statuses boosted by an account

### ISSUE THREAD

**Issue by giromide** [tootsuite/mastodon#1026] opened 2017-04-06 03:41 UTC
I might wish to follow an account strictly for its own content, not content that it boosts. Please consider giving users the option to mute statuses boosted by an account I follow.

Options in the account would thus be:
Mute @SomeAccount
Mute boosts via @SomeAccount
Block @SomeAccount
Report @SomeAccount

Thank you!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by giromide** [comment] 2017-04-06 03:45
I had not used the desktop web API until this evening and just realized the main timeline vertical allows me to hide boosts and replies along with other filtering. If you wish to mark this as "duplicate" or "already done", that's ok. I think there'd be some value in the feature I requested, but it might confuse users.

**Comment by wolfteeth** [comment] 2017-04-06 07:15
Duplicate of https://github.com/tootsuite/mastodon/issues/648

I still think this feature has value. I don't want to suppress all boosts, just those from some particularly noisy accounts I follow.

**Comment by ashfurrow** [comment] 2017-04-21 17:59
Cool, thanks for opening @giromide. Going to close and move to #648.

**Closed by ashfurrow** 2017-04-21 17:59 UTC
Labels: duplicate
