### ISSUE TITLE
turned off reblog won't show the original post, if it was rebloged

### ISSUE THREAD

**Issue by riyona** [tootsuite/mastodon#530] opened 2017-01-25 23:39 UTC
If I turn off the reblogs for my timeline in it reblogged something that was in my timeline as well, the original won't show. I'm guessing the reblog hides the original and the function to turn reblogs of hides the reblog itself, but not it's actions.

**Comment by wxcafe** [comment] 2017-09-26 01:48
I can't reproduce this, can anyone?

**Comment by Cassolotl** [comment] 2018-02-26 21:16
I can't either!

**Comment by wxcafe** [comment] 2018-02-27 12:40
Closing

**Closed by wxcafe** 2018-02-27 12:40 UTC
Labels: bug
