### ISSUE TITLE
2.0.0RC1 - Keyboard shortcut interference with toot input

### ISSUE THREAD

**Issue by Aldarone** [tootsuite/mastodon#5306] opened 2017-10-10 19:15 UTC
On 2.0.0rc1 we're unable to enter numbers in toots because the keystroke triggers the « focus column n°x » shortcut.

Tested browsers on Archlinux : 

- nw.js 0.25.4
- Firefox Nightly 58.0a1 2017-10-09
- Chromium 61.0.3163.100

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment] 2017-10-10 21:36
So, I can't reproduce this (not exactly at least).

The behavior I get is as follows:

- When I first load the page, the focus is on the input field. At this point I can type any number or other shortcut and it just writes into the input field.
- If I want to focus a column, I have to escape the focus of the input field (<kbd>esc</kbd>) then I can use its number (<kbd>2</kbd> for example). At this point I can use all normal shortcuts (<kbd>j</kbd> and <kbd>k</kbd> to move up and down, other numbers to switch columns, <kbd>f</kbd> to fav, etc)
- If I want to go back to the input field, I type <kbd>n</kbd> and then I can (again) type any character that is (or not) a shortcut and it appears in the input field.

**Comment by Sylvhem** [comment] 2017-10-10 22:28
I think I can reproduce this bug, though it works a little differently for me.

Steps to reproduce:
1. Put the focus on the input field.
2. Type a number x by pressing <kbd>Shift</kbd>+<kbd>x</kbd>. For example, to type 2, press <kbd>Shift</kbd>+<kbd>2</kbd>.
3. The number corresponding number appears in the input field **but** the focus is moved to the corresponding column.

I can reproduce this on Debian GNU/Linux 9, using Firefox 52.4.0.

**Comment by wxcafe** [comment] 2017-10-10 22:37
Okay I think this is related to keyboard disposition. I use a QWERTY keyboard so I don't have to press <kbd>Shift</kbd> before typing a number. Same with @Gargron who uses a QWERTZ keyboard.

**Comment by wxcafe** [comment] 2017-10-10 22:46
okay seems like it's just a matter of blacklisting <kbd>Shift</kbd>+<kbd>num</kbd> and that's it :)

**Comment by wxcafe** [comment] 2017-10-10 22:58
Fixed in #5306

**Closed by wxcafe** 2017-10-10 22:58 UTC
Labels: bug, help wanted, master, priority - high, ui
