### ISSUE TITLE
A default channel to communicate to users when there is maintenance on the server.

### ISSUE THREAD

**Issue by op3nus3r** [tootsuite/mastodon#1453] opened 2017-04-10 17:21 UTC
It would be great to have a default channel to communicate to users when there is maintenance on the server or other admin messages.
This could be the Admin@Instance.tld account

The message would be displayed at the top of the notifications column and you would have to click (close) to confirm that you read correctly.

Perhaps through notifications, like this:

![notif_admin](https://cloud.githubusercontent.com/assets/22491305/24873857/bf38f4a8-1e22-11e7-9bc5-a1c15e88d809.png)

**Comment by wxcafe** [comment] 2017-04-10 18:09
This is a duplicate of #1209. Please continue discussion there (and post your mockup too, it looks pretty nice). I'm closing this issue

**Closed by wxcafe** 2017-04-10 18:09 UTC
Labels: duplicate

**Comment by op3nus3r** [comment] 2017-04-10 18:13
ok, thanks.
