### ISSUE TITLE
Combine retoots and favorites in notification column

### ISSUE THREAD

**Issue by roipoussiere** [tootsuite/mastodon#7698] opened 2018-06-01 14:49 UTC
If you toot something that becomes popular, your notification column becomes full of share / favorite notification for this unique toot and it is very easy to miss an other important event.

Instead of the following:

- Liam liked 'some popular toot'
- Noah shared 'some popular toot'
- Emma liked 'some popular toot'
- William shared 'some popular toot'
- **Olivia answered to 'an other toot'**
- James shared 'some popular toot'
- Sophia shared 'some popular toot'
- Ava liked 'some popular toot'
- Logan liked 'some popular toot'

I find 3 main behaviors at this time to combine toots:

1. Combine notifications of same toot and same kind:

- Liam liked 'some popular toot'
- Noah shared 'some popular toot'
- Emma liked 'some popular toot'
- William shared 'some popular toot'
- **Olivia answered to 'an other toot'**
- James and Sophia shared 'some popular toot'
- Ava and Logan liked 'some popular toot'

2. Combine notifications of same toot, whatever the order of the notification kind:

- Liam and Emma liked 'some popular toot'
- Noah and William shared 'some popular toot'
- **Olivia answered to 'an other toot'**
- James and Sophia shared 'some popular toot'
- Ava and Logan liked 'some popular toot'

3. Combine notification with one big group, even if an event appears between popular notifications:

- James, Sophia and 2 other people shared 'some popular toot'
- Ava, Logan and 2 other people liked 'some popular toot'
- **Olivia answered to 'an other toot'**

Note that:
- considering the chronological order, `1.` is more accuracy than `2.` and `2.` is more accuracy than `3.`;
- considering the number of notifications, `1.` is more annoying than `2.` and `2.` is more annoying than `3.`;
- `3.` can be more difficult to implement because we need to know when the user last logged in.
- for both of the behaviors, I suggest here to display *and x other people* if there is more than 2 people, but maybe this number could me reduced to 1 in order to fit in the notification column;

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment] 2018-06-01 14:57
Probably better to filter notifications column for mentions only, using the checkboxes. At least, if notifications ever get grouped/collapsed in such a way, then they should be expandable for the full list, amd perhaps the collapsing functionality should be toggleable. (On mobile right now but I'll tag in other issues with discussion around this later)

**Comment by Cassolotl** [comment] 2018-06-01 15:14
>Probably better to filter notifications column for mentions only, using the checkboxes.

We can already do that, obviously.

**Comment by Gargron** [comment] 2019-08-05 09:10
Duplicate of #1483

**Closed by Gargron** 2019-08-05 09:10 UTC
Labels: suggestion
