### ISSUE TITLE
Message Change: "Content warning" is not suitable

### ISSUE THREAD

**Issue by yumetodo** [tootsuite/mastodon#2310] opened 2017-04-22 08:38 UTC
[/app/assets/javascripts/components/locales/en.jsx#L41](https://github.com/tootsuite/mastodon/blob/6af21daac9f5ed3932694b211a04a715a348d995/app/assets/javascripts/components/locales/en.jsx#L41)
=> [/app/javascript/mastodon/locales/en.json#L42](https://github.com/tootsuite/mastodon/blob/12e7c81dd8739a0f83513054c0fda22e098e2458/app/javascript/mastodon/locales/en.json#L42)

As pointed out in https://github.com/tootsuite/mastodon/pull/2305#issuecomment-296355315, Users hardly recognize it is a placeholder for a warning message.

To solve that, ``compose_form.spoiler_placeholder`` should be substituted with another text that explain about the input area, I think.

As pointed out in https://github.com/tootsuite/mastodon/pull/2305#issuecomment-296355500 by @akihikodaki, this problem should not resolve at translate text.

@MaverickTse propse in https://github.com/tootsuite/mastodon/pull/2305#issuecomment-296357518 that:

>None of the proposed wording seems to fit that field IMO.
The purpose of that placeholder should be made the user to aware that what they write in there will goes public. The content is not necessarily "sensitive".
Hence, the placeholder should be:
English: "(Public Content)"
日本語：（公開的な内容）

ref:
- #235
- https://ostatus.yoh2.ddo.jp/@yoh2/903

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by notbakaneko** [comment] 2017-04-24 07:03
I'd agree that the Content Warning input placeholder should contain a more descriptive instruction of what a user should do with it. At the moment, it appears more like a statement, which IMO is not intuitive.

**Comment by Sylvhem** [comment] 2017-07-09 02:18
I have some suggestions for new placeholders to use instead of the current "Content warning":
1. What do you want to warn the others about? (good but probably too lengthy)
2. Public warning about this toot content (can be hard to translate without making it too long)
3. Public warning about the content
4. Public warning
What did you think?

**Comment by yumetodo** [comment] 2017-07-09 03:14
Placeholders should be written in the imperative form, I think.

ex.) `Write warning why you mark as CW.` => ja-JP: `CWにした理由を書いてください`

---

BTW, In [pawoo.net](https://pawoo.net), CW placeholder's translation is `内容注意メッセージ`, which means `A message to warn content`.

**Comment by Sylvhem** [comment] 2017-07-09 14:39
You're probably right, it will make everything clearer.
What did you think of "Write you warning here"? It seems simple and straightforward.

**Comment by yumetodo** [comment] 2017-07-09 15:25
>What did you think of "Write you warning here"? 

This message cannot describe why the placeholder is displayed.

**Comment by Sylvhem** [comment] 2017-07-09 15:32
But this placeholder will only appear when the user will click on the "CW" button. They know why a field it displayed, it's the direct result of their action.

**Comment by yumetodo** [comment] 2017-07-09 15:51
Hmm, "Write you warning here" is not dot bad...

**Comment by yumetodo** [comment] 2017-07-09 15:58
@akihikodaki @MaverickTse @yiskah @notbakaneko @yoh2 Do you have any opinion?

**Comment by MaverickTse** [comment] 2017-07-10 02:13
if that field only appears after user pressed a "CW" button, and that field is intended to be a customized message, then
either
"Write your warning here"
"Warning message"
"Warning description"

would be fine.

However, note that as long as that field is a text box but not a combo box with predefined categories, user can actually put anything there, potentially allowing the "warning message" itself becoming the "sensitive material"

Some examples of categories:
"Highly political"
"Religion involved"
"Nudity Content"
"Extreme violence"

**Comment by Sylvhem** [comment] 2017-07-23 18:57
@yumetodo I changed the placeholder from "Content warning" to "Write your warning here" (see #4313). Should we close this issue?

**Comment by akihikodaki** [comment] 2017-07-24 02:34
The topic of this issue was actually about the change in the original string, not translated or localized one.
The problem is now solved and I'll close this issue. Please open another issue for localization if necessary.

**Closed by akihikodaki** 2017-07-24 02:34 UTC
Labels: ui
