### ISSUE TITLE
problem with handling about control code for bi-directional text

### ISSUE THREAD

**Issue by anmonite** [tootsuite/mastodon#2166] opened 2017-04-19 19:13 UTC
Last day,  I found collapsed strings in system oriented messages by tainted username including a unicode control code for bi-directional text like as follows.

http://i.imgur.com/QQyyh3V.png
The bottom is correct viewing of when a post is favourited, and upper is collapsed string like an anagram.

Following is an explaining the behavior in English strings. RLO is the control code of right-to-left override (U+202E).
"foo[RLO] favourited your status"  --> "foosutats ruoy detiruovaf"

It's too strange view!

For reference about RLO/LRO - UNICODE BIDIRECTIONAL ALGORITHM
http://unicode.org/reports/tr9/#Explicit_Directional_Overrides

* * * * *
Therefor, I propose some countermeasures for avoiding this behavior.

1. Add validation step to exclude RLO/LRO unicode control codes when user register the user name.
2. Add LRO/RLO elimination logic before output system strings with user name for client and also API return value.

Please consider about this problem.

Regards.

**Comment by wxcafe** [comment] 2017-04-19 23:32
duplicate of #1095, closing

**Closed by wxcafe** 2017-04-19 23:32 UTC
Labels: duplicate

**Comment by anmonite** [comment] 2017-04-19 23:35
I'm sorry for my duplicated post.
I did not find #1095 issue.

Thanks.

**Comment by wxcafe** [comment] 2017-04-19 23:36
no problem
