### ISSUE TITLE
CNs can not contain clickable hashtags or links

### ISSUE THREAD

**Issue by rohieb** [tootsuite/mastodon#2281] opened 2017-04-21 19:21 UTC
500 characters are really a lot, so sometimes I use the CN field for other things than content notices, just to be able to have the "show more" button. This way I can let the users choose whether they like to read on, without disrupting their timelines with longposts. For example:

* when adding images, write the actual content of the toot into the CN field, then use the "main toot area" for image descriptions (for people using only text-to-speech interfaces)
* general long posts: use the CN field for a short title or excerpt (e.g. title of an journal article, including a link to it), and a longer excerpt or discussion goes into the main toot.

However, text in the CN field is not transformed to links, so hashtags, user mentions, or links to other pages are not clickable. I'd like them to be clickable.

But maybe I'm using this all wrong and the title of this issue should rather be *implement a more generic "show more" feature*? I could think of a special tag, like "" in Wordpress, which makes the post appear shortened when it appears in the content.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2017-04-21 19:39
This is a duplicate of #699. :)

**Closed** 2017-04-21 23:10 UTC
Labels: duplicate
