### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by winniehell** [tootsuite/mastodon#1629] opened 2017-04-12 18:30 UTC
On twitter, I have used polls to write an interactive story together with @blinry. This is currently not possible with Mastodon.

I would like to start working on this though I am not sure if I will be able to finish.

* * * *

<details>
<summary>
I searched or browsed the repo’s other issues to ensure this is not a duplicate:
</summary>
<img src="https://cloud.githubusercontent.com/assets/1652293/24973289/7e6259a4-1fbe-11e7-806a-ab1975831b5e.png" alt="screenshot">
</details>

**Comment by blinry** [comment] 2017-04-12 19:01
Any hints and suggestions on how to implement this – datastructure/protocol-wise – are welcome, I guess!

**Comment by winniehell** [comment] 2017-04-12 19:23
<details>
<summary>I made some mockups:</summary>

<img src="https://cloud.githubusercontent.com/assets/1652293/24975441/f7172c7e-1fc5-11e7-8d7f-39b94d0af17a.png" alt="add-poll">

<hr>

<img src="https://cloud.githubusercontent.com/assets/1652293/24975447/fc63ba44-1fc5-11e7-88f3-e065a728716c.png" alt="poll-options">

<hr>

<img src="https://cloud.githubusercontent.com/assets/1652293/24975449/fe586228-1fc5-11e7-92f5-04ad13e216d9.png" alt="vote">

</details>

**Comment by winniehell** [comment] 2017-04-12 19:35
My wishlist for this feature would be:

- up to 6 options (because 6 is more than 4)
- up to 30 characters per option (so that `Die Toilettenpapierhalterungen` fits in)

Later (second or third iteration):

- let poll creator allow voting on multiple options

**Comment by winniehell** [comment] 2017-04-12 19:58
These are the database changes that I would make:

- Add the following column to [`statuses`]:

```ruby
t.string "poll_options", default: [], null: false, array: true
```

- Create the following table:

```ruby
create_table "poll_votes", force: :cascade do |t|
  t.bigint "status_id"
  t.string "poll_option", null: false
  t.integer  "account_id"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.index ["status_id"], name: "index_poll_votes_on_status_id", using: :btree
end
```

[`statuses`]: https://github.com/tootsuite/mastodon/blob/v1.1.1/db/schema.rb#L229

**Comment by winniehell** [comment] 2017-04-12 20:06
These are the API changes that I would make:

- Add `poll_options` to the [`Status` entity]
- Adjust [endpoints for statuses] to respect `poll_options`
- Provide new `Poll` entity (only `GET` endpoint) which contains:
  - The status ID
  - The number of votes per option (anonymously)

[`Status` entity]: https://github.com/tootsuite/documentation/blob/v1.1/docs/Using-the-API/API.md#status
[endpoints for statuses]: https://github.com/tootsuite/documentation/blob/v1.1/docs/Using-the-API/API.md#statuses

**Comment by winniehell** [comment] 2017-04-12 20:19
I'd like to have a very simple implementation for the first iteration so that the feature could be shipped fast. This includes:

- Use boring radio buttons for voting.
- Avoid logic for expiring polls automatically.
- Don't allow poll options or votes to be edited later.
- Don't allow adding a poll to an existing status.
- Display results as numbers instead of bar charts. (getting bars drawn correctly on different screens isn't trivial)

As an alternative for expiring polls after a specified amount of time, we could introduce a `Close poll` button for the poll creator and a matching API endpoint.

**Comment by mkosler** [comment] 2017-04-13 05:14
Other than bringing over functionality that Twitter has right now, what does this add that using an outside site like http://www.strawpoll.me/ doesn't?

**Comment by winniehell** [comment] 2017-04-13 07:00
> what does this add that using an outside site like http://www.strawpoll.me/ doesn't?

It adds another way of interacting with followers without introducing a third-party service.

**Comment by hoodiek** [comment] 2017-04-14 01:10
a strong tool for this is also an "end notification"

twitter allows it to have an expiring date, but it can be hard to scroll back and find your poll, if you are an active user

**Comment by winniehell** [comment] 2017-04-17 19:41
@wxcafe Thank you for labeling the issue! :+1:

Is there a way to get feedback on the ideas above from mastodon maintainers or should I just start working on it and submit a pull request? :smile:

**Comment by jdmansour** [comment] 2017-05-29 15:05
This is a really nice feature, thanks for working on it! I fondly remember polls from my first social network at our university, this was before Facebook and Twitter existed. Polls are a fun and low-threshold way to engage a community and a good discussion starter.

One option I'd like to suggest is to make the poll anonymous vs non-anonymous. That is, in one case just show the percentages, and in the other case also show the names of who voted. I found anonymous polls good to get honest answers, and non-anonymous polls good for asking among friends, e.g. who wants to go watch which movie.

(Note in the anonymous case, the server would still know who voted how. It is highly nontrivial in a distributed system to make this truely anonymous. We would just hide the names - I think that is what you are doing right now anyway.)

And one question, (how) do you deal with remote accounts? Can they vote, too? Does Mastodon set a cookie if you interacted using a remote account, so that we can identify that you already voted and change the UI accordingly?

**Comment by 0xj9** [comment] 2017-06-21 01:46
please keep in mind that gnu/social already has a polls feature that you may want to try to be compatible with :)

**Comment by duck57** [comment] 2017-07-10 02:53
@hoodiek Having a "poll ended" notification would make Mastodon polls much better than Twitter polls.  Do you think the notification should just go to the poster of the poll or should it also go to users who voted in it in case they want to see the final results?

**Comment by Starless-Night** [comment] 2017-07-27 17:21
This sounds awesome especially if you can choose to have it in ranked choice voting.

**Comment by ThibG** [comment] 2018-04-19 13:51
I had a quick look at the subject, and it seems polls have already been thought about in ActivityStreams: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-question
https://www.w3.org/TR/activitystreams-vocabulary/#questions

Announcing, closing and responding to polls seems pretty straightforward with those specifications. I am not too happy with how results (intermediate or final) can be synchronized across instances, however.

**Comment by Gargron** [comment] 2018-04-19 14:16
@ThibG Indeed, simple enough to make it work so the origin server has a working poll, and it's possible to forward poll answers to the author's followers just like replies, but if the poll is boosted or loaded somewhere else there's no simple way to guarantee it displays complete results...

**Comment by nightpool** [comment] 2018-04-19 14:27
I mean, making results click-to-play is probably not an unreasonable idea.

**Comment by Gargron** [comment] 2018-04-19 14:33
If loading the results was a separate, click-to-play endpoint, then that would be a bit more acceptable, yes. I suppose we don't really care if the origin server lies about the responses, do we? So we could save them in a flat structure without trying to verify/normalize into a relational schema.

**Comment by ThibG** [comment] 2018-04-19 14:35
We could also try to forward replies along the same path we forward deletes: taking boosts into account. Not sure how that would scale.
Worst case, we could just have a link “view results” that goes to the public status view, but that's suboptimal.

**Comment by Gargron** [comment] 2018-04-19 14:37
Forwarding will not be necessary in the scenario nightpool suggests. Although you can probably forget about real-time updating bars like on strawpoll, I think...

**Comment by ThibG** [comment] 2018-04-19 14:48
Another thing I dislike with the proposed handling of results is the lack of privacy. Ok sure, we don't have very strong privacy expectations for this kind of things, but still, why would every server need to know who has voted what?

**Comment by Gargron** [comment] 2018-04-19 14:56
In that case maybe you don't want polls, maybe you want to use Strawpoll... Either that or ActivityPub needs a way to display answer counts without listing individual answers. Tbh, imagine a typical poll on Twitter, it can get thousands of replies. There are hardly any threads with thousands of replies, so this is a unique leap, and a JSON document with thousands of

```json
{
  "attributedTo": "http://sally.example.org",
  "inReplyTo": "http://polls.example.org/question/1",
  "name": "arduino"
}
```

is gonna weigh a lot of KB!

**Comment by nightpool** [comment] 2018-04-19 14:59
Oh yeah i was assuming remote servers would only ever see counts.

**Comment by ThibG** [comment] 2018-04-19 15:06
@Gargron yes, that's also why I don't like that representation (though it's probably not *that* bad). Thankfully, “This section is non-normative”. I think the suggested ways of announcing a poll and replying to it are fine, but we may want to decide on something else to display the results (a list of counts associated with the different answers seems fine).

**Comment by cwebber** [comment] 2018-04-20 13:27
Maybe each answer that shows up in the poll could itself be an AS2 collection which can give its totalItems, but which can (optionally, if non-anonymous) also expose its items (which are the actual response objects) in case anyone wants to "audit" it or see what their friends said?

I wonder what @evanp thinks?

**Comment by cwebber** [comment] 2018-04-20 13:28
so the collection's name in this case would be the answer to the poll

**Comment by spaceottercode** [comment] 2018-12-29 07:44
I was recently perusing the docs for activity streams, and like @ThibG the Question activity type reminded me a lot of this old issue.  Has it reached a stand still? (And how was Question activity meant to be use?)

**Comment by aka-rin** [comment] 2019-02-06 07:36
So what is the progress after nearly two years? Let me make a brief conclusion:

- Polls are necessary and simple, the problem is the federated part.
- Although AS has a standard for polls (problems), it is impractical to implement it.
- Problem 1: Should polls be treated like toots? 
- Consensus 1: No, it should be treated as an individual service (or else we need to consider the privacy part, re-boost part and more). As I see it, polls should be loaded as third-party content (like youtube videos), but you can interact with your Mastodon account.
- Problem 2: How to sync poll data between different instances?
- Consensus 2: If the poll is still active, it is impractical to load the real time result instantly (return result after you join the poll?). And if the poll is closed, it is impractical to load a long list of accounts (paginations?).
- Problem 3: How to protect privacy in polls?
- As far as I see, the user who call for a poll must specify the type (anonymous or public), voters(public means everyone, DM means invited users only, and so on) and expiration time for this vote.

Just my two cents ...

**Comment by Cassolotl** [comment] 2019-02-06 11:50
>Problem 2: How to sync poll data between different instances?

Part of it could be, there is a little "reload" button that fetches the latest results from the originating instance when clicked. There's probably a more automated way but I thought I'd suggest it because why not?

**Comment by aka-rin** [comment] 2019-02-06 14:20
> Can the system store who has voted separately from counting how many votes for each option? So it knows how many people voted "blue", and if you try to vote again somehow it's like "no you've already voted", but it doesn't have to be like "no you've already voted and we can see that you've voted for blue"?

That's easy to implement, but it may clash with the [ActivityStreams standard](https://www.w3.org/TR/activitystreams-vocabulary/#questions) and cause problems. For example, you can't retrieve your poll if you press the wrong option, since server can't verify it.

So I think anonymous polls are not necessary ... Maybe it should work in Twitter's way, storing all votes and voter's options, but not showing it up on interface.

**Comment by Cassolotl** [comment] 2019-02-06 18:54
>For example, you can't retrieve your poll if you press the wrong option, since server can't verify it.

That's pretty much how it is on Twitter too! It is a little inconvenient, so I can see why maybe Mastodon would want to do better.

Anyway, thanks for explaining. :)

**Comment by spaceottercode** [comment] 2019-02-10 02:16
I think point 2 that @Cassolotl mentioned is the same click to play point @nightpool made...but I could be wrong.

**Comment by ThibG** [comment] 2019-02-23 17:25
Revisiting this issue, I think we can have `Collection`s as options as @cwebber suggested.
When serializing the poll to AS, we would inline the `totalItems` but not the items themselves.
This would allow the numbers to be accurate whenever the poll is fetched.
If a remote poll does not have `Collection`s as options, or the `totalItems` is not inlined, we could include a link “See results on the original server”
We need to handle `Update` to close polls.
Instead of forwarding replies (like we do for usual replies), we could simply send an `Update` with the appropriate collection(s), changing its `totalItems`.

**Comment by trwnh** [comment] 2019-02-23 23:47
the `replies {items}` should contain at minimum who voted, which question they were voting in reply to, and what their option was. changing your vote should be as simple as sending another `Update` with your new option (and `attributedTo` the same `id`)

**Comment by ThibG** [comment] 2019-02-24 12:38
@trwnh we may want to avoid returning `replies` for both efficiency and privacy reasons, that's why we were talking about using a `Collection` with `totalItems`.

**Comment by duck57** [comment] 2019-02-25 00:33
I’m not sure if this is the proper discussion, but a feature polls should have is the ability to specify a closure time and (if a finite closure has been specified) the option to hide totals until the conclusion of voting.

Related, would it be a good idea to allow poll creators of polls with totals that can be viewed prior to casting a vote the option to disallow vote changes?

— Chris

**Closed** 2019-03-03 21:18 UTC
Labels: suggestion, ui

**Comment by colinstu12** [comment] 2023-07-28 01:41
(just mentioning https://github.com/mastodon/mastodon/pull/25015 here bc Google refused to return results showing the commit that added support for voting in one's own poll)
