### ISSUE TITLE
409 'Conflict during update, please try again' errors in browser

### ISSUE THREAD

**Issue by rodti** [tootsuite/mastodon#15267] opened 2020-12-03 20:23 UTC
**Expected functionality**

User interacts with the Mastodon web interface with no errors.

**Actual functionality**

Intermittent '409 Conflict during update, please try again' errors appear below the timeline.

**Additional information**
* Mastodon v3.3.0rc1
* This seems to happen when browsing other tabs or shifting to other applications, then returning to Mastodon.
* The console shows 'Failed to load resource: the server responded with a status of 409 ()' against resource https://domain.tld/api/v1/markers
* Affects Safari, not yet confirmed in other browsers but another user reports the same issue in Firefox
* This appears on one instance but doesn't seem to affect another with identical configuration

**Comment by Gargron** [comment] 2020-12-03 21:07
I saw this once on mine, too. Weird.

**Comment by mstdn** [comment] 2020-12-04 14:37
It appears constantly when closing the tab and re-opening somewhat later..

**Comment by ThibG** [comment] 2020-12-05 16:59
Seems like it could be caused by concurrent access to the markers API, but I'm not sure what could be causing the concurrent access in the first place…

**Comment by Gargron** [comment] 2020-12-06 23:56
If you have multiple tabs open or multiple apps that call the markers API, this could happen. It seems to me like the error can be safely ignored and we should just make sure to hide the alert.

**Closed** 2020-12-07 02:23 UTC
