### ISSUE TITLE
Invalid JSON in CollectionPage

### ISSUE THREAD

**Issue by sharpaper** [tootsuite/mastodon#13956] opened 2020-06-04 07:27 UTC
### Expected behaviour

Valid JSON.

### Actual behaviour

Invalid JSON.
1. `id` should be a string
2. `id` should probably contain the value of `uri`
3. either the terms are wrong or the context is, because all the terms are expanded as `_:<name>`

### Steps to reproduce the problem

Visit https://mastodon.social/users/Gargron/statuses/102739652870393458/replies?only_other_accounts=true&page=true

**Comment by ThibG** [comment] 2020-06-04 07:48
Sounds like the `id` and `uri` thing is because individual replies are not serialized properly, most probably because of the serializer changes in #13820. I am not sure if that change further broke context building or not, though.

**Comment by Gargron** [comment] 2020-06-04 10:11
@ThibG mastodon.social is not running that code yet, this is something older. Looks like it's just not using the correct serializer at all in there!

**Comment by ThibG** [comment] 2020-06-04 11:48
hm… weird… I cannot reproduce this issue in my dev environment (running latest master), nor on my production server (which runs glitch-soc, in which I have not merged the E2EE changes yet)

… do you have custom changes on mastodon.social that could cause this? :/

**Comment by Gargron** [comment] 2020-06-04 13:14
After investigation, turns out it's not a mastodon.social-specific bug (we don't have any customizations), but the bug doesn't always appear, it depends on the data.

**Closed** 2020-06-04 17:03 UTC
Labels: bug
