### ISSUE TITLE
Code syntax highlighting

### ISSUE THREAD

**Issue by n1k0** [tootsuite/mastodon#1782] opened 2017-04-14 15:45 UTC
Would be great being able to post snippets of code, eg

    ```js
    plop()
    ```

There are many Markdown libs out there which would allow processing such fenced code blocks. What do you think?

**Comment by Spunkie** [comment] 2017-04-14 17:58
This is a duplicate of https://github.com/tootsuite/mastodon/issues/853

**Closed** 2017-04-14 23:51 UTC
Labels: duplicate
