### ISSUE TITLE
Give the alternate text field its own modal window

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#8320] opened 2018-08-20 16:08 UTC
Currently, after having uploaded a media file, users have the possibility to add an alternative text to it.
Sadly, there is, in my opinions, three problems with the current implementation:
1. The field used for the input is really small, which make it difficult to use.
2. The field isn't a true field text, and spell checking isn't available as a result.
3. When you click outside the field and then go back to it, the cursor isn't positioned at the end but at the begging of the text. This is both quite annoying and impractical.

I would suggest that, instead of having the field right on the image, we use an icon and a small snippet of text (something like "Add alternate text") that, when clicked, open a modal containing the image and a proper text field. In that way, it would be similar to the "Crop" function we already have.
I think something along the lines of Twitter's implementation of this feature (see below) is what we should aim at.

![Twitter's image description modal window.](https://user-images.githubusercontent.com/5222316/44352002-771fd700-a4a3-11e8-8a4c-d27e04283134.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment] 2018-08-20 16:14
Kind of a duplicate of #6868 and #6713. I tried to do that this week-end by reusing the `ImageLoader` (and other components for other types of media) but it was much harder than anticipated, as `ImageLoader` is quite a pile of HTML and CSS hacks and adding anything to it turns out to be tricky.

**Closed** 2019-08-14 02:07 UTC
Labels: suggestion
