### ISSUE TITLE
Wrong video linked in preview

### ISSUE THREAD

**Issue by RGB-es** [tootsuite/mastodon#12448] opened 2019-11-22 23:13 UTC
See for example this toot

https://mastodon.social/@RGBes/103182330034574396

There is a youtube video linked on it. The thumbnail does not correspond with the video actually linked. If you click the right button on top of the video preview the correct video is opened in a new tab, but if you click on the left button on top of the preview you get the random video shown in the preview.

![Wrong-toot-video-preview](https://user-images.githubusercontent.com/7756783/69466564-c9c20000-0d84-11ea-8e81-4e9992ddfad2.png)

[BTW, this is the linked video: https://youtu.be/Nkxgt-O4nH8 all about astronomy]

This started to happen a couple of weeks ago. For example, this toot from October 14 shows the right video

https://mastodon.social/@RGBes/103138103590688492

while this toot from a few days later is wrong

https://mastodon.social/@RGBes/103166820555624583

**Comment by RGB-es** [comment] 2019-11-22 23:19
The problem seems to happen when you use the short video url you get from the "share" button below the video. If you use the long url the toot works as expected.

**Comment by Gargron** [comment] 2019-11-23 16:10
Duplicate of #12433

**Closed by Gargron** 2019-11-23 16:10 UTC
