### ISSUE TITLE
Enable White theme switcher

### ISSUE THREAD

**Issue by valentin2105** [tootsuite/mastodon#1588] opened 2017-04-12 00:16 UTC
It would be a great think to add the possibility to switch to a White theme ( in user settings ).

There is a clean white CSS version maybe it can be included and used when user enable white theme ? 

I have not the skills to implement this on Ruby.. 😄 

```
@-moz-document domain("mastodon.cloud"), domain("awoo.space"), domain("epiktistes.com"), domain("social.tchncs.de"), domain("memetastic.space"), domain("icosahedron.website"), domain("social.mashek.net") {
/*It's a mess, yes, but it works.*/

body {
    font-family: "Segoe UI", Frutiger, "Frutiger Linotype", "Dejavu Sans", "Helvetica Neue", Arial, sans-serif;
}

@media screen and (min-width: 360px) {
    .columns-area {
        margin: 5px;
        padding: 5px;
    }
}

.getting-started p {
    color: #292f33;
}

.status__content a, .reply-indicator__content a {
    color: #2b90d9
}

.status__content .status__content__spoiler-link, .reply-indicator__content .status__content__spoiler-link, .muted a.status__content__spoiler-link {
    transition: 150ms;
    background-color: #2b90d9;
    color: #fff;
    border: 1px #2b90d9 solid
}

.load-more:hover {
    background-color: #2b90d9;
    color: #fff;
}

.status__content .status__content__spoiler-link:hover, .muted a.status__content__spoiler-link:hover, .load-more, .status-card {
    color: #2b90d9;
    background-color: #fff;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}

.account__header .account__header__username {
    color: #F5F5F5;
}

.status, .detailed-status, .account, .status-check-box .status__content {
    border-bottom: 1px solid #e1e8ed;
    background-color: #fff;
    color: #292f33;
}

.detailed-status__action-bar {
    background-color: #fff;
    color: #292f33;
    border-top: transparent;
    border-bottom: 1px solid #e1e8ed;
}

.status__prepend, .notification__message, .column {
    background-color: #fff;
    color: #292f33;
}

.search-results__hashtag:hover, .search-results__hashtag:active, .search-results__hashtag:focus {
    color: #292f33
}

.search-results__hashtag {
    color: #292f33;
}

.column {
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.50);
}

.ui {
    background: #e1e8ed !important;
}

.drawer__inner {
    background-color: #2b7bb9;
    color: #fff;
}

.drawer__header, .account__action-bar {
    background-color: #292f33;
}

.drawer__tab {
    color: #F5F8FA;
}

.search__input {
    transition: 300ms;
}

.search__input:focus {
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.20);
}

.drawer__tab:hover, .drawer__tab:active, .drawer__tab:focus {
    background-color: #49a0de
}

.compose-form__buttons, .icon-button.inverted, .text-icon-button {
    color: #fff;
    background-color: #3b94d9;
}

.text-icon-button:hover, .text-icon-button:focus, .icon-button.inverted:hover, .icon-button.inverted:focus {
    background-color: #fff;
    color: #3b94d9;
}

.column-header, .column-icon, .column-back-button {
    color: #292f33;
    background-color: #eaeaea;
}

.column-back-button:hover, .column-icon:hover, .column-icon.collapsable:hover {
    color: #2b90d9;
}

.drawer__header a:hover {
    color: #2b90d9;
}

.search-results__header {
    color: #292f33;
    background-color: #eaeaea;
    border: none;
}

.collapsable {
    background-color: #393f4f;
    color: #fff
}

.drawer__inner.darker {
    background-color: #fff;
    color: #292f33;
}

.collapsable:hover {
    color: #fff
}

.detailed-status__display-name strong, .status__display-name:hover strong, .reply-indicator__display-name:hover strong, .detailed-status__display-name:hover strong, .account__display-name:hover strong, .detailed-status__display-name strong, .detailed-status__display-name span {
    color: #292f33;
}

.status__display-name strong, .account__display-name strong, .notification__display-name:hover {
    color: #292f33;
}

.account__header>div {
    background: -moz-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.35) 70%, rgba(0, 0, 0, 0.7) 100%);
    background: -webkit-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.35) 70%, rgba(0, 0, 0, 0.7) 100%);
    background: linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.35) 70%, rgba(0, 0, 0, 0.7) 100%);
}

.button {
    background-color: #2588d0;
    color: #fff;
    border: 1px #2588d0 solid;
}

.button:hover, .button:focus {
    color: #2588d0;
    background-color: #fff
}

.button:disabled {
    background-color: #9baec8 !important;
    color: #fff !important;
    cursor: default;
}

.text-icon-button.active {
    color: #292f33;
}
}
```
* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment] 2017-04-12 01:11
Perhaps this could be implemented with #659?

**Comment by tomfhowe** [comment] 2017-04-12 22:58
<button onclick="document.body.style.filter='invert(100%);';">light mode</button> (jk)

**Comment by tomfhowe** [comment] 2017-04-12 23:00
`<button onclick="document.body.style.filter='invert(100%);';">light mode</button> (jk)`

**Comment by Gargron** [comment] 2017-06-29 22:20
Duplicate of #317

**Closed by Gargron** 2017-06-29 22:20 UTC
Labels: enhancement, priority - low, ui
