### ISSUE TITLE
Boosting moves toots already on your home timeline

### ISSUE THREAD

**Issue by nikkisquared** [tootsuite/mastodon#458] opened 2017-01-11 21:50 UTC
I just had a situation that shuffled up the order of toots in my home timeline in a way I think is very confusing. I follow people A and B. A made a toot, B replied to A, and A replied back to B. Then, a moment later, A boosted B's reply. This caused me to see the toots in the order of: 1) A's first toot, 2) A's reply to B, and then 3) B's reply to A. I thought at first I had accidentally followed B to not see them in my home timeline, or something similar.

I've noticed boosting moving toots on my home timeline before, but it hasn't been more than an annoyance when it's not from the middle of a conversation. The situation described above, however, effectively scrambled the reading order of a conversation. This makes it very hard for me to understand what I'm seeing.

I think it would be a good idea to not have boosts re-arrange toots already on your home timeline. I realize that there might be time scope issues with this that probably should be considered. For instance, if somebody boosted a toot of their own from 2 days ago that they hope to get more attention, it could result the toot not going to the top of anybodies timeline, making repeat exposure more difficult.

Thoughts?

**Comment by Gargron** [comment] 2017-01-17 19:15
I'm afraid that while it may be annoying in some specific cases the "bumping up" is intended behaviour and closely tied with the way we do storage of the home feeds, so this is a wontfix

**Closed by Gargron** 2017-01-17 19:15 UTC
