### ISSUE TITLE
Relaxing Ruby version requirement

### ISSUE THREAD

**Issue by akihikodaki** [tootsuite/mastodon#1898] opened 2017-04-16 05:47 UTC
Ruby version requirement has been updated in #1159. It is nice to have the latest version, but I suggest to relax the requirement because of the following concerns:

* Ruby 2.3.x is still common for some Linux distributions.

The Software Collections for Red Hat and CentOS and Ubuntu 16.04 LTS still provides Ruby 2.3.x. Though [Ruby 2.4 brings various changes](https://docs.ruby-lang.org/en/trunk/NEWS-2_4_0.html), Mastodon still works on Ruby 2.3.x for now.

* `Gemfile` specifies the `TEENY` version.

That means Ruby and Mastodon should be updated at the same time; you cannot update before a newer version of Mastodon gets released, and visa versa, even if the change is expected to be compatible.

I would like to have `ruby '>= 2.3.0', '< 2.5.0'` in `Gemfile` to solve them, but I would also like to hear your opinions.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment] 2017-04-16 05:49
why not just `ruby '>= 2.3.0'`? Also feel free to make the PR and move the discussion there.

**Comment by yumetodo** [comment] 2017-04-16 05:53
@expenses ``Ruby 2.4 brings various changes`` is the cause , I supposed.

**Comment by akihikodaki** [comment] 2017-04-16 06:14
No, I put the one because Ruby 2.5.0 and the later versions, which are not released yet, may bring breaking changes, considering the versioning scheme.

**Comment by expenses** [comment] 2017-04-16 06:25
@akihikodaki Oh, ok, fair enough.

**Comment by wxcafe** [comment] 2017-04-16 13:27
since #1901 has been merged, I'm closing this

**Closed by wxcafe** 2017-04-16 13:27 UTC
