### ISSUE TITLE
Link @username@twitter.com to Twitter

### ISSUE THREAD

**Issue by jelv** [tootsuite/mastodon#7951] opened 2018-07-05 11:47 UTC
Some cross posters link to twitter with @username@twitter.com instead of the url. Example of this behavior: https://mastodon.social/@jancborchardt/100321912254837788. Would it be a good idea to link those links to https://twitter.com/username?

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by lfuelling** [comment] 2018-07-05 12:42
I thought about implementing this on my instance but then thought about the following: What if Twitter somehow decides to implement ActivityPub? It seems improbable sure, but for example one could argue that this would make them more attractive as more and more Twitter users turn to the Fediverse. (I don't know if that's the case though)

**Comment by ykzts** [comment] 2018-07-05 12:43
duplicate of #1849

**Closed by ykzts** 2018-07-05 12:43 UTC
