### ISSUE TITLE
Numbered columns

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#4006] opened 2017-06-29 23:56 UTC
And being able to press number keys on keyboard to focus them. (Then we could get rid of the whole "clicking outside toot text doesn't open it on the right" accessibility ~~mis~~feature)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment] 2017-07-11 22:20
duplicate of #2102, closing

**Closed by wxcafe** 2017-07-11 22:20 UTC
