### ISSUE TITLE
Cronogical disorder in my TL

### ISSUE THREAD

**Issue by moshpirit** [tootsuite/mastodon#3520] opened 2017-06-02 13:59 UTC
It's not like a big deal at all, but still something to fix, I believe. Below you can see a screenshot of my timeline where the message/toot by Eugen ( @Gargron ) is 1h sooner posted but still appears later and I don't know why.

Both accounts (Alex and Eugen) are from Mastodon, Alex is the admin of animalliberation.social, the server I'm using. Eugen has his account on mastodon.social

![](https://animalliberation.social/system/media_attachments/files/000/008/332/original/00fd9ea080a3c5ec.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2017-07-02 15:48
Duplicate of #545

**Closed by Gargron** 2017-07-02 15:48 UTC
