### ISSUE TITLE
Timeline keeps repeatedly jumping up and down

### ISSUE THREAD

**Issue by fluffy-critter** [tootsuite/mastodon#3648] opened 2017-06-08 23:43 UTC
On queer.party (running 1.4.1) I often have a problem when scrolling on the timeline where the view will start repeatedly jumping up and down. I suspect it's something to do with images being dynamically added and removed based on some threshold which is causing a dynamic equilibrium to occur.

See https://www.youtube.com/watch?v=PArRfqp0o4k for a video capture of the behavior. At the beginning of the video it's already taking place; then starting at 0:02 I'm scrolling normally, and then the behavior reappears at about 0:12. While I'm scrolling manually the behavior doesn't occur but it seems to be when the scrolling ends at a particular edge condition that it happens.

I am running Safari 10.1.2 (build 12603.3.3) on macOS Sierra.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by daprice** [comment] 2017-06-11 19:22
Possibly related to (or a duplicate of) #3407?

**Comment by fluffy-critter** [comment] 2017-06-11 19:28
The thing described in #3407 isn't quite the same as the thing described here. Your comments on that issue are certainly relevant to this one though. :)

**Comment by sorin-davidoi** [comment] 2017-06-11 19:44
Been scrolling through my federated timeline for 5 minutes and I could not reproduce this. However, I have a suspicion of what may be causing this: toggling between "rendered" and "unrendered" should not cause the position of the toots in the list to change (since we save the original height). But if one expands the content warnings the height changes (and we do not update it). Will try to confirm if this is the issue and attempt a fix.

**Comment by bbonf** [comment] 2017-06-13 14:33
I am experiencing the same issue. I can't tell exactly when it happens, but it seems to be related to the relative position of the toot that's at the border between visible and invisible toots.

Here are two screenshot showing the flickering class assignment in the web inspector, I hope it helps.
![a](https://user-images.githubusercontent.com/3629585/27087464-66fcdc40-5055-11e7-89a8-9bdea38efb4e.jpg)
![b](https://user-images.githubusercontent.com/3629585/27087465-6719d58e-5055-11e7-8d49-2c0e1694f087.jpg)

**Comment by sorin-davidoi** [comment] 2017-06-15 07:38
The potential fix was released as part of `1.4.3`. Let us know if this still happens.

**Comment by nightpool** [comment] 2017-06-15 17:13
Still experiencing this on 1.4.3
![shiver](https://user-images.githubusercontent.com/233815/27193320-610ea408-51cc-11e7-8f0f-0ed1e6501e05.gif)

**Comment by nolanlawson** [comment] 2017-06-17 22:06
I opened a separate issue for that jitter: #3776

**Comment by bbonf** [comment] 2017-06-19 14:43
I still see the original problem on 1.4.3 :/

**Comment by daprice** [comment] 2017-06-19 22:12
I can also confirm that the original jumping back and forth still occurs on 1.4.3

**Comment by fluffy-critter** [comment] 2017-06-22 03:37
Yeah, I'm still having this as well. :/ I managed to capture the DOM inspector this time. See https://youtu.be/BQKpc8QUqx0

**Comment by fluffy-critter** [comment] 2017-06-22 03:38
Could a repo contributor please reopen this issue? It isn't solved.

**Comment by nolanlawson** [comment] 2017-06-22 18:25
New redesign idea based on discussion [in this thread](https://toot.cafe/@nolan/862724):

1. When scrolled to the top, toots appear automatically like the current design
2. When `scrollTop` is greater than 0, show the number of toots as a little "unread count" alert in the header. Then users can just click on the header to scroll to the top.
3. When scrolled back to the top, new toots are shown.

This would prevent any jumpiness while also preserving the current behavior where you can watch the toots appear in real-time.

**Comment by fluffy-critter** [comment] 2017-06-22 18:32
I really like that design idea.

**Closed** 2017-06-27 16:43 UTC

**Comment by bbonf** [comment] 2017-07-22 08:18
I believe I'm seeing an incarnation of this (on 1.4.7) Should I open a separate issue?

![mastodon_flashing](https://user-images.githubusercontent.com/3629585/28489585-ddaec960-6ece-11e7-880a-1db4ff302e7b.gif)

**Comment by sorin-davidoi** [comment] 2017-07-22 09:01
Can you reproduce with the following steps?
 - Scroll to the bottom and **wait** (without scrolling) for new toots to be appended
 - **Wait** (without scrolling) for new toots to be added at the top - would suggest doing this in the federated timeline, since it updates faster

**Comment by bbonf** [comment] 2017-07-22 09:11
It doesn't reproduce this way. I am able to reproduce the problem when randomly scrolling the home timeline when no new toots arrive. (seems to be more common when letting it scroll with inertia)

**Comment by sorin-davidoi** [comment] 2017-07-22 09:12
Ok, thanks for testing. We would need to reopen this then...

**Comment by kode54** [comment] 2024-07-05 22:46
Seems to be happening here again, at least on the glitch fork on some other users' instances, when using Firefox with smooth scrolling enabled.
