### ISSUE TITLE
Automatically notify all followers to follow a new account

### ISSUE THREAD

**Issue by fallerOfFalls** [tootsuite/mastodon#2854] opened 2017-05-06 18:23 UTC
This is an interim measure. Ultimately it should be possible to migrate your account more seemlessly, but that's a complex issue. See #177 

Just a feature for automatically notifying all followers that you've now moved to another account (presumably on another instance) and giving them the option to follow you, would be extremely helpful.

So, I'm thinking somewhere in settings, there should be a place where you can say the instance you're migrating to, and then press the "Make it so" button. And all your followers get a notification like the one they get when they have a new follower. It could say something like
> *old_username* has migrated to *@new_username@instance*

followed by the follow-user button.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by pvols1979** [comment] 2017-05-11 14:17
I think ultimately it would be awesome if the feature allowed (in the background) some sort of transfer of all account info and delete on existing instance.  That would allow people to move around, notify followers, and retain all account info.  I would hope that the same protocols and methods being used across the platform would allow for this.

**Comment by Gargron** [comment] 2017-07-02 14:47
(Essentially) duplicate of #177

**Closed by Gargron** 2017-07-02 14:47 UTC
Labels: enhancement, priority - low, ui
