### ISSUE TITLE
Rapidly generating notifications results in internal server error (500) for the "liker" and broken notifications for the "likee"

### ISSUE THREAD

**Issue by chr-1x** [tootsuite/mastodon#4516] opened 2017-08-04 02:13 UTC
Observed by accident when @IrisKalma@cybre.space's bird stood on their keyboard and generated a bunch of broken notifications for me.

Reproduction: In the web client, tab until the focus is on the "favorite" icon of a post. Hold enter for a while. You will see "422: Status already taken" alternating with "500 Server error" until the API throttles you.

In the web client for the target account, refresh the page -- you'll see a bunch of notifications with no attached status (see firefox JSON view of the /notifications request)

![screenshot from 2017-08-03 18-42-47](https://user-images.githubusercontent.com/1606822/28951417-b497f118-787f-11e7-9e24-ea484e0dad83.png)
![screenshot from 2017-08-03 18-53-29](https://user-images.githubusercontent.com/1606822/28951403-a8142a1a-787f-11e7-948a-78b8bb978b3b.png)

Both users involved are on cybre.space but we're not running any modifications that affect the function of the "like" button or any serverside processing.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2018-10-22 23:10
Duplicate of #2865

**Closed by Gargron** 2018-10-22 23:10 UTC
Labels: api, bug
