### ISSUE TITLE
Column not put on Firefox (desk, win / linux)

### ISSUE THREAD

**Issue by Geobert** [tootsuite/mastodon#1374] opened 2017-04-09 21:23 UTC
When the column is not at the top, it's supposed to stay put like Tweetdeck does. On Firefox, the toots moves down when new toots arrive (the scrollbar does not move though). 

After discussion with other user, Chrome works well, not Firefox :(

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Geobert** [comment] 2017-04-11 12:17
Just seen the toots going upwards this time, so maybe some kind of delay while loading toots making the whole column shaking and very hard to read.

**Comment by Geobert** [comment] 2017-04-19 07:26
Still seeing this in 1.2

**Comment by Gargron** [comment] 2017-06-29 21:33
Duplicate of #1306

**Closed by Gargron** 2017-06-29 21:33 UTC
Labels: bug, ui
