### ISSUE TITLE
Cannot boost unboosted toots

### ISSUE THREAD

**Issue by nikhita** [tootsuite/mastodon#2141] opened 2017-04-19 12:20 UTC
I boosted a toot and by mistake, clicked on the boost button again ending up unboosting it.

However, when I click the boost button again, I am unable to boost it and get a `404 record not found` message. I get this message after successive clicks on the boost button too.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rmmbear** [comment] 2017-04-19 21:53
This duplicates issue #574 (although that one seems to be old and forgotten?).

**Comment by wxcafe** [comment] 2017-04-20 00:34
duplicate of #574, which is definitely **not** forgotten

**Closed** 2017-04-20 00:39 UTC
Labels: duplicate
