### ISSUE TITLE
Follower count becomes incorrect when removing too many followers at once

### ISSUE THREAD

**Issue by MirceaKitsune** [tootsuite/mastodon#11554] opened 2019-08-12 13:23 UTC
In some cases, Mastodon will no longer list your follower count correctly if you remove too many followers at once. Once this issue occurs, the counter only gets bumped for new followers while ignoring all old ones.

I noticed this after my account was spammed with 2.000 fake follows by a bot instance: I went to Settings - Follows and Followers, clicked on the Followers tab, selected one bot from the offending instance, then used "Remove all followers from the selected domain". The bots were successfully removed, but now the instance says I have 0 followers despite having 10.

![Screenshot_20190812_161001](https://user-images.githubusercontent.com/825418/62867878-ff366680-bd1c-11e9-99f6-ff50b783f116.png)

**Comment by Gargron** [comment] 2019-08-12 16:11
Duplicate of #11403

**Closed by Gargron** 2019-08-12 16:11 UTC
