### ISSUE TITLE
Feature suggestion: Shared Domain Blocks

### ISSUE THREAD

**Issue by WorldMaker** [tootsuite/mastodon#5521] opened 2017-10-25 02:37 UTC
I was looking for lists of suggested domain blocks as a baseline for a tiny instance I'm running, and wound up at [toot.cafe's blocked instance list](https://github.com/tootcafe/blocked-instances). It seems like a good start, and there are a couple things I notice: 1) how many of the suggestions as noted in the block reasons currently have to pass word of mouth, 2) the repository is missing some useful machine formatted version of the table like a CSV or JSON file.

It seems to me that it would be great as a small instance administrator to be able to more quickly piggy back off the work of larger instances. Say that I trust toot.cafe's list as a starting point, it would be great to just be able to add that git repository or a CSV/JSON file directly into Mastodon as a domain block source.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment] 2017-10-25 02:45
duplicate of #3874?

**Comment by WorldMaker** [comment] 2017-10-25 03:08
#3874 seems orthogonal to me. It suggests having public lists with reasons accessible from inside an instance to present to curious users (which may not be a good idea in some cases to have such an autogenerated list); I'm suggesting allowing hand-curated lists outside of an instance that an instance might subscribe to for a list of socially shared/suggested blocks.

**Closed** 2018-07-14 19:58 UTC
