### ISSUE TITLE
"Add or remove from lists" option + multi-choice list selection on profile

### ISSUE THREAD

**Issue by aquariusdev** [tootsuite/mastodon#7187] opened 2018-04-18 18:16 UTC
I'm glad [lists have been added since last year](https://github.com/tootsuite/mastodon/pull/5703), but can you add the ability to add/remove users to/from lists on their profile? 

Mockup 1, borrowed a bit from Diaspora:
<img width="321" alt="mastodon aspects dropdown mockup" src="https://user-images.githubusercontent.com/28520002/38939888-e2933ab8-42f6-11e8-9ae5-fd64b15d8056.png">

Mockup 2, using existing menus on Mastodon:
<img width="429" alt="mastodon add to remove from lists thru profile" src="https://user-images.githubusercontent.com/28520002/38940962-7c4d5380-42f9-11e8-93ab-ead43691a455.png">

Mockup 3, using Twitter's Add to/Remove from Lists pop-up:
<img width="543" alt="twitter multi-select" src="https://user-images.githubusercontent.com/28520002/38941533-c0510d6e-42fa-11e8-8de8-9364f880de2e.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment] 2018-04-19 15:02
Duplicate #6058 - _[Suggestion] Add user to list, from context menu on toots + from their profile, and populate new lists._

**Comment by raingloom** [comment] 2018-04-26 14:36
To illustrate why and just how badly the current lists UI doesn't work:

I find someone who toots interesting things about, idk, ducks. I want to add them to my `ducks` list. Currently, I have to:

 1. open the Getting Started menu
 2. click on Lists
 3. click on the `ducks` list
 4. click Show Settins (which is quite easy to miss)
 5. click Edit list
 6. search for the person
 7. add the person from the search results
  7.1. the person has gone through 14 instances and I didn't memorize which instance they were on, the lists UI does not give me a preview of their posts
  7.2. I have to go back and check which instance they are on
  7.3. (repeat steps 1 through 6)
  7.4. finally add the person

**And let's not list what I'd have to do to see what lists a person is in.**

# Alternative solution
Show what lists a person is in beneath their profile description in the app and let the user edit that as text. Same way toot tagging works. It can even have autocomplete.

This also makes creating new lists easier.

![asd](https://user-images.githubusercontent.com/8085052/39312258-6ede7036-496f-11e8-978f-c5fb467ef9da.png)

What @aquariusdev suggested is not bad but this would make adding a person to multiple lists faster, especially if someone has many lists. (because they can just type the name from memory instead of looking through them all)

**Comment by Gargron** [comment] 2018-10-23 02:28
Duplicate of #6058

**Closed by Gargron** 2018-10-23 02:28 UTC
Labels: suggestion, ui
