### ISSUE TITLE
Character count for bio, and bio length modification

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#1447] opened 2017-04-10 16:27 UTC
it's in the title. i also would suggest the size be expanded to 500 characters, as i have said before i think it is only appropriate it be a toots-length of characters

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JuanjoSalvador** [comment] 2017-04-17 21:43
This could be fixed using userscript, I guess.

**Comment by KellerFuchs** [comment] 2017-04-18 21:19
Design suggestion from #2058 :
>Instead, switching to displaying the number of remaining characters (or excess characters) above a certain threshold (say, 120) would provide immediate, precise feedback.
>
> I suggest using a threshold because UI elements that change as one types are distracting, and can cause accessibility issues for some neurodivergent users.

Moreover, @bingen13 (who is blind) commented on other accessibility concerns:
> A small click 10 or 8 chars before the limit, and a louder click on trying to add chars beyond the limit, would be quite a nice UI addition for me.

**Comment by blinry** [comment] 2017-04-21 16:25
So the "character count" half is done, to close this issue, we need a consensus on the maximum bio length. 

IMHO, bios of 500 characters would look rather weird in the current UI:
![screenshot-2017-04-21_18 23 52](https://cloud.githubusercontent.com/assets/81277/25286963/d36de0be-26bf-11e7-913b-b5220d37cd67.png)

**Comment by Cassolotl** [comment] 2017-04-21 17:45
I think my preference would be around 200? But I don't mind really.

**Comment by Cassolotl** [comment] 2017-05-01 21:23
This is a duplicate of #232, opened November 2016, which has some other nice suggestions in it too.

**Closed** 2017-05-13 21:54 UTC
Labels: enhancement, priority - medium, ui
