### ISSUE TITLE
Mastodon crashes after a couple of hours in idle in Chromium-based browsers

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#12440] opened 2019-11-21 18:17 UTC
### Expected behaviour

Mastodon shouldn't crash when I go to sleep and go back to my computer

### Actual behaviour

Mastodon crashes after a couple of hours

### Steps to reproduce the problem

Just leave Mastodon open over night and lock your computer, work for a day and then it crashes.

### Specifications

Mastodon version: Latest
Operating system: All
Client: Web
Browser: Vivaldi, Google Chrome etc. (anything Chromium-based)

### Log

```
TypeError: Cannot read property 'getWrappedInstance' of null
    at https://koyu.space/packs/js/application-93c929e75d0c677aeee2.chunk.js:1:31329
    at pi (https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:34:75173)
    at mi (https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:34:75715)
    at vi (https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:34:77391)
    at zi (https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:34:81515)
    at Ki (https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:34:85080)
    at https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:34:98357
    at Object.t.unstable_runWithPriority (https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:43:3200)
    at Ns (https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:34:98291)
    at Fs (https://koyu.space/packs/js/common-9729dedd0e2546e5c545.js:34:98067)
```

**Comment by ThibG** [comment] 2019-11-21 19:14
Is there another error in the logs before this one?

A PR to fix that exact crash point has landed in master (but not in any release yet), but I'm not confident it addresses the root cause of the issue.

**Comment by koyuawsmbrtn** [comment] 2019-11-21 20:54
No, this is a 1:1 copy of the logs I was able to get.

**Comment by ThibG** [comment] 2019-11-21 20:57
Ok. The PR I was talking about is #12274. Is it possible for you to try with that commit merged?

**Comment by koyuawsmbrtn** [comment] 2019-11-22 00:07
Sadly not, my dev environment is not set up yet

**Comment by bubblineyuri** [comment] 2020-03-30 16:42
I think this ticket can be close now. The issue has been resolved. Sadly I cannot close tickets from my banned account so I have to wait for a maintainer to do it.

**Closed** 2020-03-30 16:44 UTC
