### ISSUE TITLE
OStatus URIs and Mastodon handles

### ISSUE THREAD

**Issue by ThibG** [tootsuite/mastodon#2012] opened 2017-04-17 15:05 UTC
Hi,
It seems to me that Mastodon handles (@user@domain) are mostly undefined.
Indeed, to the best of my knowledge, they are based on an optional feature of OStatus: finding remote feeds and API endpoints using webfinger. However, this mechanism is both optional and unidirectional: as far as I know, even if the feeds and the API endpoints are discoverable through a webfinger query for acct:user@domain, they do not have to refer to “user” or “domain” in any way.

Worse, OStatus not being based on those handles, interactions typically never mention them even if they exist, and mention authors' URIs (which are not restricted to a specific format by OStatus) instead.

From my understanding of the code, Mastodon handles this situation in a few different ways (sometimes differently depending on the part of the code used):
- If given author information from an atom element (e.g.: salmon API request), it builds a @user@domain handle by using the author's name field as “user” and assume the author's URI to be an URL, using its domain part for “domain”
- If it has to process an URI matching an already-known account (thus with a known handle), it uses that
- Otherwise, if the URI is not known, it assumes it is an URL to a web page with a pointer to an atom feed, from which it uses the author's email field if present, or the author's name as the “user” and the domain part of the *feed*'s URL.

This seems ill-defined to me, especially since there seem to be three (well, one of them is my fault) different ways to build a handle for an unknown user (author's email ; author's name + URI host part ; author's name + feed URL part), and at least two to find known users (URI, or author's name + URI host part) depending on the part of the code.

**Comment by ThibG** [comment] 2017-04-17 15:26
To me, it makes sense to:
1. Require remote users to be discoverable via webfinger (this is already the case as far as I can tell)
2. Require the feeds' author's “email” field to map back to the webfinger-discoverable handle (this does not break federation with existing Mastodon instances)
  This may break federation with non-Mastodon OStatus servers, but I have no data on this.
3. Unknown account discovery should be opportunistic and not impose other requirements.
  (In particular, we should not require the URI to be an URL, nor require that URL domain to match the
  account's domain)

Given an URI, we should directly return matching users (this is already the case *for most parts of the code*).

For unknown account discovery, the goal is to find a handle (that then has to be queried via webfinger) given an URI or an “author” element from an atom element. It should behave predictably and reliably discover existing Mastodon instances, even when WEB_DOMAIN and LOCAL_DOMAIN are different.
Following the previous requirements, I propose the following:
- If we have an “author” element with an “email” element, use it as the handle to discover
- If we have an URI, assume it's an handle (in which case, use it directly) *or* an URL to a feed or a webpage pointing to a feed, in which case it must have an “author” element with an email.

**Comment by ThibG** [comment] 2017-04-17 15:38
In any case, the current handling of remote accounts is inconsistent and might be slightly broken (I have to check, but I'm under the impression that salmon requests from instances with WEB_DOMAIN ≠ LOCAL_DOMAIN to other instances is broken).

Thinking more about it, the second requirement (author's “email” field mapping back to the webfinger-discoverable handle) might not be strictly needed for federating with other non-Mastodon services, but in this case, it must be clear than no interaction will be possible unless that remote account is first discovered from the instance using a webfinger-discoverable handle.

**Comment by ThibG** [comment] 2017-04-17 16:53
According to OStatus, in the absence of an “/xmlns:feed/xmlns:author/xmlns:uri” tag, email must be used as a “acct:” URI (Mastodon doesn't do that for now), so that fits nicely with the above proposal.

A last concern about Mastodon's handling of remote accounts is the handling/verification of URIs: what if two remote accounts declare the same URI?

**Comment by dariusk** [comment] 2017-04-24 00:33
I just propped up a fresh instance at https://social.tinysubversions.com with

```
LOCAL_DOMAIN=tinysubversions.com
WEB_DOMAIN=social.tinysubversions.com
```

And I still can't see that user from mastodon.social even with the recent (12 hours ago) commit 89dc29a referenced just above. Switching LOCAL_DOMAIN to social.tinysubversions.com immediately fixed the issue so I'm guessing this issue isn't fully resolved here?

**Comment by dariusk** [comment] 2017-04-24 00:36
Oh, or does this mean the change just hasn't been deployed to mastodon.social yet? Sorry, I'm not too clear on the server code so I don't know if 89dc29a is running on the server that is _looking_ for the aliased domain or if it's for the server that is _advertising_ the domain.

**Comment by nightpool** [comment] 2017-04-24 00:38
Advertising. I think there's an issue that was just opened that this is a
duplicate of.

**Comment by ThibG** [comment] 2017-04-24 02:47
@dariusk it's on the server advertising the domain: current versions of Mastodon will look up at username@uri.host on inbound salmon requests, which is a bit broken, but can be worked around by responding to acct:user@WEB_DOMAIN requests with data for acct:user@LOCAL_DOMAIN.
As for your particular issue, it seems you're lacking a /.well-known/host-meta file, as I wrote on #2375.

**Closed** 2019-08-08 18:12 UTC
Labels: api, suggestion
