### ISSUE TITLE
Media-only toots should be clickable

### ISSUE THREAD

**Issue by kit-ty-kate** [tootsuite/mastodon#9197] opened 2018-11-02 19:52 UTC
### Expected behaviour

Clicking anywhere that is not a link (e.g. not on icons/menu, profile picture, the media, time, name/handle) on a media-only toot should open the said toot.

### Actual behaviour

This currently does nothing and we have to open the menu and click on "expend this status" to actually open it. This is not straightforward.
Toots with texts can be opened by clicking on the text and this looks like straightforward behaviour, one would expect to be able to do the same thing with every toots regardless of their content.

### Specifications

Mastodon 2.6.1

**Comment by Gargron** [comment] 2018-11-02 21:43
Duplicate of #8529

**Closed by Gargron** 2018-11-02 21:43 UTC
