### ISSUE TITLE
Option to delete profile picture and cover photo

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#6503] opened 2018-02-18 15:39 UTC
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2018-02-26 23:27
I think this is a duplicate of *Impossible to erase images in config #4458*.

**Closed** 2018-02-27 05:57 UTC

**Comment by ThisIsMissEm** [comment] 2018-04-15 16:45
This is also implemented partially from a moderator perspective in #6998
