### ISSUE TITLE
Feature: file storage plugin of IPFS

### ISSUE THREAD

**Issue by FingerLiu** [tootsuite/mastodon#7657] opened 2018-05-28 15:05 UTC
I am a mastodon heavy user, and a huge fan of IPFS.
For the purpose of decentralization, how about we build **a storage plugin to store images
to IPFS**?
I've read IPFS code but not familiar with mastodon code, any idea of where should I start?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment] 2018-05-28 16:13
duplicate of #360 

to get any benefit from using IPFS, you'd have to have other instances using it as well—otherwise there's no benefit over just storing the images locally. 

what are your thoughts for how an ipfs plugin would function from a high level?

from a technical level, what you'd want to do is read the Paperclip docs on how to implement a storage backend.

**Closed by nightpool** 2018-05-28 16:13 UTC

**Comment by FingerLiu** [comment] 2018-05-29 02:34
One thing we can get benifit from IPFS is that if other instance don't support IPFS we can just render it from public gateway(ipfs.io/xxx) and the image hash.
