### ISSUE TITLE
Clarify meaning of "Unlisted" when tooting

### ISSUE THREAD

**Issue by daprice** [tootsuite/mastodon#1201] opened 2017-04-07 21:54 UTC
This might be a matter of opinion, but as someone coming from Twitter I'm confused by the wording of the description of "Unlisted" when posting a toot.

![img_0216](https://cloud.githubusercontent.com/assets/3615519/24820905/301e250e-1bb1-11e7-8337-6d770a379dda.PNG)

My thought process when first seeing the "Unlisted" option was "ok, if it's not shown in public timelines, then where is it shown? Is there such a thing as a non-public timeline?" Since I'm familiar with the twitter/facebook model, when I read "do not show in public timelines" my first thought was "oh, that would mean it only shows up to my followers, since private (aka followers only) is the opposite of public." But then there's a separate option for "private" that is followers only, so "unlisted" is unclear. Does it mean the toot goes to the "local" timeline but not the "federated" one (which seems to be synonymous with "public", but both terms are used in different places in the UI)?

I think part of the confusion stems from the fact that the definitions of the "Public", "Private", and "Direct" options are written in terms of where the toot *does* go, but the one for "Unlisted" is written in terms of where it *doesn't*. It would be clearer IMO if the description of "unlisted" explained where the toot *does* show up, e.g. something like "Post to local timeline, but not federated ones" (if that's indeed what it does – I'm still not really sure even after reading the related issue #172).

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kirkmawa** [comment] 2017-04-07 22:02
I always thought it meant "post to user profile and to followers, but not local/federated timelines" but maybe someone else can clarify.

**Comment by wxcafe** [comment] 2017-04-09 15:09
It does mean "post to user profiles and to followers, but not local/federated timelines". Private is different in that it doesn't post to your profile, like private twitter accounts do : you have to be logged in and following the user to see the toot

**Comment by wxcafe** [comment] 2017-04-09 22:51
This is a duplicate of #1319 and as such I'm closing it.

**Closed by wxcafe** 2017-04-09 22:51 UTC

**Comment by msappir** [comment] 2017-04-11 14:23
In the other issue I suggested this minimal edit, and it seems to do the trick without adding a line break:
![170411-privacy_text1](https://cloud.githubusercontent.com/assets/7591121/24913928/61bd745c-1edb-11e7-8753-7909612d8b9d.png)

**Comment by caos30** [comment] 2019-07-04 04:05
I'm sorry to reopen this thread, but i continue founding confuse the type "Unlisted". Before comment here, I've read the issue #1319, but certainly it doesn't talk about "Unlisted" message type, but "Only-followers".

Can someone detail the EXACT DIFFERENCE between "Unlisted" and "Only-followers"? 

Furthermore, can someone confirm to me what is said in that issue: "Only-followers" messages are seen ONLY by LOCAL followers? I cannot believe it. I means: the main interest for a "federation of social networks" is to be able to follow and be followed by people of other instances... So, there would be a message type "Only-around-followers", i think so. 

Said with other words, maybe the attempt to make a categorization of "scope/visibility" of a message USING A UNIQUE "dimension" is an error. I think that like in the categorization of Creative Commons licenses is necessary to manage different marks for different dimensions:

- attribution mention: yes / no
- commercial use: yes / no
- etc...

So in this question of the visibility of a message in a federated social network, the unique clear and effective way to give control the user is to let set marks over different DIMENSIONS:
- Global Timelines: Yes/no
- Local Timelines: Yes/no
- Followers: Yes/no
- Global searches: Yes/no
- Local searches: Yes/no

It's my opinion. But i recognise that i'm a newbie in Fedivers.

**Comment by caos30** [comment] 2019-07-04 04:18
Reading the "new" guide here [https://github.com/joyeusenoelle/GuideToMastodon/](https://github.com/joyeusenoelle/GuideToMastodon/ ) it says:

- **Public** means that everyone can see your post.
- **Unlisted** means that everyone can see your post, but it won't appear on the public timelines - either Local or Federated. Anyone who follows you or views your profile can see the toot, though.
- **Followers-Only** means that only people who follow you and people mentioned in the post can see your post in their timelines or on your profile page. If someone who doesn't follow you views your profile, they won't see this post.
- **Private** means that only people who are mentioned in your post can see it in their timelines or on your profile page.

So, after reading these definitions several times, i think that instead of "Unlisted" maybe it would be more clear to name it "**Profile & followers**". Am i wrong?

**Comment by Gargron** [comment] 2019-07-04 04:50
Please refer to the official user documentation: https://docs.joinmastodon.org/usage/privacy/#publishing-levels

**Comment by caos30** [comment] 2019-07-04 17:59
Perfect! Let me share here this interesting table from that official documentation :-)
![imatge](https://user-images.githubusercontent.com/1767547/60682740-5eb17480-9e49-11e9-82fd-0d51c6bbd650.png)

After read that documentation i understand now better this question: the important thing is to decide who to communicate to your new post (public timelines, profile, home feed). In other words, followers is NOT  a DESTINATION where to publish (!), but simply people SUBSCRIBED to new posts on your "home posts".

**Comment by James-Firth** [comment] 2022-11-21 17:35
For anyone looking around these days the current official documentation link is now: https://docs.joinmastodon.org/user/posting/#privacy

**Comment by nickpsnapper** [comment] 2023-01-01 19:05
If a non-follower loads a public post, and that post has an Unlisted reply (also from myself), will the visitor see the reply? Trying to understand if I should encourage users to Add Toots to threads with Unlisted as the default.

**Comment by trwnh** [comment] 2023-01-01 21:27
@nickpsnapper yes, unlisted replies will show up in threads, regardless of who sent it.
