### ISSUE TITLE
Allow login with same credentials among federated instances

### ISSUE THREAD

**Issue by mustaqimM** [tootsuite/mastodon#1828] opened 2017-04-15 06:24 UTC
I feel if instances are federated with one another, then instead of creating multiple accounts for each instance, a user should be able to login with an account created with one instance.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by randoms** [comment] 2017-04-15 08:25
I want this feature too.
Without this feature, it cannot avoids the risks of a single company monopolizing your communication. Your account only exists on a single server, so the own of the server can close your account easily, he or she can also force you to delete or edit your posts.

**Comment by wxcafe** [comment] 2017-04-15 10:20
This is a duplicate of so many other issues I'll let you look for them yourself, closing

**Closed by wxcafe** 2017-04-15 10:20 UTC
Labels: duplicate
