### ISSUE TITLE
Open toot when clicking on the blank zone below profile picture

### ISSUE THREAD

**Issue by roipoussiere** [tootsuite/mastodon#8529] opened 2018-08-30 12:23 UTC
When a user posts a toot containing only a picture, it's annoying to open the toot, because when you click on it, it just opens the picture.

![1](https://user-images.githubusercontent.com/1665542/44851009-45ef9580-ac5f-11e8-9c6e-a679d081993b.png)
*User: hmm, where I'm supposed to click to open this toot?*

Of course you can open it by clicking on the three-dot button, then open toot. But many users don't know this trick and it's two clicks instead one: maybe we can improve the usability for this scenario.

My suggestion is to open the toot when the user clicks on the blank zone below the profile picture:

![2](https://user-images.githubusercontent.com/1665542/44851053-64559100-ac5f-11e8-9f73-012e5a4bc977.png)

In this way it's still possible to open any toot, with or without text, with or without image.

![3](https://user-images.githubusercontent.com/1665542/44851273-0d9c8700-ac60-11e8-88a4-13822cc6dd9e.png)
![4](https://user-images.githubusercontent.com/1665542/44851275-0f664a80-ac60-11e8-8b79-f1590d35706a.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by zcdunn** [comment] 2018-08-30 13:35
This would especially be an improvement on mobile, where it's nearly impossible to open some posts with one tap.

**Comment by Cassolotl** [comment] 2018-08-30 16:32
This is a duplicate of *image-only toots don't have any space to click on to load them in the 4th column #564*, which was closed. It's also related to *On toots with only URLs, there is nowhere in the toot area to click to expand the toot #4314*, which I opened because I didn't like that the first one was closed!

**Comment by roipoussiere** [comment] 2018-08-30 17:30
Ok, thanks, I didn't find these issues.

But here I propose a concrete suggestion.

**Comment by Down10** [comment] 2018-08-31 04:10
I would note that the post date (in the upper right corner) is a reliable place to open the toot's permalink page. Maybe make the hitbox for that link a little larger?

**Comment by Cassolotl** [comment] 2018-08-31 07:55
That opens the toot in a new tab, which you can't interact with, rather than expanding it in the last column

**Comment by trwnh** [comment] 2018-09-01 01:32
One problem: the current "blue area" you highlighted is for selecting and focusing a certain toot already. If clicking in that area is made to open the toot instead, then navigating the column by keyboard shortcuts would become a lot harder, as you would have to click Tab 23 different times just to select the top toot in the Home column, and then who knows how many times down to reach some arbitrary position.

**Comment by yaomtc** [comment] 2018-09-02 00:15
Couldn't "expand" be moved out of the '...' menu and into its own button? Or at least that could be done when there's no text...

**Comment by roipoussiere** [comment] 2018-09-05 09:29
Ok, I understand the problem, I didn't know that this area was already dedicated to a "focus" feature.

What about this?

![44851273-0d9c8700-ac60-11e8-88a4-13822cc6dd9e](https://user-images.githubusercontent.com/1665542/45084563-ea118a80-b0fe-11e8-94a1-6e61fefdd23a.png)

**Comment by roipoussiere** [comment] 2018-09-05 09:43
Or maybe a new dedicated button to expand the toot, like this?

![toot_suggestion_with_button](https://user-images.githubusercontent.com/1665542/45085368-d36c3300-b100-11e8-94a7-df75a868dd69.png)

**Comment by roipoussiere** [comment] 2018-09-06 08:45
> One problem: the current "blue area" you highlighted is for selecting and focusing a certain toot already. If clicking in that area is made to open the toot instead, then navigating the column by keyboard shortcuts would become a lot harder, as you would have to click Tab 23 different times just to select the top toot in the Home column, and then who knows how many times down to reach some arbitrary position.

In fact, I think these 2 behaviors are compatible: a click on a blank zone could focus the toot *and* open it, it's not so annoying.

**Comment by Cassolotl** [comment] 2018-10-07 07:41
This is extremely annoying.

![noclicky](https://user-images.githubusercontent.com/6607512/46579581-b16e1500-ca0c-11e8-872e-10d06b4392bb.gif)

**Comment by trwnh** [comment] 2018-10-07 19:55
@Cassolotl Technically right now, the next step after clicking the blank area is to hit Enter on your keyboard. That expands the toot without having to use the ... menu. Which I guess is the reason this issue exists, because that's non-obvious unless you know how keyboard shortcuts work.

**Comment by Cassolotl** [comment] 2018-10-07 21:39
Yeah, if you're clicking with your mouse then you're probably not going to expect to have to switch to keyboard commands when you don't have to do that for posts with text!

**Comment by BenLubar** [comment] 2018-10-21 03:39
I'd like to point out that on toots containing text, there is no gap between the username and the text that isn't clickable.

On image-only posts, there *is* a gap with no interactivity.

**Comment by ryliejamesthomas** [comment] 2018-12-16 10:32
Subway Tooter uses an icon with two speech bubbles for this, I like its position as the left-most icon.

![subwaytooter](https://user-images.githubusercontent.com/25972447/50052556-069b7500-017a-11e9-9b38-004dc40df05a.jpg)

**Comment by crockwave** [comment] 2019-02-05 16:46
Another possible solution is to auto-insert a new line above a link or image, so that there is one line available above the link/image that can be hovered over to open the toot

**Comment by roipoussiere** [comment] 2019-02-06 10:36
I'm pretty sure that clicking on a blank zone should be sufficient, because it's not so annoying for keyboard shortcuts users: the toot is just displayed on a column and they can continue to use their keyboard to navigate.

And it's probably the most instinctive way for a user to open a toot.

**Comment by Cassolotl** [comment] 2019-05-15 09:01
This should have been fixed with *Adds click-able div that expands status (#10733)*, right?

**Closed** 2019-06-14 22:10 UTC
Labels: suggestion
