### ISSUE TITLE
Mastodon Causing Load Spikes on GNU Social Instances

### ISSUE THREAD

**Issue by ThatBrickster** [tootsuite/mastodon#1813] opened 2017-04-14 23:23 UTC
Summary:
GNU Social admins have been experiencing heavy load originating from Mastodon instances.

Description:
For the past week, there has been a massive influx of new users on the platform and some have decided to host new instances of Mastodon. The problem with the federation of users (and possibly followbots) is that there have been cases where load averages on GS instances like GNU/Smug, FreezePeach and Sealion have noticeably jumped since the attention Mastodon received from technology news sites and InfoSec professionals, and has forced some GS admins to redirect spammy requests elsewhere. I believe it's down to Mastodon constantly asking for timeline data and I know there have been efforts to mitigate the problem such as making use of a cache like Varnish. 

STR:
None, although admins of affected instances are free to offer reproducible examples.

Actual Results:
GNU Social instances have been bombarded with enough requests to go down (unintentional DDoS).

Expected Results:
Mastodon and GNU Social should be able to play nicely without one negatively affecting the other.

* * * *

- [x] I have searched/browsed the repo's other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-14 23:42
If you are experiencing load problems, please instance block until you can sort out performance on your end. the mastodon software developers cannot help you with traffic spikes.

Since this is not related to mastodon the software itself, I'm closing this as invalid

**Closed by wxcafe** 2017-04-14 23:42 UTC

**Comment by Gargron** [comment] 2017-04-15 00:00
Here are cases when Mastodon pulls data from origin:

- First time look-up (Webfinger, Atom feed)
- Thread linked from `<thr:in-reply-to href />` (HTML page, Atom entry)
- After you are followed, Atom feed look-up to confirm whether data about whether your account is locked or unlocked is up to date
- If a URL is linked in a status, HTML page look-up for OpenGraph tags

None of these are illegitimate in my opinion. Your software should be able to handle that, it is real-world use.

**Comment by ThatBrickster** [comment] 2017-04-15 00:09
Could you please profile so that I may verify what you are saying is truth? Design and implementation are two different things.

**Comment by ThatBrickster** [comment] 2017-04-15 00:34
I'm willing to offer a bug bounty for a fix. I propose to give you a donation of $30 if you fix this. If an individual contributor patches it and PRs for merging with mainline code I'll pay them directly.

Sound fair?

**Comment by Gargron** [comment] 2017-04-15 00:40
>Could you please profile so that I may verify what you are saying is truth?

You are right inside a repository of source code where you can verify whether what I'm saying is truth. If you provide logs of what you think is unnecessary activity, we can look at that.

**Comment by ThatBrickster** [comment] 2017-04-15 00:47
Ruby isn't my ballpark so I'm too dumb to spot issues in code. I'm currently collating logs that should help diagnose what's being experienced.

**Comment by ThatBrickster** [comment] 2017-04-15 01:16
I'm going to have to wait until tomorrow to provide anything as network logs retained contain IPs, work in itself to scrub them for our use. It could very well be a problem present in the protocol itself but seeing as this is only occurring under Mastodon and not other OStatus-compliant applications I believed this to be the problem.

I'll get back to this when I can.

**Comment by lambadalambda** [comment] 2017-04-15 08:07
I thought the problem was the other way around, where Mastodon would advertise an url that returned a 404 because it wasn't publicly visible and GS would try again to get it. Is this a separate issue?

**Comment by ThatBrickster** [comment] 2017-04-15 12:48
I believe that to be a separate issue as I'm only aware of a constant stream of timeline requests causing havoc to GS admins whenever someone posts with a load of Mastodon followers (as described above).

On a separate note I still don't have any extra information about this. Surprising how people were quick to complain and not file an issue with supporting evidence. It would be nice to come to a conclusion as to what's at fault instead of the mudslinging I've seen for the past two weeks.

**Comment by KellerFuchs** [comment] 2017-04-15 22:46
After discussion (see [thread](https://gs.smuglo.li/notice/1873531)), it seems the core of the issue is that many instances cannot cope with “all” Mastodon instances attempting to fetch a user's profile quasi-simultaneously. This happens when a toot mentioning said users reaches many instances at once (e.g. because it was boosted or tooted by someone followed by many instances).
The issue is not specific to GNU Social; the correlation seems to be caused by most Mastodon instances being less low-powered.

The code causing said behavior seems to be https://github.com/tootsuite/mastodon/blob/master/app/services/process_feed_service.rb#L169
@Gargron, @wxcafe, could you clarify
- whether this is the part causing the behaviour in question;
- whether changing the behaviour to not fetch on mention (but simply fetch/cache the first time a user attempts to interact with the mentioned user) would break other features.

**Comment by Gargron** [comment] 2017-04-16 14:56
@KellerFuchs Thanks for pointing to the right direction. Your description of the problem made sense and you pointed in absolutely the right direction, one extra check before the fallback to HTTP look-up was missing.

**Comment by KellerFuchs** [comment] 2017-04-16 17:43
\o/
