### ISSUE TITLE
Failure when creating toot with audio-only mp4 attached

### ISSUE THREAD

**Issue by dlowe-net** [tootsuite/mastodon#6147] opened 2018-01-01 13:37 UTC
What I did:
Created an mp4 of some music, but with no video stream. Checked that it worked in web browser.Attached it to a toot. Clicked Toot! button.

What I expected:
Toot posts with an audio-only mp4 control.

What actually happened:
500 Server Error. Checking the logs indicates that transcoding assumes a video stream and errors if one isn't present.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment] 2018-01-02 00:39
duplicate of #4827.

**Closed by ykzts** 2018-01-02 00:39 UTC
Labels: duplicate
