### ISSUE TITLE
Option to disable CWs clientside.

### ISSUE THREAD

**Issue by SangriaSnake** [tootsuite/mastodon#5394] opened 2017-10-14 21:40 UTC
Requesting there be a option to disable CWs clientside. Im not saying this should be for everyone but most CWs dont really effect me and having to click through CWs to view toots is rather tedious. An option to disable that feature would be great, and of course have CWs on by default.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2017-10-14 22:43
This could be a duplicate of #1123 - what do you think?

**Comment by SangriaSnake** [comment] 2017-10-14 23:00
Ah ok. Sorry for duplicating. Guess I missed that thread. ^^

**Comment by Cassolotl** [comment] 2017-10-15 09:34
No worries! :) Feel free to close this issue whenever!

**Closed** 2017-10-15 18:46 UTC
