### ISSUE TITLE
Filter toots from a specific app from the local & federated timeline

### ISSUE THREAD

**Issue by catgirlsec** [tootsuite/mastodon#12700] opened 2019-12-28 01:40 UTC
### Pitch

The Twitter Crossposting bots are controversial in the fediverse community. Some users love them and some hate them. To balance this we should provide settings to both users and admins to hide all toots from an app from their home feed, local & federated timelines. This could be integrated into the existing word filters system. This won't work in cases where the user has hidden the app used but in most cases users would be able to hide content from specific apps. We should make this filter available FOR BOTH USERS AND ADMINS to maximize benefits.

### Motivation

This would remove frustrations from users who don't want to see content from a certain app (for example crossposters).

**Comment by trwnh** [comment] 2019-12-28 01:44
Duplicate of #8271

**Comment by catgirlsec** [comment] 2019-12-28 01:48
Thanks @trwnh for the heads up

**Closed** 2019-12-28 01:47 UTC
