### ISSUE TITLE
Ability to block bot accounts

### ISSUE THREAD

**Issue by martinmuc** [tootsuite/mastodon#14774] opened 2020-09-11 12:39 UTC
Hello,

Since there is in the profile a checkbox, where to mark an account (bot) as bot. Why isn't there no option for disabling/blocking those bot accounts in general on a per user level.

Since there are so many bots, the most of them post useless stuff (in my opinion). So i don't want to see all this accounts anymore, which are marked as bot in my timelines.

As an option, to be not that restrictive, there could be an option like:
Block all bots except these (List of bot names to allow)

ciao,
Martin

**Comment by Cassolotl** [comment] 2020-09-12 19:59
I think this is probably a duplicate of *Add an option to hide bots' posts #8293*? If you agree, you can close this issue and go to #8293 and add your comment and 👍  there, to keep everything in one place and add weight to one issue. :)

**Closed** 2020-09-13 07:04 UTC
