### ISSUE TITLE
Add wall of ban and wall of silenced for basic user

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#4578] opened 2017-08-10 21:05 UTC
Actually, user not display if instance banned user or not (distance or local) and this is not safe for his (censorship, kill other point of view...)
For me, all user can view who is banned, silenced and instance to create his point of view.
And all of ban / silenced are explain. Admin can lie but if lot of user are banned with same sentence or if user visit banned account and not see the banned raison, the was decridibilitize

Regard

(ok... Bad english... Too many complicated word and my english level is very bad...)

**Comment by nightpool** [comment] 2017-08-12 03:05
duplicate of https://github.com/tootsuite/mastodon/issues/3874

**Closed by nightpool** 2017-08-12 03:05 UTC
