### ISSUE TITLE
Toots from blocked users still appear in the Home timeline when boosted

### ISSUE THREAD

**Issue by Sylvhem** [tootsuite/mastodon#7230] opened 2018-04-22 15:27 UTC
Some users seem to see toots from people they have blocked if they have been boosted by someone they follow.
For example, on Eldritch Café, one user apparently sometimes sees toots from someone they have blocked and muted when they are boosted by one of their followings. According to [this thread](https://eldritch.cafe/@Sylvhem/99903014689784844), other peoples seems to experience this behavior.
According to [this comment](https://pleroma.site/notice/64474), the problem may be coming from a badly formated SQL query. Applying https://github.com/kaniini/mastodon-hardened/commit/47d8ae216d9e24ca9a760459160149ae73675e04 may help.
I couldn't reproduce this bug myself.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2018-04-22 15:47
>Toots from blocked users still appear in the public timelines when boosted

The title doesn't sound correct based on the body of the issue

**Comment by trwnh** [comment] 2018-04-22 16:46
Duplicate of #251 according to the title, at least.

**Comment by Gargron** [comment] 2018-04-22 16:50
Yeah the title is very wrong imo.

But: "Blocked users' toots still appear on the profiles of users who retoot them" is something completely different. It's specifically when you open someone's profile, you see everyone who they boost. And I kinda think it's supposed to be like that. If a user is boosting someone I blocked I'd rather know about it.

**Comment by trwnh** [comment] 2018-04-22 17:01
I think there needs to be a minor reworking / clarification of the block and mute systems, to deal with all of the assorted and often-confused issues being filed (of questionable duplicity).

#251 - "Blocked users' toots still appear on the profiles of users who retoot them"
#6921 - "Blocking someone does not necessarily prevent them from getting your toots, if they are boosted."
#7172 - "Muted and blocked users still appear on other peoples' profiles"
#7230 - "Toots from blocked users still appear in the public timelines when boosted"

**Comment by Sylvhem** [comment] 2018-04-22 19:54
> > Toots from blocked users still appear in the public timelines when boosted
> 
> The title doesn't sound correct based on the body of the issue

Yeah you're right, I suppose I didn't pay attention when writing it. I just updated it.


> - Blocked users can't follow you
> - Blocked users can't see your toots on timeline
> - Blocked users can't see your toots on profile
> - Muted users should be hidden on timeline

It seems good to me. As long toots from a user totally disappear when you block and mute them it seems fine to me.

I feel like one of the current problem for a lot of people with the current way mute and block behave is that it's not really clear which one do what.

**Comment by trwnh** [comment] 2018-04-24 12:32
@Sylvhem As it stands right now, users can be hidden via mute. It's just that there seems to also be the expectation that a block should do this as well, judging by the various issues filed against seeing blocked users in timelines or in profiles when they are boosted by someone else.

I'm of the opinion that blocks and mutes should represent directionality and not severity, but I suspect I'm in the minority -- the prior example from Twitter that most people are accustomed to is that mutes are just weaker blocks. This obviously leads to confusion in delineating the exact differences between mutes and blocks, though... by contrast, there is no ambiguity in using direction; it breaks birdsite convention, but ultimately it makes more sense for unidirectional relations.

Blocks are essentially an artifact of bidirectional relationships a la Facebook friends; setting a block will cut off the two-way friendship and prevent someone from communicating with you, so you are invisible to them but also their communications are invisible to you.

In a unidirectional system (e.g. followers and following), a relationship is only valid in one direction and does not imply the reverse direction -- you can follow someone without them following you. As a result, there should be a way to hide from someone (disabling the follower relationship), *as well as* a way to hide someone from you (disable the following relationship). Blocks and mutes should be antiparallel functions.

Still, even with this distinction, that doesn't solve the expectation that blocks should also include mutes, based on years of Twitter usage.

**Closed** 2018-05-02 13:50 UTC
