### ISSUE TITLE
Android back button does not work on media overlay

### ISSUE THREAD

**Issue by fwenzel** [tootsuite/mastodon#3060] opened 2017-05-14 21:30 UTC
STR:
* open mastodon UI on mobile
* switch to one of the timelines
* open the media attachment on a toot
* press Android device `<back>` button

Expected:
* media overlay closes and I am back on the timeline underneath

Actual:
* media overlay stays open
* timeline *underneath* goes back one step (to the previously visited column/page)

--> I suspect this can be fixed with a `pushState()` for the overlay state, so that the "back" behavior takes us to the timeline again.

Dismissing the overlay in any other way would then have to `popState()` too of course.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2017-08-30 22:59
I want this!

**Comment by zaccolley** [comment] 2017-11-14 01:10
I'd like to fix this. Might have time on the weekend.

**Comment by Cassolotl** [comment] 2018-01-17 23:17
Duplicate of #364.

**Closed** 2018-01-17 23:20 UTC
Labels: duplicate
