### ISSUE TITLE
Uploading images sometimes results in all-black image upload - possibly related to EXIF stripping?

### ISSUE THREAD

**Issue by TrollDecker** [tootsuite/mastodon#7550] opened 2018-05-19 17:59 UTC
I seem to be having a weird problem of late in which certain images, usually JPEG photos taken with my phone camera, show up as an all-black image when they're uploaded. This just happened recently, at which point, I tried a couple of things to try and get to the bottom of it. What did the trick was opening them in GIMP and re-saving them.

Upon opening the original file, GIMP reports that the images contain EXIF rotation data, which I guess my phone uses to orient the image the correct way as opposed to just saving the bloody thing in the correct orientation to begin with, and asks if I want to rotate the image according to that data. I can then save the file in that orientation without using EXIF rotation data, after which point, the resaved image can be uploaded correctly without becoming a black rectangle.

So my point is that I suspect the problem is related to that? Either Masto is stripping the EXIF rotation data which results in a borked image or it's trying to rotate the image properly and making a right hash of it? I'm not even remotely sure tbh, but I suspect it's linked to that.

* * * *

- [YES] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [YES] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by usbsnowcrash** [comment] 2018-05-19 18:12
I’ve also noticed that mastodon completely ignores the exif rotation data from my iPhone camera.  Other sites like twitter Instagram read it and do the right thing.

@trolldecker do you have an unedited image somewhere you can share so I can compare your exif data to mine?

**Comment by trwnh** [comment] 2018-05-19 18:12
Which version of Mastodon are you running?

**Comment by TrollDecker** [comment] 2018-05-19 18:17
@trwnh I'm running v2.4.0rc3, though this was an issue I've been experiencing at least since the first RC, if I remember correctly.

@usbsnowcrash:
Here's an original photo:
![20180518_152820](https://user-images.githubusercontent.com/4513715/40271706-ec086f54-5b98-11e8-888c-36087f49b185.jpg)

And the re-saved version:
![20180518_152820-v2](https://user-images.githubusercontent.com/4513715/40271710-f14818a2-5b98-11e8-8a8f-b1284399f916.jpg)

(Not that I have an idea if Github actually touches the EXIF data in images to begin with)

**Comment by usbsnowcrash** [comment] 2018-05-19 18:36
Gimp definitely messed with the orientation metadata

Original: Orientation	Rotate 180
Gimp: Orientation	Horizontal (normal)

Gimp also added some stuff about color like this so maybe that’s related?
Photometric Interpretation	YCbCr

**Comment by Gargron** [comment] 2018-05-19 19:29
@usbsnowcrash This issue isn't about Gimp, Gimp *solves* the issue because it rotates the image while removing Exif orientation metadata (presumably) so the code that has to rotate the image in Mastodon JS never needs to run.

**Comment by Gargron** [comment] 2018-05-19 19:31
I was able to 1) download your original image and inspect it to confirm it wasn't stripped of exif data by github 2) upload it on my development environment. I could not reproduce your issue, so it might already be fixed in master.

**Closed by Gargron** 2018-05-19 19:31 UTC

**Comment by TrollDecker** [comment] 2018-05-19 20:06
"It works fine on my end" is a bizarre justification for closing an issue. :neutral_face:

**Comment by trwnh** [comment] 2018-05-19 21:45
@TrollDecker "fixed in master" means it was fixed after 2.4.0rc3 -- most likely by #7514 as a side effect (see https://github.com/tootsuite/mastodon/issues/7487#issuecomment-388981920 on what was wrong with the EXIF logic beforehand)
