### ISSUE TITLE
do-not-federate flag

### ISSUE THREAD

**Issue by hoodiek** [tootsuite/mastodon#2698] opened 2017-05-01 23:34 UTC
federation is a strength, but also in some cases, a downside. users should be able to post purely to their own instance, and choose not to federate something. this is for all level of posts, due to the many uses of such a tool, depending on instance type, post intent, etcetera. there are several posts about such a thing, and this solves all of them, and yet no individual post specifies it to be available for all posting levels, so i created this one.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by bortzmeyer** [comment] 2017-05-02 07:59
Yes, this would be really useful (think of the NO_EXPORT attribute of BGP) for things like:

- local announcements '"we will upgrade, and be down one hour")
- messages intended to a specific community (animal rights demo, for a instance dedicated to animal rights)

**Comment by gordonzola** [comment] 2017-05-02 08:17
There is already a pull request for that, with comments from @Gargron : #1761

**Comment by hipparkhos** [comment] 2017-05-02 09:24
Something that would be nice in the future would be to implement some sort of "circles", i.e. I post a status, but only for followers which are in a liste of circles. In real life you have different circles of relationships. You might want to limit the exposure of some toots.

"do-not-federate" could be a first step : only followers on the local instance would see the status. That would be very useful both for admin messages, and for thematic instances.

**Comment by alex73630** [comment] 2017-05-02 09:27
Possible duplicate of this issue : https://github.com/tootsuite/mastodon/issues/861

**Comment by wolfteeth** [comment] 2017-05-02 14:08
+1. I was thinking about how useful this would be for announcements AND to have the old style of local-only private toots. Being able to turn off federation for some posts seems very valuable. It lets users avoid the concerns of private toot federation, instead of making private toots useless for anyone with followers running something besides Mastodon.

**Comment by ashfurrow** [comment] 2017-05-11 21:09
This looks like a duplicate of https://github.com/tootsuite/mastodon/issues/861 – I'm going to close this issue but please continue the discussion over there. Thanks again for the suggestion!

**Closed by ashfurrow** 2017-05-11 21:09 UTC
