### ISSUE TITLE
PWA uses too much space in web browser

### ISSUE THREAD

**Issue by Exagone313** [tootsuite/mastodon#7893] opened 2018-06-26 12:34 UTC
Hi

I just saw that Mastodon uses **769MB** of data in my profile, I think this is due to the PWA. This is way too much, and I don't need images or videos to be saved locally at all.
Is there anything that can be done?

Thanks!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment] 2018-06-26 13:00
Duplicate of #7615

**Comment by ykzts** [comment] 2018-06-26 14:03
> Aside from that, there's now an enormous (varies, but I've seen over 150MB) directory in
>
> ```plain
> ~/.mozilla/firefox/$profiledir/storage/default/https+++mastodon.social^firstPartyDomain=mastodon.social/cache/morgue/
> ```

Is not your problem the same as above?

**Comment by nightpool** [comment] 2018-06-26 14:21
speed of writes isn't the same problem as magnitude or total cache size.

**Comment by nightpool** [comment] 2018-06-26 14:24
I agree with aki on #7615 that it should be tracked separately, although I agree that it's likely the two issues have the same solution  (cache less aggressively)

**Comment by unarist** [comment] 2018-07-03 13:20
Our cache logic will clear caches if our cache hits storage quota, but the quota is very large on many browsers. I think having our limits or settings for caches is good, though browsers may should have too.

**Closed** 2018-07-03 17:50 UTC
