### ISSUE TITLE
Statuses not sorted in UI

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#545] opened 2017-01-26 08:30 UTC
Right now, statuses are sorted by their status ID in the web client. This creates oddities, such as when a status takes a few hours to be delivered to an instance - you end up with a "3 hours ago" status at the top of the timeline, above "1 minute ago".

**Comment by Gargron** [comment] 2017-01-26 11:18
Initially feeds were sorted by created_at: https://github.com/tootsuite/mastodon/blob/6c4c84b161947cb11ad0451a39e26b25be4c93d5/app/services/fan_out_on_write_service.rb#L28 Then in 12559b01eae408c0f3e820ef9c6bc6e356ab889a I realized we needed key-based pagination, for which unique primary keys are required for sorting. created_at does not guarantee uniqueness. Then #25 made use of this to also implement reblog bumping. What I'm saying is that i'm at the end of my wits with this particular issue.

**Comment by snorthway** [comment] 2017-04-04 19:08
I'm seeing some weird stuff that I think falls under the scope of this issue(? please correct me if I'm wrong):

This is the top of my Home timeline in React dev tools after I've been sitting idle for a bit, e.g. not refreshing the page. It's not ordered correctly, you see 158x before 159x. (Screenshots redacted for privacy)

<img width="221" alt="screen shot 2017-04-04 at 2 38 44 pm" src="https://cloud.githubusercontent.com/assets/2825499/24673578/d14ccae2-1946-11e7-98c6-a083666f21f8.png">

Then I make a post and it gets ID 160x and sits on top:

<img width="223" alt="screen shot 2017-04-04 at 2 39 11 pm" src="https://cloud.githubusercontent.com/assets/2825499/24673640/00bb4fba-1947-11e7-9984-db100a62f4b9.png">

Then I refresh the page and it's ordered correctly again but my most recent post is gone, even though it has a higher ID number than all of these:

<img width="216" alt="screen shot 2017-04-04 at 2 39 48 pm" src="https://cloud.githubusercontent.com/assets/2825499/24673690/283835bc-1947-11e7-98ac-9b72834e61f0.png">

**Comment by Gargron** [comment] 2017-06-29 14:40
Duplicate of #1059

**Closed by Gargron** 2017-06-29 14:40 UTC
Labels: requires in depth
