### ISSUE TITLE
Broken conversations in lists

### ISSUE THREAD

**Issue by cbayerlein** [tootsuite/mastodon#8385] opened 2018-08-23 14:21 UTC
In lists, all Toots of the list members are displayed. Even those, which are aimed at people from outside the list (e. g. replies to other Toots). This will display fragments of conversations without context. These Toots should be hidden.

**Comment by renatolond** [comment] 2018-08-23 15:07
I think duplicate of #5916

**Comment by cbayerlein** [comment] 2018-08-23 15:25
true. sorry.

**Closed** 2018-08-23 16:29 UTC
Labels: duplicate
