### ISSUE TITLE
[Request] Mute posts from a specific app

### ISSUE THREAD

**Issue by calmasis** [tootsuite/mastodon#9693] opened 2019-01-02 01:41 UTC
**Pitch**
Add the ability to mute posts made by specific apps. For example, the option to mute any post by any user made in Mastodon Twitter Crossposter. This would be in line with the ability to mute individual users and individual instances. 

**Motivation**
There are a large number of users who crosspost from Twitter to Mastodon, using clients such as Moa. I don't want to see crossposts. Manually muting every user who crossposts is time consuming. Adding the ability to mute any posts made in (eg) Moa would simplify the process enormously for users. In addition, sometimes users who crosspost also post original toots to Mastodon - being able to selectively mute crossposts whilst retaining their original posts would be beneficial, as that isn't currently possible.

**Comment by trwnh** [comment] 2019-01-02 01:51
Duplicate of #8271

**Comment by calmasis** [comment] 2019-01-02 01:55
Thanks, sorry!

**Closed** 2019-01-02 01:55 UTC
