### ISSUE TITLE
Democracy on mastodon

### ISSUE THREAD

**Issue by matyapiro31** [tootsuite/mastodon#6595] opened 2018-03-02 08:05 UTC
Now, mastodon is governed despotically.
No public moderation log, no public reason for account suspension.
No public rules.
Users always be afraid of being banned, so no complication about administration.
So, I think mastodon must have a own diet that everyone can join, and monitor the moderation and become a moderator.
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment] 2018-03-02 09:18
Closing this

**Comment by matyapiro31** [comment] 2018-03-02 09:27
@wxcafe  Listen me please.

**Comment by TheKinrar** [comment] 2018-04-08 18:50
Maybe not a good idea to respond to an issue about democracy by closing then locking it?

I don't want to make my audit log public, and I think most instances don't want to. Still, some instances might, I suppose. The fact that @wxcafe and probably others, including me, don't want to make this log public doesn't mean it has to be impossible.

This repo is about Mastodon, not mastodon.social (or others) only. I understand that probably no one wants to implement this in the core dev team, but this is not a problem.
This issue can stay open, this is free software, you known. If one person can close an issue because they feel like the issue is not important, then I'm not sure users really have power here.

I know this issue is not really friendly, but still the discussion might be interesting and there was *none* here. That's not how it should work on a free software project.

**Comment by TheKinrar** [comment] 2018-04-08 19:27
(Unsure if reopening was useful, most important was unlocking I think. It's useless to lock if the conversation isn't violent or something like that.)

**Closed** 2018-04-09 09:04 UTC
Labels: wontfix

**Comment by wxcafe** [comment] 2018-04-09 09:07
This issue is out of scope, badly worded, doesn't talk about any specific changes that would be wanted/needed, and as such it has no place on the issue tracker. I locked it because there was no point having a discussion in this thread.

If you want to open an issue about having a public log of moderation decisions (which is a very bad idea imo, but either way), open a new issue. Locking again.

(it's seriously tiring having to explain such basic moderation decisions on the issue tracker, to be honest)

**Comment by trwnh** [comment] 2018-04-09 09:54
It's also not even technically valid:
* there are moderation logs for all staff, and the reason can be shared with users at their discretion
* rules are usually posted on /about/more; if not, this is something to take up with specific instances
* users are not and should not be afraid of being banned; either follow the rules or find a new instance

(btw @wxcafe you didn't actually lock the issue btw)
