### ISSUE TITLE
Support groups (not dup of #139, not using bangtags)

### ISSUE THREAD

**Issue by ThisIsMissEm** [tootsuite/mastodon#7081] opened 2018-04-09 02:05 UTC
This would be useful for having essentially private lists / toots. The particulate use case mentioned by a user on Switter.at is for a “private group where we can post ugly mugs information”

The idea is to create a list, and then when you toot, you can select “Visibility > Specific List” and then you get a dropdown with all the lists you’re on. 

I’m not entirely sure how this would fully work with ActivityPub, but I assume we can just add visibility as something like `list:1234` and it’d be fine.

There is the issue of federation: should you be able to post to a list on a different instance to your account? If so, do lists actually have an addressable ID (`list:1234@switter.at`) or something.

I see this as akin to the Facebook post visibility of like “Only Family” or similar.

Wanting to start discussion before looking at doing a PR for this.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kaniini** [comment] 2018-04-09 02:30
this should be done with AP groups

groups are AP actors which just boost anything sent to them, the challenge is the group membership dynamics, you would need to be able to approve who is in the group

**Comment by ThisIsMissEm** [comment] 2018-04-09 02:48
Hm, I’m not sure that a bot that retoots is as user friendly; in particular, if it gets out that someone has been reported as an ugly mug, then there’s a very real threat to human life, which is why I see this more as a privacy setting on the post. 

I’m understanding AP as auto-post, as in a bot that boosts thing’s they’re tagged in to followers, and then making that bot only viewable by followers. But I fear this could easily go wrong and the wrong people gain access to that information.

For more background, we keep lists privately of ugly mugs, i.e., abusive clients, if one of them finds out they’ve been posted as an ugly mug, they either attack the last provider they saw, and/or change details preventing future providers from screening them out using list data.

The problem lies in the chance that you could accidentally publicly post an ugly mug, hence endangering yourself (again).

**Comment by Cassolotl** [comment] 2018-04-09 07:05
If it helps, with the private group setting members of the group have to be approved by the person running the group. It's no different from DMing several trusted people.

**Comment by ThisIsMissEm** [comment] 2018-04-09 08:12
@Cassolotl that's for the entire instance though, isn't it? I only see "lists" on mastodon, and there doesn't appear to really be a "group" concept. Unless I'm missing something?

**Comment by kaniini** [comment] 2018-04-09 08:38
the use of boosts (well, AP `announce`) is a boring implementation detail.  mastodon would simply handle an `announce` from a group as a normal message instead of displaying it as a boost.

**Comment by Gargron** [comment] 2018-04-09 08:56
Yep, I think this is the group feature that you want, though I am uneasy with the idea of exchanging life-threatening information over it. Although a tightly-controlled group wouldn't have to even leave your server... I suppose some uneasiness is just simply warranted here no matter what.

**Comment by ThisIsMissEm** [comment] 2018-04-09 09:35
I think the bangtag is a bit strange — why not build it just like the lists functionality & add it as a visibility option?

As for it being used for potentially life threatening information, that’s just a use we have on switter. For many I could see it being used as a private group chat type thing.

The main thing I’m concerned about is the UX & making sure that what’s intended for a group doesn’t accidentally get posted publicly (embarrassing at best, life-threatening at worst). I think bangtags would confuse new users, but people already get the idea of “visibility”, and they can understand a “lists” like UI.

**Comment by Cassolotl** [comment] 2018-04-09 09:45
> why not build it just like the lists functionality & add it as a visibility option?

@ThisIsMissEm Does that mean that I'd have to have a column for each group I'm in?

**Comment by ThisIsMissEm** [comment] 2018-04-09 10:59
@Cassolotl no, I'm thinking it'd be sort of menu based — you could pin them as columns, but a "new message in <list/group>" would be a notification in the "notifications column"

**Comment by Cassolotl** [comment] 2018-04-09 11:05
Ahhh I get you! Alright. :)

**Comment by Gargron** [comment] 2018-04-09 12:32
I hate bangtags, people just bring them up because that's what GNU social does.

**Comment by zcdunn** [comment] 2018-04-09 13:16
Bangtags are also used by Hubzilla/Friendica for forums, which are basically groups

**Comment by SoniEx2** [comment] 2018-04-10 02:39
bangtags are a nice convenience but they should have placement restrictions (first/last thing in a toot, toggleable on/off, etc).

without bangtags you can do it the facebook/google+ way, I guess?

but yeah `#bangtagsareanaccessibilityfeature` (also `#nobodycaresaboutaccessibilityfeatures`)

**Comment by kaniini** [comment] 2018-04-10 08:30
i don't really have any opinion on bangtags, i am just saying that the AP group actor type is what is needed here

i also second @Gargron's view that perhaps sharing life-threatening information inside an activitypub server is not necessarily a good idea.  it seems better to use a dedicated tool for that job.

**Comment by ThisIsMissEm** [comment] 2018-04-10 08:42
Really it’s a case of working with what we’ve got: currently there were services, but they all shut due to FOSTA-SESTA, then there’s been private groups on Facebook, those too will potentially be shut.

Essentially it’s about what software we can access, and at the moment, one option is Mastodon if it supports better “private” communication.

Of course dedicated tools would be better, but have a greater cost to them: someone has to make them.

Really private groups for ugly mugs is just one use case out of many; everyone has a private circle of people that they want to communicate with sometimes.

**Comment by ThisIsMissEm** [comment] 2018-04-10 08:45
Bangtags might be accessible in that you can type them, but we can also make select menus and forms accessible too. 

A form UI like Facebook/Google+ is simpler for a non-technical user to understand, what the visibility implications are of special tags in your message are harder to understand.

We’ve already seen this cause issues with direct toots, where people were being caught out by them going to all mentioned users & not just the users mentioned at the start of the message.

**Comment by gellenburg** [comment] 2018-04-15 19:41
Count me in as wishing Mastodon supported bang-tags like GNU Social.

They're very intuitive.

!-mentions = messaging a group
@-mention = messaging a person
# = hashtags (keywords)
$ = typically referred to stock symbols on Twitter at least

**Comment by SoniEx2** [comment] 2018-04-15 22:08
I feel like, if anything, they should be `@!` and `#$` on mastodon. Because they're special cases of `@` and `#` respectively.

**Comment by highfellow** [comment] 2018-04-16 12:31
Just regarding good platforms for private group communication, I think you would be better to use something that supports end to end encryption, like Signal.  https://signal.org .This does support groups, so should be okay for what you want. Also with Signal and similar platforms, the messages are never seen in clear text by their systems - all the encryption and decryption is done on the end devices, so even if someone hacks their servers or turns up with a warrant, there is still no way they can read your messages. Nothing is totally secure, but something like this is the best bet we have at the moment.

That said, I definitely support the idea of a groups functonality for uses where privacy is not so serious.

**Comment by Gargron** [comment] 2018-04-16 12:49
(This totally is a duplicate of #139 though, bangtags or no)

**Closed by Gargron** 2018-04-16 12:49 UTC
