### ISSUE TITLE
Manual refresh of columns

### ISSUE THREAD

**Issue by Geobert** [tootsuite/mastodon#1538] opened 2017-04-11 14:03 UTC
something like twitter does.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-11 15:44
I'm guessing this is a reference to this UI in twitter web
<img width="594" alt="screen shot 2017-04-11 at 17 43 47" src="https://cloud.githubusercontent.com/assets/3009327/24917761/77b7151c-1ede-11e7-819b-d8f34a393058.png"> where the website is not on streaming mode, and you have to click to see new tweets.

**Comment by Geobert** [comment] 2017-04-11 17:06
Yes :D

**Comment by Gargron** [comment] 2017-06-29 22:15
Duplicate of #240

**Closed by Gargron** 2017-06-29 22:15 UTC
Labels: enhancement, priority - low, ui
