### ISSUE TITLE
What to clean up old, abandoned, remote posts

### ISSUE THREAD

**Issue by 7kry** [tootsuite/mastodon#2112] opened 2017-04-18 23:03 UTC
I launched a Mastodon instance on my server, and I appreciate the developers as a user.

As you know, many geeks (like me) have already launched their own instances.
While running such an instance, the disk quota of the server is one of the concerns.
I think it's necessary to append a rake task to clean up old, abandoned, remote posts.

I mean by "abandoned", posts which are not reblogged nor favourited by any local user.
For instance, posts in the result of `Status.joins(:account).where(favourites_count: 0).where(reblogs_count: 0).where('"accounts"."domain" IS NOT NULL').where('"statuses"."created_at" < ?', 30.day.ago)` are to be deleted.
Then `rake mastodon:media:clear` to free up disk space. 

Now I wonder if there is any necessary process in addition to the above ?

Thank you.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment] 2017-04-18 23:09
So posts would be saved only if someone saves or reposts them? That's a lot of pressure on writers!

**Comment by 7kry** [comment] 2017-04-18 23:17
In my example, After 30 days of caching, and it's concerned with remote posts only.
Of course, this task reduces searchability of old posts. So it should be an optional task.

**Comment by 7kry** [comment] 2017-04-19 00:27
Oops, I'd completely forgotten posts mentioned by local users.

**Comment by wxcafe** [comment] 2017-04-20 01:22
duplicate of #1554, closing

**Closed by wxcafe** 2017-04-20 01:22 UTC
