### ISSUE TITLE
Show posts when checking profile from another instance

### ISSUE THREAD

**Issue by Lertsenem** [tootsuite/mastodon#830] opened 2017-04-04 12:10 UTC
I'm not sure if this is due to the underlying protocols, but when I check the profile of someone from another instance (someone that nobody from my instance interacted with) I usually see 0 posts. But I can check the user URL and see posts there.

Shouldn't Mastodon download (at least the latest) posts from a user when I'm looking for them?

Or maybe I misconfigured something on my instance...

**Comment by rhaamo** [comment] 2017-04-04 12:17
Actually Mastodon doesn't fetch the timeline for a new profile, it would show only new posts since you followed that profile/person.

So this would be a feature request yes !

**Comment by jdiez17** [comment] 2017-04-05 08:51
In general, when someone in the Mastodon server follows some other user's profile, a background task should be started to download that user's profile, their following/followers and up to N toots.

**Comment by mxroo** [comment] 2017-04-09 20:48
I think this is also related to the oldest open issue, #34

**Comment by daynaskully** [comment] 2017-04-23 17:13
Should at the very least use an api call to pull in the users recent posts.

**Comment by Gargron** [comment] 2017-06-29 16:28
>Should at the very least use an api call to pull in the users recent posts

Mastodon API is not the same as OStatus. Assuming the Mastodon API for any remote user, which could be from different platforms, would be counter to the idea of standards and open protocols.

Duplicate of #34

**Closed by Gargron** 2017-06-29 16:28 UTC
Labels: enhancement
