### ISSUE TITLE
Set update intervals for timeline displays (instead of continuous)

### ISSUE THREAD

**Issue by HongPong** [tootsuite/mastodon#879] opened 2017-04-04 19:58 UTC
The local timeline and federated timeline update pretty continuously in a firehose effect. It would be nice to be able to change that per user setting to fixed time intervals. Like 5 seconds, 15 seconds, 30 seconds, 1 minute etc. This would also reduce the server load I would think (perhaps not, I don't know how this thing works internally). Perhaps under high load it could fall back to slower batches of updates, to avert failmastodons.

Anyway thrilled to see that a good GNU social frontend has taken off. Cheers 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment] 2017-06-29 16:47
Duplicate of #240

**Closed by Gargron** 2017-06-29 16:47 UTC
Labels: enhancement
