### ISSUE TITLE
Allow moderators to mark an entire toot (including text) as sensitive

### ISSUE THREAD

**Issue by irlcatgirl** [tootsuite/mastodon#12307] opened 2019-11-05 14:55 UTC
### Pitch

Some toots may have content that is sensitive (including the text). A content warning may or may not be appropriate here. Currently a moderator can ask the user to delete and redraft the post with a content warning, delete the post, or take action against the user (such as silence, suspend, etc). A moderator tool to mark the entire toot as sensitive in response to a report would be helpful. Text could say something like "A moderator has marked this toot as sensitive, continue?" and a click could display the toot anyways.  Additional tools such as removal of posts from the public timeline (without a delete) may also be helpful. Thoughts?

### Motivation

It will improve moderation workflows.

**Comment by Cassolotl** [comment] 2019-11-05 15:40
I think this might be a duplicate of *Add moderation tool to edit content warning on a post #1307*.

**Comment by nsuchy** [comment] 2019-11-05 16:34
> I think this might be a duplicate of _Add moderation tool to edit content warning on a post #1307_.

No, that issue asks to edit the content warning part of a post, this would be a separate system that hides the entire toot without custom text and is specifically when hidden by a moderator.

**Closed** 2020-10-15 16:16 UTC
Labels: suggestion
