### ISSUE TITLE
Bug with URL handling?

### ISSUE THREAD

**Issue by marrus-sh** [tootsuite/mastodon#678] opened 2017-03-24 20:15 UTC
When a URL is enclosed in angle brackets (`<http://example.com>`) the brackets are turned into character escapes before URL processing (`&lt;http://example.com&gt;`) and then the `&gt` ends up appended to the end of the url (`&lt;<a href="http://example.com&gt">http://example.com&gt</a>;`).

**Comment by mulander** [comment] 2017-04-09 14:14
There is some general issue with escaping what gets passed into the `href` attribute.

In this thread: https://mastodon.social/@mulander/2066273

The URL:
http://undeadly.org/cgi?action=article&sid=20170409123528

renders a broken URL with the ampersand escaped:
http://undeadly.org/cgi?action=article&amp;sid=20170409123528

**Comment by ashfurrow** [comment] 2017-04-23 12:29
Looks like this was closed in https://github.com/tootsuite/mastodon/pull/2138 and released in 1.2.2. I'm going to close this issue, but if you see the problem happening, please re-open. Thanks!

**Closed by ashfurrow** 2017-04-23 12:29 UTC

**Comment by mulander** [comment] 2017-04-23 20:31
Confirmed working:
 https://mastodon.social/@mulander/3967306

Thanks!
