### ISSUE TITLE
Missing Toots

### ISSUE THREAD

**Issue by duckinator** [tootsuite/mastodon#880] opened 2017-04-04 20:30 UTC
**UPDATE:** Eugen already tooted about this but I missed it because of the very problem being described here. 😧 https://mastodon.social/@Gargron/1600183

I'm leaving the issue open for informational purposes, for anyone else who looks at the issue tracker because of this. :heart: 

---

On mastodon.social, a few of my recent Toots aren't showing up on the Home column of myself and people who follow me, but show up if you view my profile. On awoo.space, they don't show up at all. It's been 22 minutes since I posted the first one, at the point I'm opening this issue (4:30pm Eastern time).

Toots in question:
* This entire thread: https://mastodon.social/@pup/1607891
* This Toot: https://mastodon.social/@pup/1609333

Here's what it looks like to me:
![screenshot_2017-04-04_16-19-52](https://cloud.githubusercontent.com/assets/39698/24677013/44571072-1953-11e7-95c9-aeda2ab08457.png)

Here's what it looks like to someone who follows me from the same instance (mastodon.social):
![kit-screenshot-1](https://cloud.githubusercontent.com/assets/39698/24677104/a3907eac-1953-11e7-97d0-89a63f2e1178.png)

It doesn't show up at all from awoo.space:
![kit-screenshot-2](https://cloud.githubusercontent.com/assets/39698/24677100/9ac7e72e-1953-11e7-9cc1-0347030d0256.png)

If you need any further information, let me know!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by duckinator** [comment] 2017-04-04 20:40
A few updates:

* These toots show up on the local timeline.
* I looked at the profiles of everybody I follow. 10 people have Tooted in the past 3 hours, and none of those Toots show up in my Home timeline. I didn't check if these showed up in the local timeline.

**Comment by duckinator** [comment] 2017-04-04 20:54
haha nevermind Eugen tooted about it but I missed it because of the timeline being so delayed. 😧

https://mastodon.social/@Gargron/1600183

I'll leave this issue open so it's visible in the issue list, if anyone else decides to open a similar issue. I'll also update the original post to mention this.

**Comment by ashfurrow** [comment] 2017-04-22 02:35
@duckinator thanks for opening the issue and being so diligent about documenting everything! I think it's been long enough that I'm going to close it, thanks again!

**Closed by ashfurrow** 2017-04-22 02:35 UTC
Labels: bug

**Comment by XenGi** [comment] 2017-05-03 12:52
I don't get why this issue is closed. The problem still persists. Nothing changed. It should stay open and only closed if the problem is identified and fixed.

**Comment by duckinator** [comment] 2017-05-03 21:22
It was resolved at the time this was closed. If it's happening again, you should open a new issue with more details about what you're experiencing.

**Comment by XenGi** [comment] 2017-05-04 00:01
I'm experiencing the exact same behavior. I have my own mastodon instance at https://mastodon.xengi.de/ and my account there is following @ShowerThoughts@mastodon.social but I can't see any of the toots of this account. My other mastodon account on mastodon.social also follows this account and sees it. Also when I toot on my own mastodon and mention my mastodon.social account I get no reaction on my mastodon.social account.

Also when I check the profile of i.e. @ajuvo@schuppentier.org I see 2 toots from my own instance and 14 from mastodon.social and I'm pretty sure the real number is even higher than that.

**Comment by duckinator** [comment] 2017-05-04 00:39
Yeah, that definitely sounds related to this one. Unfortunately I don't actually work on Mastodon, and as such don't have the capacity to re-open this issue, so my recommendation is still to open a new issue. (If you do so, I'd also recommend linking to this issue when creating the new one.)

Good luck getting it sorted out!

**Comment by Gargron** [comment] 2017-05-04 01:03
The original problem was that the distribution of home toots took too long (~1h). Public timelines use direct access to the DB rather than distribution to followers, so they always have the up to date data. Other servers receive toots in a different way than local followers, so they might also get it faster. The original issue had *nothing* to do with missing toots, they were all *delayed*. Please open a different issue if that is not what you're observing.

**Comment by XenGi** [comment] 2017-05-04 01:11
OK, I'll open a new one then. Thx for clarifying!
