### ISSUE TITLE
1.4.7: Process out of memory on 2GB OpenStack instance when running webpack

### ISSUE THREAD

**Issue by aral** [tootsuite/mastodon#4059] opened 2017-07-03 21:05 UTC
When running the webpack precompile command (`RAILS_ENV=production bundle exec rails assets:precompile`) in 1.4.7 on a 2GB RAM OpenStack VPS instance at CloudScale.ch, I get a memory error:

```
Webpacker is installed 🎉 🍰
Using /home/ubuntu/live/config/webpacker.yml file for setting up webpack paths
[Webpacker] Compiling assets 🎉
[Webpacker] Compilation Failed
yarn run v0.24.5
$ "/home/ubuntu/live/node_modules/.bin/webpack" --config /home/ubuntu/live/config/webpack/production.js

<--- Last few GCs --->

  834852 ms: Scavenge 461.1 (483.3) -> 460.6 (483.3) MB, 3.8 / 0.0 ms [allocation failure].
  834865 ms: Scavenge 461.3 (483.3) -> 460.9 (483.3) MB, 4.6 / 0.0 ms [allocation failure].
  834874 ms: Scavenge 461.6 (483.3) -> 461.1 (483.3) MB, 3.7 / 0.0 ms [allocation failure].
  834886 ms: Scavenge 462.0 (483.3) -> 461.5 (484.3) MB, 3.9 / 0.0 ms [allocation failure].
  835017 ms: Scavenge 462.2 (484.3) -> 461.8 (484.3) MB, 106.0 / 10.2 ms [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x8e39f6cfb39 <JS Object>
    1: toStringWithSourceMap(aka SourceNode_toStringWithSourceMap) [/home/ubuntu/live/node_modules/source-map/lib/source-node.js:~324] [pc=0x1b50070ee215] (this=0x3b085d0ffd69 <a SourceNode with map 0x1b6e3df2899>,aArgs=0x3b085d0fff09 <an Object with map 0xedc84fdb139>)
    2: /* anonymous */ [/home/ubuntu/live/node_modules/webpack-sources/lib/ReplaceSource.js:~71] [pc=0x1b50070f65bc] (this=0x34...

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(node:23740) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: node::Abort() [node]
 2: 0x10d368c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 6: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [node]
 7: 0xc567f2 [node]
 8: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
 9: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
10: 0x1b50044079a7
Killed
error Command failed with exit code 137.
```

Any thoughts? This was not an issue on the same instance in previous versions.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [1.4.7](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2017-07-04 00:08
Is it consistent? If you retry, it OOMs again?

**Comment by clworld** [comment] 2017-07-06 03:48
I checked memory requirement of asset:precompile for each releases.
(I run command "RAILS_ENV=production time bundle exec rake assets:precompile")

1.3.2(after asstes:clobber, rm -r -f tmp/cache, rm -r -f node_modules, yarn install)
93.40user 6.49system 1:26.06elapsed 116%CPU (0avgtext+0avgdata 522136maxresident)k
34280inputs+127200outputs (0major+1315556minor)pagefaults 0swaps
 => 509MB
1.3.2(retry)
3.80user 0.97system 0:04.79elapsed 99%CPU (0avgtext+0avgdata 172000maxresident)k
0inputs+752outputs (0major+53605minor)pagefaults 0swaps
 => 168MB

1.3.3
3.87user 0.95system 0:04.83elapsed 99%CPU (0avgtext+0avgdata 170492maxresident)k
272inputs+752outputs (0major+53159minor)pagefaults 0swaps
 => 167MB
1.3.3(after asstes:clobber)
5.94user 1.18system 0:06.19elapsed 115%CPU (0avgtext+0avgdata 205040maxresident)k
0inputs+46192outputs (0major+62647minor)pagefaults 0swaps
 => 200MB
1.3.3(after asstes:clobber, rm -r -f tmp/cache, rm -r -f node_modules, yarn install)
95.32user 6.43system 1:28.18elapsed 115%CPU (0avgtext+0avgdata 501056maxresident)k
0inputs+127200outputs (0major+1307209minor)pagefaults 0swaps
 => 489MB

1.4rc1(Webpack is used since 1.4)
113.89user 6.98system 1:47.73elapsed 112%CPU (0avgtext+0avgdata 1025132maxresident)k
7096inputs+88800outputs (0major+1236280minor)pagefaults 0swaps
 => 1001MB
1.4rc1(after asstes:clobber)
101.58user 6.40system 1:36.42elapsed 111%CPU (0avgtext+0avgdata 1017696maxresident)k
0inputs+70352outputs (0major+1110496minor)pagefaults 0swaps
 => 994MB
1.4rc1(after asstes:clobber, rm -r -f tmp/cache, rm -r -f node_modules, yarn install)
114.78user 6.98system 1:48.54elapsed 112%CPU (0avgtext+0avgdata 1045412maxresident)k
0inputs+89976outputs (0major+1253990minor)pagefaults 0swaps
 => 1021MB

1.4.1
98.19user 3.62system 1:30.40elapsed 112%CPU (0avgtext+0avgdata 1121712maxresident)k
0inputs+84808outputs (0major+872481minor)pagefaults 0swaps
 => 1095MB
1.4.1(after asstes:clobber)
85.79user 3.26system 1:19.51elapsed 111%CPU (0avgtext+0avgdata 1025404maxresident)k
0inputs+76488outputs (0major+713209minor)pagefaults 0swaps
 => 1001MB
1.4rc1(after asstes:clobber, rm -r -f tmp/cache, rm -r -f node_modules, yarn install)
97.50user 3.71system 1:31.38elapsed 110%CPU (0avgtext+0avgdata 1070696maxresident)k
0inputs+96112outputs (0major+853973minor)pagefaults 0swaps
 => 1046MB

1.4.2
90.76user 3.74system 1:24.86elapsed 111%CPU (0avgtext+0avgdata 1130412maxresident)k
2040inputs+107384outputs (0major+897252minor)pagefaults 0swaps
 => 1104MB
(I skipped asstes:clobber test for >1.4.1 because Webpack doesn't use cache it seems.)
1.4.2(after asstes:clobber, rm -r -f tmp/cache, rm -r -f node_modules, yarn install)
87.82user 3.91system 1:20.48elapsed 113%CPU (0avgtext+0avgdata 1142028maxresident)k
0inputs+111216outputs (0major+892301minor)pagefaults 0swaps
 => 1115MB

1.4.6(The bug yarn is called in assets:precompile was fixed in 1.4.6)
81.18user 5.80system 1:17.85elapsed 111%CPU (0avgtext+0avgdata 1032780maxresident)k
792inputs+96008outputs (0major+632082minor)pagefaults 0swaps
 => 1008MB
1.4.6(after asstes:clobber, rm -r -f tmp/cache, rm -r -f node_modules, yarn install)
86.22user 3.07system 1:19.62elapsed 112%CPU (0avgtext+0avgdata 1054092maxresident)k
2248inputs+111176outputs (0major+754557minor)pagefaults 0swaps
 => 1029MB

1.4.7
99.72user 3.56system 1:33.91elapsed 109%CPU (0avgtext+0avgdata 1549156maxresident)k
56inputs+163640outputs (0major+935399minor)pagefaults 0swaps
 => 1513MB
1.4.7(after asstes:clobber, rm -r -f tmp/cache, rm -r -f node_modules, yarn install)
94.96user 3.65system 1:28.19elapsed 111%CPU (0avgtext+0avgdata 1459088maxresident)k
0inputs+173848outputs (0major+911437minor)pagefaults 0swaps
 => 1425MB

master(a37cf9548c)
87.04user 12.07system 1:30.58elapsed 109%CPU (0avgtext+0avgdata 1526752maxresident)k
88inputs+155984outputs (0major+767226minor)pagefaults 0swaps
 => 1491MB
master(after asstes:clobber, rm -r -f tmp/cache, rm -r -f node_modules, yarn install)
97.57user 12.07system 1:39.18elapsed 110%CPU (0avgtext+0avgdata 1433784maxresident)k
3688inputs+174080outputs (0major+962028minor)pagefaults 0swaps
 => 1400MB

It seems webpack uses 2x memory than sprockets and webpack does not use cache(recompile whole thing every time). (from 1.4)
Something happened between 1.4.6 -> 1.4.7 and It requires 1.5x memory...

**Comment by Gargron** [comment] 2017-07-06 13:33
Nothing stands out to me between 1.4.6 and 1.4.7... A bunch of JS dependencies were updated, including webpack (update to 3.0), but webpack config wasn't touched much, I think. `transform-decorators-legacy` and  `babel-plugin-transform-react-remove-prop-types` were added to .babelrc

cc @nolanlawson

**Comment by ykzts** [comment] 2017-07-06 15:18
@Gargron I don't think that the two plugins are the cause. I think that [`webpack.optimize.ModuleConcatenationPlugin`](https://github.com/tootsuite/mastodon/blob/v1.4.7/config/webpack/production.js#L15) is what caused it.

**Comment by clworld** [comment] 2017-07-06 16:23
Yes. webpack.optimize.ModuleConcatenationPlugin spend +300～500MB memory...

master(e7c0d87d98)
84.73user 4.71system 1:22.85elapsed 107%CPU (0avgtext+0avgdata 1508052maxresident)k
152568inputs+152432outputs (43major+757797minor)pagefaults 0swaps
 => 1473MB
84.67user 3.13system 1:18.39elapsed 112%CPU (0avgtext+0avgdata 1534476maxresident)k
0inputs+151840outputs (0major+758945minor)pagefaults 0swaps
 => 1498MB

master(e7c0d87d98) + remove webpack.optimize.ModuleConcatenationPlugin
85.22user 2.83system 1:18.47elapsed 112%CPU (0avgtext+0avgdata 1199700maxresident)k
8inputs+89944outputs (0major+680165minor)pagefaults 0swaps
 => 1172MB
82.52user 2.59system 1:16.65elapsed 111%CPU (0avgtext+0avgdata 1045888maxresident)k
0inputs+89944outputs (0major+612855minor)pagefaults 0swaps
 => 1021MB

**Comment by clworld** [comment] 2017-07-06 16:48
Choices:
* No problem: Instance admins should use strong server. / or use many swap.
* Recommend that run assets:precompile on other host (i.e. on Desktop PC. not on VPS or Cloud server with small memory limitation.)
* Try to reduce memory usage webpack uses.
* Add precompiled assets for each release. (Users use customized assets need recompile them.)

**Comment by Gargron** [comment] 2017-07-06 21:02
@clworld @ykzts The PR said it saved 14.8kB. I don't think that's worth 1.5x memory consumption increase. I suggest removing ModuleConcatenationPlugin

**Comment by nolanlawson** [comment] 2017-07-07 00:55
In theory `ModuleConcatenationPlugin` also improves startup JS parse costs (by removing excessive `function(){}` blocks), but yeah that is a heavy toll for instance admins to pay.

This seems related: https://github.com/webpack/webpack/issues/5089

As a temporary workaround, instance admins can add swap space using e.g. [this guide](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04).

**Comment by Gargron** [comment] 2017-07-07 01:19
>It's also expected that the ModuleConcatenationPlugin needs more memory.

I think we should remove that plugin.

**Comment by nolanlawson** [comment] 2017-07-07 15:38
@aral Can you confirm that commenting out [this line of code](https://github.com/tootsuite/mastodon/blob/9fe6cfca48b005158979583e2266d7899e84dbe0/config/webpack/production.js#L15) fixes the out-of-memory issue for you? If so, then yeah let's remove it until it's less memory-intensive.

**Closed** 2017-07-10 16:46 UTC
