### ISSUE TITLE
Add bot disable feature in federated

### ISSUE THREAD

**Issue by FinecoFinit** [tootsuite/mastodon#14270] opened 2020-07-08 20:11 UTC
### Pitch
Maybe a filter will be good for this

### Motivation
I’m really tired of the endless news bots, and yet it’s worthwhile to completely abandon the bots on the social network

**Comment by Sasha-Sorokin** [comment] 2020-07-08 20:17
Duplicate of #8293?

**Comment by FinecoFinit** [comment] 2020-07-08 20:26
@Sasha-Sorokin idk, just do something already

**Comment by Sasha-Sorokin** [comment] 2020-07-08 20:32
I *cannot* do anything besides commenting. Read the linked issue, if it's correctly describes what you want, then this issue is duplicate, so I suggest adding a :+1: reaction there and closing this issue to keep the tracker clean.

**Comment by penloy** [comment] 2020-07-08 21:09
> @Sasha-Sorokin idk, just do something already

that's a little rude

**Comment by FinecoFinit** [comment] 2020-07-08 21:45
![image](https://user-images.githubusercontent.com/22540805/86973502-7cb95f80-c196-11ea-921c-98504acba070.png)
@penloy We all can be rude sometimes. I really tired of this endless p0rn, useless news, propaganda stuff.

**Comment by penloy** [comment] 2020-07-08 22:07
> @penloy We all can be rude sometimes. I really tired of this endless p0rn, useless news, propaganda stuff.

Being needlessly rude to open-source development teams providing you with a free services makes you an insufferable person. Don't do it.

**Comment by mstdn** [comment] 2020-07-09 15:39
> > @penloy We all can be rude sometimes. I really tired of this endless p0rn, useless news, propaganda stuff.
> 
> Being needlessly rude to open-source development teams providing you with a free services makes you an insufferable person. Don't do it.

That.

**Comment by Cassolotl** [comment] 2020-07-10 22:48
Rude, using racist memes, and refusing to move their feature request support to an older issue even though it would help their cause. :/

**Comment by FinecoFinit** [comment] 2020-07-13 08:31
> 
> 
> Rude, using racist memes, and refusing to move their feature request support to an older issue even though it would help their cause. :/

Hey, can you tell me why pepe the frog is racist meme? Also, don't be stupid and stop post unrelated

**Comment by Sasha-Sorokin** [comment] 2020-07-13 13:23
@FinecoFinit kindly ask to stop with calling names and read [code of conduct](https://github.com/tootsuite/mastodon/blob/master/CODE_OF_CONDUCT.md). You can also learn about pepe the frog [here](https://www.adl.org/education/references/hate-symbols/pepe-the-frog), but this is not the place to discuss that.

**Closed** 2020-07-13 14:34 UTC
