### ISSUE TITLE
Group : usage possibility

### ISSUE THREAD

**Issue by Shnoulle** [tootsuite/mastodon#1809] opened 2017-04-14 21:27 UTC
I know @Gargron (and surely other's) didn't want to implement group for 2 reason

1. think [hashtag](hashtags) is OK
2. think it's like an user account

But : the usage is totally different, maybe mastodon concept is not for this on gnusocial

See [gnusocialfr](https://quitter.no/group/gnusocialfr) group for example : you can find anyone anywhere on the [fediverse](http://oracle.skilledtests.com/group/464/id). You have interested by gnusocial and spek french : you can ask help, advice give good tips (or bad if you want) about  gnu-social in french language.

Currently an french user want to help new mastodon user, create an `#MastodonEntraide` tag for this. Good idea, but on the 1st instance : there are less hep than on another instance of mastodon. Th tag is local only, not for all instance. If one user goes to a little instance, he see only one or two help tags ... With a group system, more global : you can have people on this group (they choose to appear on this group), and you have a place, a specific hasthag to have information from whole mastodon user's , not only local or linked group.

I don't have to ask a feature for mastodon, i'm not a mastodon user. But i see a lot of situation where we need !mastodon or !mastodonadmin or !mastodonfr or !mastodonjp group. And even if after there are more specific group : user choose to integrate it, nobody force to go to 'Register to the group'

-----
Edit : example with `#MercrediFiction` tag

* ![capture du 2017-04-20 11-02-00](https://cloud.githubusercontent.com/assets/1439428/25222694/71174010-25b9-11e7-823e-1a702f2675c8.png)
* ![capture du 2017-04-20 11-02-13](https://cloud.githubusercontent.com/assets/1439428/25222693/71144d74-25b9-11e7-9c63-a3d60cca9fb7.png)
* ![capture du 2017-04-20 11-02-23](https://cloud.githubusercontent.com/assets/1439428/25222695/71194554-25b9-11e7-8cac-4a53203e987c.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Shnoulle** [comment] 2017-04-20 08:54
Maybe if not able to create group on mastodon, allow to regsiter to existing group on gnusocial ?

I try to register to http://oracle.skilledtests.com/group/fediverse , 

1. with `@user@example.org`, receiving `Invalid XML` .
2. with `https://example.org/@user`, receive a 404 on https://example.org/main/ostatussub?profile=http%3A%2F%2Foracle.skilledtests.com%2Fgroup%2F464%2Fid

**Comment by Gargron** [comment] 2017-06-29 23:01
Duplicate of #139

**Closed by Gargron** 2017-06-29 23:01 UTC
Labels: enhancement, priority - low, requires in depth
