### ISSUE TITLE
Profile in web interface won't load more posts

### ISSUE THREAD

**Issue by nightpool** [tootsuite/mastodon#3673] opened 2017-06-09 19:24 UTC
happens on 1.4.1

Steps to reproduce:

1. click on a profile, but don't scroll at all
2. click off onto something else (another profile, a toot, etc)
3. click back into the same profile
4. scroll down, but notice that it won't load any more statuses.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment] 2017-06-09 19:25
The only way to fix this is refreshing the page.

If you do scroll in step 1, that doesn't fix the problem—it will only show the pages you load in your *very first viewing* of a user, you can't scroll any further then that.

**Comment by unarist** [comment] 2017-06-09 23:49
duplicate of #3447?

**Comment by nolanlawson** [comment] 2017-06-16 17:58
This does appear to be a dup, yes.

**Closed by nolanlawson** 2017-06-16 17:58 UTC
