### ISSUE TITLE
Account export/data liberation

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/mastodon#454] opened 2017-01-10 15:41 UTC
Users should be able to download a copy of their user data, including:
- All their toots (ideally in a CSV format, probably)
- Toot media (?)
- Following list
- Followers list

Similar to #177 but simpler and with a different end-goal in mind.

**Comment by iztoogood** [comment] 2017-04-25 18:23
maybe an export format in xml for toots
and zip/rar/7z format for medias ...???

**Comment by Gargron** [comment] 2017-06-29 14:24
Duplicate of #201

**Closed by Gargron** 2017-06-29 14:24 UTC
Labels: enhancement
