### ISSUE TITLE
Toot expiry option

### ISSUE THREAD

**Issue by jckw** [tootsuite/mastodon#3823] opened 2017-06-17 15:32 UTC
Hi, 

This is a feature request for settings for Toots to automatically delete/expire within a certain amount of time. By expiry time I mean the amount of time which has to pass before a Toot is automatically deleted, rather than a specific date/time that a Toot expires on. 

I would suggest keeping the default to Toots never expiring unless a user deletes them, however it would be nice to get the option to set a default expiry time in your account settings, but also have the option to alter the time on a Toot-by-Toot basis. 

The range for expiry times would be pretty large and it could make an awkward input to design if a user can choose anything between an hour and 6 months, but the more flexibility the more useful the feature is. 

This is a feature that I (@jck@mastodon.social) and a few others thought would be useful and make Mastodon feel like a social network where you *actually* have control over your own data. 

There would obviously need to be exceptions of some sort for Toots that have been marked for moderation, so that the feature can't be used for harassment that auto-deletes before a moderator can get to it. 

Thanks for looking at this!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by joyeusenoelle** [comment] 2017-06-17 16:00
Check out ephemeral.glitch.social, which does exactly this.

**Comment by jckw** [comment] 2017-06-17 16:14
So I guess auto-deletion, in general, is possible, but letting users select expiry would require quite a bit more work?

**Comment by Lemmmy** [comment] 2017-06-17 16:14
not too much work but yea

**Comment by Kimik0** [comment] 2017-06-17 21:18
I don't see the need for this. If you want to delete one of your toots you can do so, but why would you want to do this automatically? Is it that troublesome if someone reads an old toot?

It would add yet another setting to the already complex toot box (CW/NSFW, visibility).

**Comment by Lemmmy** [comment] 2017-06-17 21:18
why not add an overflow menu for additional options then?

**Comment by Kimik0** [comment] 2017-06-17 21:28
That doesn't make it less complex. Haven't you noticed how often new users ask how the content warning and visibility functions work? Expiring toots would make it even harder for newcomers to understand what's going on.

**Comment by ggtea** [comment] 2017-06-17 21:38
FYI: pawoo.net already implements this feature.
They says it's experiment but it works.
User can select expiration time and added as hashtag. '#exp1m' means expires in 1 minutes.
Toot with expiry does not federated to other instances for safety. (Federated toot deletion not always succeed)

**Comment by jckw** [comment] 2017-06-17 22:01
In comparison to the content warning, the UI for an expiry setting would be far more intuitive considering the simplest option would be something like a timer, and a label 'Auto-delete after:'. 

It was really a feature suggestion to help users keep their digital-footprint down and bring the social network back to them (as Mastodon aims to do). Deleting Toots from last month or even last week isn't practical at all at the moment if you post just 10 times a day, since there's no mass deletion option. For some people like myself, long-gone posts and footprint control are ultimately privacy issues.

If a post-by-post basis is too complex for the UI, then it would be useful to at least have mass deletion controls somewhere in the Settings page. If that's possible, I don't see why having an automated mass deletion after X weeks setting is unreasonable.

**Comment by Lemmmy** [comment] 2017-06-17 22:03
![](https://shitty.download/yoXE.png)

there's plenty of space here for an accordion with more advanced features such as expiry, scheduling, etc.

**Comment by Lemmmy** [comment] 2017-06-17 22:04
![](https://shitty.download/znlR.png)

there's plenty of space here for an accordion with more advanced options such as expiry, scheduling etc

**Comment by Cassolotl** [comment] 2017-06-17 23:00
@Kimik0

>I don't see the need for this. If you want to delete one of your toots you can do so, but why would you want to do this automatically?

Fun.

**Comment by Kimik0** [comment] 2017-06-17 23:01
> It was really a feature suggestion to help users keep their digital-footprint down and bring the social network back to them (as Mastodon aims to do). Deleting Toots from last month or even last week isn't practical at all at the moment if you post just 10 times a day, since there's no mass deletion option. For some people like myself, long-gone posts and footprint control are ultimately privacy issues.

Ah, now it's starting to make sense to me. The only use for short expiration times (~minutes) I could think of was silliness or trolling, but longer expiration times (~weeks) seem like a reasonable addition.

But the best place for something like that would be the Settings pages. You wouldn't want to have to configure that again and again for every toot. Either an "Automatically delete my toots after ` ` days" setting or a "Delete all toots older than ` ` days" action would work.

**Comment by Cassolotl** [comment] 2017-06-17 23:02
>The only use for short expiration times (~minutes) I could think of was silliness or trolling

This would never go down well on Mastodon, at ALL. \*very serious face\*

**Comment by Kimik0** [comment] 2017-06-17 23:04
It depends. Some chaos-loving instance admins would allow it, but I think the more serious ones would disable the feature if it could be abused that way.

**Comment by jckw** [comment] 2017-06-17 23:09
I can still see a use for short-life posts. 

If you're having a conversation with someone often I don't want that to stay around too long after since I'd like to put an end to it at some point. 

Post scope settings don't work at all in this case since more people can join in, but after a certain amount of time (should that be 30 minutes or so), the post series could auto-delete so that you can escape the discussion more easily, and it would be far easier considering a discussion can last 30 posts – every one of which have to be deleted or any one of which other users can reply to past the time that you intended to be involved with the discussion.

**Comment by Cassolotl** [comment] 2017-06-17 23:10
@kimik0 Well, of course, it could be a configurable option. But why disallow it? ephemeral is getting along fine and not making everything terrible, right? It can be a little confusing but people are clearly enjoying it. It's like saying Snapchat is bad because you can only look at the pictures for a few seconds.

**Comment by Kimik0** [comment] 2017-06-17 23:24
Nah, it just feels like something only a few people would use often. For the rest of us it would only clutter up the interface.

**Comment by jckw** [comment] 2017-06-18 07:48
I think more people would use it and see the benefits of this feature after it's been implemented. Since no other major social network has implemented something like this or even made it easy to control your footprint, it's a new concept; and one that I think people will take well too once it's available. 

I really don't think this would clutter up the interface. For the slight inconvenience (perhaps), we get another feature for Mastodon to make it stand out as a privacy-centric non-twitter clone. 

Here are a couple of ideas that don't clutter up the interface at all.

Either a clear option without a menu.
![Clear option](https://user-images.githubusercontent.com/11884004/27259039-e74a24d4-5401-11e7-90ca-2c82db4fd782.png)

Or the icon can be hidden in a menu. This would allow for other features if necessary. 
![Hidden in menu](https://user-images.githubusercontent.com/11884004/27259067-92435b94-5402-11e7-8e6e-1f59f02d70cb.png)

**Comment by wxcafe** [comment] 2017-06-20 10:56
The problem with that is with federation. You can guarantee the toot has been deleted from the originating instance, but you can't guarantee that remote instances will delete them when they get the message to do so (or that they will get the message at all)

but then that's the same problem as with normal toot deletion.

**Comment by jckw** [comment] 2017-06-20 13:35
I guess the main idea with time-expiry is to make it *more* difficult to keep that post on the record. 

In any case, a screenshot or something can be taken which would also have a similar effect as another instance storing a toot for longer than requested. Time-expiry just obfuscates the process of bringing up the contents of the post, which is all that's necessary.

**Comment by wxcafe** [comment] 2017-06-20 13:36
Yeah totally. I'm for it, just pointing out that it can't be a certified deletion

**Comment by beatrix-bitrot** [comment] 2017-06-20 15:34
likely going to be testing this at the instance and user level but not at the level of individual toots, mostly due to interface clutter and it maybe not being necessary

will try to remember to post back here when there's some results

**Comment by Cassolotl** [comment] 2018-02-26 23:13
I think this is a duplicate of the slightly older *Content auto expire / delete for users #1295*?

**Comment by wxcafe** [comment] 2018-02-27 12:39
yeah looks like, closing

**Closed by wxcafe** 2018-02-27 12:39 UTC
Labels: priority - medium, suggestion

**Comment by KaKi87** [comment] 2024-01-10 00:02
Hello,

@Cassolotl, @wxcafé, this issue is not a duplicate because requesting a per-post option and a wider duration range (especially lower ones).

Please consider reopening it.

Thanks
