### ISSUE TITLE
2.6.2 does not show full in a screen, have to scroll Horizontal.

### ISSUE THREAD

**Issue by star2056** [tootsuite/mastodon#9357] opened 2018-11-26 14:27 UTC
My computer screen resolution is 1280x720.
2.6.2 updated at cmx.im
I found the screen can't show everything. have to scroll horizontal.
And I feel not so handy to use.
>>This is 2.6.1
![2 6 1](https://user-images.githubusercontent.com/26737255/49019910-0981f600-f1ca-11e8-8b9b-b1e30a5c6b22.png)

>>This is 2.6.2
![2 6 2](https://user-images.githubusercontent.com/26737255/49019925-1272c780-f1ca-11e8-9f63-a2bd50b282cd.png)

You can compare them and easily found the upper area is a bit wider.
So could Developers fix this problem please?

**Comment by phil-r** [comment] 2018-11-26 15:44
it was intentional https://github.com/tootsuite/mastodon/pull/9227

**Comment by star2056** [comment] 2018-11-26 15:59
> it was intentional #9227

yeah I see.
but this is eh... not so friendly to low resolution user.
I know I can set resolution bigger but the fonts will be so small and kill my eyes.

**Comment by Gargron** [comment] 2018-11-27 11:35
Duplicate of #9344

**Closed by Gargron** 2018-11-27 11:35 UTC
