### ISSUE TITLE
CopyStatusStats Migration consumes a lot of time

### ISSUE THREAD

**Issue by isidai** [tootsuite/mastodon#8275] opened 2018-08-18 17:41 UTC
I found a bug that CopyStatusStats Migration consumes a lot of time.
The cause commit is https://github.com/tootsuite/mastodon/pull/8256/commits/f1fd7b79a92d675b6e71fbe61402209f0090d4ba .

Please try to remove "where.not (id: StatusStat.select ('status_id')). "
I confirmed that it works well.

**Comment by Gargron** [comment] 2018-08-18 19:40
Could you give me more details? Are you certain the issue is in that part? It's meant to ensure that if you run the migration twice (because it failed before, for example), that it will only process statuses that need processing. What's the timing?

**Comment by midhunkrishna** [comment] 2018-08-18 19:58
Slow perf issues can be due to multiple reasons. Depending on batch size, the find_in_batches might create lot of objects in memory and object creation might take time after while if there are a lot of objects. 

I checked the code base, and we do have Kaminari as a dependency. May be we can do the following:

```ruby
per_page = 1000
if defined? Kaminari
  if Status.respond_to? :page
    Status.per_page = per_page
  else
    Status.class_eval do
        paginates_per per_page
    end
  end
  
  total_count = Status.where.not(id: StatusStat.select('status_id')).count
  page_count = (total_count / 1000) + 1
  page_count.down_to(1) do |index|
    scope = Status.where.not(id: StatusStat.select('status_id')).page(index) # ar scope object
  end
else
  Status.where.not(id: StatusStat.select('status_id')).select('id').find_in_batches do |statuses|
    # yield the block
  end
end 
```

This also means fewer queries.

**Comment by Gargron** [comment] 2018-08-18 20:44
It could be an issue with `Filter: (NOT (hashed SubPlan 1))` if it has to hash an entire table (statuses_stats), depending on how big it has become since it was created (so, time between first migration that creates statuses_stats and this migration).

This should not really affect people upgrading at once, it sounds like something only those who upgrade from commit to commit would encounter, but then again I am pretty sure that the migrations were released in a single commit.

**Comment by isidai** [comment] 2018-08-18 22:08
exactly.
`statuses_status` table is bloated each time it loops, and the loop rescans the entire `statuses_status` table, so performance gets worse as the loop progresses.

**Closed** 2018-08-19 00:01 UTC
