### ISSUE TITLE
Add notification to threads

### ISSUE THREAD

**Issue by splacat** [tootsuite/mastodon#13689] opened 2020-05-10 11:57 UTC
When you are interested on reading a thread you don’t know when new toots arrive to that thread

### Pitch

Add possibility to receive a Notification when that happens.

### Motivation
Don’t loose any toots from interesting thread.

**Comment by trwnh** [comment] 2020-05-12 03:30
duplicate of #7969

**Comment by resynth1943** [comment] 2020-05-12 18:17
Hope this becomes a feature!

**Closed** 2020-05-13 02:12 UTC
Labels: suggestion
