### ISSUE TITLE
Allow code formatting with backticks

### ISSUE THREAD

**Issue by joyeusenoelle** [tootsuite/mastodon#7433] opened 2018-05-10 02:44 UTC
This is mentioned briefly in #853, but the scope of that issue is much broader than what I'm addressing.

I suggest that we allow users to use the backtick character (`) to surround text intended to be preformatted, such as code. This should do two things:

* Preserve spacing, even at the beginning of a line
* Do not interpolate account names or hashtags, allowing the @ and # characters to be used indiscriminately

No other formatting needs to be done. (Converting to monospace would be nice, but isn't strictly necessary.)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment] 2018-05-10 02:47
duplicate of #853

**Closed by ykzts** 2018-05-10 02:47 UTC
Labels: duplicate

**Comment by no-boot-device** [comment] 2018-05-10 02:48
I suggest instead we have it so that
\`\`\`
[code]
\`\`\`
works. 
Less easy to misdo.

**Comment by no-boot-device** [comment] 2018-05-10 02:48
Aaaand it's closed.
Oh well.

**Comment by joyeusenoelle** [comment] 2018-05-10 02:48
I mentioned #853 in the post. Don't close issues without reading them, @ykzts.

**Comment by ykzts** [comment] 2018-05-10 02:51
Obviously the problem is duplicated. There is no point in distributing the discussion more than necessary.

**Comment by joyeusenoelle** [comment] 2018-05-10 02:54
@ykzts It really isn't. This is asking for a single specific feature that was mentioned tangentially in another issue. If you're not going to take the time to read the discussions in question then please step down as a moderator of this repo.

**Comment by joyeusenoelle** [comment] 2018-05-10 02:57
If we're using StackOverflow as our model for interaction with this project then I am done contributing.

**Comment by ck-slackz** [comment] 2019-01-06 20:42
Yo @ykzts, this is the type of thing that makes ppl not wanna be involved in a project.  You can't rudely close qn issue, ignore pushback about it, and then decide to not respond to criticism about your hasty decision.

Please reopen and respond respectfully

**Comment by ck-slackz** [comment] 2019-01-06 20:45
This is a distinct issue from 853 and a subset that shouldn't potentially be mired in a larger discussion about markdown.

Even if it's not the best approach, it's not for you to shut it down unilaterally (esp without responding to subsequent challenges to that decision).

Yo @gargron are there guidelines about how admins engage here?  Because this isn't a good look...

**Comment by bobcanthelpyou** [comment] 2019-01-06 21:20
@ck-slackz Why is this feature request not a duplicate or at least a subset of #853 ? The Markdown formatting is mentioned in the "Text formatting" feature request in nearly all comments.

**Comment by ck-slackz** [comment] 2019-01-06 21:31
@bobcanthelpyou  The OP specifically referenced other issue, so even if it is a subset, it's valid to consider as a separate issue.

This is also fundamentally not the point.  My concerns is about an admin abruptly shutting this down and not responding to concerns about how that was done.  

This is about process and encouraging community engagement, not markdown
