### ISSUE TITLE
[Bug] Error 400: In Reports - clicking "mark as sensitive" without clicking the box on the image

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#8360] opened 2018-08-22 08:54 UTC
Reports area in admin.
1) Don't Select toot.
2) Click 'mark as sensitive'

400 error.

**Comment by ThibG** [comment] 2018-08-22 09:45
This sounds like a duplicate of #8168

**Closed by ThibG** 2018-08-22 09:45 UTC
