### ISSUE TITLE
Allow users the ability to block an entire instance

### ISSUE THREAD

**Issue by mostlyghost** [tootsuite/mastodon#937] opened 2017-04-05 12:17 UTC
itd be nice to be able to block everyone over at BigotedJerkInstance.social. Or mute. Either or both would be cool. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by RaitoBezarius** [comment] 2017-04-05 12:22
It does already exists, it's called "Domain Block".
Contact your instance administrator to add the domain to the block list.

**Comment by ghostfromicosahedron** [comment] 2017-04-05 13:06
But that would block the target for the entire instance's user base, right? That may not be the admin's preference. What if an individual user just wants to opt out of an entire domain?

**Comment by blackle** [comment] 2017-04-05 14:05
this would be covered by PR #501 if it ever gets merged

**Comment by BjarniRunar** [comment] 2017-04-18 11:10
I think this issue is very important.

Individual users should not need to rely on a friendly admin being willing to block an entire site, they need to have the tools to protect themselves.

It would also neatly sidestep a lot of the politics around instance-wide blocks.

**Comment by jfmcbrayer** [comment] 2017-04-18 11:59
I think we still need instance-wide blocks (because giving users the tools to protect themselves is great; making them have to protect themselves is not great). But I agree that this is very, very important. Could @Gargron please prioritize reviewing #501?

**Comment by no-boot-device** [comment] 2017-04-19 22:26
bumping this issue

**Comment by majestrate** [comment] 2017-04-21 19:41
make it regex based that way you can block `*.jp$`

**Comment by Cassolotl** [comment] 2017-04-21 19:48
I don't know how to use regex so that's probably not accessible to average users, perhaps? Something more user-friendly in addition to regex would be good though!

**Comment by M-D-M** [comment] 2017-04-21 20:04
Agreed -- regex is cool, but it's way out of the realm of ability for most users.  Upvoting this.

**Comment by Cassolotl** [comment] 2017-04-23 09:12
I think this is a duplicate of the much older #423.

**Comment by Gargron** [comment] 2017-05-19 01:13
Duplicate of #423

**Closed by Gargron** 2017-05-19 01:13 UTC
Labels: enhancement, priority - high, requires in depth, ui
