### ISSUE TITLE
Streaming not working due to websocket connection failure

### ISSUE THREAD

**Issue by ramlmn** [tootsuite/mastodon#2369] opened 2017-04-23 18:42 UTC
### Expected behavior
Streaming URLs (using wss) should establish a connection and get responses from the server whenever a toot or notification.

### The issue
WebSocket connections for `/api/v1/streaming/` seem to fail due to a network timeout by a malformed URL.

A streaming URL is generated [here](https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/stream.jsx#L14), using an anchor tag for parsing URLs. But when the `href` property of an anchor tag is set to something like `http://google.com`, the user-agent transforms the URL into something like `https://google.com/` (note the trailing slash)

The code apparently appends another `/` after the `streamingAPIBaseURL`
``` js
const ws = new WebSocketClient(`${createWebSocketURL(streamingAPIBaseURL)}/api/v1/streaming...`;
//                                                                        ^- here
```

Timeout happens as there is no handler for exactly matching `//api/v1/...` requests.

### Symptoms
* A continuous stream of websocket connections created for each websocket connection failure.
  
  ![websocket-request-tree](https://cloud.githubusercontent.com/assets/12368291/25316150/161bf638-287f-11e7-8e99-0b2d49efc6e5.png)
* All empty requests:
  
  ![websocket-request](https://cloud.githubusercontent.com/assets/12368291/25316249/10466bd8-2881-11e7-82be-52b0de0b902a.PNG)
 * Failed requests:
  ![websocket-request-failed](https://cloud.githubusercontent.com/assets/12368291/25316250/14f6468a-2881-11e7-9baa-efd7763316c1.PNG)

Due to this, the page had to be frequently refreshed manually to get new toots and notifications displayed.

Some instances and users don't seem to experience this issue, because I think there might be an issue with caching (see 'steps to reproduce' below).

### Where is this tested
* Chrome 57:
  
  ![websocket-error-chrome](https://cloud.githubusercontent.com/assets/12368291/25316003/75d17d3a-287c-11e7-8c1a-89179a07f413.PNG)
* Firefox 52:
  
  ![websocket-error-firefox](https://cloud.githubusercontent.com/assets/12368291/25316004/8e5d8c7c-287c-11e7-82af-c8c7182ec24d.PNG)
* Edge 15:
  
  ![websocket-error-edge](https://cloud.githubusercontent.com/assets/12368291/25316014/d8da11bc-287c-11e7-8a43-d80993a5ac58.PNG)

### Steps to reproduce
* **Clear all cache** an cookies for the site (instead use incognito or guest mode).
* Open devtools and select 'disable-cache' option
* View network panel for continuous websocket requests and console for errors (this is a timeout error, have to be patient)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by woganmay** [comment] 2017-04-23 20:23
I'm not able to reproduce this.

I've tested in raw node using the same WebSocket client that the frontend uses, and it's able to successfully connect to stream URLs that have a // after the domain, like in the screenshot above. This has been proven from 3 different network connections (home, cloud9 and digitalocean).

Is it not possible that there was a local network error/filtering issue when you experienced the bug?

**Comment by mjankowski** [comment] 2017-04-23 20:50
Is streaming actually supported on your instance?

**Comment by ramlmn** [comment] 2017-04-24 04:04
> Is streaming actually supported on your instance?

@mjankowski Streaming is supported on my instance [https://toot.cafe](https://toot.cafe) \cc @nolanlawson 

****

> Is it not possible that there was a local network error/filtering issue when you experienced the bug?

@woganmay Tested in
* mobile chrome on mobile network:

  ![chrome-mobile-mobile-network](https://cloud.githubusercontent.com/assets/12368291/25321952/12f56e70-28d0-11e7-9951-ea50f78b910c.PNG)

* mobile chrome on wifi:

  ![chrome-mobile-wifi](https://cloud.githubusercontent.com/assets/12368291/25321961/1ed19cc8-28d0-11e7-878a-1b12caa70d6e.PNG)

* desktop chrome on wifi:

  ![chrome-desktop-wifi](https://cloud.githubusercontent.com/assets/12368291/25321972/2de484b4-28d0-11e7-885b-bf5df5d50272.PNG)


Even if i manually create a WebSocket (like in the images), it still fails. The connections fail immediately.

The same goes for Firefox and Edge.

**Comment by wxcafe** [comment] 2017-04-24 12:05
This is not a bug but a problem with how your instance is setup, so I removed the bug label

**Comment by nolanlawson** [comment] 2017-04-24 15:18
I'm looking into this. My config should be exactly as suggested in [the nginx instructions](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) but I may have messed something up. So far I am unable to reproduce in Firefox or Chrome although in Edge I'm seeing multiple 101 requests and then no updates in the UI.

**Comment by nolanlawson** [comment] 2017-04-24 15:27
OK, I am comparing toot.cafe to mastodon.social, and I see no difference between the two either in the logs or in functionality, except in Edge 15 where the logs appear the same but notifications don't appear 😕 .

Maybe this is an ISP issue? I've had problems in the past where ISPs differed in how they allowed WebSocket connections. Can you check http://websocketstest.com/ and make sure websockets work on your ISP over port 443?

**Comment by wxcafe** [comment] 2017-04-24 15:28
it seems you're having network problems yeah. ERR_NET_TIMED_OUT would seem to indicate this

**Comment by nolanlawson** [comment] 2017-04-24 15:39
This appears to be related to exceeding the PostGres connections limit. I've restarted all service and throttled the threads a bit, and I can't even reproduce the Edge issue anymore. Since this is probably something on the toot.cafe end of things, you can probably close this. :)

**Closed** 2017-04-24 15:49 UTC
Labels: help wanted, question

**Comment by ramlmn** [comment] 2017-04-24 16:35
It works now.
