### ISSUE TITLE
[Feature Request] Have some accounts show a confirmation when posting

### ISSUE THREAD

**Issue by madprops** [tootsuite/mastodon#10014] opened 2019-02-11 19:29 UTC
In my case I have 2 accounts. One is personal where I write random stuff. One is used for my online radio, and should only post automated updates through a bot, the cases I write something myself here are few. I've had this problem several times where I accidentally post a thought on the radio account, since sometimes I get confused dealing with 2 different accounts. Having an option to show a confirmation before posting from the client would be nice, I can enable that on my radio account. This shouldn't affect automated posting through bots of course, it should be a client thing.

**Comment by trwnh** [comment] 2019-02-11 19:47
Duplicate of #7860

**Closed** 2019-02-11 22:02 UTC
