### ISSUE TITLE
Mastodon www stack on brave+android titup

### ISSUE THREAD

**Issue by pabloski80** [tootsuite/mastodon#15925] opened 2021-03-19 11:25 UTC
### Expected behaviour
Allowing closing image with x in top right when looking at attached pic.

### Actual behaviour
Brave goes titsup and says due to error on page the page cant be displayed but should work in other browsers.

### Steps to reproduce the problem
Click on attachef image in  toot from instance tootlist. Click x in top right.

### Specifications
Cant tell what version  nas server is using.

Brave omn android on galacy s6.

Stack:

TypeError: Cannot read property 'get' of null

TypeError: Cannot read property 'get' of null
    at t.render (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:256881)
    at Bi (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1024466)
    at qi (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1024261)
    at Os (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1059875)
    at bu (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1051316)
    at mu (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1051241)
    at su (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1048271)
    at https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:999912
    at t.unstable_runWithPriority (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:1074970)
    at Va (https://noagendasocial.com/packs/js/common-a34d4fc19bd4731b9983.js:2:999621)

render (webpack:///app/javascript/mastodon/features/picture_in_picture/components/footer.js:124:65)
gi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4333:75)
Lg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4324:9)
fi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6700:85)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6150:10)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6139:8)
Ej (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5880:8)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)

**Comment by pabloski80** [comment] 2021-03-19 11:26
Mastodon v 3.3.0 is version.

**Comment by ClearlyClaire** [comment] 2021-03-19 18:01
Looks like a duplicate of #15860

**Closed by ClearlyClaire** 2021-03-19 18:01 UTC
Labels: bug
