### ISSUE TITLE
Uploading big non-MP4 video files may result in 504 error

### ISSUE THREAD

**Issue by ichi-i** [tootsuite/mastodon#11633] opened 2019-08-21 00:37 UTC
## Expected behaviour
Uploading a big *.webm, *.mov, *.m4v file would result in the file being uploaded. Possibly without conversion if the server cannot handle it.

### Actual behaviour
Small servers may not have enough CPU resources to allow ffmpeg to convert the uploaded video file in 60 seconds. This results in nginx timing out the connection (504) as by default nginx doesn't wait more than 60 seconds (default nginx setting) to get a response.

### Steps to reproduce the problem
Upload a big enough file (say 10MB *.webp or *.mov) to a server with 1 vCPU.

### Specifications
Mastodon v2.9.3

This can be fixed by either avoiding conversion or increasing the nginx time out time in the configuration file.

I can understand it is hard to create something that works both for smaller and bigger servers. Maybe a configuration option to disable conversion could be added?

**Comment by Gargron** [comment] 2019-08-21 14:55
Technically duplicate of #9106

**Closed by Gargron** 2019-08-21 14:55 UTC
