### ISSUE TITLE
On Single-Column layout scrolling should work everywhere.

### ISSUE THREAD

**Issue by comzeradd** [tootsuite/mastodon#11551] opened 2019-08-12 10:42 UTC
### Pitch

On single-column layout to scroll down you need to hover on top of the column. Since most of the items outside the column are fixed, it makes more sense to scroll the content in the column regardless of where the mouse cursor is.

### Motivation

Scrolling the column only on hover is not very obvious and intuitive (especially for people coming from the bird site). This is also easier in terms of accessibility.

**Comment by Gargron** [comment] 2019-08-12 11:30
Duplicate of #10840

**Closed by Gargron** 2019-08-12 11:30 UTC
