### ISSUE TITLE
end-to-end encrypted messanger just like on cryptpad, no browser addons

### ISSUE THREAD

**Issue by Serkan-devel** [tootsuite/mastodon#8123] opened 2018-08-04 16:59 UTC
It would be great to have PMs be encrypted over the Fediverse.
Better would it be to have encryption run completely on the browser instead of using a browser addon.

There already is an open source real-time collaboration service, similar to Etherpad, called [CryptPad](https://cryptpad.fr/index.html), which uses [tweetnacl.js](https://github.com/dchest/tweetnacl-js) and [scrypt-async.js](https://github.com/dchest/scrypt-async-js) to encrypt everything on the client-side. It seems to be a very promissing [cross-browser project](https://fosdem.org/2018/schedule/event/cryptpad/).

Using a seperate extension would make it herder to use on Mobile browsers, which don't support addons (except Firefox for Android but it's clunky) and non-conventional browsers. It would make sense to utilize all mastodon features completely within a browser, rather than relying on an extension use everything. Using the extension as an app in the background, to access encripted messages in the browser would be terrible for UX.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
There is one similar issue, suggesting the same thing but with a browser addon

**Comment by Gargron** [comment] 2020-05-21 19:26
Duplicate of #1093

**Closed by Gargron** 2020-05-21 19:26 UTC
Labels: suggestion
