### ISSUE TITLE
Broken links in API documentation

### ISSUE THREAD

**Issue by shaftoe** [tootsuite/mastodon#14085] opened 2020-06-17 14:48 UTC
I'm assuming https://docs.joinmastodon.org/ is the online documentation reference, so I'd like to let you know that some of the links there are broken, e.g.

- https://docs.joinmastodon.org/client/methods/accounts/#account
- https://docs.joinmastodon.org/client/methods/accounts/#statuses
- https://docs.joinmastodon.org/client/methods/statuses/#view-specific-status

I take the chance to ask how to find out my account :id (to make use of `GET /api/v1/accounts/:id/statuses` for example), I can't find it anywhere in the web admin interface 😢

**Comment by trwnh** [comment] 2020-06-17 18:36
Duplicate of https://github.com/tootsuite/documentation/issues/764

**Closed** 2020-06-17 18:37 UTC
