### ISSUE TITLE
Per-instance verified users/checkmarks

### ISSUE THREAD

**Issue by ticki** [tootsuite/mastodon#3821] opened 2017-06-17 10:56 UTC
A checkmark system solves a lot of hazards with identity theft and fake accounts. Adding decentralized, per-instance verification would be really nice.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment] 2017-06-17 12:58
What would it verify?

I'm asking because most people who ask for verification want a centralised thing to make sure people can't use "their" username on other instances, and since no one can use my username on my own instance... I am confused!

**Comment by joyeusenoelle** [comment] 2017-06-17 15:31
Mastodon doesn't have verified users by design; it goes against the decentralized nature of the platform, devalues anonymity-by-choice, and reinforces a power structure antithetical to the values of the project.

At mastodon.social we're considering user flair for admin and moderator accounts, and even that is a matter of debate.

Individual instances are welcome to implement a verification system, but it's unlikely to make its way into the core Mastodon codebase.

**Comment by wxcafe** [comment] 2017-06-20 11:17
Closing this following the previous comment

**Closed by wxcafe** 2017-06-20 11:17 UTC
Labels: wontfix
