### ISSUE TITLE
Activitypub interoperability

### ISSUE THREAD

**Issue by git-marijus** [tootsuite/mastodon#5653] opened 2017-11-10 20:23 UTC
Mastodon does not seem to deliver "reply to thread" messages from users i am not connected with. There is no issue with direct replies to the top level posts (connected and not connected users) and "reply to thread" messages from users i *am* connected with.

For "reply to thread" messages from not connected users i don't receive any payload - nothing. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment] 2017-11-10 20:27
Can you give an example of this? Mastodon currently should deliver a message to all users that are *mentioned* in a post.

**Comment by git-marijus** [comment] 2017-11-10 21:03
Ok, i am not mentioned. Anyway, here is an example:

This is a thread from @Gargron on mastodon: https://mastodon.social/@Gargron/98982006024569769

Here is a copy of this thread in my timeline: https://hub.somaton.com/display/b64.aHR0cHM6Ly9tYXN0b2Rvbi5zb2NpYWwvdXNlcnMvR2FyZ3Jvbi9zdGF0dXNlcy85ODk4MjAwNjAyNDU2OTc2OQ

You will see that the second reply (maria) is missing from my copy - she was replying to the first reply.

Please disregard the missing posts of Hyper in my copy (he is using ostatus and we don't deal with that in our activitypub implementation).

**Comment by nightpool** [comment] 2017-11-10 23:02
Mastodon uses JSON-LD Signatures to implement thread forwarding. If your code doesn't support linked-data signatures (I don't know if hubzilla does) then it won't see forwarded statuses from other users.

**Comment by nightpool** [comment] 2017-11-11 03:31
Oh, nevermind, I misread this. Yes, currently mastodon only delivers for followers of the person directly replied to. It doesn't do any type of recursive retrieval.

**Comment by Gargron** [comment] 2017-11-11 03:39
>Currently mastodon only delivers for followers of the person directly replied to. It doesn't do any type of recursive resolution of replies....

This is true, but usually not an issue if all participants are mentioned in the post. The post gets delivered to all mentioned users, and then those forward it to their followers.

**Comment by nightpool** [comment] 2017-11-11 03:51
@Gargron 

```ruby
def forward_for_reply
    return unless @json['signature'].present? && reply_to_local?
```

seems to contradict that? you'll get it, but it's not a reply to a local post, so it doesn't get forwarded to you.

to be clear, this is the situation:

 - A@A posts
 - B@B replies to A, mentioning A
 - C@C replies to B, mentioning B and A

Followers of A won't see C's post.

I think this is expected behavior, but if it's not, then we should fix it.

**Comment by git-marijus** [comment] 2017-11-11 07:46
7.1.3 states 
> Additionally, if an object is addressed to the Public special collection, a server MAY deliver that object to all known sharedInbox endpoints on the network.

It is a may not a must. IMO it breaks the conversation to some extent not to do so though...

**Comment by Gargron** [comment] 2017-11-11 11:14
>a server MAY deliver that object to **all known** sharedInbox endpoints on the network.

That would be quite a massive endeavor. This is probably written from the perspective of one actor per server (what we call single-user instance), in which case it would translate to delivering to followers.

**Comment by git-marijus** [comment] 2017-11-11 11:31
> in which case it would translate to delivering to followers

That is what i would expect.

**Comment by nightpool** [comment] 2017-12-27 07:39
this is now documented on https://activitypub.rocks/implementation-report/ since the publishing of that page ("No" under inbox:accept:special-forward), so i'm going to close out this issue as a duplicate of #5631, which tracks the known/identified inconsistencies with AP spec documented in that report. 

New inconsistencies with AP spec should be given their own issue so they can be triaged appropriately.

**Closed by nightpool** 2017-12-27 07:39 UTC
Labels: activitypub
