### ISSUE TITLE
Empty favourite notifications generated

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#10343] opened 2019-03-22 05:57 UTC
![image](https://user-images.githubusercontent.com/10606431/54803335-1aed8300-4c3d-11e9-9379-90f022f1f715.png)

The post was not favorited by Jacky Alcine, nor was it favorited at all, nor was it my post.

**Comment by trwnh** [comment] 2019-03-22 06:01
Just inspected the element and it's actually an empty favourite that happened to be above another notification.

**Comment by trwnh** [comment] 2019-04-08 19:42
Just received an empty notification, also from Jacky, so hmm. It might have something to do with duplicate notifications being improperly deduplicated? In the web UI it was the same toot favourited twice, but in Subway Tooter it arrived as an empty notification.

**Comment by ThibG** [comment] 2019-06-08 08:39
Duplicate of #2865 and #9234

**Closed** 2019-10-07 03:36 UTC
Labels: bug
