### ISSUE TITLE
Display character count when editing bio

### ISSUE THREAD

**Issue by KellerFuchs** [tootsuite/mastodon#2058] opened 2017-04-18 06:23 UTC
Right now, the allowed character count (160) is displayed when editing the bio, but not the current count.
This results in repeatedly editing, clicking submit, then getting told the bio is too long (but not by how much).

Instead, switching to displaying the number of remaining characters (or excess characters) above a certain threshold (say, 120) would provide immediate, precise feedback.

I suggest using a threshold because UI elements that change as one types are distracting, and can cause accessibility issues for users of screen readers (though they would need some ARIA markup for the updates to be taken into account), and for some neurodivergent users.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by KellerFuchs** [comment] 2017-04-18 06:29
@bingen13, a blind friend, had some feedback on the proposed design:
> A small click 10 or 8 chars before the limit, and a louder click on trying to add chars beyond the limit, would be quite a nice UI addition for me [instead of the count being read].

**Comment by wxcafe** [comment] 2017-04-18 13:43
This is a duplicate of #1447, closing

**Closed by wxcafe** 2017-04-18 13:43 UTC
Labels: duplicate

**Comment by KellerFuchs** [comment] 2017-04-18 21:19
@wxcafe Thanks, I hadn't found the duplicate when searching.

I copied over the design proposal to the other bug.
