### ISSUE TITLE
Option to keep EXIF for images and custom emoji

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#7270] opened 2018-04-26 17:11 UTC
https://vgy.me/ can do it, why can't you?

this is most important for custom emoji, ofc, but it's also a big deal for normal images, especially if you're a content creator.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Laurelai** [comment] 2018-04-26 17:30
EXIF data has also been used to dox people and a lot of uploaders wash it for privacy reasons.

**Comment by SoniEx2** [comment] 2018-04-26 17:42
there's a reason it's called opt-in.

**Comment by Laurelai** [comment] 2018-04-26 17:58
Sure, but if this is done it should be a per post setting by the user, not something set by the server admins.

**Comment by SoniEx2** [comment] 2018-04-26 18:34
Obviously it should be per-post and per-emoji.

Altho ofc, user shouldn't be able to strip emoji exif.

**Comment by codl** [comment] 2018-04-26 19:44
related: #5239 talks about keeping EXIF authorship fields in emoji

**Comment by SoniEx2** [comment] 2018-04-26 21:00
Even tumblr supports keeping EXIF.

**Comment by SoniEx2** [comment] 2018-04-26 22:27
I need to get around to adding codl to ublock origin at some point...

**Comment by beatrix-bitrot** [comment] 2018-04-26 22:29
@SoniEx2 not ok

**Comment by SoniEx2** [comment] 2018-04-26 22:31
I have all ppl who blocked me on ublock origin. I'm not supposed to see their comments.

**Comment by beatrix-bitrot** [comment] 2018-04-26 22:35
@SoniEx2 github issues are not the place to talk about it

**Comment by mal0ki** [comment] 2018-05-02 08:59
> can do it, why can't you? 

@SoniEx2 can you please refrain from this kind of posturing?

**Comment by SoniEx2** [comment] 2018-05-02 10:05
not if I'm trying to push for an useful feature.

**Comment by mal0ki** [comment] 2018-05-02 10:51
@SoniEx2 I'm trying to ask you kindly here. Please stop. 

This is a warning, after having received several complaints from several people.

**Comment by SoniEx2** [comment] 2018-05-02 11:09
I wouldn't be so bitter if my complaints weren't being completely ignored.

Anything that I say about "mastodon should do better than mainstream social media" just gets ignored, so yes I'm bitter. I didn't make myself bitter tho.

**Comment by Cassolotl** [comment] 2018-05-02 12:01
I think this is a duplicate of *Mastodon removes metadata and with that authorship/copyright information from images #2710*, which was closed in May 2017, because [BrunoSpy and Gargron said](https://github.com/tootsuite/mastodon/issues/2710#issuecomment-298786302):

>> My humble point of view: Mastodon is not a photo sharing platform and as such I do not see an issue if Mastodon strips down EXIF metadata.
> 
> This is exactly my position. We strip metadata, we downsize originals to 1280px at most, etc. If you want to share authentic files, you should use a file sharing platform or specialized hosting e.g. youtube for videos, flickr for photos etc.

**Comment by mal0ki** [comment] 2018-05-02 12:30
@SoniEx2 I'm not going to explain to you why people aren't standing at attention for your issues. If you are just going to add issues and comments for the sake of it you will not be welcome here anymore. 

This is going to be the last warning, stop being rude, stop complaining that we are not here for your whims. Just stop. 

If you want to vent about us not listening to you, that's what your own account on any social media of your choice is for. This is not the place, other's have already been trying to kindly tell you several times to stop. I've already issued you a warning. If you do not cease this, you will be removed from further involvement. 

This isn't about if you're bitter or not, because frankly I don't care, it's about respect for other people and their time. You are not showing it. 

Take a week, think about this, go through all the motions of the emotions that will come up while you do it.

**Closed by mal0ki** 2018-05-02 12:30 UTC
