### ISSUE TITLE
Add option to remove uploaded avatar/header image

### ISSUE THREAD

**Issue by ihavesevenlives** [tootsuite/mastodon#1315] opened 2017-04-09 05:10 UTC
Add an option to remove your uploaded avatar/header image around here or somewhere better:

![removeah](https://cloud.githubusercontent.com/assets/26913497/24834933/93e3be04-1cc0-11e7-92fb-29818614c465.png)

Also, maybe add an administrative option somewhere to remove a user's avatar/header if it's offensive/illegal/instance rule breaking?

**Comment by Gargron** [comment] 2017-06-29 19:18
Duplicate of #3220

**Closed by Gargron** 2017-06-29 19:18 UTC
Labels: enhancement, ui

**Comment by MasterGroosha** [comment] 2017-10-28 19:27
So...is it implemented? #3220 doesn't contain an answer.

**Comment by Cassolotl** [comment] 2017-10-28 19:50
@MasterGroosha If #3220 doesn't have an answer and it's still open, I think that means it hasn't been implemented yet! But if you click Subscribe on that issue you'll get notified when it *is* implemented.

**Comment by Cassolotl** [comment] 2018-05-01 19:00
I just checked because I got notified of semente's comment, and on 2.3.3 (the current version) there's no way to remove avatars. I agree that this needs to be reopened.

**Comment by eai04191** [comment] 2019-04-10 01:16
Any update on this?
I think I need to be able to delete server mascots as well as icons and headers.
