### ISSUE TITLE
Language Filters

### ISSUE THREAD

**Issue by soaklord** [tootsuite/mastodon#1094] opened 2017-04-06 19:23 UTC
It would be nice to filter by language, perhaps by keyboard being utilized. This would cut down on noise in a given instance in that I would not see scrolling toots in languages I don't understand.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jeepfromoil** [comment] 2017-04-06 19:40
Do plurilingual people switch keyboard when they switch language? I don't ;)

I'd prefer a language selector similar to [Wikimedia's](https://www.mediawiki.org/wiki/Universal_Language_Selector). It allows users to set a default language, a pick a few favs for quick switching.

A function could also detect the language as the user type.

Question: should the whole toot be considered in one language? What about toots translated by the user [example](https://octodon.social/@jerome/87959)?

**Comment by sansloi** [comment] 2017-04-06 20:54
I'm just speaking randomly right now.

You can filter searches by regular expression, but that seems to be include only hash tags and account names? If you could filter the 'real time' feed in a similar way, maybe we could have something  that runs client side that prevents toots with words within a blacklist form showing. The blacklist can function as an extension of blocked accounts, but for strings. A table with the words: C'est, vans, or sin would be enough to clear out X% of toots from a specific language, but we'll risk getting false positives. Someone should design a classifier for this.

With your request soaklorde, what would happen with toots that use multiple languages? Some people are already doing their own translations for their own followers, and others are combining them to create colorful sentences. I agree with jeepfromoll that a keyboard approach is not the way to do this. Must of us just hit a few hotkeys to switch our keyboard layouts. The bilingual users of mastodon protest against this recommendation! Won't anyone think of the bilingual users? (j/k)

**Comment by wxcafe** [comment] 2017-04-06 21:54
which language*s* they'd like to post in, please.

**Comment by soaklord** [comment] 2017-04-06 22:36
The keyboard idea was merely a suggestion and not something I am particularly married to.  The idea is that there is something place that determines the audience for a federated feed by language. There has not yet, to my knowledge, been a huge adoption by countries using non-western alphabets, however, I have a feeling that if Mastodon is highly successful, you could end up with federated timelines that are 80% non-western characters alone. Considering the populations of Russia, Asia, India, the Middle East, this could create an environment that dilutes the federation to a point of irrelevance as hundreds of millions of multiple languages compete for a spot in what would become severe noise. With some form of language filtering, perhaps a choice upon sign in, this would help to alleviate what I think could go from being a wonderful place to discover new and fresh to largely ignored.

**Comment by sansloi** [comment] 2017-04-06 23:04
Reposting someone's toot:
==================Begin Toot=======================
people are posting about language again. consider these idle thoughts: 

1) mandating english is rooted in a history of imperialism and continuing that just because you don't understand a thing is lowkey pretty gross
2) maybe not everything on this site is for you. we can be kinder to each other than that
3) many of the people speaking french are silenced in their real lives as marginalized people in a stifling society. let people be free to talk however (excluding harmful impact/bigotry, obv)
==================End Toot=======================

Considering that, the simplest solution would be to take it at a per-instance level. Let each admin's code of conduct dictate what is allowed, and leave it to the local timeline to filter itself by those rules? 

Another idea, perhaps filter via 3rd party plugin? I know there's a repo that's based off rainbow stream already on the works. You can probably get a "piped | grep" filter going with that via CLI.

**Comment by davidcelis** [comment] 2017-04-07 17:27
> Considering that, the simplest solution would be to take it at a per-instance level. Let each admin's code of conduct dictate what is allowed, and leave it to the local timeline to filter itself by those rules?

The issue author isn't asking people to stop tooting in other languages, or mandating that everybody write in English. They're just asking for a way to _personally_ filter out toots in other languages that they can't read. That's a reasonable request, IMO.

**Comment by soaklord** [comment] 2017-04-07 17:38
@sansloi As someone who is trying to teach myself French, I am not opposed to other languages being utilized at all and support a polyglot environment. I don't want to see the federated timeline nor even the local timeline lose the ability for people to post in the language of their choice! Rather, I think it would be beneficial to have a filter in place that allowed for the federated scroll to show only toots in a given language (or ideally languages). This is a scalability question as Mastadon grows. The media is referring to Mastadon as a Twitter Killer. If that became even remotely true, there will be literally hundreds of millions of people tooting across more than 100 languages. That would create a federated timeline that would be virtually unreadable. Being able to filter by language reduces the ambient noise to something that can be understood by a given user. And it creates the platform to perhaps also filter federate timelines by other criteria in the future.  Allowing a user to sign up for federation by interests or to create something akin to parental controls at an individual level. i.e. filter all toots related to anything Kardashian is a very compelling use case. Without the ability to do some kind of filtering on the federation that doesn't rely on instance level filtering of full instances, I don't see how the federated timeline can remain remotely relevant as this scales.

**Comment by sansloi** [comment] 2017-04-07 18:01
Understood, it's just the timing of the post corresponding with complaints of the American user-base. Anyways, already we can use regular expression to filter toots via our home timeline on the web app. I suggest applying the same filter with an inverse selection. Think "grep -v "string" for a library of words you would associate with another language. 

*expand the same filter on the home time line to local
*--inverse-select from library
*say good bye to le fromage

**Comment by Toub** [comment] 2017-04-07 18:12
Languages filters would be very useful.

But not only. Should provide to the user the ability to filter the data based on custom queries too.

**Comment by jeanbaptisteb** [comment] 2017-04-13 05:41
Isn't this discussion a duplicate of issue #691 ?

**Comment by davidcelis** [comment] 2017-04-13 16:58
It is; this can be closed as a dupe.

**Comment by mjankowski** [comment] 2017-04-18 20:24
Closing as dupe of https://github.com/tootsuite/mastodon/issues/691 and because there's some WIP on this request.

**Closed by mjankowski** 2017-04-18 20:24 UTC
Labels: enhancement, i18n, priority - low, ui
