### ISSUE TITLE
Turn off boosts from specific user in home timeline

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#648] opened 2017-02-20 19:45 UTC
Similar to Twitter's "Disable Retweets" feature. I'm following User X, but I only want to see their toots in my home timeline, not the toots they have boosted.

I should still be able to see the boosted toots by directly visiting User X's profile.

**Comment by jwisser** [comment] 2017-04-02 15:43
Definitely seconded. I'd also like a preference to disable boosts universally. I find a lot more value in only seeing what people take the time to talk about themselves. Boosts/retweets encourage a lot of noise because they're so low-effort.

**Comment by Cassolotl** [comment] 2017-04-21 13:08
@giromide says in #1026:

> Options in the account would thus be:
> Mute @SomeAccount
> Mute boosts via @SomeAccount
> Block @SomeAccount
> Report @SomeAccount

**Comment by akihikodaki** [comment] 2017-05-29 03:34
What about favourites? Are they still notified even boosts are turned off?

**Comment by Cassolotl** [comment] 2017-05-29 08:22
@akihikodaki This isn't about *notifications*, this is about the boosts themselves. We want to be able to follow someone but only see their original posts, but not see the posts they boost.

**Comment by erisdev** [comment] 2017-07-11 15:08
please yes to this, it's nice to be able to turn them off altogether but i'd love to see boosts from my friends who always boost things i like. i just wanna hide the boosts from folx who always boost fundraising and political shit

**Comment by wxcafe** [comment] 2017-09-26 02:54
Duplicate of #133

**Closed by wxcafe** 2017-09-26 02:54 UTC
Labels: enhancement, priority - high, ui
