### ISSUE TITLE
Add markdown support to mastordon

### ISSUE THREAD

**Issue by Ravenbird** [tootsuite/mastodon#1031] opened 2017-04-06 05:43 UTC
Please add markdown support to mastordon, like on github or diaspora. This has no high priority but would by a very nice feature for formating the postings.

**Comment by rhaamo** [comment] 2017-04-06 08:12
There is already #853 about text formatting too

**Comment by nhoizey** [comment] 2017-04-07 11:48
Duplicate of #761 IMHO

**Comment by zacanger** [comment] 2017-04-08 05:11
If someone can confirm this is a desired feature to get in and point me to where the relevant code lives (I do React for a living but have never even seen a Rails project before) I'd be down to look this.

**Comment by krainboltgreene** [comment] 2017-04-09 01:08
Moving to #853

**Closed by krainboltgreene** 2017-04-09 01:08 UTC
Labels: duplicate

**Comment by krainboltgreene** [comment] 2017-04-09 01:09
@zacanger I agree.
