### ISSUE TITLE
Part of the settings menu hidden

### ISSUE THREAD

**Issue by thomaskuntzz** [tootsuite/mastodon#1853] opened 2017-04-15 14:28 UTC
When the translation of a navigation item in the settings takes two lines, the "Authorized Apps" link is cut and hidden in part.

In this case, it's the 2FA link that takes two lines in the French translation instead of one in the English version:

![capture du 2017-04-15 16-17-39](https://cloud.githubusercontent.com/assets/16361470/25064286/ba34b16c-21f7-11e7-9221-a625cc91cbc9.png)

![capture du 2017-04-15 16-19-57](https://cloud.githubusercontent.com/assets/16361470/25064294/d7fc68ac-21f7-11e7-9470-94b47f7bdb0d.png)

I think the navigation links should not be stuck at the bottom of the screen as they are now, or **at least the content of the navigation menu has not to be hidden if its height exceeds the on it has in the English version.**

Also, maybe we could put less white space around the Mastodon logo at the top?

**Comment by SansPseudoFix** [comment] 2017-04-15 14:54
Regarding the right side, I have a PR ( #1633 ) waiting that fix it.

**Comment by wxcafe** [comment] 2017-04-16 21:15
Duplicate of #781, closing

**Closed by wxcafe** 2017-04-16 21:15 UTC
Labels: duplicate, enhancement, priority - low, ui
