### ISSUE TITLE
I want to display ogp card on the timeline like twitter.

### ISSUE THREAD

**Issue by mitsugu** [tootsuite/mastodon#8725] opened 2018-09-19 01:28 UTC
[Issue text goes here].
I want to display ogp card on the timeline like twitter.
This timeline is the timeline displayed as url of https: // hostname / web / *.

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment] 2018-09-19 01:35
Duplicate of #819

**Closed by ykzts** 2018-09-19 01:35 UTC
