### ISSUE TITLE
SMTP config break when no auth

### ISSUE THREAD

**Issue by rhaamo** [tootsuite/mastodon#772] opened 2017-04-03 11:41 UTC
If I set the configuration to like:
```
# E-mail configuration
SMTP_SERVER=127.0.0.1
SMTP_PORT=25
SMTP_LOGIN=
SMTP_PASSWORD=
SMTP_FROM_ADDRESS=whatever@domain.tld
```

I got in the logs: ```WARN: Net::SMTPAuthenticationError: 503 5.5.1 Error: authentication not enabled``` and emails doesn't seems to be send.

I have needed to comment the following lines in ```config/environments/production.rb```:
```
  # E-mails
  config.action_mailer.smtp_settings = {
    :port           => ENV['SMTP_PORT'],
    :address        => ENV['SMTP_SERVER'],
#    :user_name      => ENV['SMTP_LOGIN'],
#    :password       => ENV['SMTP_PASSWORD'],
    :domain         => ENV['SMTP_DOMAIN'] || config.x.local_domain,
    :authentication => :plain,
  }
```
And then it works.

Is it possible to add something like SMTP_AUTH=true/false to use, or not, the :user_name and :password fields ?

**Comment by zorun** [comment] 2017-04-03 23:55
I had the same issue, exim was complaining:

```
SMTP protocol error in "AUTH PLAIN AAA=" H=localhost (XXXX) [::1] AUTH command used when not advertised
```

Also, before that, I had another issue where exim was complaining:

```
rejected HELO from localhost [::1]: syntactically invalid argument(s): {}
```

I fixed this issue by setting `SMTP_DOMAIN` in `.env.production`. It looks like a template that does not get expanded when the variable is not set.

**Comment by rhaamo** [comment] 2017-04-04 05:40
For SMTP_DOMAIN, by default:
```    :domain         => ENV['SMTP_DOMAIN'] || config.x.local_domain,```
SMTP_DOMAIN isn't in the config file, it took it's value from ```config.x.local_domain```, defined in https://github.com/tootsuite/mastodon/blob/master/config/initializers/ostatus.rb#L8
```
host  = ENV.fetch('LOCAL_DOMAIN') { "localhost:#{port}" }
https = ENV['LOCAL_HTTPS'] == 'true'

Rails.application.configure do
  config.x.local_domain = host
```

So it would set SMTP_DOMAIN to the value of LOCAL_DOMAIN or "localhost:xxxx" if undefined.

And LOCAL_DOMAIN should be the (sub)domain of the running instance if I understand correctly.

**Comment by postblue** [comment] 2017-04-04 12:55
Another option is to use the sendmail command, with

```
config.action_mailer.delivery_method = :sendmail
```

instead of

```
config.action_mailer.delivery_method = :smtp
```

in the same file.

**Comment by vincib** [comment] 2017-04-06 10:51
Hi, I have a similar issue here : 
SMTP_SERVER=127.0.0.1
my smtp server uses STARTTLS, but the sidekiq says : 
2017-04-06T10:49:44.012Z 29644 TID-ovxozjrx4 WARN: OpenSSL::SSL::SSLError: hostname "127.0.0.1" does not match the server certificate
Is it possible to just SKIP starttls when using localhost or 127.0.0.1 as SMTP_HOST ?

**Comment by tcitworld** [comment] 2017-04-10 08:12
@Gargron Could we have the `delivery_method` inside the `.env.production` file ?

**Comment by foozmeat** [comment] 2017-04-11 16:57
This should do it
https://github.com/tootsuite/mastodon/pull/1556/commits/8d52a75c11b40c2a20410b3093848aaf801bab78

**Comment by ineffyble** [comment] 2017-04-14 06:52
Hey all (especially @rhaamo),

Just made a pull request to fix a bug that I discovered - the SMTP domain should in theory be set from the SMTP_DOMAIN environment variable, and fallback to the LOCAL_DOMAIN variable otherwise.

The problem was, the fallback wasn't working, it was referencing an internal variable that wasn't yet set. That would explain some of the issues mentioned.

**Comment by evilny0** [comment] 2017-04-19 19:41
#1597 added 'none' to SMTP authentication. However, I spent some time not understanding why it was still not working. I had to comment SMTP_LOGIN & SMTP_PASSWORD.

Just made a pull request (#2167) with a small update to the note in .env.production.sample stating that they should be commented, not left blank.

**Comment by ashfurrow** [comment] 2017-04-22 00:30
@evilny0 thanks for the pull request! Now that https://github.com/tootsuite/mastodon/pull/2167 is merged do you think this issue has been resolved?

**Comment by evilny0** [comment] 2017-04-22 11:42
Actually, I think #2167 is not necessary now that #2180 was merged. I just upgraded my instance to check, and #2180 fixed the issues I had with sending mail.

I believe this issue is now resolved.

**Comment by ashfurrow** [comment] 2017-04-22 15:03
Awesome, thanks for following up 👍

**Closed by ashfurrow** 2017-04-22 15:03 UTC
Labels: bug, question

**Comment by suoko** [comment] 2017-04-22 21:17
Has anybody an env file that works with a local posix ? No smtp auth needed

**Comment by foozmeat** [comment] 2017-04-23 15:42
This is what I use. I can probably be simplified but I don't like modifying
working configs.

SMTP_SERVER=server.com
SMTP_PORT=587
SMTP_LOGIN=
SMTP_PASSWORD=
SMTP_FROM_ADDRESS=admin@pdx.social
SMTP_AUTH_METHOD=none
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_DELIVERY_METHOD=sendmail

My production.rb is also slightly different than upstream

  config.action_mailer.smtp_settings = {
    :port                 => ENV['SMTP_PORT'],
    :address              => ENV['SMTP_SERVER'],
    :user_name            => ENV['SMTP_LOGIN'],
    :password             => ENV['SMTP_PASSWORD'],

    :domain               => ENV['SMTP_DOMAIN'] || ENV['LOCAL_DOMAIN'],
    :authentication       => ENV['SMTP_AUTH_METHOD'] == 'none' ? nil :
ENV['SMTP_AUTH_METHOD'] || :plain,

    :openssl_verify_mode  => ENV['SMTP_OPENSSL_VERIFY_MODE'],
    :enable_starttls_auto => ENV['SMTP_ENABLE_STARTTLS_AUTO'] || true,
  }



James

**Comment by suoko** [comment] 2017-04-24 07:07
Hi, thanks for sharing.
Thanks to a guy on matrix i found out that the problem is actually the docker container which is not communicating with the host.
I have mastodon in the docker and i installed both postfix and sendmail in the host.
While in the host if i try to telnet localhost port 25 it's ok, but if i try to telnet the host ip (172.18.0.1) assigned by docker i see no smtp.
As far as i understood i should use that ip in my docker conf (the docker container ip is 172.18.0.4)

**Comment by rev138** [comment] 2017-04-24 11:33
@suoko One possible solution is to create a new subdirectory 'postfix', then add a Dockerfile to it:
`FROM alpine:latest

EXPOSE 25 587

RUN apk -U upgrade && apk add \
  postfix \
 && rm -rf /tmp/* /var/cache/apk/*

CMD syslogd && /usr/sbin/postfix start && tail -f /var/log/*`

Then you can add a new service to docker-compose.yml:
`  postfix:
    restart: always
    build: ./postfix
`
Then set your SMTP host to 'postfix'.

**Comment by suoko** [comment] 2017-04-24 18:22
Thats a solution but i dont understand why the container is not able to access​ the host. In postfix i set up the 172.18.0.0/24 subnet in mynetworks option

**Comment by suoko** [comment] 2017-04-25 21:21
With option like:
SMTP_LOGIN=none
SMTP_PASSWORD= 
SMTP_FROM_ADDRESS=notifications@mastodon.net
#SMTP_DOMAIN= # defaults to LOCAL_DOMAIN
SMTP_DELIVERY_METHOD=smtp
SMTP_AUTH_METHOD=none
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS_AUTO=false

I got this error
2017-04-25T21:15:21.237Z 1 TID-gqo8xeiwo WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::DeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::DeliveryJob","job_id":"00d69650-b5f7-43bf-87c6-d8ef02315117","queue_name":"mailers","priority":null,"arguments":["UserMailer","confirmation_instructions","deliver_now",{"_aj_globalid":"gid://mastodon/User/3"},"rK_FLnaP2UJuXkdBAiTo",{"_aj_symbol_keys":[]}],"locale":"it"}],"retry":true,"jid":"9f30e8aaa8c53c9f9079b6a1","created_at":1493154777.4159162,"enqueued_at":1493154921.2221618,"error_message":"503 5.5.1 Error: authentication not enabled\n","error_class":"Net::SMTPAuthenticationError","failed_at":1493154807.4308774,"retry_count":1,"retried_at":1493154921.237089},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::DeliveryJob\",\"queue\":\"mailers\",\"args\":[{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"00d69650-b5f7-43bf-87c6-d8ef02315117\",\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"UserMailer\",\"confirmation_instructions\",\"deliver_now\",{\"_aj_globalid\":\"gid://mastodon/User/3\"},\"rK_FLnaP2UJuXkdBAiTo\",{\"_aj_symbol_keys\":[]}],\"locale\":\"it\"}],\"retry\":true,\"jid\":\"9f30e8aaa8c53c9f9079b6a1\",\"created_at\":1493154777.4159162,\"enqueued_at\":1493154921.2221618,\"error_message\":\"execution expired\",\"error_class\":\"Net::OpenTimeout\",\"failed_at\":1493154807.4308774,\"retry_count\":0}"}
sidekiq_1    | 2017-04-25T21:15:21.237Z 1 TID-gqo8xeiwo WARN: Net::SMTPAuthenticationError: 503 5.5.1 Error: authentication not enabled
sidekiq_1    | 
sidekiq_1    | 2017-04-25T21:15:21.237Z 1 TID-gqo8xeiwo WARN: /usr/local/lib/ruby/2.4.0/net/smtp.rb:981:in `check_auth_response'

I'm trying various configuration but no chance 
I'm sure the smtp works from a docker container, I tested with telnet while into one of them

**Comment by ashfurrow** [comment] 2017-04-26 07:38
Do you have an `SMTP_SERVER` set as well?

**Comment by suoko** [comment] 2017-04-26 18:15
Sure
Server is at 172.18.0.1 (docker gateway) and port is 2525 (i changed the standard 25 due to conflicts with sidekick).
In postfix i set 172.18.0.0/24 in mynetworks (networks safe for postix) and i had to set 172.18.0.1 in my inet_interfaces too

**Comment by suoko** [comment] 2017-04-26 18:22
If you want to reproduce it all, like the telnet test, i did like this:
Enter the db docker instance (docker exec -it instanceID bash), that's the only one allowing a bash session
From there do 'telnet 172.18.0.1 2525' and send an email

**Comment by sjlongland** [comment] 2025-08-31 09:51
Hate to bump an old thread… but it seems this problem has reared its ugly head again since 4.4.2 was released.

```
2025-08-31T19:46:17.800932+10:00 mastodon bundle[88972]: 2025-08-31T09:46:17.777Z pid=88972 tid=147g WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"mailers","wrapped":"ActionMailer::MailDeliveryJob","args":[{"job_class":"ActionMailer::MailDeliveryJob","job_id":"c906a8f0-3b6f-49e8-b61c-d92ff33bb37c","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["NotificationMailer","mention","deliver_now",{"params":{"recipient":{"_aj_globalid":"gid://mastodon/Account/109573513395599946"},"notification":{"_aj_globalid":"gid://mastodon/Notification/26542"},"_aj_symbol_keys":["recipient","notification"]},"args":[],"_aj_ruby2_keywords":["params","args"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2025-08-31T09:44:15.941148403Z","scheduled_at":"2025-08-31T09:46:15.939338686Z"}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"d7f0fb1b386881feb3d2874e","created_at":1756633455.9415061,"enqueued_at":1756633576.950485}}
2025-08-31T19:46:17.801335+10:00 mastodon bundle[88972]: 2025-08-31T09:46:17.777Z pid=88972 tid=147g WARN: Net::SMTPAuthenticationError: 503 5.5.1 Error: authentication not enabled
```

The mail server here requires _no_ authentication for local clients.  I even went as far as installing Postfix on the Mastodon server here (standard Debian "Satellite" configuration, pointed at my local mail server) and get the same message.

Relevant config:

```
SMTP_SERVER=localhost
SMTP_DOMAIN=example.org
SMTP_PORT=25
SMTP_LOGIN=
SMTP_PASSWORD=
SMTP_AUTH_METHOD=none
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS=false
SMTP_FROM_ADDRESS='Mastodon <mastodon@example.org>'
#SMTP_DELIVERY_METHOD=sendmail
```

Mail server logs:
```
2025-08-31T19:46:17.648559+10:00 mastodon postfix/smtpd[93039]: connect from localhost[::1]
2025-08-31T19:46:17.773470+10:00 mastodon postfix/smtpd[93039]: lost connection after AUTH from localhost[::1]
2025-08-31T19:46:17.773699+10:00 mastodon postfix/smtpd[93039]: disconnect from localhost[::1] ehlo=2 starttls=1 auth=0/1 commands=3/4
2025-08-31T19:46:42.449274+10:00 mastodon postfix/smtpd[93039]: connect from localhost[::1]
2025-08-31T19:46:42.580129+10:00 mastodon postfix/smtpd[93039]: lost connection after AUTH from localhost[::1]
2025-08-31T19:46:42.580555+10:00 mastodon postfix/smtpd[93039]: disconnect from localhost[::1] ehlo=2 starttls=1 auth=0/1 commands=3/4
2025-08-31T19:47:09.139925+10:00 mastodon postfix/smtpd[93039]: connect from localhost[::1]
2025-08-31T19:47:09.265654+10:00 mastodon postfix/smtpd[93039]: lost connection after AUTH from localhost[::1]
2025-08-31T19:47:09.265899+10:00 mastodon postfix/smtpd[93039]: disconnect from localhost[::1] ehlo=2 starttls=1 auth=0/1 commands=3/4
2025-08-31T19:47:57.432589+10:00 mastodon postfix/smtpd[93039]: connect from localhost[::1]
2025-08-31T19:47:57.541025+10:00 mastodon postfix/smtpd[93039]: lost connection after AUTH from localhost[::1]
2025-08-31T19:47:57.541616+10:00 mastodon postfix/smtpd[93039]: disconnect from localhost[::1] ehlo=2 starttls=1 auth=0/1 commands=3/4
2025-08-31T19:49:53.388532+10:00 mastodon postfix/smtpd[93315]: connect from localhost[::1]
2025-08-31T19:49:53.496919+10:00 mastodon postfix/smtpd[93315]: lost connection after AUTH from localhost[::1]
2025-08-31T19:49:53.497162+10:00 mastodon postfix/smtpd[93315]: disconnect from localhost[::1] ehlo=2 starttls=1 auth=0/1 commands=3/4
```

**Comment by sjlongland** [comment] 2025-08-31 10:05
Looks like commenting out `SMTP_USER` and `SMTP_PASSWORD` forces it to _not_ try authenticating, something prior versions of Mastodon used `SMTP_AUTH_METHOD=none` to enforce.
