### ISSUE TITLE
"directory" listing all known hashtags regardless of opt-in status

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#9869] opened 2019-01-20 09:19 UTC
<img width="316" alt="image" src="https://user-images.githubusercontent.com/17537000/51437262-e8ccad00-1cef-11e9-8ad4-960ba9ade23a.png">

### Expected behaviour
* directory/expore should be empty as nobody as opted-in yet.

### Actual behaviour
* directory/explore includes all hashtags even for users who have not enabled/disabled. 

### Steps to reproduce the problem
https://aus.social/explore

### Specifications
v2.7.0-rc3

**Comment by Gargron** [comment] 2019-01-20 11:06
Duplicate of #9858

**Closed by Gargron** 2019-01-20 11:06 UTC
