### ISSUE TITLE
Inproper calculation of user description's lenght

### ISSUE THREAD

**Issue by redsPL** [tootsuite/mastodon#7485] opened 2018-05-14 17:52 UTC
It appears that frontend calculates newlines as 1 character, and backend as 2. This makes it pretty difficult for me to use the space to its full potential :3

![before](http://sakamoto.pl/tmp/bugreport/profile_desc/before.png)
![after](http://sakamoto.pl/tmp/bugreport/profile_desc/after.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by charlag** [comment] 2018-05-14 19:25
I've tried to edit my description recently on 2.3.3 and I had troubles editing things because of some error in calculation on either frontend or backend.

**Comment by renatolond** [comment] 2018-05-17 09:07
Maybe this is a duplicate of #4419 ?

**Comment by charlag** [comment] 2018-05-17 16:05
Maybe, but you need to test to make sure

**Comment by redsPL** [comment] 2018-05-18 21:56
@renatolond Probably, but this issue needs more spotlight. It's been like this for almost a year, or more!

**Comment by BillyWM** [comment] 2018-08-18 04:06
This sure sounds like an `\r\n` vs `\n` thing to me.

I'm not a RoR guy but I wonder if there isn't some funky translation in transmission. (I have vague memories of something like that in, I dunno, Perl probably, a million years ago)

**Closed** 2018-08-18 08:42 UTC
