### ISSUE TITLE
update gun emoji with the different (water) pistol emoji

### ISSUE THREAD

**Issue by novadeviator** [tootsuite/mastodon#7446] opened 2018-05-11 01:26 UTC
So, everyone seem to be onto changing the pistol/gun emoji into a water pistol. It would be nice if that would also happen on Mastodon.

please see https://blog.emojipedia.org/all-major-vendors-commit-to-gun-redesign/
and
https://twitter.com/Emojipedia/status/990021362721832960?ref_src=twsrc%5Etfw

* * * *
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Laurelai** [comment] 2018-05-11 01:44
I think this is silly.

**Comment by nightpool** [comment] 2018-05-11 02:40
We don't provide our own Emoji, we use Twemoji. So when twitter updates their emoji, ours will update also.

**Comment by UberActivist** [comment] 2018-05-11 06:05
![image](https://user-images.githubusercontent.com/11623577/39909203-650b30d2-54b7-11e8-9dbc-4473148ebfd2.png)
latest twitter emoji changed it already @nightpool

**Comment by marrus-sh** [comment] 2018-06-06 04:02
this is a duplicate of #5579 at this point i think?

**Comment by vpzomtrrfrt** [comment] 2018-07-27 19:21
#5579 is closed, I think this is done?

**Closed** 2018-07-27 23:21 UTC
