### ISSUE TITLE
Implement ActivitiyPub Update method (e.g. for editing of posts)

### ISSUE THREAD

**Issue by steckerhalter** [tootsuite/mastodon#7209] opened 2018-04-21 05:14 UTC
Since the ActivityPub standard defines the `Update` [activity](https://www.w3.org/TR/activitypub/#update-activity-inbox), could Mastodon implement it too? This would allow users to edit posts which is (I suppose) a much desired option.

**Comment by nightpool** [comment] 2018-04-21 05:40
this is a duplicate of #256?

**Comment by nightpool** [comment] 2018-04-21 20:52
Closed in favor of the discussion on #256 

(The implementation details, like ActivityPub, aside, this is a request for a new feature to be added to Mastodon. The problems with allowing users to edit posts are well-dissected by that issue already)

**Closed by nightpool** 2018-04-21 20:52 UTC

**Comment by trwnh** [comment] 2018-09-05 19:10
Outside of editing toots: I'd like to bring up how this affects other, non-Mastodon software. I see #256 as specifically asking for a Mastodon feature, while this issue #7209 is simply for accepting the `Update` activity.

The reason this is important is because remote content may change without any of the expectations that Mastodon has for immutability of content.

Here's a concrete example: write.as is a blogging platform that lets you publish your posts over ActivityPub as well as RSS/etc. Mastodon displays incoming `Article` objects as a title and a URL link. But in a blogging environment, you can change the title of a post, and more importantly, **you can change the URL slug**. This means that once an `Article` post is pulled into Mastodon, it can very easily become orphaned once you change the slug in write.as. write.as is either currently in the process of implementing, or has already implemented sending an `Update` activity to change the URL when you change the slug, but because Mastodon ignores this activity, **the cached copy in Mastodon will remain forever broken**.
