### ISSUE TITLE
[Feature Request] Stack Common Notifications

### ISSUE THREAD

**Issue by shawneric** [tootsuite/mastodon#9182] opened 2018-10-31 17:57 UTC
Please stack common notifications instead of having each notification being mentioned. This floods my notification bar. If five people favorite a status, I'd like it to say "John and four others favorited your status", and if I want to see more, I can click it and see who else favorited it. But other than that, I'd really like to clean up this notification screen some please. :)

**Comment by trwnh** [comment] 2018-11-01 02:37
Duplicate of #7698

**Comment by Gargron** [comment] 2019-08-05 09:10
Duplicate of #1483

**Closed by Gargron** 2019-08-05 09:10 UTC
Labels: suggestion
