### ISSUE TITLE
"Toot" is a stupid name. Just call it post already

### ISSUE THREAD

**Issue by 153** [tootsuite/mastodon#8739] opened 2018-09-20 05:10 UTC
"Toot" is a stupid name. Just call it post already

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment] 2018-09-20 06:52
duplicate of #7667

**Closed by ykzts** 2018-09-20 06:52 UTC

**Comment by 153** [comment] 2018-09-20 08:47
Excuse me? No, it's not.

**Comment by 153** [comment] 2018-09-20 08:48
Unclose this, NOW.
