### ISSUE TITLE
Muting is too awful

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#14211] opened 2020-07-05 16:37 UTC
### Pitch

Please get rid of the whole "muting hides mentions" thing.

### Motivation

I wanna hide posts from image bots without hiding posts mentioning said bots. And still be able to interact with them/like their posts/etc every now and then. There is currently no way.

**Comment by ThibG** [comment] 2020-07-05 17:20
I believe this is a duplicate of #14028, please let us know if not.

**Closed by ThibG** 2020-07-05 17:20 UTC
