### ISSUE TITLE
css bug in static profile page

### ISSUE THREAD

**Issue by HLT** [tootsuite/mastodon#3856] opened 2017-06-19 14:48 UTC
the white area in the "posts" section has rounded edges on top. the sections "follows" and "followers" only have rounded edges at the bottom.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment] 2017-06-19 16:16
@Gargron Is this a bug? or intended behavior?

**Comment by Gargron** [comment] 2017-07-14 01:23
@unarist A bug :weary:

**Comment by nightpool** [comment] 2017-07-14 01:34
a similar class of bugs:

![image](https://user-images.githubusercontent.com/233815/28194566-0efbd480-6813-11e7-98a4-aaa31ebafeb7.png)

**Comment by ykzts** [comment] 2017-08-22 14:04
@HLT Is this fixed by #4341 ?

**Closed** 2018-04-08 19:14 UTC
Labels: bug, fit for beginners, priority - low, ui
