### ISSUE TITLE
Middle-click-to-scroll expands toot in addition to starting scroll

### ISSUE THREAD

**Issue by creideiki** [tootsuite/mastodon#10798] opened 2019-05-21 05:30 UTC
### Expected behaviour

I use Firefox autoscroll (middle click then move mouse) almost exclusively, especially on laptops without scroll wheels. This used to work well, with a big open space below the account avatar on each post where middle-clicking was safe.

### Actual behaviour

Since v2.8.3, middle-clicking below the avatar expands the toot in addition to starting scrolling.

### Steps to reproduce the problem

1. Enable Preferences -> General -> Browsing -> Use autoscrolling.
2. Middle-click the open space below the avatar to start scrolling.
3. Note that the toot is expanded even though it wasn't left-clicked.

### Specifications

The web interface of v2.8.3 on mastodon.social, using Firefox 66.0.5 on Gentoo Linux.

### Related

It seems the code was added in #10766, to solve #10733.

The same problem has appeared before, in #528, solved in  #536.

**Comment by Dar13** [comment] 2019-05-24 18:36
I almost thought I couldn't reproduce this issue but I can. If you start dragging the mouse after pressing down the middle button it will not expand the status. If you click the mouse fully before dragging then the status will expand.

I'll take a look at this in the upcoming couple of days (since it was my PR that broke stuff...), hopefully it'll be simple to fix.

**Comment by Dar13** [comment] 2019-06-04 00:11
Seems @Gargron has made mastodon.social run the latest on the master branch, does this issue still occur for you @creideiki?

**Comment by creideiki** [comment] 2019-06-04 14:38
After reloading the web page, I no longer see this issue.

**Comment by Dar13** [comment] 2019-06-04 16:50
Seems like we can close it then @creideiki @Gargron

**Comment by ykzts** [comment] 2019-10-26 06:45
Resolved with #10837

**Closed by ykzts** 2019-10-26 06:45 UTC
Labels: bug, wontfix
