### ISSUE TITLE
[Feature request] Allowing the user to disable timeline streaming

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#9031] opened 2018-10-20 22:16 UTC
There should be an option in the settings menu that lets people disable timeline streaming. It would be extremely helpful for people who follow a bunch of other people and it gets extremely annoying when you interact with the wrong post just because someone just sent another one.

**Comment by realityfabric** [comment] 2019-06-14 02:58
Is this a duplicate of #7913? They're both tied to the same PR (#9984).

**Comment by koyuawsmbrtn** [comment] 2019-06-14 07:35
@realityfabric #7913 would be rather the duplicate of this issue. There was no further work on PR #9984 so I would drag that attention there. cc @Gargron

**Closed** 2019-07-16 04:30 UTC
Labels: suggestion
