### ISSUE TITLE
Mastodon Streaming Failing

### ISSUE THREAD

**Issue by 4nanook** [tootsuite/mastodon#14894] opened 2020-09-28 12:55 UTC
Mastodon Streaming Failed.  I don't know much about ruby and java and perl so don't know how to fix.
### Expected behaviour

Expect it to just work.
### Actual behaviour

node streaming
/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:18
        throw err;
        ^

Error: Cannot find module '../dist/bindings/cws_linux_83'
Require stack:
- /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js
- /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/server.js
- /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/client.js
- /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/index.js
- /misc/www/mastodon/live/streaming/index.js check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:14:16
    at Object.<anonymous> (/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js',
    '/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/server.js',
    '/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/client.js',
    '/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/index.js',
    '/misc/www/mastodon/live/streaming/index.js'
  ]
}

### Steps to reproduce the problem
Install the latest Mastodon from github on to a Ubuntu 20.04 platform.

### Specifications

I don't know enough about github to know how to find this out.  I just went to gethub mastodon and selected code,
then did git clone and the URL I obtained.

Also using Ubuntu 20.04 Firefox 80.0.1

**Comment by matt-y** [comment] 2020-09-28 17:20
Looks like a duplicate of #14866

**Comment by ThibG** [comment] 2020-09-29 12:34
Duplicate of #14866 indeed.

**Closed by ThibG** 2020-09-29 12:34 UTC
