### ISSUE TITLE
Add ability to hide all images by default

### ISSUE THREAD

**Issue by mkosler** [tootsuite/mastodon#3882] opened 2017-06-21 04:27 UTC
Add the ability to mark as NSFW all images/media by default in the preferences.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by unarist** [comment] 2017-06-21 05:05
looks duplicate of #2828

**Comment by nightpool** [comment] 2017-06-22 11:24
thanks for taking the time to send us this suggestion! currently we're tracking this proposed change as issue #2828. You can read more discussion about the feature there.

I'm going to close this issue, but only to keep conversation centered in one location—feel free to add your vote or comments there!

**Closed by nightpool** 2017-06-22 11:24 UTC
