### ISSUE TITLE
Notification for a favorite shows wrong toot

### ISSUE THREAD

**Issue by raingloom** [tootsuite/mastodon#7481] opened 2018-05-14 16:07 UTC
I see this on cybre.space and that is obviously not my toot:

![asd](https://user-images.githubusercontent.com/8085052/40009058-3e6ab91a-57a1-11e8-96b2-cee48da8896e.png)

Sorry, I have no idea how to reproduce this and this is the first time it has happenned.

I tried reloading the page a few times, but it didn't help.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment] 2018-05-14 17:49
can you ping me about this on matrix/Mastodon in 5ish hours so I can look
into it?

**Comment by ThibG** [comment] 2018-05-14 19:14
My guess is that it's not a favorite on this toot, but an orphaned favorite due to some race condition.
That toot is in your notifications because you got mentioned, while someone favorited/unfavorited one of your toots in such a way that there is a `Notification` record referencing an nonexistent activity. Maybe a duplicate of #2865.

**Comment by Gargron** [comment] 2018-10-23 00:46
Duplicate of #2865

**Closed by Gargron** 2018-10-23 00:46 UTC
Labels: bug
