### ISSUE TITLE
Private Account but follow request wasn't appearing.

### ISSUE THREAD

**Issue by MatthewAllan93** [tootsuite/mastodon#644] opened 2017-02-17 20:33 UTC
Hello,
I made my account private on Mastodon https://mastodon.social/ but one of my friends on IRC @shymega tried following me and it didn't appear in the follow request section of Mastodon. But as soon as I made my account public and asked him to refollow me. It appeared then, I am not sure if this a bug or not. But I thought it was best letting you know :). I hope this feedback helps :).

**Comment by zorun** [comment] 2017-04-12 18:04
I encountered the same issue!  I made my account private, and a friend on another instance tried to follow me, but I didn't receive any notification.

Even worse, when I switched my account back to public, the friend still couldn't follow me (because a "follow request" was already pending according to his instance).

**Comment by wxcafe** [comment] 2017-09-26 02:51
closing this preemptively since the report is old and who knows if this still happens. please open a new issue if you still encounter this bug.

**Closed by wxcafe** 2017-09-26 02:51 UTC
Labels: bug

**Comment by shymega** [comment] 2017-09-26 14:58
Hi,

wxcafé <notifications@github.com> writes:

> closing this preemptively since the report is old and who knows if
> this still happens. please open a new issue if you still encounter
> this bug.

With all due respect, I must protest the closure of this bug.

Yes, the bug report *is* old. But this does not - in my humble opinion
- justify closing the bug report.

My personal manta is: if a bug isn't resolved, then keep it open. If
it *is* resolved or invalid, then closing is acceptable.

But we just haven't been able to test it recently, that's all. And
that does not justify a closure of a bug report, IMHO.

I will ping the author of this bug report tonight on IRC, and I'll do
some testing with them on the bug report ASAP.

However, I feel it would be best to reopen the bug report. I urge you
to do so, thank you.

Essentially, innocent until proven guilty...

--
Best regards,
Dom Rodriguez (shymega / dzr).

**Comment by shymega** [comment] 2017-09-26 17:46
Eh. I just don't think closing an issue is the best solution.

Regards.

**Comment by nightpool** [comment] 2017-09-26 18:16
>My personal manta is: if a bug isn't resolved, then keep it open. If
it *is* resolved or invalid, then closing is acceptable.

This is a fine strategy for mature and stable code-bases. But so much about mastodon has changed architecturally since February that even if this *is* an issue it's probably not even the same underlying problem and has been fixed and broken since then.

Also note that the bug is impossible to replicate with the information given, so stricter projects would just close it right away. We basically use the github issue tracker as a hybrid support/issue tracker, and if we can't reproduce an issue after *eight months*, it's hard to say that we're ever going to get enough info to reproduce it.

**Comment by shymega** [comment] 2017-09-26 18:56
Hi,

nightpool <notifications@github.com> writes:

>>My personal manta is: if a bug isn't resolved, then keep it open. If
> > it *is* resolved or invalid, then closing is acceptable.
>
> This is a fine strategy for mature and stable code-bases. But so
> much about mastodon has changed architecturally since February that
> even if this *is* an issue it's probably not even the same
> underlying problem and has been fixed and broken since then.
>
> Also note that the bug is impossible to replicate with the information
> given, so stricter projects would just close it right away. We
> basically use the github issue tracker as a hybrid support/issue
> tracker, and if we can't reproduce an issue after *eight months*, it's
> hard to say that we're ever going to get enough info to reproduce it.

Fair enough. It was interesting to hear this project's point of
view. My apologies for moaning about it :)

--
Best regards,
Dom Rodriguez (shymega / dzr).
