### ISSUE TITLE
Previous toots not loading

### ISSUE THREAD

**Issue by valentinp72** [tootsuite/mastodon#1547] opened 2017-04-11 15:20 UTC
Hi!

I've created my instance 2 days ago, and there is something I'm having trouble with...

All the toots, followers and other informations of people on other instances that were "updated" before my instance started doesn't show up.
For example, if I go on Eugen's page from my instance, it only display the toots Eugen made after the creation of my instance (even the number of toots is wrong). It's the same thing for followers...

![Example](http://img4.hostingpics.net/pics/145460Capturedcran20170411153113.png)

Is it normal, or a problem from my instance? 
If it's normal, it could be great to add this feature!

Thanks in advance,
Valentin
* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-11 15:28
This is normal, and it's just how federation works. I'm closing this since it's not a bug nor a feature that is likely to be added in the near future (or at all)

**Closed by wxcafe** 2017-04-11 15:28 UTC

**Comment by valentinp72** [comment] 2017-04-11 16:23
Why won't it be added?
Because it's quite disturbing when you go for the first time on an account you've never been, to see not any toots and followers...
From my point of view, this might dissuade people to use all the decentralization chance that offers Mastodon, because if they want to see everything, they would need to be on the same instance (like for mastodon.social)...

If it's not possible, what about a link to the original instance to be able to see everything? Something like this for example:

![idea](https://cloud.githubusercontent.com/assets/2760679/24919242/4d42cf10-1ee3-11e7-9d23-49dee565f819.png)

**Comment by wxcafe** [comment] 2017-04-11 16:31
You don't need to be on the same instance, your instance simply needs to federate that user with the other. Basically if anyone on your instance follows that person you'll see all their toots since they were first followed by anyone on your instance. To do what you're proposing (getting all toots of the user since they started using mastodon) would mean that when a user starts following a remote user, the server would have to get all that remote user's toots and boosts and the toots from these boosts (which is basically non-feasible).

I think the fact that you get all the toots since anyone on your instance followed the remote user will suffice most of the time, and the user's profile picture is already a link to their profile page on their home instance (and there's already an issue about making the display name / @ be a link too)

**Comment by valentinp72** [comment] 2017-04-11 16:44
Okay, I see what you mean!
The problem of that, is it only work on big instances, and not little or single-user instances...
Never mind!
And thanks for the links on the profile picture, I didn't know.

**Comment by kek-coin** [comment] 2018-08-11 00:00
Would love to see this issue revisited - how exactly is this non-feasible?

**Comment by trwnh** [comment] 2018-08-11 06:04
Duplicate of #34
