### ISSUE TITLE
Page blocking error overlay cannot be dismissed 

### ISSUE THREAD

**Issue by rubahness** [tootsuite/mastodon#12937] opened 2020-01-24 03:37 UTC
[audiotoot-stacktrace.txt](https://github.com/tootsuite/mastodon/files/4106727/audiotoot-stacktrace.txt)
<img width="651" alt="Screen Shot 2020-01-23 at 9 36 03 PM" src="https://user-images.githubusercontent.com/10877955/73042980-dc11f600-3e28-11ea-8ea6-a3ddd67d7a3a.png">

Arguably there shouldn't be an error, but I'm willing to accept repercussions for being on an old Firefox. 

Browser: FF 52.4.1
Affected Toots: seems to be any arbitrary audio post, as long as they are viewed in the mastodon web client, rather than the public view.  E.g. https://weirder.earth/web/statuses/103534986250372468 will show that error but not https://weirder.earth/@rubah/103534986250372468.  
Mastodon version: 3.0.1

Expected behavior: errors can be dismissed or they do not persist after navigating backwards.

Actual behavior: error is displayed until navigating back to a working page and then refreshing (losing statuses loaded in the home view)

**Comment by Gargron** [comment] 2020-01-24 10:19
It's not an overlay, the page crashed, it can't be fixed without a refresh.

**Comment by rubahness** [comment] 2020-01-24 14:42
> It's not an overlay, the page crashed, it can't be fixed without a refresh.

Oh, wow. Well, in this case, refreshing will always cause the page to crash again. Maybe a wording tweak or a back link that will also trigger a refresh?

**Comment by PeterKW** [comment] 2020-01-27 16:32
I am having the same error on multiple browsers. Including old Edge & Chromium based browsers

**Comment by ThibG** [comment] 2020-02-18 14:31
Duplicate of #13015 (choosing that one even though it's newer because it's more detailed, but the cause is the same)

**Closed by ThibG** 2020-02-18 14:31 UTC
