### ISSUE TITLE
Hide all media of some account

### ISSUE THREAD

**Issue by Dryusdan** [tootsuite/mastodon#7179] opened 2018-04-18 10:09 UTC
Hello
Actually, some account post sensitive image without "sensitive content mode". I know it's possible to mark all image of an instance NSFW or tag toot by toot as NSFW but it's not possible to mark all media NSFW for a specific account.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JohnD28** [comment] 2018-04-30 17:43
We also need the possibility to mark all media NSFW for a specific instance.

**Comment by mal0ki** [comment] 2018-05-03 09:46
Something like this?

As Admin Feature:
- [ ] Flag Media of individual posts
- [ ] Flag Media for the entire account (past and future) 
- [ ] Flag all incoming media from another instance 

As a user feature: 
- [ ] Allow individual users to auto hide all media from other specific users 
These are a parenthesis (
 - [ ] Allow server side word muting (this is currently on the road map)
- [ ] Allow CW applied to any post with certain keywords (via web UI) )

**Comment by Dryusdan** [comment] 2018-05-03 10:16
@mal0ki That's exactly what I was thinking. ! :D

**Comment by dracos** [comment] 2018-08-24 19:33
An additional option that might be nice would be to prevent a user on an instance from uploading media at all.

**Comment by Dryusdan** [comment] 2018-08-24 20:41
A moderation option ? Not for all user right ?

**Comment by Gargron** [comment] 2018-08-24 20:55
Gonna close this in favour of the linked older issue which this is a duplicate of.

**Closed by Gargron** 2018-08-24 20:55 UTC
Labels: admin support, priority - medium
