### ISSUE TITLE
customization of columns in webinterface

### ISSUE THREAD

**Issue by byteturtle** [tootsuite/mastodon#827] opened 2017-04-04 11:51 UTC
would be nice if you could move the columns around, and tune them how you like.
e.g. filter for specific words, open profiles/toots in same/other column and so on.
kinda like tweetdeck does it.

**Comment by lattera** [comment] 2017-04-04 14:06
+1 from me. Also add/remove columns.

**Comment by fhemberger** [comment] 2017-04-07 19:05
Duplicate of #351

**Comment by wxcafe** [comment] 2017-04-10 19:05
Closing this since it's a duplicate

**Closed by wxcafe** 2017-04-10 19:05 UTC
Labels: enhancement, ui
