### ISSUE TITLE
Clearing notifications doesn't work anymore

### ISSUE THREAD

**Issue by kballard** [tootsuite/mastodon#1294] opened 2017-04-08 22:01 UTC
Clearing notifications works fine on an instance running slightly older code (where it still has the trash can icon). But on an instance I just set up running current master (9acdb166e8871632f592bfcd2386dfc288d81a07), where the icon is now an eraser, clicking the eraser does absolutely nothing.

**Comment by wxcafe** [comment] 2017-04-08 22:14
Have you tried reverting to 49043f6? If it works then the bug was introduced in 157f0a2, which seems likely since that commit changed how clearing notifications works

**Comment by kballard** [comment] 2017-04-08 22:20
Reverting to 49043f644d668e6c525d299e4193033236d22c35 fixes the behavior.

**Comment by wxcafe** [comment] 2017-04-08 22:45
Okay so pinging @alimony I guess?

**Comment by wxcafe** [comment] 2017-04-08 23:16
This is a duplicate of #1259 but since we started the discussion here...

**Comment by Fastidious** [comment] 2017-04-08 23:18
@kballard how reverting to that commit will fix anything? It is only a change to `List-of-Mastodon-instances.md`.

**Comment by kballard** [comment] 2017-04-08 23:20
@Fastidious Because reverting to that commit also throws away b89f007862bb06bbf892c4f37dbc31ed83138b53, 9acdb166e8871632f592bfcd2386dfc288d81a07, 470eb0042ea99e0632ccc62a0b7c01e910f70491, fc146a19cc2fe37a4701caa5b0911e859d46255d, 941a593ea8a9d5e863117db574242fde3aab96db, 982fef811e98916f28d1b9dea9efa7817405f971, 41f8fde83e62bd20d3c0a2bb6cff1ed8b3279a4a, and 157f0a2aa74737fbe1654984cbe6879b584f2721.

**Comment by wxcafe** [comment] 2017-04-08 23:21
The next commit is the one that changes the way the way the notification
clearing icon works. Reverting to that one undoes the changes in that
next commit and allows us to test how the clearing icon worked before
that change.

-- 

Clément 'wxcafé' Hertling

**Comment by alimony** [comment] 2017-04-09 10:02
Sorry about that, seems to have been fixed in b1881a3d481bccfba984d42380ab2f3780bd0845

**Closed** 2017-04-09 10:30 UTC
Labels: bug
