### ISSUE TITLE
Seeing a toot in Home from not followed user 

### ISSUE THREAD

**Issue by Geobert** [tootsuite/mastodon#1643] opened 2017-04-12 19:41 UTC
And it was not boosted either. (1.1.1)

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ashyon** [comment] 2017-04-12 22:44
Possible explanation: It was boosted and then unboosted, leaving the toot in your timeline without a boost message.

**Comment by symac** [comment] 2017-04-13 07:53
Possible duplicate of #1601

**Closed** 2017-04-13 12:12 UTC
Labels: duplicate
