### ISSUE TITLE
Direct messages sent from your account redirect to the wrong user

### ISSUE THREAD

**Issue by redsPL** [tootsuite/mastodon#10526] opened 2019-04-09 13:47 UTC
### Expected behaviour

After clicking upon the nick like pic related, I should've been redirected to user's profile

### Actual behaviour

I've got redirected to my own profile.

### Steps to reproduce the problem

1. Sent a DM to anybody
2. Open the DM column
3. Click on the nick of the person DM was directed to
4. Redirect to your own profile

![pic 1](http://sakamoto.pl/tmp/09-04-2019_15-43-42.png)
![pic 2](http://sakamoto.pl/tmp/09-04-2019_15-44-08.png)

### Specifications

Found on niu.moe, v2.8.0rc1.

**Comment by Gargron** [comment] 2019-08-05 09:04
Duplicate of #11414

**Closed by Gargron** 2019-08-05 09:04 UTC
Labels: bug
