### ISSUE TITLE
Add Option to Pause Timeline

### ISSUE THREAD

**Issue by robcee** [tootsuite/mastodon#1113] opened 2017-04-06 22:48 UTC
Add a pause button to the local or federated timelines to prevent scrolling. Unpausing resumes the feed.

* * * *

- [√] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment] 2017-04-21 05:22
See #1711

**Comment by Gargron** [comment] 2017-06-29 18:25
Duplicate of #240

**Closed by Gargron** 2017-06-29 18:25 UTC
Labels: enhancement, priority - low, ui
