### ISSUE TITLE
remote follow fails with "NoMethodError (undefined method `n=' for #<OpenSSL::PKey::RSA:0x007fe10ab2d4a8>"

### ISSUE THREAD

**Issue by matyapiro31** [tootsuite/mastodon#4741] opened 2017-08-30 02:15 UTC
log is here:
```
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] method=POST path=/api/salmon/2 format=html controller=Api::SalmonController action=update status=500 error='NoMethodError: undefined method `n=' for #<OpenSSL::PKey::RSA:0x007f6872370cd0>
Aug 30 01:59:16 instance-1 bundle[1262]: Did you mean?  n' duration=2471.24 view=0.00 db=1.40
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25]
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] NoMethodError (undefined method `n=' for #<OpenSSL::PKey::RSA:0x007f6872370cd0>
Aug 30 01:59:16 instance-1 bundle[1262]: Did you mean?  n):
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25]
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] app/services/resolve_remote_account_service.rb:119:in `public_key'
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] app/services/resolve_remote_account_service.rb:87:in `update_account'
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] app/services/resolve_remote_account_service.rb:46:in `block in call'
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] app/services/resolve_remote_account_service.rb:41:in `call'
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] app/services/concerns/author_extractor.rb:21:in `author_from_xml'
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] app/services/verify_salmon_service.rb:12:in `call'
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] app/controllers/api/salmon_controller.rb:27:in `verify_payload?'
Aug 30 01:59:16 instance-1 bundle[1262]: [88fb9b5f-9d06-4847-a425-0988c78c1c25] app/controllers/api/salmon_controller.rb:8:in `update'
Aug 30 01:59:16 instance-1 bundle[1262]: [118fadae-b687-4f5f-b9fe-aa40ec9e8a89] [active_model_serializers] Rendered REST::InstanceSerializer with ActiveModelSerializers::Adapter::Attributes (5.62ms)
Aug 30 01:59:16 instance-1 bundle[1262]: [118fadae-b687-4f5f-b9fe-aa40ec9e8a89] method=GET path=/api/v1/instance format=html controller=Api::V1::InstancesController action=show status=200 duration=10.93 view=9.23 db=0.00
Aug 30 01:59:17 instance-1 bundle[1262]: [f10fe4ad-9407-4746-9d07-6f42e9990d93] [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Attributes (136.91ms)
```

Mastodon version is 1.5.1, and ruby version is 2.3.3.

**Comment by ykzts** [comment] 2017-08-30 05:58
Duplicate of #3628 #4676

**Closed by ykzts** 2017-08-30 05:58 UTC
