### ISSUE TITLE
Enhancement: Events and invitations

### ISSUE THREAD

**Issue by supercheetah** [tootsuite/mastodon#6925] opened 2018-03-27 00:27 UTC
This is an enhancement request.

One of the things that's keeping me from completely deleting my FB account is creating events, and the invitations that go along with it.  It would be awesome to be able to do that within Mastodon, and even be able to invite people that don't have a Mastodon account on any instance (e.g. through an email with a magic number.)  Maybe it could even be tied into OSM for mapping.

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2018-03-27 06:17
I think this is a duplicate of *[Feature Request] Users should be able to organize events #4179*?

**Comment by strand** [comment] 2018-03-28 19:07
This duplicates that issue and should be closed.

**Comment by supercheetah** [comment] 2018-03-31 17:28
Yeah, this is a duplicate of #4179. Somehow I missed that in my searches.

**Comment by nightpool** [comment] 2018-03-31 18:04
no worries! it's a pretty commonly requested issue.

**Closed by nightpool** 2018-03-31 18:04 UTC
