### ISSUE TITLE
API endpoint for building quotes (for "Share on mastodon" bookmarklets)

### ISSUE THREAD

**Issue by tyrosinase** [tootsuite/mastodon#943] opened 2017-04-05 13:58 UTC
We need an url which will take input(s) and pre-populate the status update box, so users can share links with context. Something along the lines of 

`/api/v1/buildquote?status="Mastodon%20is%20a%20free%2C%20open-source%20social%20network%20server.%20A%20decentralized%20alternative%20to%20commercial%20platforms%2C%20it%20avoids%20the%20risks%20of%20a%20single%20company%20monopolizing%20your%20communication.%20Anyone%20can%20run%20Mastodon%20and%20participate%20in%20the%20social%20network%20seamlessly%20https%3A%2F%2Fmastodon.social%2Fabout%20via%20Mastodon"`

or some such.

* * * *

- [Y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment] 2017-06-29 17:51
Duplicate of #442

**Closed by Gargron** 2017-06-29 17:51 UTC
Labels: enhancement
