### ISSUE TITLE
Add ordering for gallery items

### ISSUE THREAD

**Issue by koyuawsmbrtn** [tootsuite/mastodon#11410] opened 2019-07-26 13:44 UTC
### Pitch

It's kinda annoying having to delete and re-upload images when you want to order them in a gallery.

### Motivation

A user of my server suggested this feature. It's actually a good idea.

https://koyu.space/@jovianarchiver/102507710551499079

**Comment by Gargron** [comment] 2019-08-05 09:05
Duplicate of #5857

**Closed by Gargron** 2019-08-05 09:05 UTC
Labels: suggestion
