### ISSUE TITLE
Support Off-Fediverse User Names

### ISSUE THREAD

**Issue by joycem137** [tootsuite/mastodon#10797] opened 2019-05-20 22:16 UTC
Whenever we use a fediverse user style reference to a user, but the server name is a well known off-site server, we should create a link to that person.

For example, 
@user@twitter.com should create a clickable link to http://twitter.com/@user
@user@soundcloud.com should create a clickable link to http://soundcloud.com/user
etc.

We could setup mappings for "well known services" and enable us to have consistent links to non-fediverse users.

## Motivation

While we all certainly have our issues with those corporate networks, we do know a lot of people on those networks.  Having a clean and consistent way to reference them would make it a little easier to reference them in a post and make it easier to understand and read posts crossposted from those services.

**Comment by trwnh** [comment] 2019-05-21 06:03
What purpose would this serve vs. linking to their profile URL? For one, it would mean Mastodon would have to start keeping track of arbitrary services and their URL schemas. For another, it would be confusing since those are not real accounts on the network.

See also: #1849

**Comment by Cassolotl** [comment] 2019-05-21 16:48
It's another way to link to a profile that is consistent with profile-linking conventions in the fediverse, is in harmony with the fediverse philosophy of maximum interlinky goodness, people already use it all the time (especially for `@user@twitter.com`), the only reason to avoid it is to spite Twitter. (It's not confusing if you leave the `@website.com` on the end for non-fediverse sites, because people would learn fast that if you can see the second part of the handle then it'll open the profile in a new tab.) It means you don't have to go look up whether a profile is linked twitter style (twitter.com/person) or tumblr style (person.tumblr.com) or some other weird way (site.com/@person etc).

**Comment by trwnh** [comment] 2019-05-22 02:01
It's one thing to say you want to link to Twitter in a more "native" way. But once you start asking for other services to be supported, you now have to keep track of how every single proprietary service formats its URLs. Attempting to force everything into a `@user@domain.tld` format doesn't exactly work without the translation layer that maps the fake mention to a real URL. **There's enough complexity that you might as well just use the real URL directly.**

Really, at its core, the usage of `@username@domain.tld` within Mastodon implies that a Webfinger lookup will be successful, because that's what happens when you type something yourself that looks like a mention into the compose box and make a post via the API -- **the server then does a Webfinger lookup and converts the mention to ActivityPub ID + inserts the HTML link.** Networks like Twitter, Instagram, Soundcloud, etc. do not use Webfinger and would therefore be untranslatable by default.

There are already enough challenges with Mastodon supporting "pure" ActivityPub implementations that don't use Webfinger and instead use HTTP(S) URIs. I think those are more worthy of being solved before Mastodon starts having to store dozens of mappings for proprietary networks on top of that.

Entire projects like https://activitypub.actor were formed to try to fake the Webfinger lookup, because it's non-trivial. Asking for generic mention support in this way is basically the same as asking to integrate activitypub.actor into Mastodon's logic. **It'd actually be much easier to allow users to define custom inline links/mentions.**

**Comment by Gargron** [comment] 2019-05-23 13:03
> It'd actually be much easier to allow users to define custom inline links/mentions.

Like writing `https://twitter.com/user` instead of `@user@twitter.com` :eyes:

**Comment by Gargron** [comment] 2019-05-23 13:07
> We could setup mappings for "well known services" and enable us to have consistent links to non-fediverse users.

Managing a mapping isn't that hard but why legitimize/advertise those propritery services many of which are our competitors? Especially when good old URLs are a neutral way of accomplishing the same thing. It's not like a mapping like that will allow Mastodon users to *notify* people on those platforms, or open their profiles within the Mastodon UI. "Mentions" have those connotations, whereas plain URLs do not.

**Comment by jotaf98** [comment] 2019-05-23 17:25
I wonder if there's a way to break down the walls of those walled gardens, by allowing Mastodon users to follow those links into Mastodon-wrapped versions of the proprietary actors and react to them.

It would probably violate their ToS though (although if you don't have a twitter account can you really violate their ToS, by reading the public page through custom software/a wrapper webpage?).

**Comment by DavidLibeau** [comment] 2019-05-29 09:55
Mapping @username@twitter.com as a Twitter link is a bad idea because users may not be aware that they are actually going to Twitter. They will need to hover a long time to see the `title` tip. In Twitter.Activitypub.actor I did not implement an automatic redirection because users may not want to use Twitter at all. If u are trying to escape from GAFAM services, you may not want to go to these websites at all. It a matter of privacy. Implementing a link as profile mention, is a very bad idea because it didn't respect this rigth.

**Comment by realityfabric** [comment] 2019-06-14 02:23
> Having a clean and consistent way to reference them would make it a little easier to reference them in a post and make it easier to understand and read posts crossposted from those services.

I think that it may be a good idea to support custom hyperlinks (for example: [Google](https://google.com)), but I do not think that usernames should be specifically supported as described in this issue. If users want to format usernames with @ handles (for example: `@example@twitter.com`) then custom hyperlinks would allow that, but as has been mentioned several times... supporting non-federated usernames is misleading and would require the devs to understand countless non-AP username schemes.

**Comment by Gargron** [comment] 2019-08-05 09:18
I'm closing this as duplicate of #1849 since the reasoning for rejecting it hasn't changed.

**Closed by Gargron** 2019-08-05 09:18 UTC
Labels: suggestion
