### ISSUE TITLE
Confusing DM UI

### ISSUE THREAD

**Issue by SISheogorath** [tootsuite/mastodon#11888] opened 2019-09-19 08:47 UTC
### Expected behaviour

When clicking on the username and picture of a external account it should send me to this account's profile, not my own.

### Actual behaviour

![image](https://user-images.githubusercontent.com/8719867/65228181-4fe27180-daca-11e9-9687-40903e2f0c93.png)

The DM overview displays the account of the user you have the conversation with, but links to the account that send the last message, which sometimes is yourself.

I hope it's understandable that this is more than confusing.

### Steps to reproduce the problem

1. Send a direct toot to an account
2. Open the DM overview and click on the account picture (or username)
3. End up on your own profile

### Specifications

Version: v2.9.3 (Release from docker hub)

User agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by trwnh** [comment] 2019-09-19 23:48
duplicate of #11414

**Closed** 2019-09-20 09:35 UTC
