### ISSUE TITLE
Error Processing xxxxxx : undefined method `+' for NilClass

### ISSUE THREAD

**Issue by kuratowsky** [tootsuite/mastodon#14763] opened 2020-09-08 15:42 UTC
### Expected behaviour

When we use `tootctl media remove` the system should remove the media without prompting Errors.

### Actual behaviour

Using `tootctl media remove` in some cases is showing 

`Error processing 398253: undefined method '+' for nil:NilClass`  in each line the number is different.

### Steps to reproduce the problem

- Access your server via ssh
- Use the `tootctl media remove` command
- In some cases, the error(s) shows up in the command line
- The task is still running

### Specifications

- Mastodon v3.2.0

**Comment by ThibG** [comment] 2020-09-08 22:40
Duplicate of #14398

**Closed by ThibG** 2020-09-08 22:40 UTC
