### ISSUE TITLE
Emoji v5

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#4452] opened 2017-07-30 11:12 UTC
The Emoji standard is currently in version 5, with 2623 emoji symbols as part of Unicode 10. As far as I know, Mastodon uses EmojiOne in its 2.x branch, which only supports Emoji version 4, with far less symbols: no gender-neutral characters, no witches and wizards, no dinosaurs (those are only examples, there’s nearly 200 new symbols in version 5).

EmojiOne version 3.x supports all of these, but is no longer freely licensed, so I believe it’s a no-go for Mastodon. The only other option currently is… Twemoji, in its versions post-2.3, which has full support for current emoji. It may be counter-intuitive to use a package from Twitter in Mastodon, but that’s the current best option. Future options are: the EmojiTwo project if it’s working out, and the next major version of Noto Color Emoji (or “the new Android emoji”) when it is released.

**Comment by nullkal** [comment] 2017-07-31 06:50
Duplicate of #717

**Comment by nclm** [comment] 2017-07-31 16:23
Not exactly, unless a choice is made to completely remove any assets to display emoji and in this case the version supported is the version of the system. But that’s not good for people using older devices and/or Linux, so I think it’s nicer to keep an Emoji set on Mastodon itself. And in any case there would still list in the Emoji picker to upgrade. So it’s quite a different issue eventually :)

**Comment by nightpool** [comment] 2017-07-31 17:25
re: "It may be counter-intuitive to use a package from Twitter in Mastodon", we already use twitter libraries for hashtag and mention extraction :P

**Comment by nightpool** [comment] 2017-07-31 17:35
I would be interested in looking into Twemoji or Noto, although the new android emoji have seen very negative user reaction so Noto is probably not going to be the best choice. EmojiTwo looks like it's having a hard time gaining traction.

I personally enjoy the twitter emoji, although it might be useful to solicit broader feedback here. We also would either need to fork, rewrite, or find a new emoji picker, since the one we use is tied pretty heavily to emojione. (This is something that has been a pain point in the past anyway)

**Comment by Komic** [comment] 2017-08-01 11:21
> the new android emoji have seen very negative user reaction so Noto is probably not going to be the best choice

The upcoming version of Nato is awful, yeah. You'll be missed, [blob faces](https://github.com/googlei18n/noto-emoji/blob/master/svg/emoji_u1f60a.svg).
For reference, [here](https://emojipedia-us.s3.amazonaws.com/thumbs/120/google/101/face-with-one-eyebrow-raised_1f928.png)'s a Nato one, [here](https://emojipedia-us.s3.amazonaws.com/thumbs/120/twitter/103/face-with-one-eyebrow-raised_1f928.png)'s the same but from Twemoji. The flatter look of the latter would IMO be much better, since we display them at quite small sizes.

**Comment by nclm** [comment] 2017-08-01 15:57
Alternative solution: we design 2623 custom mastodon emoji with little elephants/mammoths/mastodons as figures in each one 🐘 🐘 🐘 

More seriously, I’d be for going with Twemoji:
* It’s already available and up to date.
* There are associated libraries that may be of use one day.
* In addition to the flat look indeed, it’s in every aspect designed to be displayed at small sizes, the shapes are simple, almost pictographic, I won’t be surprised to learn they are drawn on a 16x16 or 24x24 pixel grid. They are probably the most legible emoji out there. I use them on an everyday basis as a system wide set and they work well.
* They are also quite neutral, they’re not trying to be original. The style of the new Noto, the blobs of the old Noto, they are quite distinctive. Twemoji is made to not be noticed, like any good content font, and they can fit anywhere.
* They are unconsciously familiar to Twitter users, so when migrating to Mastodon, it’s one thing less to get used to.

**Comment by nclm** [comment] 2017-08-26 06:51
In addition to Twemoji, the new Noto Emoji for Android Oreo is now an option since the files have just been released: https://github.com/googlei18n/noto-emoji/tree/master/svg

**Comment by nolanlawson** [comment] 2017-09-21 20:30
For anyone who, like me, was wondering what changed in EmojiOne 3's license, [here it is](https://www.emojione.com/licenses). Seems SVG is only available for the paid license. :confused:

**Comment by sdukhovni** [comment] 2017-09-22 05:41
There's also Mutant Standard, a set of alternative gender/race/species-inclusive emoji created by a mastodon user: http://mutant.noct.zone/

It's still under development, and isn't necessarily the right option if our goal is compliance with the Unicode emoji standards, but if we just want a wide-ranging and inclusive set of emoji then this might be worth looking into.

**Comment by nightpool** [comment] 2017-09-22 05:48
I love mutant standard, but it currently only has 200 emoji, and no
publicly available index, development repo, or sprite sheets that I can
see....

**Closed** 2017-10-03 20:31 UTC
Labels: enhancement, priority - medium, requires in depth
