### ISSUE TITLE
can't upload webm (25MB)

### ISSUE THREAD

**Issue by alex-tee** [tootsuite/mastodon#12873] opened 2020-01-16 14:13 UTC
### Expected behaviour

1. Upload webm
2. Video shows below the text input for the toot

### Actual behaviour

1. Upload Webm
2. Upload finishes, then video disappears

### Steps to reproduce the problem

Upload a webm of around 25MB

### Specifications

on mastodon.social v3.0.1

Firefox 72.0.1 (64-bit) on MacOS Mojave 10.14.6 (18G2022) with Adblock plus, ublock origin and privacy badger

**Comment by ThibG** [comment] 2020-01-16 17:48
Does any error notification appear in the corner of the screen when that happens?
If so, what does it say?

**Comment by alex-tee** [comment] 2020-01-16 18:01
no, that's the problem. no notification at all. the video just disappears after it's finished uploading

**Comment by ThibG** [comment] 2020-01-16 19:27
Can you upload that webm anywhere so that we can try reproducing the issue?

**Comment by alex-tee** [comment] 2020-01-17 16:19
here: https://ufile.io/gs3is83r

**Comment by ThibG** [comment] 2020-01-18 16:27
Here, it fails with “Gateway timeout”, as the file takes too long to transcode to mp4.
I'm not sure what could be done about it.

**Comment by fwenzel** [comment] 2020-01-19 19:27
Narrowly this is a server issue; more broadly, probably would have to do any transcoding outside of the main thread and not block on it, displaying a placeholder until done.

**Comment by Gargron** [comment] 2020-03-06 04:23
Duplicate of #9106

**Closed by Gargron** 2020-03-06 04:23 UTC
