### ISSUE TITLE
Show account preview when hovering over account name in all timelines

### ISSUE THREAD

**Issue by dadosch** [tootsuite/mastodon#11347] opened 2019-07-18 13:22 UTC
### Pitch

When you hover over a account name (in any Timeline) a preview of that account could be shown, similar to what Wikipedia does with articles:
![Screenshot_20190718_151655](https://user-images.githubusercontent.com/12801390/61460503-60f1f380-a95e-11e9-8b14-03621dc74400.png)

In that preview, there should be shown all the things from the account page, but maybe in a more wider rectangle and without the header image (?) 

![Screenshot_20190718_152000](https://user-images.githubusercontent.com/12801390/61460800-06a56280-a95f-11e9-8527-e5520b96da7e.png)

### Motivation

This would help identify bogous accounts (fake news) or help find interesting ones you want to follow.

**Comment by Gargron** [comment] 2019-08-05 09:06
Duplicate of #1471

**Closed by Gargron** 2019-08-05 09:06 UTC
Labels: suggestion
