### ISSUE TITLE
Allow the expansion of a toot by on the whole block instead of only the text

### ISSUE THREAD

**Issue by mlorant** [tootsuite/mastodon#1673] opened 2017-04-13 08:41 UTC
On a toot displayed in the timeline, it seems only the text is clickable to expand it (to see replies and such). From another social network tool I use (hint: it ends with Deck...), I am used to be able to click everywhere on the block, except the handle and avatar, to expand the message. 
I think it would be nice to have the same behaviour so the following red zones are clikcable:

![Screenshot from Mastodon](http://i.imgur.com/3JofYyS.png)

I find it easier/quicker to click in the left zone (the reddest one on the screen) than aiming in the text, which can have links and images like in this example.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment] 2017-04-14 06:12
This would be very helpful. I've made an attempt to implement it, but I'm not familiar with jsx at all, so it's going to take a bit of learning. For anyone else who wants to take a look, [status.jsx](https://github.com/tootsuite/mastodon/blob/master/app/assets/javascripts/components/components/status.jsx) is a good start.

**Comment by mlorant** [comment] 2017-04-14 06:17
@expenses Quickly digging into the code, I guess the handleClick (given as a prop to StatusContent) should be handled on the wrapper div of this Status component AND sub components should stop the propagation of their click events if they are doing something else with it (to avoid the expansion of the toot if you click on a link/spoiler/image/profile)

**Comment by expenses** [comment] 2017-04-14 06:57
@mlorant Yep, thats right, I just don't know how (stopping) propagation works in React.

**Comment by mlorant** [comment] 2017-04-14 07:41
@expenses It is just plain good ol' Javascript, using `e.stopPropagation()` where `e` is the Javascript event object. I don't have any Mastodon development environement set up, so I can't check, but there may be other things to consider.

**Comment by expenses** [comment] 2017-04-14 07:45
@mlorant That didn't seem to work, will try again later though.

**Comment by expenses** [comment] 2017-04-15 07:56
@mlorant Ok, I've been able to stop propagation on, afaik, everything but the trigger (`...`) for the drop down, which is [handled externally](https://github.com/Fauntleroy/react-simple-dropdown). I'm not sure what to do.. Should I make a PR with the changes so far?

**Comment by wavebeem** [comment] 2017-04-15 17:43
I think we need to get in an option to stop propagation upstream.

**Comment by wavebeem** [comment] 2017-04-15 17:44
I opened an issue in the dependency library so it's probably worth implementing it and hoping they're cool with merging it.

**Comment by wavebeem** [comment] 2017-04-17 23:46
Does anyone have the background on this issue to know if this proposed dependency change would be useful to solve the issue? https://github.com/Fauntleroy/react-simple-dropdown/issues/34#issuecomment-294527900

**Comment by Gargron** [comment] 2017-04-18 00:20
This is historical behaviour due to user request #140

**Comment by wavebeem** [comment] 2017-04-18 00:23
That makes sense but given the UI it's entirely unclear you can't simply
click there. Adding a border around statuses would make this a non issue I
think.

**Comment by wavebeem** [comment] 2017-04-25 04:00
It looks like this is possible to add already per this comment: https://github.com/Fauntleroy/react-simple-dropdown/issues/34#issuecomment-296834269

**Comment by Gargron** [comment] 2017-06-29 22:42
Duplicate of #564

**Closed by Gargron** 2017-06-29 22:42 UTC
Labels: enhancement, priority - medium, ui
