### ISSUE TITLE
Ability to change username

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#5645] opened 2017-11-09 22:01 UTC
Folks seem to ask semi-frequently if it's possible to change usernames, so I think this might be good.

However, I did see rumours at some point that it's not possible to alter subscription info *on other instances*, so if I changed my username the accounts of my followers on other instances wouldn't update to my new username. I'm wondering if that's still the case?

Edit: If this isn't possible, can there be some kind of indication at registration that changing usernames isn't possible?

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Chronister** [comment] 2017-11-09 22:55
I think the main problem is that the unique identifier for an account remotely _is_ the username. All remote instances might give alice@example.social different IDs but that string, alice@example.social, is how they identify alice as the same person.

If there's some mechanism in activitypub to effectively do a "redirect" or "symbolic link" of one handle to another this might be possible, but if not then it doesn't really seem feasible. Someone who's read the AP spec in detail might be able to give a more definitive answer here.

**Comment by nightpool** [comment] 2017-11-09 22:57
functionally a duplicate of #177

**Closed by nightpool** 2017-11-09 22:57 UTC

**Comment by dysinger** [comment] 2020-01-09 12:09
In the case of ham radio, where people want to be identified by their call sign, this is a highly desirable feature. My call sign changed. I now have to delete my account and create another account. That's a PITA.

**Comment by Cassolotl** [comment] 2020-01-09 12:57
In light of @dysinger's comment, I'd like to reopen this issue.

**Comment by pinpox** [comment] 2020-02-11 13:05
Any update on this? Would like to change my name/handle

**Comment by jubalfh** [comment] 2024-06-14 23:58
note that account migration is very much not the same action as account migration (different behaviours, different scopes). can this issue be re-opened or does it need to be created anew?

**Comment by RokeJulianLockhart** [comment] 2024-06-15 00:02
> https://github.com/mastodon/mastodon/issues/5645#issuecomment-2168947749

@jubalfh, how does it differ?

**Comment by Cassolotl** [comment] 2024-06-19 15:45
@RokeJulianLockhart You can't take your posts with you when you migrate to a new account, for example.
