### ISSUE TITLE
Error when using tootctl - " cannot load such file -- thor (LoadError)"

### ISSUE THREAD

**Issue by tcreek** [tootsuite/mastodon#9082] opened 2018-10-24 16:31 UTC
When using tootctl per listed here:

 https://docs.joinmastodon.org/administration/post-installation/#from-the-command-line

> RAILS_ENV=production bin/tootctl accounts create \
>   alice \
>   --email alice@example.com \
>   --confirmed \
>   --role admin

Using my own details, I get this returned:

> Traceback (most recent call last):
>         4: from bin/tootctl:3:in `<main>'
>         3: from bin/tootctl:3:in `require_relative'
>         2: from /home/mastodon/live/lib/cli.rb:3:in `<top (required)>'
>         1: from /home/mastodon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> /home/mastodon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- thor (LoadError)

**Comment by Gargron** [comment] 2018-10-24 22:46
Duplicate of #8593 (There is your answer)

**Closed by Gargron** 2018-10-24 22:46 UTC
Labels: troubleshooting

**Comment by tcreek** [comment] 2018-10-25 02:07
I am sorry, but I am not sure how running those two listed help functions help me with my problem (with function just fine by the way, unlike the . This seems to NOT be a duplicate

**Comment by tcreek** [comment] 2018-10-25 02:30
Hello

I have done that, but get a different error instead.

> ERROR: "tootctl accounts help" was called with arguments ["create", "tcreek", "--email", "tcreek@email.com", "--confirmed", "--role", "admin"]
> Usage: "tootctl accounts help [COMMAND]"

**Comment by Gargron** [comment] 2018-10-25 03:04
Did you call `tootctl accounts help create`  instead if `tootctl accounts create`?

**Comment by tcreek** [comment] 2018-10-25 03:08
No.
This is the command:


 

> RAILS_ENV=production bundle exec  bin/tootctl accounts create tcreek --email tcreek@email.com --confirmed --role admin

**Comment by tcreek** [comment] 2018-10-25 04:31
No.
This is the command:


 RAILS_ENV=production bundle exec  bin/tootctl accounts create tcreek --email tcreek@email.com --confirmed --role admin

**Comment by kevingimbel** [comment] 2018-10-25 08:49
I was experiencing the exact same error yesterday evening. I tried the solution from #8593 and I am getting the same error 
> ERROR: "tootctl accounts help" was called with arguments ["create", ...

It looks like there's something wrong with the command. If I can provide any additional information or help please let me know.

**Comment by tcreek** [comment] 2018-10-26 21:48
Maybe this needs to be reopened?

**Comment by Gargron** [comment] 2018-10-26 21:52
Are you using master or 2.5.2?

**Comment by kevingimbel** [comment] 2018-10-28 14:46
@Gargron I am using `2.5.2`. I just did a fresh install (new server) and I am seeing the same issue.

```
mastodon@host:~/live$ RAILS_ENV=production bin/tootctl accounts create \
> xxx \
> --email xxx@xxx.xxx \
> --confirmed \
> --role admin
Traceback (most recent call last):
	4: from bin/tootctl:3:in `<main>'
	3: from bin/tootctl:3:in `require_relative'
	2: from /home/mastodon/live/lib/cli.rb:3:in `<top (required)>'
	1: from /home/mastodon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/mastodon/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- thor (LoadError)
```

(Sensitive data has been replaced with `xxx`)

@tcreek you can check like this:

Go to the mastodon directory, e.g `/home/mastodon/live`.
```sh
$ su - mastodon
$ cd ~/live
```
Run the following command
```
$ git branch
git branch
* (HEAD detached at v2.5.2)
  master
```

`* (HEAD detached at v2.5.2)`

**Comment by tcreek** [comment] 2018-10-28 16:54
Response was:

* (HEAD detached at v2.5.2)
  master

**Comment by tcreek** [comment] 2019-03-13 18:30
Well, I was using what was given during their installation procedure, which was new at the time
