### ISSUE TITLE
unfavouriting animation/action inconsistent

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#575] opened 2017-01-29 12:34 UTC
When i click a star on a favourited toot it does not play the animation, but actually unfavs it. If i then click it again, it plays the unfav animation, and does not change the status of the toot further.

**Comment by wchristian** [comment] 2017-01-29 16:37
More animation inconsistency:

1. Boost a toot with replies.
2. Expand the toot.
3. Expand a reply.
4. Click back.

Result: Boost button animates again. (Or sometimes the fav button.)

**Comment by unarist** [comment] 2017-06-19 16:26
I'm going to close this because I cannot reproduce on recent releases. If you still see this issue, please reopen and tell me what version you checked.

**Closed by unarist** 2017-06-19 16:26 UTC
Labels: bug
