### ISSUE TITLE
Relaxing HTML sanitization for markup that reverses meaning.

### ISSUE THREAD

**Issue by tateisu** [tootsuite/mastodon#15553] opened 2021-01-13 09:54 UTC
Mastodon does HTML sanitization when accepting remote posts.
However, removing the some markup reverses the meaning of the text.
Some markup should be acceptable such as :
- <del>
- <s>
- <strike>

**Comment by ThibG** [comment] 2021-01-13 12:24
(I assume this has been posted by error and its a duplicate of #15554)

**Closed by ThibG** 2021-01-13 12:24 UTC
