### ISSUE TITLE
Hovercard on display names?

### ISSUE THREAD

**Issue by nthall** [tootsuite/mastodon#15467] opened 2020-12-30 19:17 UTC
### Pitch

I did try to search past issues for this question - sorry if I missed it. I'm a fan of the hovercard interaction pattern, where hovering over a username or relevant bit of the page triggers displaying an element with more information about the entity (some sites with examples would be Facebook, Twitter, and Soundcloud). Would a PR adding this be welcome?

### Motivation

It would be nice to have another level of preview/additional information about someone before clicking through to their profile. I imagine it'd be very welcome for people using the single-column layout, and even in the multi-column layout it would have some advantages, e.g. if media is playing in the right-most column, you could preview some information about someone from another column without clicking through and thus interrupting the media playback.

Unless there's some antipathy to the idea from the main contributors, or a technical reason I haven't realized yet, I'd be happy to work on a PR for this.

**Comment by michel-slm** [comment] 2020-12-31 19:50
Would this be passive only, or would it allow interactions e.g. following someone? Either would be beneficial, I think; if it's the latter, it's especially important to display someone's additional info since they might list, for example, their personal pronouns somewhere, or specify that you shouldn't request to follow them unless you've interacted before.

**Comment by Gargron** [comment] 2021-03-27 16:07
Oh, this is a duplicate of #14918, please continue discussion there

**Closed by Gargron** 2021-03-27 16:07 UTC
