### ISSUE TITLE
2.4.0 upgrading -> PG::UndefinedObject: ERROR:  type "jsonb" does not exist

### ISSUE THREAD

**Issue by salvadorpla** [tootsuite/mastodon#7599] opened 2018-05-23 05:43 UTC
When running ‘RAILS_ENV=production bundle exec rails db:migrate’ it throws this error:

== 20180410204633 AddFieldsToAccounts: migrating ==============================
-- add_column(:accounts, :fields, :jsonb)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedObject: ERROR:  type "jsonb" does not exist
LINE 1: ALTER TABLE "accounts" ADD "fields" jsonb

Just found this possible solution but not tried yet:

https://stackoverflow.com/questions/29393562/rails-and-jsonb-type-jsonb-does-not-exist#29423224

My Postgres version is :

postgres=# SHOW SERVER_VERSION;
 server_version 
----------------
 9.2.23
(1 row)

**Comment by ykzts** [comment] 2018-05-23 05:55
Duplicate of #7154

**Closed by ykzts** 2018-05-23 05:55 UTC
Labels: duplicate
