### ISSUE TITLE
[Feature] Follow to list - Follow and place in a list in a single click.

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#8330] opened 2018-08-20 23:31 UTC
Hi G,
I'd love to be able to follow people straight into a list... I'm moving over from Twitter and have "Adelaide Twitter" "Art Twitter" "Twitch Twitter" "infosec twitter" etc etc. I've got pinned lists to archive this.

I'd love to be able to group these people into different feeds quickly and easily. 

Lists is one of those things that Twitter really dropped the ball on.

**Comment by imathew** [comment] 2018-08-21 09:07
+1 to this. I'm currently using Tootdon on Android because it's the easiest way to follow and add to a list in a single step, it's a killer feature over other apps that I'd otherwise prefer. Would love similar here.

**Comment by trwnh** [comment] 2018-08-21 19:06
Duplicate of #7187, which is itself a duplicate of #6058

**Closed** 2018-10-04 02:51 UTC
