### ISSUE TITLE
[Feature] Ability to add accounts to a list without having to follow them first

### ISSUE THREAD

**Issue by lashman1985** [tootsuite/mastodon#8294] opened 2018-08-19 14:00 UTC
it would be nice to be able to add accounts to lists without having to follow them first ... especially if it's a news bot, or just a website tooting out their articles etc. ... i wouldn't necessarily want to follow them and see that stuff in my main timeline, but it would be nice to have that in a separate pinned "news" list

if it's a privacy concern - they can also get notified about getting added to a list 

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment] 2018-08-19 14:50
Duplicate of #6982

**Closed by ThibG** 2018-08-19 14:50 UTC
