### ISSUE TITLE
Feature Request: Mute Single Posts

### ISSUE THREAD

**Issue by bannisdale** [tootsuite/mastodon#11973] opened 2019-09-27 11:08 UTC
### Pitch

Instead of just being able to mute/block a user in a post menu, it should also be possible to mute this exakt post.

### Motivation

Every once in a while, there is this one posting that comes back every few hours. While a joke might be funny the first two times, it's simply annoying to see them 20 times over the course of a week. So I propose the easy solution to mute this exact posting, so it won't appear in the home timeline again when being boosted once again.

**Comment by Cassolotl** [comment] 2019-09-27 16:08
Is this a duplicate of *Hide a specific status #1669*? It's good to combine all the comments and 👍s and so on in one place.

**Comment by bannisdale** [comment] 2019-09-28 07:32
@Cassolotl Yeah, looks like it. Thanks for letting me know.

This one can be closed then. :)

**Comment by Cassolotl** [comment] 2019-09-28 15:13
@bannisdale You can just close it yourself. :)

**Closed** 2019-09-28 15:29 UTC
