### ISSUE TITLE
Notification summaries for multipleboosts/favorites of the same toot

### ISSUE THREAD

**Issue by penguin42** [tootsuite/mastodon#11297] opened 2019-07-14 12:49 UTC
On the WebUI, For a popular toot, collapse multiple notifications so that you see 'a, b, c, d, and 10 others boosted your status'

### Pitch
Wherre there are multiple (almost?) neighbouring boosts/faviourited's for the same toot, collapse them into a single item in the notification stream; i.e. at the moment we have

   $a favourited your status
      <text of toot>
    $b boosted your status
      <text of toot>
    $c favourited your status
       <text of toot>

collapse this to:
     $a, $c favourited your status
     $b boosted your status
          <text of toot>

maybe also limit it (like G+ did) so you'd get something like $a, $c and 15 others favourited your status

### Motivation
I posted a popular toot; it's got lots of boosts and favourites; and that's completely dominating my Notification column.  However, most of the column is just copies of the original text from my toot - copied for each response; that's pretty pointless.

**Comment by trwnh** [comment] 2019-07-15 01:51
Duplicate of #7698 and #9182

**Comment by Gargron** [comment] 2019-08-05 09:10
Duplicate of #1483

**Closed by Gargron** 2019-08-05 09:10 UTC
Labels: suggestion
