### ISSUE TITLE
Feature: Bookmarklet to share URL + <title>

### ISSUE THREAD

**Issue by 153** [tootsuite/mastodon#1318] opened 2017-04-09 05:55 UTC
Twitter has a snazzy bookmarklet that (a) opens a new window with a tweet box, that (b) includes the current page's URL and (c) the current page's <title> prefilled in the tweet input box. 

Adding this to Mastodon would encourage more sharing of content around the web and something to tide us over until the [Tweet] buttons are replaced with [Toot] buttons on websites 

It's likely that someone's done this for GNU social before

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
(i lied)

**Comment by Gargron** [comment] 2017-06-29 19:19
Duplicate of #442

**Closed by Gargron** 2017-06-29 19:19 UTC
Labels: enhancement
