### ISSUE TITLE
Allow users to edit recently published toots 

### ISSUE THREAD

**Issue by davidcelis** [tootsuite/mastodon#742] opened 2017-04-02 20:29 UTC
One of the most annoying things about Twitter is publishing a tweet, noticing that it has a typo or other dumb mistake, copying the tweet text, deleting it, and re-posting it (while potentially re-adding a picture) to fix the typo.

While editing toots could be problematic because of changing the context of replies, it could be completely reasonable to allow users to edit a toot that they've published in the last, say, five minutes.

**Comment by blackle** [comment] 2017-04-13 01:45
duplicate of #256, move discussion there

**Closed by blackle** 2017-04-13 01:45 UTC
