### ISSUE TITLE
users with extremely large bios causing issues in column view

### ISSUE THREAD

**Issue by tronmaximum** [tootsuite/mastodon#196] opened 2016-11-22 16:13 UTC
visual example of what's happening:
![image](https://cloud.githubusercontent.com/assets/23643474/20531331/4f326482-b08b-11e6-9214-70fa7be528c0.png)

basically since bios don't have a scroll bar on the right, when they get huge like this it makes it impossible to see a person's posts, or open the mention/follow/block menu, which is a little troublesome if you want to get someone out of visibility but you can't access the tools to make them invisible to you.

**Comment by unsmell** [comment] 2016-11-23 13:36
should be worth mentioning that there's currently no other way to block someone with such a bio without using the API or devtools

**Comment by Gargron** [comment] 2017-01-30 22:45
Dupe of #257, now resolved

**Closed by Gargron** 2017-01-30 22:45 UTC
Labels: enhancement
