### ISSUE TITLE
Notification for new content / Following profiles

### ISSUE THREAD

**Issue by beerisgood** [tootsuite/mastodon#14805] opened 2020-09-15 20:58 UTC
Under https://docs.joinmastodon.org/user/network/#notifications the following different notification types are listed:

> Mentions: received when someone has mentioned you in a post.
> Favourites: received when someone has favourited one of your posts.
> Boosts: received when someone has boosted one of your posts.
> Polls: Received when a poll that you have voted in or created has ended.
> Follows: Received when someone has followed your profile.

Sadly no option for new posts like from following profiles.
For example i follow the [FediNINA](https://meta.prepedia.org/wiki/FediNINA) project which is a (inofficial) Bot for "Current warnings in Germany" from German "Federal Office for Civil Protection and Disaster Assistance" (Bundesamt für Bevölkerungsschutz und Katastrophenhilfe) to get warnings without the official "NINA" app.

But i need to check new posts by myself instead of just wait for a notification which is possible with every browser - as i use the Mastodon website instead of a App. (current notifications works in browser in the background)

So i hope new posts can be added to notifications.

**Comment by trwnh** [comment] 2020-09-16 01:20
Duplicate of #4890

**Comment by Gargron** [comment] 2020-09-16 01:23
As above, it's being worked on!

**Closed by Gargron** 2020-09-16 01:23 UTC

**Comment by beerisgood** [comment] 2020-09-16 15:35
> As above, it's being worked on!

Awesome
