### ISSUE TITLE
Local only toots

### ISSUE THREAD

**Issue by stemy2** [tootsuite/mastodon#11809] opened 2019-09-11 16:10 UTC
### Pitch

Implement a option to make a toot visible only on its instance and not the whole fediverse.

### Motivation

User would be more in confidence if they could post toots that could be not visible outside the server he trusts. It would also be cool for closed communities.

**Comment by ThibG** [comment] 2019-09-11 20:24
Duplicate of #861

**Closed by ThibG** 2019-09-11 20:24 UTC
