### ISSUE TITLE
Getting notification of a follow multiple times

### ISSUE THREAD

**Issue by simonv3** [tootsuite/mastodon#2532] opened 2017-04-27 15:20 UTC
There's a couple of users who have followed me multiple times. This might be because they unfollowed me and then followed me again, or there might be some other bug to do with federation. I shouldn't get notified every time they do so.

It's the same user on the same instance (One example is @flowman@mastodon.coffee), so it's not someone moving accounts.

I'm not sure they qualify as spam because sometimes these users do have toots that seem genuine.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2018-10-22 23:10
Duplicate of #4118

**Closed by Gargron** 2018-10-22 23:10 UTC
Labels: bug, ui
