### ISSUE TITLE
paste text and soon toot by Ctrl+Enter, so toot content in textaera before paste

### ISSUE THREAD

**Issue by ncaq** [tootsuite/mastodon#2348] opened 2017-04-23 06:31 UTC
paste text and soon toot by Ctrl+Enter, so toot content in textaera before paste.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment] 2017-04-23 07:16
Hi there, thanks for opening the issue! I'm afraid I don't quite understand what you're asking for, can you clarify with more details? Thanks!

**Comment by ncaq** [comment] 2017-04-24 00:35
I'm Japanese and I don't fluency English.Sorry.

It's frontend trouble.
For instance, The postbox have `foo `.
I paste text(`bar`) from clipboard to postbox by keybind.
And soon I push `Ctrl+Enter`.
So browser toot body `foo `.

I short think to did not update react state?
I don't know still mastodon frontend detail, sorry.

Thanks!

**Comment by ashfurrow** [comment] 2017-04-24 06:58
No need to apologize. I'll follow your steps and see if I can reproduce the bug. Thanks for following up.

**Comment by ashfurrow** [comment] 2017-04-24 07:46
I see, let me check that I understand what's going on. 

Steps to reproduce:

1. 'foo' is in the postbox.
1. 'bar' is on the clipboard.
1. Postbox is _not_ selected.
1. Hit paste via keybindings.

Expected results: 'bar' is pasted into the postbox.
Actual results: nothing happens.

Is this correct? Thanks!

**Comment by ncaq** [comment] 2017-04-24 12:00
Postbox is selected.
Expected results: toot `foo bar`.
Actual results: toot `foo`.

**Comment by ashfurrow** [comment] 2017-04-24 12:22
Interesting, so your not able to paste at all? Or you paste, then hit ctrl-enter, and only 'foo' is tooted even though 'foo bar' was in the box?

**Comment by S-YOU** [comment] 2017-04-24 12:43
@ncaq, 少し日本語で説明してもらっていい？向こうに翻訳してあげられると思うので。

**Comment by nightpool** [comment] 2017-04-24 12:59
@ashfurrow here are the reproduction steps as I understand them:

1. Compose a toot with the contents "foo"

2. Have "bar" in your paste buffer

3. Press ctrl-v, ctrl-enter in quick succession

4. Notice that although "bar" appeared in the box, it does not appear in
the toot that is created.

This seems like a straightforward react issue to me

**Comment by S-YOU** [comment] 2017-04-24 13:00
@nightpool, can you reproduce it too? I can't, so I am asking him in Japanese.

**Comment by ashfurrow** [comment] 2017-04-24 14:03
I understand now, thanks for clarifying everyone. I've tried reproducing but can't on macOS; @ncaq can you provide your operation system, version, and hardware information? Thanks!

@nightpool my React expertise aren't super sharp, have you seen this before? Any help would be welcome.

**Comment by S-YOU** [comment] 2017-04-24 18:09
I tried to reach him on his mastodon instance, not sure he see my message or not, but based on his toots, he looks like optimist about the issue. So, I am not sure, he will reply or come back to issue any time soon.

**Comment by nightpool** [comment] 2017-04-24 18:22
@ashfurrow I haven't, but I have seen similar things in angular, which is
what i was basing my comment on.

**Comment by ncaq** [comment] 2017-04-25 09:18
ごめんなさい,今`keysnail`という拡張機能を無効化して試してみた所,ペーストは正常に作動しました.
I'm sorry, I disable `keysnail` firefox addon and tri, so paste correct work.

keysnailにはペーストのキーバインドを変える機能があり,これを使って`C-y`(emacsのキーバインド)を使うとこの状態になります.
keysnail have function that modify paste keybinding, if use it `C-y`(emacs keybindings) than become state.

これがバグではないと判断するならば,閉じてください.
If your decide that it is not bug, than close this issue please.

ありがとう.
Thank.

**Comment by ashfurrow** [comment] 2017-04-25 09:40
No problem! If I understand, by disabling the keysnail plugin everything worked? Then I will close this issue. Please re-open if the issue is not fixed, thanks!

**Closed by ashfurrow** 2017-04-25 09:40 UTC
Labels: enhancement
