### ISSUE TITLE
Shared groups/organisations or possibility to manage several accounts

### ISSUE THREAD

**Issue by akien-mga** [tootsuite/mastodon#2134] opened 2017-04-19 09:23 UTC
I would like to be able to manage "group" accounts for the Mageia and Godot Engine free software project I contribute to.

Having to create a specific user account for each of them and log out/log in each time I want to impersonate them (as well as sharing credentials with other "group" managers) is something I used to do on Twitter before I discovered the group management feature in Tweetdeck - I'd like to see something similar in Mastodon.

I can imagine that it's quite some work, and maybe already planned somewhere down the line, so feel free to use this issue for further technical discussion.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] *`master` not tested* This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment] 2017-04-20 00:46
duplicate of #380

**Closed by wxcafe** 2017-04-20 00:46 UTC

**Comment by Moini** [comment] 2019-09-26 22:33
This isn't a duplicate, at least not entirely. I, too, am looking for a way to have multiple managers with access to a single outlet. 

So, more than one person can post to a thread under the same name (e.g. the one of an open source project) without using the same credentials, plus having some kind of basic permission management.

**Comment by hex-m** [comment] 2023-02-22 18:56
@Moini what you are asking for is requested in #20804 and #15896. Basically the "Facebook Page" use case.

**Comment by Moini** [comment] 2023-02-22 20:09
@hex-m https://github.com/mastodon/mastodon/issues/20804 is not the same thing - it asks for a property of the account, not for having multiple accounts being able to access one output.

https://github.com/mastodon/mastodon/issues/15896 seems very similar, indeed. Seems they did not look for duplicates when posting ;-) (or rather... this was closed prematurely, as explained before...)

**Comment by Moini** [comment] 2023-02-22 20:10
We would still like to have that for Inkscape.
