### ISSUE TITLE
Could not reset password until I used incognito mode in browser

### ISSUE THREAD

**Issue by tardisx** [tootsuite/mastodon#6293] opened 2018-01-18 23:16 UTC
* accidentally set wrong password for my user because I'm a doof
* log out out of instance
* follow password recovery process
* follow link from email for password recovery
* try to enter new password

Receive the following error:

![pw_1](https://user-images.githubusercontent.com/39711/35126386-1d55969a-fcfd-11e7-915b-6e4bd63194f3.png)

Interestingly, whatever is failing seems to fail "early", as even entering a password that would trigger the "password too short" message gives the same response as shown here.

Opening the link in a browser window set to incognito mode (actually, Safari and "private window") allows me to change my password successfully. So I suspect there is some cookie/session detritus which is causing this problem.

I had the same problem on both my desktop and my mobile client (Mac Safari and iOS Safari).

(Possibly related to #6213 ?)

```
mastodon@myhost:~/live$ git status
HEAD detached at v2.1.3
nothing to commit, working directory clean

```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2018-02-25 20:14
For whatever reason, I cannot reproduce this in development environment on current master.

**Comment by Gargron** [comment] 2018-02-25 20:16
I was able to reproduce this in v2.1.3 so I'm assuming this means it's fixed in master.

**Closed by Gargron** 2018-02-25 20:16 UTC
