### ISSUE TITLE
Can't see anyone in the federated timeline

### ISSUE THREAD

**Issue by Perdouille** [tootsuite/mastodon#1104] opened 2017-04-06 20:49 UTC
Hello !

I tried to install Mastodon on my dedicated server. I can connect correctly and see other profiles with the search bar, but the "federated timeline" is empty, there is only what I'm posting

Sending / Receiving messages to/from other instances works, but if look at a profile hosted on a different instance I can't see any toots (except the ones sent at me directly with the @)

Is there anything I forgot to do ?

Thanks !

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-06 21:17
That's expected behavior. The Federated Timeline is made from the toots by people that are on your instance, and the ones by people on remote instances that people on your instance follow, since they started following them. If you don't follow anyone, or follow a few people and they haven't tooted since you started following them, you shouldn't see anything in there.

**Comment by gled-rs** [comment] 2017-04-06 21:44
For those wondering, you can just use a bot like https://github.com/gled-rs/mastodon-autofollow and follow a few people from other instances, then the bot will take care of populating your federated timeline by following each new person that appears on the federated timeline. 

Beware, it'll get ugly soon though ( you can check the result with @followbot@mastodon.pericles.world ) and it kind of defeats the purpose of having theme or community instances, as you'll end up eventually with a lot more than you asked.

**Comment by foozmeat** [comment] 2017-04-07 03:08
sorry to jump in here...

I just set up an instance as well and imported the people I follow on mastodon.social. It's been about 1.5 hours and nothing is appearing in my timeline. Its as if my server isn't fetching data from the other servers. Do they need to whitelist me? What should I be looking for if things are working as expected?

It would be great if there was an admin FAQ or troubleshooting doc.

Thanks for all of the hard work!

**Comment by Perdouille** [comment] 2017-04-07 09:49
I thought the Federated Timeline was every instance's timelines :/

That would be an awesome feature but I suppose it would be hard to do

**Comment by wxcafe** [comment] 2017-04-10 11:42
I'm closing this since the original question was answered (afaict). @Perdouille you can reopen if you feel your question wasn't appropriately answered.

**Closed by wxcafe** 2017-04-10 11:42 UTC
