### ISSUE TITLE
Please add NSFW mark for accounts

### ISSUE THREAD

**Issue by shioko** [tootsuite/mastodon#9613] opened 2018-12-24 09:13 UTC
need a mark as NSFW in account settings, and other users can choose to hide them.

### Motivation

there are many porn bot on the federation timeline after tumblr's NSFW ban, although they coverd the toots, they usually have a NSFW avatar too. some people may not want to see these toot or avatar, and they need someway to hide them.

**Comment by spaceottercode** [comment] 2018-12-25 23:47
Hi @shioko 

This is being discussed in #9468 (related issue). Do you mind taking a look please.

**Comment by nightpool** [comment] 2018-12-26 03:15
closed as duplicate of #9468

**Closed by nightpool** 2018-12-26 03:15 UTC
