### ISSUE TITLE
LOCAL_HTTPS=true causes HTTPS redirects

### ISSUE THREAD

**Issue by maxguru** [tootsuite/mastodon#899] opened 2017-04-05 00:30 UTC
I have a reverse proxy in front of the web container.  Docs say I need to set LOCAL_HTTPS to true, however, I am getting HTTPS redirect from within a container if I do this.  It would be nice if it would be possible to disable the redirects but keep HTTPS URLs.

**Comment by lmorchard** [comment] 2017-04-05 06:08
What's the configuration for your reverse proxy look like? For Apache, I had to add this to let Rails know the protocol was indeed HTTPS:
```
RequestHeader set X_FORWARDED_PROTO 'https'
```

**Comment by cjeanneret** [comment] 2017-04-05 06:08
@maxguru heya! did you try to pass a header like "X-Forwarded-Protocol: https" to the backend? It's pretty standard, maybe the RoR app understand it and won't force redirect loop

**Comment by Gargron** [comment] 2017-04-05 09:15
The production guide gives an example nginx config in which you set the `X-Forwarded-Procotol: https` header - this is how Rails would know if you're already connected through https. Whatever reverse proxy you're using, you should set that header in the proxy.

**Comment by maxguru** [comment] 2017-04-06 00:04
I am using nginx proxy setup within a docker container (https://hub.docker.com/r/jwilder/nginx-proxy/). It already sends the 'X-Forwarded-Proto' header (see https://github.com/jwilder/nginx-proxy#replacing-default-proxy-settings). Maybe it needs to be 'X-Forwarded-Protocol'?

**Comment by maxguru** [comment] 2017-04-11 00:25
Looks like sending 'X-Forwarded-Protocol' did actually resolve the issue.  This is good and bad.  Good because there is a workaround, bad because people are having problems.  You guys should change the code to use 'X-Forwarded-Proto' header because everybody is using this version of the header instead of 'X-Forwarded-Protocol'.

**Comment by ashfurrow** [comment] 2017-04-22 02:00
It looks like [the Apache docs](https://github.com/tootsuite/documentation/blob/088c49141172aec70d9dd87bef436b94627136a3/Running-Mastodon/Alternatives.md#apache) now include the `X-Forwarded-Proto` header. I'm going to close this issue, since you've confirmed the fix works (thanks!) and it's been documented. Feel free to re-open if there's anything we missed!

**Closed by ashfurrow** 2017-04-22 02:00 UTC
