### ISSUE TITLE
favourite notification without a status

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#7240] opened 2018-04-23 09:54 UTC
```
$ curl -s 'https://chitter.xyz/api/v1/notifications/180009' -H 'authorization: Bearer (redacted)' | jq
{
  "id": "180009",
  "type": "favourite",
  "created_at": "2018-04-23T08:51:40.580Z",
  "account": {
    "id": "11912"
    // (redacted)
  },
  "status": null
}
```

```
chitter=> select * from notifications where id = 180009;
 activity_id | activity_type |         created_at         |         updated_at         | account_id | from_account_id |   id
-------------+---------------+----------------------------+----------------------------+------------+-----------------+--------
      164815 | Favourite     | 2018-04-23 08:51:40.580158 | 2018-04-23 08:51:40.580158 |          1 |           11912 | 180009
(1 row)

chitter=> select * from favourites where id = 164815;
 created_at | updated_at | account_id | id | status_id
------------+------------+------------+----+-----------
(0 rows)
```

the notification appears in the web UI as only the header of a favourite notification

![2018-04-23t11-50-24-ooo0](https://user-images.githubusercontent.com/315139/39119644-ac212702-46ec-11e8-8fcf-52f274fd8954.png)

I checked the logs around the time of the notification but couldnt find anything relevant

**Comment by Gargron** [comment] 2018-04-23 10:04
Race conditions happen. Notifications have a polymorphic association which unfortunately does not support database-level constraints for data integrity. This stuff has happened, does happen, and will happen. I think there might be a couple open issues about this

**Comment by Gargron** [comment] 2018-04-23 10:06
Duplicate of #2865

**Closed by Gargron** 2018-04-23 10:06 UTC
