### ISSUE TITLE
My Federated Timeline is Empty

### ISSUE THREAD

**Issue by cumbiame** [tootsuite/mastodon#4952] opened 2017-09-14 18:53 UTC
Hey guys,
You guys have been awesome so far. Created an instance 2 days ago. But how do you get other intances to show in your federated timeline? Mine is empty. Did I forget to do something? 

Sorry if the question is basic. You guys have been great help already and I appreciate it very much.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by cumbiame** [comment] 2017-09-14 21:54
so I can only follow individuals, not a whole instance correct?

Thank you for your time by the way.

**Comment by Komic** [comment] 2017-09-15 07:00
By following bob@instance.example, your instance will federate with instance.example. You can't "force" a federation.

**Comment by Cassolotl** [comment] 2017-09-16 18:52
@cumbiame You could go to mastodon.social, and find some interesting people to follow from the public federated timeline on the About page. Once `@you@your.instance` follows some people from other instances, they'll show up in `your.instance`'s federated timeline.

You could also create an account on mastodon.social and follow `@you@your.instance`, just so that people in the mastodon.social public timeline will see your instance. When some people on mastodon.social are following `@you@your.instance` you can delete your mastodon.social account, safe in the knowledge that your `@you@your.instance`'s toots will continue to show up in the mastodon.social federated timeline because some people over there are following you. Or you could keep your mastodon.social account, because it can be good to have a backup!

Then, boost good things, boost interesting things, and follow interesting people that you see boosted into your home feed and federated timeline.

**Comment by wxcafe** [comment] 2017-09-21 00:43
Mind if I close this @cumbiame

**Comment by MasterGroosha** [comment] 2017-11-07 07:55
I've deployed Mastodon on my own instance, followed user from mastodon.social.

I see his profile, he has "113 toots", but when I open his profile from my instance, it's empty and nothing is shown in Global tab.
![default](https://user-images.githubusercontent.com/2780044/32482749-161aa456-c3aa-11e7-8568-cab0f8f204c8.png)


Sorry for Russian language on screenshot. The problem is his profile from my perspective is empty. Will I only see new toots? 
Using Mastodon 2.0.0

**Comment by wxcafe** [comment] 2017-11-07 12:18
Yes

Clément 'wxcafé' Hertling

**Comment by MasterGroosha** [comment] 2017-11-07 12:21
@wxcafe Sorry, I didn't understand you. "Yes" what?
I've created a separate issue: https://github.com/tootsuite/mastodon/issues/5610, which describes my comment better.

**Comment by wxcafe** [comment] 2017-11-07 12:29
sorry, I was still waking up. Yes, it's normal that you don't see anything because yes, you will only see new toots.

**Comment by wxcafe** [comment] 2017-11-07 12:29
It is also normal that you see toots from users who interact with users that you or users on your instance follow on your federated timeline

**Closed** 2018-04-08 19:27 UTC
Labels: question
