### ISSUE TITLE
New toot overwrites old toot.

### ISSUE THREAD

**Issue by ricardusvincencius** [tootsuite/mastodon#8716] opened 2018-09-17 22:23 UTC
When I compose a toot, and then get distracted by a notification, and hit reply, it over-writes my original toot. I would at the very least have it ask, or better yet cash the original toot, and once you've sent the 2nd toot, the original comes back.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment] 2018-09-18 02:05
Duplicate of #878

**Comment by ricardusvincencius** [comment] 2018-09-18 02:39
Duplicate

**Closed** 2018-09-18 02:39 UTC
