### ISSUE TITLE
Regression : some colors aren't customizable anymore

### ISSUE THREAD

**Issue by Naouak** [tootsuite/mastodon#2922] opened 2017-05-08 18:22 UTC
Introduced by #2912

Some colors are not customizable anymore.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment] 2017-05-08 18:45
Can you elaborate more on what you were doing before and what doesn't work now?

**Comment by Naouak** [comment] 2017-05-08 18:50
https://github.com/tootsuite/mastodon/blob/master/app/javascript/styles/variables.scss

````
$base-shadow-color: $black;
$base-overlay-background: $black;
$base-border-color: $white;
$simple-background-color: $white;
$primary-text-color: $white;
$valid-value-color: $success-green;
$error-value-color: $error-red;
````
None of those can be changed without modifying variables.scss when it was possible with custom.scss before.

**Comment by yookoala** [comment] 2017-05-10 08:06
Other than "custom*.scss", I think we should specifically have a `variables.scss` in `app/assets/stylesheets` to override variables. Here is the reason:

1. CSS rules comes later is always more powerful than sooner ones. Therefore `custom*.scss` should be imported / required after `application.scss`.
2. SCSS variables are inherits from **declarations before uses**. That means if you want to override a variable in `application.scss`, you should override before importing it.
3. You can use SASS / SCSS [`!default`](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_) syntax to have the default values declared after the overridden values.

So if I'm not mistaken, you cannot override scss variables in files after `applications.scss`. And you cannot override the result css rules in files before `applications.scss`.

So practically, the code in [pack/application.js](https://github.com/tootsuite/mastodon/blob/af6a84da147f4230807b37c64bc09760e6ab5055/app/javascript/packs/application.js#L6,L18) should in look something like this:
```javascript
require.context('../../assets/stylesheets/', false, /^variables.*\.scss/); // variable overrided here
import '../styles/application.scss';

//...
//...

require.context('../../assets/stylesheets/', false, /^custom.*\.scss$/);
```

And [javascript/styles/variables.scss](https://github.com/tootsuite/mastodon/blob/af6a84da147f4230807b37c64bc09760e6ab5055/app/javascript/styles/variables.scss#L15,L22) should looks like this:
```scss
// Variables for defaults in UI
$base-shadow-color: $black !default;
$base-overlay-background: $black !default;
$base-border-color: $white !default;
$simple-background-color: $white !default;
$primary-text-color: $white !default;
$valid-value-color: $success-green !default;
$error-value-color: $error-red !default;
```

The problem:
1. What the the naming rules for variable override files should be?
    (i.e. `variables*.scss` in my mock code)
2. We need to document this change for users who got used to just `custom.scss`.

**Comment by Naouak** [comment] 2017-05-10 08:32
Unless it has changed recently, `custom.scss` is a file that is loaded directly in replacement of `application.scss`. It should stay like that to permit to make a fully custom theme without modifying git files (and avoiding conflicts on update). See the [documentation](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Customizing.md).

Note that documentation should be updated too to reflect the name change in variables.

**Comment by yookoala** [comment] 2017-05-10 11:12
The program has been vastly changed since 1.3.3 and the documentation is no longer up-to-date for master branch.

**Comment by Naouak** [comment] 2017-05-10 12:45
It seems custom.scss is completely broken in current master (which is a major regression IMO). I can't test to verify but reading the code, I don't see any entrypoint for custom.scss. 

We should not change how it is working because there is already some instances completely changing the default css.

**Comment by mjankowski** [comment] 2017-05-10 13:03
I don't think this is related to the changes in https://github.com/tootsuite/mastodon/pull/2912 - I think it's related to this change -  https://github.com/tootsuite/mastodon/commit/f5bf5ebb82e3af420dcd23d602b1be6cc86838e1#diff-b7186ba040870c69d2ae394fa317ea64L22 - which used to insert custom.css when it existed, but now just always uses the application css.

**Comment by Naouak** [comment] 2017-05-10 13:12
Custom.scss is defined in the webpack package (not sure if it's a good idea): https://github.com/tootsuite/mastodon/pull/2617/commits/1aa7c105b5fb668e0dbe738a191683763dc914f4

The issue I was originally reporting is that some variables can't be redefined (as shown in one of my early comments in this issue).

**Comment by mjankowski** [comment] 2017-05-10 13:22
Right, so to summarize a previous comment -- before the variables+webpack changes, we were loading custom.css *instead of* application.css when it existed. This let custom.css do whatever it wanted to, including redefining any variable values, before the css was built.

With the webpack change, the custom css file is loaded *in addition* to the already loaded application.css.

This means that it can't redefine variables in a meaningful way.

It's not clear to me what the promises made about custom css were.

If the promise was "the application will insert your custom css file after everything else is loaded, so you can override styles by being the last loaded" - then I would argue that this is not a regression, and that the previously-working variable overriding was taking advantage of something which wasn't promised to exist.

If the promise was "we'll replace the application css with your custom css and you can control everything and either use or override the variables", then yes, the webpack changes are certainly a regression, because it changes that behavior.

Someone else ( @Gargron ?) will have to weigh in on what the intended behavior here was.

**Comment by Naouak** [comment] 2017-05-10 13:29
The documentation written for `custom.scss` was saying it replaced `application.scss` on loading the webpage.

**Comment by yookoala** [comment] 2017-05-13 09:43
@Naouak #2987 has been merged.

You can now override the variables in `app/assets/stylesheets/variable*.scss`. but if you want to add your own custom scss rules, you're recommended to use `app/assets/stylesheets/custom*.scss`.

**Comment by nolanlawson** [comment] 2017-05-23 01:43
I was confused about what I needed to change in `custom.scss` to upgrade to 1.4, so here's what I figured out from https://github.com/tootsuite/mastodon/commit/b85dec2b976e0bea9f7a3ede832f3c8e16c8e2ef.

New color names are:

```scss
$ui-base-color: $color1;
$ui-secondary-color: $color2;
$ui-primary-color: $color3;
$ui-highlight-color: $color4;
$base-border-color: $color5;
$simple-background-color: $color5;
$primary-text-color: $color5;
$error-value-color: $color6;
$valid-value-color: $color7;
$base-shadow-color: $color8;
$base-overlay-background: $color8;
```

I couldn't actually get `custom.scss` itself to work, so instead I just preprended this to `application.scss`. If you want a working example, here's [what I had before](https://github.com/tootcafe/mastodon/blob/8b3c49a48522188fb25de7abc063fa9420b8ad7c/app/assets/stylesheets/custom.scss) for toot.cafe and [here's what I had after](https://github.com/tootcafe/mastodon/blob/c094e5202eea712a701e52587652c2e04357f3cc/app/javascript/styles/variables.scss).

**Comment by beatrix-bitrot** [comment] 2017-05-23 02:18
@nolanlawson this is not the first I've heard of this problem with the custom scss and having to modify application.scss and i kinda think this is NOT something admins should have to do, much less figure out for themselves on upgrading

if there's not an existing issue for this (having to do this as part of the upgrade specifically) can you maybe make one? I think it's a kink in the process that should really be fixed before 1.4 is rolled out for real

**Comment by yookoala** [comment] 2017-05-23 03:32
For variables, please use `variables.scss` instead of `custom.scss`.

**Comment by jpfox** [comment] 2017-05-23 20:47
I don't understand where to put css customization now.
I was using app/assets/stylesheets/custom.scss but in v1.4rc3 webpack precompilation fails.
I tried with custom.css and application.css (in same folder), precompilation works but css code is not embedded in assets pack.
Will there be a solution in 1.4 final release ?
Thanks for your help

**Comment by esetomo** [comment] 2017-05-24 00:22
I wrote app/assets/stylesheets/variables.scss, but the variables do not seem to reflect.
The CSS rules in app/assets/stylesheets/variables.scss was output.
It seems that require() in app/javascript/mastodon/main.js is handled separately and the resulting CSS is concatenated.

**Comment by nolanlawson** [comment] 2017-05-24 02:36
I have a working example in my comment above, does that help? I agree with @beatrix-bitrot though that it's annoying that custom.scss no longer works and that you have to manually upgrade.

**Comment by jpfox** [comment] 2017-05-24 07:57
I've found how to compile app/assets/stylesheets/custom.scss
@import 'application'; is no more needed. You can put directly your css customization in it.

Example of a app/assets/stylesheets/custom.scss : (to extend columns on wide screen)

    @media screen and (min-width: 1025px) {
      .columns-area>div
      {
        width: 24.9%;
      }
    
      .columns-area>div>.column,
      .columns-area>div>.mastodon-column-container>.column
      {
        width: 99.5%;
      }
    }

**Comment by Gargron** [comment] 2017-05-25 21:38
@Naouak @yookoala @jpfox @esetomo Can you check if #3314 does it for you?

**Comment by nightpool** [comment] 2017-05-26 01:20
@mjankowski  The promise of custom.scss was a total conversion (you could write your own css completely)

nearly every custom.scss has variable definitions, `@import "application"`, and then style definitions. #3314 is a good alternative here, but it's pretty confusing for admins: two files, instead of one, tracked by git now. additionally, there's less flexibility for total conversion stuff—you have to override everything, instead of styling from a blank slate

**Comment by jpfox** [comment] 2017-05-26 13:15
@Gargron I've checked #3314 by moving app/assets/stylesheets/custom.scss to app/javascript/styles/customizations.scss
But css customization is not applied :-(

**Comment by mjankowski** [comment] 2017-05-26 14:28
Possible interim "solution" to this:

- Revert back to using asset pipeline for css, which would preserve the "custom.css will override when present" behavior.
- Keep webpack in place for JS assets
- Leave open the future possibility of changing this again if we figure out a better way to do it

As it is now, I do think that the breakage here is large enough that it will be an issue for instances with a lot of customization. As a side effect - the variable renaming will be less of an issue to deal with if we keep the asset pipeline and previous override behavior around.

**Closed** 2017-05-27 14:55 UTC
Labels: bug, deployment

**Comment by jpfox** [comment] 2017-05-29 11:10
Sorry, but I don't understand how custom.css is used now :-(

I've installed v1.4.1 and create a live/app/assets/stylesheets/custom.css with same content as I described in https://github.com/tootsuite/mastodon/issues/2922#issuecomment-303647692 but it is not integrated by assets precompilation.
Is my file has the right name, and is in right directory ?

Thanks for details

**Comment by jpfox** [comment] 2017-05-29 11:39
Ok, I've found my error in [customizing doc page](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Customizing.md).
I've forgotten to create custom.js.
For other admins encountering trouble for customizing just few css to overrides standard application css : 

- Create app/javascript/packs/custom.js with two lines `require('../styles/application.scss');` and `require('../styles/custom.scss');`
- Create app/javascript/styles/custom.scss with your css snippet
- Recompile your assets
- Restart Mastodon web service
