### ISSUE TITLE
Scroll down to clicked toot when opening a thread

### ISSUE THREAD

**Issue by AbelToy** [tootsuite/mastodon#1725] opened 2017-04-13 20:47 UTC
If there's a long thread involving many toots, clicking a toot should automatically scroll there when opening the thread, instead of just staying at the top.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment] 2017-04-14 06:25
I generally like to read threads from the top down, even if they're quite long. Maybe an option could be implemented to automatically scroll?

**Comment by AbelToy** [comment] 2017-04-14 13:22
yeah, but when you're clicking for a thread you've already read part of, it gets annoying

**Comment by hoodiek** [comment] 2017-04-21 19:53
this is a duplicate of #471

advise closing.

**Comment by ashfurrow** [comment] 2017-04-22 16:31
Agreed, going to close. Let's move discussion to https://github.com/tootsuite/mastodon/issues/471 everyone. Thanks!

**Closed by ashfurrow** 2017-04-22 16:31 UTC
Labels: enhancement, help wanted, priority - medium, ui
