### ISSUE TITLE
Indicator when new content in column is added but the user is scrolled down

### ISSUE THREAD

**Issue by Gargron** [tootsuite/mastodon#38] opened 2016-09-16 21:32 UTC

**Comment by swaldie** [comment] 2016-12-05 21:35
There's a user request in #277 to have the feed stop automatically loading new toots while the user is scrolled down.  I closed that as a duplicate of this but I'm adding the comment here so the user's suggestion isn't lost.

**Closed** 2017-02-20 23:11 UTC
Labels: enhancement
