### ISSUE TITLE
Profile hashtags

### ISSUE THREAD

**Issue by m4sk1n** [tootsuite/mastodon#5578] opened 2017-10-31 23:24 UTC
In profile descriptions, hashtags should link to page with list of other people using the same hashtag, that would be nice way to find interesting people. It seems to be easy to implement, but does it make sense?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThisIsMissEm** [comment] 2018-04-11 21:36
This seems like a duplicate of https://github.com/tootsuite/mastodon/pull/7094 and related to https://github.com/tootsuite/mastodon/pull/6645

**Comment by Gargron** [comment] 2018-04-12 00:43
How would accounts-in-hashtag be sorted in the results? There's no clear relevance metric. On the other hand, if it's designed more like an A-Z directory, that would work...

**Comment by ThisIsMissEm** [comment] 2018-04-12 01:45
We could sort by recent activity or number of toots + followers as a signal indicating relevance.

**Closed** 2018-12-06 16:36 UTC
Labels: suggestion
