### ISSUE TITLE
Can't mention users at another federations

### ISSUE THREAD

**Issue by gummipunkt** [tootsuite/mastodon#13155] opened 2020-02-26 08:41 UTC
### Actual behaviour

1) toot "@bla@chaos.social": method=POST path=/api/v1/statuses format=html controller=Api::V1::StatusesController action=create status=404 duration=136.42 view=0.51 db=10.74

2) toot "bla@chaos.social": method=POST path=/api/v1/statuses format=html controller=Api::V1::StatusesController action=create status=200 duration=192.69 view=72.63 db=33.47

### Steps to reproduce the problem

Mentioning users at other federations

### Specifications

v3.1.1

**Comment by ThibG** [comment] 2020-02-26 09:59
Closed as a duplicate of #13154 since the root cause is the same

**Closed by ThibG** 2020-02-26 09:59 UTC
