### ISSUE TITLE
Profiles on a remote instance don't show full follow count or toot list

### ISSUE THREAD

**Issue by wolfteeth** [tootsuite/mastodon#1037] opened 2017-04-06 07:05 UTC
When I'm logged in on an instance, and visit the profile of a user on a remote instance, their following and follower counts (and lists) appear to reflect only the subset of users in my instance, even though they have followers from other instances. Their toot list is sometimes incomplete as well.

The (incorrect) follow numbers have a '*' next to them in the web interface, which is confusing as there is no explanatory text.

Exploration amongst instances should be seamless for the user who potentially has contacts on many instances.

**Comment by wirehack7** [comment] 2017-04-06 08:30
Encountering the same problem. Also not seeing any profile pictures from other instances of users whom I don't follow.

I am seeing error `Status because: Validation failed: Username has already been taken` kinda often in *sidekiq* log when it tries to pull info from remote user.

**Comment by Technowix** [comment] 2017-04-06 08:47
Having a similar problem here, profil won't load even if we follow them/ they toot after we follow.
I can see the post-follow toots, but the profile load only if the user interact with us : https://niu.moe/@Technowix/1885

Also, no error on sidekiq/logs :|

**Comment by DeadSuperHero** [comment] 2017-04-06 08:56
This is actually a pretty big problem with adding people from other servers - you have to wait for new posts to start coming in.

Is there a way that Webfinger could fetch a manifest of public posts?

**Comment by Technowix** [comment] 2017-04-06 08:57
@DeadSuperHero That not the issue here tbh.
But yeah, I agree that would be cool to crawl instances a bit to provide federated content to users.

**Comment by DeadSuperHero** [comment] 2017-04-06 09:02
You're right, thinking on it further these fall under two categories that are loosely related. Regardless, it might make sense to periodically pull updated information on a profile after following it or looking it up - and that might affect counts as well as content.

**Comment by Gargron** [comment] 2017-04-06 13:51
Question to people in this thread experiencing this problem on their instances - is your Sidekiq processing the "pull" queue?

**Comment by Technowix** [comment] 2017-04-06 14:22
Yup, that it right ? :
![screen shot 2017-04-06 at 16 21 59](https://cloud.githubusercontent.com/assets/1571367/24759250/32c8cc36-1ae5-11e7-97f4-34daeaf401af.png)

**Comment by Technowix** [comment] 2017-04-06 15:29
Catched somes errors, if this help @Gargron .
![screen shot 2017-04-06 at 17 28 10](https://cloud.githubusercontent.com/assets/1571367/24762374/76521314-1aee-11e7-97cb-c0b9e4d85701.png)
Seem like timeout, the tasks are too long...

**Comment by wirehack7** [comment] 2017-04-06 16:02
Mine is processing the queue. Errors are occuring because some instances are offline sometimes (like securitymastod.one). So these time out as in their nature.

**Comment by RX14** [comment] 2017-04-06 16:08
I have this issue but I don't see anything in any queues. Maybe I just don't know how to read sidekiq right?

![](https://aww.moe/cl0kzn.png)

Yet I still can't see profile pics or bios of toots who are federated indirectly (boosted, replied to, etc). I can see when I manually input a URL into the search tool however.

**Comment by Cassolotl** [comment] 2017-04-08 13:36
This is something me and a few other users have just been talking about, and one person suggested I copy-paste their words about this issue over here:

>Thing is, I have extensive experience with decentralised systems, and they don't surprise me.  This one is constantly surprising me with what it does - and doesn't - do, and my experience tells me that this will be a significant stumbling block for people who expect things to "just work".  I suspect it will hinder adoption significantly.

>You say clicking through to their profile on their instance is easy, but it's not obvious to me. Why isn't clicking on their name the same thing?  It's opaque as to the existence of a difference, let alone what the difference is.

>Now that you've told me about it I've tried clicking on a few things that don't look like links and I've found it. Not knowing, associated with non-discoverability, makes the system somewhat user-hostile.

**Comment by wolfteeth** [comment] 2017-04-08 19:18
I've never been able to figure out how to get to a remote user's home instance profile without just typing in the expected URL in a different tab. I think that should be the default when I click a remote user profile, display current content from the remote instance.

If the remote is down, I'd rather know the remote isn't responding (show an error saying it's down, try again later) than see cached(?) data and not know it's incomplete.

**Comment by rhaamo** [comment] 2017-04-08 21:24
I was investigating my issue about profiles being "empty" and have this error too
```
Nothing was saved for tag:oc.todon.fr,2017-04-08:objectId=124231:objectType=Status because: Validation failed: Username has already been taken
```
or
```
ActiveRecord::RecordInvalid: Validation failed: Username has already been taken
```

I have the four queues, but I can see the "failed" counter in sidekiq grow... but sidekiq doesn't let investigate with more infos, and the logs, varying for the flow of events are somewhat mixed...

I can also see:
```
Apr 08 23:18:22 masto-web bundle[5784]:  (7.4ms)  BEGIN
Apr 08 23:18:22 masto-web bundle[5784]: Account Exists (1.8ms)  SELECT  1 AS one FROM "accounts" WHERE "accounts"."username" = $1 AND "accounts"."domain" = $2 LIMIT $3  [["username", "xxx"], ["domain", "toot.cat"], ["LIMIT", 1]]
Apr 08 23:18:22 masto-web bundle[5784]:  (7.0ms)  ROLLBACK
Apr 08 23:18:22 masto-web bundle[5784]: Nothing was saved for tag:unixcorn.xyz,2017-04-08:objectId=44762:objectType=Status because: Validation failed: Username has already been taken
```
But maybe unrelated.

I don't see what's wront with profiles right now. For most of them click on it or searching the user load them but any "new" profile I can see are empty.

**Comment by Lertsenem** [comment] 2017-04-08 21:31
(Isn't that the same as #830?)

**Comment by rhaamo** [comment] 2017-04-08 21:35
I don't have issues with posts it seems.
Only profiles as reported by @wirehack7 but I don't know.
The bug I am experiencing should be fixed (but I'm still experiencing it)
But in the same time I seems to have the same one according to some logs as this issue (reported by @wirehack7 )

**Comment by kballard** [comment] 2017-04-08 22:11
I'm having this same issue. I just set up a new single-user instance, and followed ashfurrow@mastodon.technology. Looking at his profile on his site, he has 289 toots. Looking at it from a different instance, I see 115 toots. Looking at it from my brand new instance, I see 0 toots. So it's definitely not back-filling any info. I also checked Sidekiq, there's 0 failures and it's currently idle, with nothing in the queue.

**Comment by cybercatgurrl** [comment] 2017-04-13 07:10
@kballard I'm certainly getting the same behavior on my instance. The only content that's filled out is content created after I interact with that account.

**Comment by Angristan** [comment] 2017-04-13 08:38
I'm having this behavior, too. But is this a bug ? Because every single instance have the same behavior

**Comment by RX14** [comment] 2017-04-13 11:54
The existence of a "pull" redis queue makes me believe that *some* pulling of data is supposed to happen, however I'm unsure as to exactly which data it's meant to pull when. Maybe @Gargron can clear this up.

**Comment by ivansafrin** [comment] 2017-04-16 19:03
Same behavior on our instance as well.  If I click on a profile I follow within the page, I see the number of posts from the time I started following them, none of their follows and just myself as the only follower. (If I click on their profile page, all the actual counts are there).

**Comment by KellerFuchs** [comment] 2017-04-17 02:32
`mastodon.ninetailed.uk` seems to also exhibit the behaviour.

**Comment by Artoria2e5** [comment] 2017-04-18 01:52
Is it possible, though, to reply to an arbitrary toot with its remote URL given? If someone could give me some workaround like that I would be happier with what I got for now...

**Comment by jamesmwright** [comment] 2017-04-20 05:34
I am having this issue with my single instance too. When I view people, I see no toots or follows/followers, until I start interacting with them. Has this been fixed? I'm on v1.2.2.

**Comment by hugoestradam** [comment] 2017-04-28 14:44
I joined mastodon today. I am seeing this error. It is disorienting.

**Comment by stragu** [comment] 2017-04-29 01:58
One example: I **follow** [studiodessai@framapiaf.org](https://framapiaf.org/@studiodessai) (6 toots and 4 followers currently) but I only see 2 posts and 2 followers when looking at their profile from my account [stragu@mastodon.indie.host](https://mastodon.indie.host/@stragu).

Could it have something to do with differing versions? I am not sure how to check for versions (it would be great to see it on listed on https://instances.mastodon.xyz/list).

**Comment by wolfteeth** [comment] 2017-04-29 02:31
I think it is specifically to do with federation. It only shows you toots that were sent to your instance - which can happen for a few different reasons, the most obvious being someone on your instance started following them. But federation only starts after the following starts - earlier toots won't show up.

I imagine the reason why the follower/following counts are wrong is the same. It's only the people following/followed on your instance.

I'm not sure of the reason. Maybe the goal is to avoid putting too much strain on remote servers? It's confusing though.

**Comment by BrunoSpy** [comment] 2017-04-30 10:09
Is this linked to #2613 ?
I'm not talking about toots that are not visible, but toots that are definitively missing.
Explanations :
Account 1 on instance 1 (brunospy@metal.odon.space)
Account 2 on instance 2 (brunospy@mastodon.social)
Account 3 on instance 2 (brunospy@quitter.se)
Each accounts following the others
* account 1 posts a toot
* the toot doesn't appear in the timeline of account 2
* the toot appears ine the timeline of account 3

**Comment by andrejsavikin** [comment] 2017-08-20 09:39
Can confirm similar behavior. I made a mastodon instance and followed someone on the federation, and waited for them to toot something new so it shows up on my instance. I then shut down the instance completely(keeping the databases) and reopened it after a couple of days. His toots from the point of re-starting the instance and onwards appeared, but his toots during the downtime didn't get re-synced.

**Comment by Gargron** [comment] 2017-09-08 11:51
Backloading of toots is not fixed by this, but counts are now more correct thanks to #4840

**Comment by deutrino** [comment] 2017-11-28 19:20
I cannot find an issue regarding backloading of toots specifically, does anyone know of one?

This and #3307 are partial duplicates. I proposed a way of improving follow counts in #3307. However, in my view backloading of toots is of equal or greater importance.

Should we change this issue title, or open a new issue (if one does not exist), purely to discuss backloading of toots? I believe my proposal in #3307 could be leveraged as part of the solution to backloading of toots.

**Comment by schmittlauch** [comment] 2017-12-01 16:11
@deutrino #34 looks quite relevant for that.

**Comment by nightpool** [comment] 2018-02-25 00:23
duplicate of #34

**Closed by nightpool** 2018-02-25 00:23 UTC
Labels: bug, requires in depth
