### ISSUE TITLE
Tooltip of DM's icon (envelope) says "Boost"

### ISSUE THREAD

**Issue by eidolies** [tootsuite/mastodon#2049] opened 2017-04-18 00:15 UTC
Thought it might better say "DM" or "Direct", since you can't boost a DM.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [I'm a user so I don't worry about this] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ashfurrow** [comment] 2017-04-18 12:40
Looks like this might be a duplicate of https://github.com/tootsuite/mastodon/issues/1394

**Closed** 2017-04-18 19:36 UTC
Labels: enhancement, priority - low, ui
