### ISSUE TITLE
Getting context for a thread

### ISSUE THREAD

**Issue by thor-the-norseman** [tootsuite/mastodon#1995] opened 2017-04-17 11:53 UTC
After discussions with Amaroq's author about the lack of a "view all statuses in a conversation, not only its direct ancestors and descendants" feature in his client, he has opted to NOT fix this, because he thinks that, for instance performance and scaling reasons, a single context request should be able to fetch this information.

In the web app, I believe one can click the top post in the thread in order to view the entire conversation. This is still one more click than I think is necessary, since 90% of the time, stuff has happened elsewhere in the larger thread that you don't want to miss out on, even if you weren't tagged directly.

Now, perhaps Amaroq could just implement this extra click in order to fetch a context for that post, but I don't see the harm in eliminating the extra click and the extra API request. Fetching the full context is probably less taxing on an instance than processing an entire new API request, which will return much duplicated information anyway.

EDIT: Original Mastodon thread: https://snabeltann.no/@thor/27784

**Comment by thor-the-norseman** [comment] 2017-04-17 12:49
Original Mastodon thread:
https://snabeltann.no/@thor/27784

**Comment by d4a11n** [comment] 2017-04-28 12:39
I was going to create a new issue, but this is related:

Can ancestors_count and descendants_count be added to the Status json returned by the api?  reblogs_count and favourites_count exist in the Status json, but you need to call api/v1/statuses/:id/context to see if there are replies.

**Comment by Gargron** [comment] 2017-06-30 14:32
Duplicate of #731

**Closed by Gargron** 2017-06-30 14:32 UTC
Labels: api, enhancement, priority - medium
