### ISSUE TITLE
error throttled after login try

### ISSUE THREAD

**Issue by jonazc** [tootsuite/mastodon#6149] opened 2018-01-01 22:00 UTC
I just created a new account on mastodon.social. After I tried to login, I got a white page with the "error message" 

`{"error":"Throttled"}`

the first 5 times I tried to login. The 6th time it worked suddenly.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment] 2018-01-02 00:37
Duplicate of #1017.

**Closed by ykzts** 2018-01-02 00:37 UTC
