### ISSUE TITLE
Toots that start with a @mention without being replies are displayed on the profile

### ISSUE THREAD

**Issue by nclm** [tootsuite/mastodon#8564] opened 2018-09-02 08:46 UTC
…even though they are addressed to a specific person.

- [x] I searched or browsed the repo’s other issues, but I can’t ensure this is not a duplicate since it was not evident to find the rights keywords.

A user can posts toots starting with one or several @mentions, without clicking on reply, in order to start a conversation with someone. On their profile, I expect them to be filed under “Toots and replies”, as they are not interesting to anyone else than the person⋅s mentioned (without necessarily having to be private). However, they are displayed like any other public toot, on the default “Toots” tab.

This also gets me wondering how they are displayed in their followers’ timeline. As a the poster, I expect them to be only displayed to my followers following both the recipient and me. Seeing how it is displayed on the profile, I’m now afraid they are displayed to every followers, including the ones that has no interest in these messages.

**Fix:** treat anything starting with a @mention like a reply.

**Comment by trwnh** [comment] 2018-09-02 19:45
Duplicate of #8311

**Comment by nclm** [comment] 2018-09-02 20:03
Indeed, thanks!

I think the issue needs more discussion. And examples. If most of the toots starting with @ uses it as a subject, then no change needed. But if most of the toots starting with @ uses it as an apostrophe, then we should reconsider.

For me it’s very counter intuitive. It also means that there is no way to write to someone if not replying to them. As for publicly writing about someone, there is an usage on Twitter to prefix it with a dot (.@mention) or simply to write the sentence differently.

**Closed** 2018-10-09 22:08 UTC
