### ISSUE TITLE
Link previews not shown outside of individual toot detail view

### ISSUE THREAD

**Issue by daprice** [tootsuite/mastodon#1495] opened 2017-04-11 00:32 UTC
Currently link previews are only shown in the detail view for a particular toot (i.e. when clicking on a toot to show it in the right column). I'd like to request that they also be shown inline anywhere toots are displayed, such as in the timeline, notifications list, user profiles, etc.

My rationale is that the previews are more informative than raw URLs, more visually appealing, and easier for a human to parse when looking through a timeline. Since they are a fixed size, they shouldn't clutter the timeline any more than images, which are already displayed inline in the timeline and everywhere else.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment] 2018-02-26 22:16
I think this might be a duplicate of *URL unfurling in timeline? #819* ?

**Closed** 2018-10-28 05:35 UTC
Labels: suggestion, ui
