### ISSUE TITLE
Wrong status, weird like

### ISSUE THREAD

**Issue by krainboltgreene** [tootsuite/mastodon#5074] opened 2017-09-24 06:42 UTC
Got a like on a status, that status isn't the actual one I'm looking at.

![a](https://user-images.githubusercontent.com/334809/30780130-d0f3522e-a0b8-11e7-97dc-03c0c6528c7a.PNG)
![b](https://user-images.githubusercontent.com/334809/30780129-d0f2672e-a0b8-11e7-88b8-c36efd7af492.PNG)
![c](https://user-images.githubusercontent.com/334809/30780131-d0f3e4e6-a0b8-11e7-98a0-de307b19ab45.PNG)
![d](https://user-images.githubusercontent.com/334809/30780132-d0f44a26-a0b8-11e7-9996-8e42d6606e7d.PNG)

(mastodon.social)

**Comment by Gargron** [comment] 2018-10-22 23:13
I don't think this happened since and might have been caused by a really old bug, so closing.

**Closed by Gargron** 2018-10-22 23:13 UTC
Labels: bug
