### ISSUE TITLE
Groups Feature

### ISSUE THREAD

**Issue by leandrosalvador** [tootsuite/mastodon#13130] opened 2020-02-23 04:37 UTC
Groups feature

### Pitch

Groups would be a simple but powerful improvement to Mastodon. Any user of an instance could create or join a group. A group have a name, a description, an avatar, a cover, a user creator, users joined, and the toots published to the group by its joined users.

The toot published to a group appears both in the group timeline and in the user timeline. It's a two-dimensional view: group followers and user followers.

The groups in which the user is joined would appear near the lists created by him/her.

### Motivation

I think this resource would be a definitively revolution in Mastodon. It's something like groups were in Orkut: it was the heart of that community.

Mastodon already has the Local view. Groups would be like a very specific sub-Local aggregation of toots based on themes/subjects created by the instance users, something more specific than all the toots available in the Local instance visualisation tab based on their very specific interests.

For example, an instance which the main theme is data science and data visualization (like vis.social, for ex.). Some toots could be more to Python buddies, and others more to R people. The vis.social instance's users could create groups and share toots between themselves about Python and R in their very specific groups, empowering the community sharing of content and change of ideas.

**Comment by Cassolotl** [comment] 2020-02-25 22:41
Duplicate of *Support groups #139* from November 2016.

**Comment by ykzts** [comment] 2020-02-26 00:54
Duplicate of #139

**Closed by ykzts** 2020-02-26 00:54 UTC
