### ISSUE TITLE
Shouldn't be able to send a DM without any mentions

### ISSUE THREAD

**Issue by enterprisey** [tootsuite/mastodon#7635] opened 2018-05-27 06:51 UTC
The "Toot" button should be disabled if the privacy level is "Direct" and nobody's mentioned.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Tagadda** [comment] 2018-05-27 07:33
Duplicates #4885

**Comment by ykzts** [comment] 2018-05-27 07:55
Duplicate of #4885

**Closed by ykzts** 2018-05-27 07:55 UTC
Labels: duplicate
