### ISSUE TITLE
Boost but add a content warning

### ISSUE THREAD

**Issue by LloydScottUni** [tootsuite/mastodon#15599] opened 2021-01-19 11:46 UTC
### Pitch

Add an option when boosting a toot to add a content warning.

### Motivation

Sometimes you want to boost a toot which needs a content warning but doesn't have one. It'd be nice to be able to add one when boosting.

**Comment by ThibG** [comment] 2021-01-20 09:09
Duplicate of #13291 and #2719

**Closed by ThibG** 2021-01-20 09:09 UTC
