### ISSUE TITLE
Quote Toots

### ISSUE THREAD

**Issue by irlcatgirl** [tootsuite/mastodon#12753] opened 2020-01-03 19:12 UTC
The Mastodon Web Client does not have a quote button and rather requires you to reply to a users toot directly rather than adding a comment on top. Arguably this prevents some forms of harassment but is a feature many miss from Twitter. If you link to a toot in a toot an open graph preview already generates. I propose adding the following:

- A quote toot button in Mastodon-FE
- A ping back that notifies users when a toot has been posted.

Right now the Open Graph behavior just results in “sub-toots” where the user doesn’t know they’ve been quoted and has no ability to respond if they’ve been criticized by another user unless someone shows them the quote toot. It may even lead to more toxic behavior than we see on Twitter due to the stealth nature of it.

I wrote about the behavior at https://lgbtqia.is/@catgirl/103420943539457706

Thoughts?

**Comment by nuklearfiziks** [comment] 2020-01-03 19:21
Possible duplicate of #309?

My feeling is that quote retweets dramatically worsened the discourse on Twitter and I'm pretty strongly opposed to any such functionality being added to Mastodon, though it's possible that people's positions on this have changed.

**Comment by catgirlsec** [comment] 2020-01-03 19:46
> Possible duplicate of #309?
> 
> My feeling is that quote retweets dramatically worsened the discourse on Twitter and I'm pretty strongly opposed to any such functionality being added to Mastodon, though it's possible that people's positions on this have changed.

The issue is that quoting is already possible by copying a link. The user doesn’t even have to click it to see the preview. This change would do two things:

- Improve UX and workflows
- Give users an opportunity to respond to criticism and reduce subtooting

It may also end the screenshots problem. With a proper quote system users are able to delete their posts freely. With screenshots it’s preserved forever or at least until instance owners stop paying their bills.

Making it harder to quote doesn’t remove the negative aspects of quoting or solve the problem at best it’s a bandaid that covers up the problem and pretends it doesn’t exist. This is the equivalent of disabling mentions because people
might use them to bully others. Mastodon is a tool, it’s up to instance admins to stop abuse of it.

**Comment by Shleeble** [comment] 2020-01-04 03:36
The image shown above looks quite clean and I'd be keen to see how this could be rendered in the webapp.

I support making toots more dynamic using quoted toots.

**Comment by trwnh** [comment] 2020-01-04 06:18
>Improve UX and workflows

The friction is intentional, to discourage exactly that behavior. If you want someone to see something, mention them. If you want to talk about something they posted, reply to that.

And yes, this is a duplicate of #309

**Comment by catgirlsec** [comment] 2020-01-04 06:23
> > Improve UX and workflows
> 
> The friction is intentional, to discourage exactly that behavior. If you want someone to see something, mention them. If you want to talk about something they posted, reply to that.
> 
> And yes, this is a duplicate of #309

Why should users be coerced into replying to a toot rather than quoting it? Often arguing with someone won’t change anything and the reply feature isn’t the best way to go about it.

**Comment by trwnh** [comment] 2020-01-04 06:46
>Often arguing with someone won’t change anything and the reply feature isn’t the best way to go about it.

Neither will posting to your followers about it.

**Comment by catgirlsec** [comment] 2020-01-04 15:58
Next argument: Like it or not, not everyone uses alt tags. It’s worse of a problem on mobile apps where OCR isn’t possible yet. If someone takes a screenshot and doesn’t add alt text visually impaired people can’t participate. Opposed to a proper quotes system where they can. Enabling quotes would improve accessibility. Should add it’ll save ever so slightly on media storage and bandwidth.

**Comment by catgirlsec** [comment] 2020-01-04 19:47
Oh I should point out the Mastodon Twitter makes great use of Quote Tweets:

- https://twitter.com/MastodonProject/status/1206933919402283008
- https://twitter.com/MastodonProject/status/1206784223471919104
- https://twitter.com/MastodonProject/status/1205924718337036297

So Mastodon Devs can't be entirely against quoting otherwise they to would reply instead of "being anti-social"

**Comment by wakest** [comment] 2020-01-04 21:34
There are already forks of mastodon that have implemented quote posts like fedibird.com
here is an example of the admin of the instance quoting Gargron
https://fedibird.com/@noellabo/103411167299803486

I am very keen to see this feature being implemented in mainline. It is the job of the community and mods to decide how this feature is used and abused. Not having it does not solve the problem we are trying to prevent. And I don't think it even lessons the problem, it may but I have not seen any evidence that it has as people are constantly subposting eachother and screenshotting eachother and just using links to do the same thing in a less visually appealing and user friendly way.

**Comment by catgirlsec** [comment] 2020-01-04 21:44
> There are already forks of mastodon that have implemented quote posts like fedibird.com
> here is an example of the admin of the instance quoting Gargron
> https://fedibird.com/@noellabo/103411167299803486
> 
> I am very keen to see this feature being implemented in mainline. It is the job of the community and mods to decide how this feature is used and abused. Not having it does not solve the problem we are trying to prevent. And I don't think it even lessons the problem, it may but I have not seen any evidence that it has as people are constantly subposting eachother and screenshotting eachother and just using links to do the same thing in a less visually appealing and user friendly way.

Yup it's another example of software pretending human problems will go away if they make bad behavior slightly more difficult. Not to mention the hypocrisy involved here:

- Mastodon Admins: Quoting is bad and anti social (Context: https://lgbtqia.is/@catgirl/103420943539457706)
- Also Mastodon Admins: Look at our quotes on Twitter. (Context: above links)

**Comment by codesections** [comment] 2020-01-05 01:42
I agree @nuklearfiziks that quote-tweets significantly worsened Twitter and introducing them to Mastodon risks similar negative effects.  Indeed, I view the *lack* of quote tweets as one of Mastodon's killer features and have for a long time—I first [blogged about the lack of quote-tweets](https://www.codesections.com/blog/mastodon-elevator-pitch/) back in August of 2018.)

As I said back then:
> One of the most pernicious parts of Twitter is how people will quote-tweet something dumb, offensive, or awful that an opponent said, along with a message mocking that opponent. Over time, this leads people on all sides of an issue to see only a distorted caricature of their opponents, comprised of an amalgam of all the worst features of that group.   (This phenomenon of cherry-picking the worst bits of an opposing group exists independently of Twitter, but Twitter makes it much, much worse.)

Engaging with someone via a reply is great—I'm all for dialog.  Gossiping about someone behind their back is frequently puerile, but doesn't tend to do much harm.  But if someone publicly criticizes an opponent *and* notifies the opponent of the criticism (and thus invites a response) … well, I can't think of a faster road to toxicity. 

> Right now the Open Graph behavior just results in “sub-toots” where the user doesn’t know they’ve been quoted and has no ability to respond if they’ve been criticized by another user unless someone shows them the quote toot.

IMO, subtoots are rude and should be discouraged.  But—precisely because they *don't* encourage the other user to reply—they don't lead to the type of toxic behavior that drove many away from Twitter and to Mastodon.

**Comment by trwnh** [comment] 2020-01-05 03:02
>not everyone uses alt tags. If someone takes a screenshot and doesn’t add alt text visually impaired people can’t participate.

So don't post screenshots without alt text, then?

>Enabling quotes would improve accessibility.

No it would not. It would incentivize a lot of terrible things because it would be too prominent and easy.  This has been discussed in #306 and in https://blog.joinmastodon.org/2018/07/cage-the-mastodon/ as well. The following are all inaccessible or otherwise toxic behaviors that "quote boosting" would create:

- Broken threads (because it's just a link instead of an actual reply)
- Nested quotes (you can quote a quote and end up with a massive onion of posts that's a nightmare to read in reverse order)
- Performativeness (you are now posting to your followers instead of engaging with the person whose post you have quoted, which is bad for conversational usage and incentivizes soapbox behavior)

There absolutely should not be a one-click button for this kind of behavior. Replies scale. Inline quotes do not. Have you ever seen old Tumblr posts with blockquotes stretching off the page? There's a reason why Tumblr redesigned its reblogs to be flat and linear instead of continuing to use nested blockquotes.

>Oh I should point out the Mastodon Twitter makes great use of Quote Tweets [...] So Mastodon Devs can't be entirely against quoting otherwise they to would reply instead of "being anti-social"

Those are not the same people, and I think you'll find plenty of people have issues with the way the twitter account is run, too... Still, even from the examples you used, I would say that those are performative. "Look at this person being awful" is not something that should be more prevalent. Constantly pushing awful people into the spotlight is something that becomes too easy and too rewarding if you give people a button to do exactly that. Yes, you can highlight good people by quoting them, too, but this still leaves the issue of broken threads and nested quotes. It should be a reply. If you want your followers to see it, boost that reply. If you think that's too much or not appropriate, then the friction has worked in discouraging behavior.

>software pretending human problems will go away if they make bad behavior slightly more difficult.

The problem doesn't go away. It just becomes less common, which is still a good thing. And the human element should be used to bridge that gap. This is just my opinion, but moderators should discourage or moderate against screenshot usage as well, where appropriate. If people are being abusive, then it doesn't matter what they're using to do it -- moderate against that. That doesn't mean making it easier to perform actions with less thought.

---

>I am very keen to see this feature being implemented in mainline. [...] And I don't think it even lessons the problem, it may but I have not seen any evidence that it has as people are constantly subposting eachother and screenshotting eachother

Except:

> just using links to do the same thing in a less visually appealing and user friendly way.

It is, as you say, less user friendly. If it were more user friendly and more visually appealing, then more people would do it.

**Comment by Cassolotl** [comment] 2020-01-05 10:48
>> not everyone uses alt tags. If someone takes a screenshot and doesn’t add alt text visually impaired people can’t participate.
>
> So don't post screenshots without alt text, then?

I'm not really interested in participating with the rest of the discussion, but this isn't an appropriate response. The OP raised a systemic accessibility issue, and regardless of whether or not you think it's a valid one, advocating for individual action doesn't make sense on a personal level (it isn't a response to the words that they said) or a development level (it won't make the system more accessible).

(It would have made more sense to point out that Mastodon has an OCR thing built-in that transcribes images with words on into the alt text box, but you have to tell it to do so and it's not very obvious where.)

**Comment by Cassolotl** [comment] 2020-01-05 10:51
I feel like this discussion is a bit pointless. Gargron decided that quote-tweets were bad and enabled harassment, so he resolved to never introduce them into Mastodon, and has used this among other similar things (post text search is limited to hashtags, etc.) as a selling point. This is one of those things where the buck stopped with Gargron and he decided according to how he felt and that's that. It comes up every now and again, and Gargron says no to it every time.

**Comment by Sasha-Sorokin** [comment] 2020-01-09 19:18
*I was passing by this issue over and over again but didn't want to add anything until now.*

Actually, I think — adding comments to boosts would be a nice feature, BUT. Users should have a choice whether they want to be quoted or not. Simple checkbox in the settings (default value for new users could probably be set by server admins) “Allow others to quote my toots” with description somewhat like “Other users my boost your toot and add comments to it.”

---

I would also propose that if user later checks this box after they were quoted, the quotation will disappear with tombstone “This quotation is no longer available.” Or give users option to “De-reference this toot” in ⋯ menu, prompting that “This will send requests to all known instances that interacted with this toot ordering to remove all boosts of it. Processing would take some time and certain instances may not comply with the request because of incompatibility. You can re-draft this toot for more efficient action.”

GOING FURTHER, we probably should have privacy settings category where users could select default toot privacy setting, who can boost them (everyone, “People I follow”) and who can add comment when boosting. On the same page search indexing opt-out can be moved and a few other settings, but this is for discussion in another issue.

But this all may be technically hard to accomplish :(

**Comment by catgirlsec** [comment] 2020-01-09 19:21
> _I was passing by this issue over and over again but didn't want to add anything until now._
> 
> Actually, I think — adding comments to boosts would be a nice feature, BUT. Users should have a choice whether they want to be quoted or not. Simple checkbox in the settings (default value for new users could probably be set by server admins) “Allow others to quote my toots” with description somewhat like “Other users my boost your toot and add comments to it.”
> 
> I would also propose that if user later checks this box after they were quoted, the quotation will disappear with tombstone “This quotation is no longer available.” Or give users option to “De-reference this toot” in ⋯ menu, prompting that “This will send requests to all known instances that interacted with this toot ordering to remove all boosts of it. Processing would take some time and certain instances may not comply with the request because of incompatibility. You can re-draft this toot for more efficient action.”
> 
> GOING FURTHER, we probably should have privacy settings category where users could select default toot privacy setting, who can boost them (everyone, “People I follow”) and who can add comment when boosting. On the same page search indexing opt-out can be moved and a few other settings, but this is for discussion in another issue.
> 
> But this all may be technically hard to accomplish :(

My concern would be people deleting a toot when they realize it’s unpopular and then deleting all criticism of it. The original toot author shouldn’t later be able to delete people’s quotes if they said something stupid they’ll have the live with the criticism. Copyright doesn’t extend to you deleting quotes of yourself when someone says something about you that you disagree with.

**Comment by Sasha-Sorokin** [comment] 2020-01-09 19:33
I disagree. If original tooter wants to delete their toot or account, the quotations must be gone too, leaving us only with boost comment and sad “This toot is no longer available” text. Nobody has to live with anything.

<p align=center>
<img src="https://user-images.githubusercontent.com/10401817/72098586-5898d500-3351-11ea-81b9-b5247d7e462d.png" alt="Demo screenshot">
</p>

**Comment by catgirlsec** [comment] 2020-01-09 19:39
> I disagree. If original tooter wants to delete their toot or account, the quotations must be gone too, leaving us only with boost comment and sad “This toot is no longer available” text. Nobody has to live with anything.
> 
> ![Demo screenshot](https://user-images.githubusercontent.com/10401817/72098586-5898d500-3351-11ea-81b9-b5247d7e462d.png)

Hypothetically speaking if I wrote a WordPress blog post on a disagreement I had with one of Mastodon’s maintainers and I quoted something they said and they decide that they regret saying it do they have the right to take down the blog article on copyright grounds? If the answer is no the same applies to quotations on Mastodon.

The US presidential candidate Andrew Yang actually has a Mastodon instance, if I quote him should he later have the right to delete his toot and therefore my quote? This behavior would obviously not be in the publics’ best interest as politicians using Mastodon could just delete any criticism of their posts and minimize reputational harm.

I already disagree with Twitter removing quotes when a tweet is deleted, this harms political discussions and harms transparency let’s not bring that behavior to mastodon keeping quotes up is in the publics’ interest.

**Comment by CoWinkKeyDinkInc** [comment] 2020-01-09 19:57
I support the implementation of quote toots. I think this will be really helpful to news sites to promote more posts and activity on Mastodon as it lets users easily share articles and their thoughts with it with their followers.

**Comment by Sasha-Sorokin** [comment] 2020-01-09 19:59
@catgirlsec 

> I already disagree with Twitter removing quotes when a tweet is deleted, this harms political discussions and harms transparency let’s not bring that behavior to mastodon keeping quotes up is in the publics’ interest.

If you want to preserve toot, you better go to [Internet Archive](https://archive.org/web/) and request that toot page archived like [that](https://web.archive.org/web/20200109194253/https://bitcoinhackers.org/@mastodonusercount/103398978658815642). What you're suggesting is a vector for abuse, which is why previous requests about quoting were rejected. If we want to have this functionality, we have to ensure it is safe. Disallowing quoting of toots, de-referencing or deleting them later are the ground methods for this safety, I believe.

**Comment by catgirlsec** [comment] 2020-01-09 20:09
> @catgirlsec
> 
> > I already disagree with Twitter removing quotes when a tweet is deleted, this harms political discussions and harms transparency let’s not bring that behavior to mastodon keeping quotes up is in the publics’ interest.
> 
> If you want to preserve toot, you better go to [Internet Archive](https://archive.org/web/) and request that toot page archived like [that](https://web.archive.org/web/20200109194253/https://bitcoinhackers.org/@mastodonusercount/103398978658815642). What you're suggesting is a vector for abuse, which is why previous requests about quoting were rejected. If we want to have this functionality, we have to ensure it is safe. Disallowing quoting of toots, de-referencing or deleting them later are the ground methods for this safety, I believe.

The quoted text can still remain up for transparency purposes. And like you said the internet archive exists so toots can’t be completely erased anyways. So why should I need to copy a link onto the internet archive manually when software can preserve it for me and do it decentralized at that.

I don’t understand how this is any less safe than using the internet archive links. Perhaps you could elaborate.

People wouldn’t be able to reply to your toot only the quote if the toot is later deleted, the text would just remain up so people could see the context of a quote. That’s not unreasonable and occurs with traditional media all the time.

The idea that people should be able to instantly take down criticism of themselves is scary and I hope this doesn’t occur on Mastodon.

**Comment by Sasha-Sorokin** [comment] 2020-01-09 20:46
@catgirlsec 

>  So why should I need to copy a link onto the internet archive manually when software can preserve it for me and do it decentralized at that.

Because it's against interest of developers of that software to compromise theirs users' right to delete any information associated with them. Archiving by manually saving the page or making screenshots is makes information less trustworthy because you could have edited that information.

Almost same applies to Internet Archive, but it's actually more trusted as you don't have access to its infrastructure, but AFAIK their dedication is to provide more reliable information sources, thus archive useful information, but the archiving function is no wonder primarily abused by people to save literally any stuff; and they [IA] delete your information on request, same as with DMCA takedowns. 

> People wouldn’t be able to reply to your toot only the quote if the toot is later deleted, the text would just remain up so people could see the context of a quote. That’s not unreasonable and occurs with traditional media all the time.

If we are going to keep the quotation, any identifying information must be gone too then, including any media, only text and nothing else, no referencing to original sender. But I personally still against keeping even the text:

> The idea that people should be able to instantly take down criticism of themselves is scary and I hope this doesn’t occur on Mastodon.

“Criticism” is a very wide term, y'know — it can start from insults/harassment to actual criticism, you can't tell difference — so yeah, I'm all hands to be able take down all references to my posts, leaving some “critics” with their comments, post unavailability placeholders (“tombstones”), but not my actual posts.

**Comment by catgirlsec** [comment] 2020-01-09 20:55
> @catgirlsec
> 
> > So why should I need to copy a link onto the internet archive manually when software can preserve it for me and do it decentralized at that.
> 
> Because it's against interest of developers of that software to compromise theirs users' right to delete any information associated with them. Archiving by manually saving the page or making screenshots is makes information less trustworthy because you could have edited that information.
> 
> Almost same applies to Internet Archive, but it's actually more trusted as you don't have access to its infrastructure, but AFAIK their dedication is to provide more reliable information sources, thus archive useful information, but the archiving function is no wonder primarily abused by people to save literally any stuff; and they [IA] delete your information on request, same as with DMCA takedowns.
> 
> > People wouldn’t be able to reply to your toot only the quote if the toot is later deleted, the text would just remain up so people could see the context of a quote. That’s not unreasonable and occurs with traditional media all the time.
> 
> If we are going to keep the quotation, any identifying information must be gone too then, including any media, only text and nothing else, no referencing to original sender. But I personally still against keeping even the text:
> 
> > The idea that people should be able to instantly take down criticism of themselves is scary and I hope this doesn’t occur on Mastodon.
> 
> “Criticism” is a very wide term, y'know — it can start from insults/harassment to actual criticism, you can't tell difference — so yeah, I'm all hands to be able take down all references to my posts, leaving some “critics” with their comments, post unavailability placeholders (“tombstones”), but not my actual posts.

You shouldn’t be able to have all references to your identity deleted on demand. Imagine someone posts something supportive of the nazi party, later on should they be able to delete the quote of them and any reference to their identity? Hopefully the answer to that is no they’re being an asshole and are being called out for their bullshit. Quoting them is fair use even if it hurts their feelings.

Using DMCAs to remove criticism is illegal. The DMCA and Copyright Law specifically allows for fair use of someone else’s content. It’s illegal (US Code 512(f)) to send falsified notices and you can face both civil and criminal penalties for abusing the process.

**Comment by Sasha-Sorokin** [comment] 2020-01-09 21:22
> Imagine someone posts something supportive of the nazi party, later on should they be able to delete the quote of them and any reference to their identity?

So, you want call-out culture in Mastodon? Heck no.

Your example can be reversed as that: Imagine someone posts something that someone finds offensive even that it wasn't meant to be like that, while they away from Mastodon, someone quotes them and calling that person names, and then being supported by the followers, who bother not bring up the details, but rather straight join the outrage. Person comes online next hour and sees they are being publicly shamed and insulted for their incorrect wording, they delete post and write apology, but to no avail — other instances keep their copies of the post, the person is still being shamed by those who did not notice the other message.

That's absurd and exactly why people did not want this feature in Mastodon and why they hate Twitter for it. I thought you actually wanted to have it for good reasons (such as accessibility, commenting on news or something like that), but now I see why.

**Comment by catgirlsec** [comment] 2020-01-09 21:32
> > Imagine someone posts something supportive of the nazi party, later on should they be able to delete the quote of them and any reference to their identity?
> 
> So, you want call-out culture in Mastodon? Heck no.

Call-out culture isn’t necessarily bad. I don’t delete toots after being called out for them. I’d rather let the public reach their own conclusions after reading both sides, whether or not they agree with me.

> Your example can be reversed as that: Imagine someone posts something that someone finds offensive even that it wasn't meant to be like that, while they away from Mastodon, someone quotes them and calling that person names, and then being supported by the followers, who bother not bring up the details, but rather straight join the outrage. Person comes online next hour and sees they are being publicly shamed and insulted for their incorrect wording, they delete post and write apology, but to no avail — other instances keep their copies of the post, the person is still being shamed by those who did not notice the other message.

Not all call-outs are insulting. The best way to fight speech is with more speech. You can’t completely delete something once you post it. Just like you can’t unsay something when away from keyboard.

> That's absurd and exactly why people did not want this feature in Mastodon and why they hate Twitter for it. I thought you actually wanted to have it for good reasons (such as accessibility, commenting on news or something like that), but now I see why.

This feature benefits a lot of things, although every technology has negative side effects. Under this logic we should disable posting entirely because someone might say mean things in them right? If the answer is no because we have moderation tools the same applies to a quotes system.

**Comment by Sasha-Sorokin** [comment] 2020-01-09 22:03
[Cage the Mastodon § Design decisions](https://blog.joinmastodon.org/2018/07/cage-the-mastodon/#design-decisions):

> Another feature that has been requested almost since the start, and which I keep rejecting is **quoting messages**. Coming back to my disclaimer, of course it’s impossible to prevent people from sharing screenshots or linking to public resources, but quoting messages is immediately actionable. It makes it a lot easier for people to immediately engage with the quoted content… and it usually doesn’t lead to anything good. When people use quotes to reply to other people, conversations become performative power plays. “Heed, my followers, how I dunk on this fool!” When you use the reply function, your message is broadcast only to people who happen to follow you both. It means one person’s follower count doesn’t play a massive role in the conversation. A quote, on the other hand, very often invites the followers to join in on the conversation, and whoever has got more of them ends up having the upper hand and massively stressing out the other person.

And you, with that example above and affirming that “call-out culture isn’t necessarily bad” just proving Eugen's point from linked article and also trying to counter my arguments that are attempt to try lower the negative side effects of proposed quoting functionality. And that leads us nowhere.

Guess we aren't mature enough for that feature and this is another issue to close.

**Comment by nuklearfiziks** [comment] 2020-01-09 22:08
+1 to close. This is becoming an increasingly argumentative and unconstructive issue.

**Comment by wakest** [comment] 2020-01-13 04:10
Flame war in the comments is not going to resolve this issue. Fediverse software, including *multiple* forks of Mastodon, MissKey, Dolphin and Friendica *already* have this feature. Really what need to figure out is a system for standardizing this in a way that can be dealt with and moderated properly. Discussing whether we should have it or not is somewhat moot when we *already* have it. The question is how should mainline Mastodon go about safely and effectively interacting with a feature that already exists.

**Comment by catgirlsec** [comment] 2020-01-13 04:17
> Flame war in the comments is not going to resolve this issue. Fediverse software, including _multiple_ forks of Mastodon, MissKey, Dolphin and Friendica _already_ have this feature. Really what need to figure out is a system for standardizing this in a way that can be dealt with and moderated properly. Discussing whether we should have it or not is somewhat moot when we _already_ have it. The question is how should mainline Mastodon go about safely and effectively interacting with a feature that already exists.

Posts can already be moderated by removing the status or restricting the user. Internet users aren’t the maintainers’ children to babysit, it’s up to instance moderators to decide the rules. It’s clear that Mastodon and other fediverse software have different approaches to abuse and that’s fine. If we’re going to limit features because they might be abused, I’ll start sending my suggestions to those projects instead and let internet users decide what project they like more.

**Closed** 2020-01-19 02:54 UTC

**Comment by zichy** [comment] 2022-11-08 14:09
How about only being allowed quote toot people who follow you?

**Comment by lorenzlm** [comment] 2022-11-08 14:55
I would argue that quote tweets enable the **curating** function, which is a HUGE quality in Twitterverse. Curating means **introducing something** to your audience while **giving context** and (possibly) **evaluation**. 

And neither **commenting** nor **boosting** comes remotely close to this. It is, actually, one of the main reasons why I stayed for such a long time with Twitter. 

So, a very passionate plea to the developers to reconsider their decision and make quote posts possible on Mastodon.

**Comment by ell1e** [comment] 2022-11-15 20:45
I also use it for curating. It is one of the reasons why I find it hard to migrate. Especially for tech or generally educational accounts, I think it's kind of a showstopper to not have this.

**Comment by mattwynne** [comment] 2022-11-15 21:25
[This thread](https://mastodon.social/@shengokai@zirk.us/109346992260778623) makes an interesting point about how quote tweets have been used to *build* communities on Twitter, especially for people of colour.

I would prefer to see a discussion about how this feature could be added with good moderation tools around it. For example, @zichy's suggestion above:

> How about only being allowed quote toot people who follow you?

Or a configurable limit on the relative follower count, or minimum follower overlap allowed for RTs. Both of those could prevent it being used for "dunking".

**Comment by mattwynne** [comment] 2022-11-15 21:27
=> https://github.com/mastodon/mastodon/issues/20673

**Comment by ell1e** [comment] 2022-11-15 21:27
It's useless for educational use however if the other person needs to follow you, since you'd usually be quoting news article posts. But who's possibly going to make all news posters follow them first?

**Comment by jmturner** [comment] 2022-11-15 21:50
> It's useless for educational use however if the other person needs to follow you, since you'd usually be quoting news article posts. But who's possibly going to make all news posters follow them first?

I have a humble suggestion: at least allow for quote-tweeting bots? Media outlets often share their stories via bots or automated processes. Bots are abuse-resistant. This would allow for the curating of news stories (at least) without fear of abuse.

Ideally I would like to see this expanded to everyone as I fully agree that QT's are wonderful for curating opinions. For now, though, why not allow this for bot accounts?

**Comment by lorenzlm** [comment] 2022-11-15 21:54
Yeah, I also found @shengokai 's thread very inspiring! But, when you look closely, one of his points is that in the Black community, a kind of playful aggression is part of the fun (e.g. the Dozens game). So this makes for bad arguments in the context of a community that wants to structurally reduce the incentive for aggression... ;-)

> How about only being allowed quote toot people who follow you?

I think this is a very bad idea, because at least my favourite use case, curation, is basically the wish to introduce SOMETHING NEW to my followers, something outside their bubble. 

And that, on the other hand, complies with @shandokai 's argument: It is about bridging or connecting sub-communities in a way. That can be friendly and constructive, can be playfully aggressive, but can also be outright hostile, of course. My suggestion would be to eliminate the hostility by other means.

**Comment by ThatOneCalculator** [comment] 2022-11-16 16:10
@ell1e ya know, there is other Fediverse software out there that has quotes. It'd just be nice if Masto federated with then

**Comment by noqqe** [comment] 2022-11-21 15:20
Just because I've read it many times here 

> My feeling is that quote retweets dramatically worsened the discourse on Twitter

A actual Twitter Designer that introduced Quotes recently said the effect was not bad to the twitter community. 

> 
> I remember when we added quote tweet, and we have the receipts. It does *not* increase abuse. (Source: I was the lead designer on the abuse team)
>
> You know what increases abuse? Reverse-chron replies without any sorting or algorithm, because someone can say 
> "Kill yourself" as the first response. It becomes a game. It silences people.
>
> Source: @jon@social.lot23.com  https://social.lot23.com/@jon/109372301129404830

Not saying mastodon should be copying twitter, but we can stop talking about the social aspects on this feature request now.

**Comment by trwnh** [comment] 2022-11-21 16:07
> we can stop talking about the social aspects on this feature request now.

Disagree, as "actual Twitter Designer" doesn't mean anything. In any case, I'm not going to rehash a discussion from over 2 years ago, but I would specifically point out that "abuse" needs to be defined first -- if you mean "actionable reports by Twitter's terms of service", then sure, but that's not a good metric for anything. I wouldn't report someone for quoting something 20 levels deep, or quoting some awful person just to make fun of them (and also give them additional attention and visibility), or etc. But I would also not say that these are good outcomes. Nor would I agree that "reverse-chron" increases abuse -- if someone says "kill yourself" then reporting it actually works better, as an actual human being will see it and take action, suspending the account (unlike Twitter, which just buries it under "more replies").

**Comment by pljakobs** [comment] 2022-12-19 10:15
I know this is an old issue and I know people are very opinionated about it and I appreciated that probably smarter people have thought about it already, but hear me out for a second:

This came up in a discussion today and I can see the validity of the points that reject this. It can lead to negative behaviour, especially if a toot is qouted out of context and pulled into another bubble without reference. Even a pingback of a quote will not fully fix this, because the discussion below the quote will happen without the original poster and their bubble, which may lead to a spiral of unmoderated negativity.

In the discussion the following was proposed: would it be possible to make a quote RT not just a new toot in the Quoter's timeline(s) but also a reply to the original toot? That is, it would probably be a reply first that is then also shown in the quoting person's timelines. This way, it would not fork off a whole new discussion "room" aside from the original post but still help to share and comment something said by the OT. 

Managing the discussion might then be helped by giving the original poster tools to, in the extreme, mute responses for the followers of this discussion.

I will say I don't know if the data model makes this easy or hard to implement, but it seems like an idea to think about..
