### ISSUE TITLE
Cannot Open Post In TL if Post is Image With no Text

### ISSUE THREAD

**Issue by TheDiscordian** [tootsuite/mastodon#9061] opened 2018-10-23 01:43 UTC
I searched through all bugs with the word "image" and didn't see an issue matching this, sorry if it's a duplicate. I had trouble articulating the issue in title-form.

### Expected behaviour

When I left-click anywhere on a post, it opens in the right-most bar so I can view replies, etc.

### Actual behaviour

Post itself highlights, the cursor style does not change to hand when moused over.

### Steps to reproduce the problem

Find a post that's just an image:

https://niu.moe/@SarcasmKid/100942027261937592
https://niu.moe/@SarcasmKid/100942325505148158
https://shelter.moe/@dd86k/100942346300097021

Try to click within the post (not the image itself), it'll highlight, but it won't open in the right-most bar. If the image contains text, you can mouse over the text and the cursor style changes to a hand, click the text to open the post in the right-most bar.

### Specifications

Mastodon: v2.5.0 and v2.6.0rc1
OS: Windows 10
Browsers: Opera 56.0.3051.43, FireFox 62.0.3 (64-bit), and Google Chrome 69.0.3497.100 (Official Build) (64-bit)

**Comment by Gargron** [comment] 2018-10-23 01:51
Use dropdown -> Expand toot, or press "o" or "enter" once the toot is selected. Toot backgrounds not having a click handler is intentional due to past requests for keyboard navigation, so this isn't a bug.

**Comment by Gargron** [comment] 2018-10-23 01:52
Also duplicate of #8529

**Closed by Gargron** 2018-10-23 01:51 UTC

**Comment by TheDiscordian** [comment] 2018-10-23 01:52
That's ridiculous, so you can highlight the post but not open it? Why even do that? Why not make it clickable? or at least an option? ffs I'm done defending your stupid decisions.

**Comment by Gargron** [comment] 2018-10-23 01:56
#140
