### ISSUE TITLE
A mistyped confirmation email locks a username

### ISSUE THREAD

**Issue by goingtomaine** [tootsuite/mastodon#1131] opened 2017-04-07 05:24 UTC
Just tried to make an account on an instance, but mistyped my email - the confirmation went to a non-extant address. The account has now been generated but can't be claimed. I can browse it ([ref.](https://octodon.social/@going_to_maine)) but it can't be visited. At what point does the confirmation email expire and the account get freed up? If it doesn't, that seems like a bug.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-09 23:20
#1286 is a duplicate of this but we already started the discussion of this there (sorry) so I'm closing this and asking you to please move over there for discussion of this issue.

**Closed by wxcafe** 2017-04-09 23:20 UTC
