### ISSUE TITLE
Cannot expand a toot by clicking in negative space if it consists of only an image

### ISSUE THREAD

**Issue by BenLubar** [tootsuite/mastodon#9032] opened 2018-10-21 02:12 UTC
### Expected behaviour

Clicking above the image in a toot opens the toot in the large view on the right.

### Actual behaviour

This only works if there is text above the image.

### Steps to reproduce the problem

Example of a toot with only an image: https://mastodon.social/@Gargron/100929407318942637
Example of a toot with an image and text: https://mastodon.social/@Gargron/100211283409260120
Example of a toot with only text: https://mastodon.social/@Gargron/100928920851754990

In the timeline view, the first toot cannot be expanded by clicking negative space and the other two can.

### Specifications

Existed in 2.5.2 and still exists in 2.6.0rc1

Occurs on both my Windows 10 machine and my Chromebook, both running Chrome.

**Comment by trwnh** [comment] 2018-10-21 03:37
Duplicate of #8529

**Closed** 2018-10-21 03:39 UTC
