### ISSUE TITLE
Social Plugins to share to Mastodon

### ISSUE THREAD

**Issue by yookoala** [tootsuite/mastodon#1978] opened 2017-04-17 05:07 UTC
Really really low priority. But I think it is a nice feature to have.

Social media sites like Twitter, Facebook provides websites with Social Plugins. Website owners can include a piece of JS / HTML embed to display a "Share to XXX" button. Visitors can share the website's like and perhaps part of the content to that social media site.

Examples,

- Twitter: [Tweet Button](https://dev.twitter.com/web/tweet-button)
- Facebook: [Share / Like Button](https://developers.facebook.com/docs/plugins/#like-share-send)

Propose to:

1. Write and host a "Share to Mastodon" script.
2. By embeding, website owner can display the "Share to Mastodon" or "Toot it" button on the site.
3. Visitor, when first use on the button in any site,
   1. Visitor will get a dialog to input the instance URL to share.
   2. Then a dialog to actually edit the post content for sharing.
   3. The dialog should have a "Toot" button to actually toot on the site.
   4. Should the visitor not login to the site, it should direct the user to additional login process.
4. The instance specified will be stored in cookie (of the script's CDN domain).
5. Later on, if a visitor use the button on any site with again,
   1. Visitor will get a dialog to actually edit the post content for sharing.
   2. This dialog also show that it will Toot to "Preferred instance", which the script memorized with cookie earlier. Visitor should have an option to specify another instance.
   3. Other behavior should be the same as the first use.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by alexisju** [comment] 2017-04-17 17:46
Low priority? I think it is a HIGH priority issue to not have such feature. 

It is not just about add another plugin, but to have an easy way to share content on Mastodon.

Related to : #1318 #1162 #943

**Comment by nIQnutn** [comment] 2017-04-23 07:23
it's available for Diaspora* https://share.diasporafoundation.org/

**Comment by jeroenpraat** [comment] 2017-05-06 22:27
Yes this a high priority. A bookmarklet or something similar is really needed to share content much easier on Mastodon.

**Comment by jeroenpraat** [comment] 2017-05-06 22:28
You also have Firefox share service. https://activations.cdn.mozilla.net/ Mastodon should really use that.

**Comment by jeroenpraat** [comment] 2017-05-08 17:27
Please see this: https://sharetodiaspora.github.io/about/

It's something very useful and maybe someone with the right skills can make this for Mastodon?

**Comment by Gargron** [comment] 2017-06-29 23:20
Duplicate of #442 (trust me I am interested in this, just consolidating)

**Closed by Gargron** 2017-06-29 23:20 UTC
Labels: enhancement, priority - low, ui

**Comment by albjeremias** [comment] 2019-12-19 00:07
i dont get it.. how can I use this then?
