### ISSUE TITLE
Feature Request: comment while boosting a toot

### ISSUE THREAD

**Issue by chaica** [tootsuite/mastodon#3999] opened 2017-06-29 13:44 UTC
It would be great if it was possible to add a comment while boosting a toot. It allows a more personal touch and add value for next readers while boosting a toot.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2017-06-29 14:35
I suspect this may be a duplicate of #309?

**Comment by Gargron** [comment] 2017-06-29 14:36
Yes, sorry but it is a duplicate!

**Closed by Gargron** 2017-06-29 14:36 UTC
