### ISSUE TITLE
Minimal thread compatibility with Friendica

### ISSUE THREAD

**Issue by warpsync** [tootsuite/mastodon#1854] opened 2017-04-15 14:34 UTC
Replies to Friendica posts work, but replies from Friendica are shown as standalone posts. Please, bring the minimal thread compatibility. It shouldn't break anything in mastodon.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Hypolite** [comment] 2017-04-27 03:42
Here are a few examples:
Friendica thread: https://friendica.mrpetovan.com/display/52acf9cd1a7da0da2797f2a09af0cb1c096e3c62
Mastodon reply: https://mastodon.social/users/VictorienVifArgent/updates/2146568

Example 2:
Friendica thread: https://friendica.mrpetovan.com/display/26ab94b589e7f2de80358d7ca22a90ec3f47b226
Mastodon reply 1: https://mastodon.social/users/Gargron/updates/2142914
Mastodon reply 2: https://mastodon.social/users/jeroenpraat/updates/2144469
Mastodon reply 3: https://mastodon.host/users/vespin_feebler/updates/15920

I'm not able to know if the people I replied too ever received my replies.

**Comment by annando** [comment] 2017-05-18 09:19
@warpsync @Hypolite please test with the current RC of Friendica. We improved a lot concerning the elements that are part of the messages that we send from Friendica to Mastodon.

**Comment by Hypolite** [comment] 2017-05-18 22:20
Let's see: https://friendica.mrpetovan.com/display/735a202910591e1e0c8c9fc265621146

**Comment by Gargron** [comment] 2017-06-30 14:29
Has this been resolved?

**Comment by Hypolite** [comment] 2017-06-30 21:53
Nope, none of my replies to Mastodon replies to my post show up in conversations to this date.

**Comment by annando** [comment] 2017-07-26 04:53
I cannot reproduce this:
https://mastodon.social/@heluecht/13743663
https://mastodon.social/@heluecht/4892681

**Comment by nightpool** [comment] 2017-07-26 12:35
closing since Frendica can't reproduce. feel free to reopen if it remains an issue.

**Closed by nightpool** 2017-07-26 12:35 UTC
Labels: api, enhancement, priority - medium
