### ISSUE TITLE
Feature Request: Showing an instance's toots in another column (appart from yours)

### ISSUE THREAD

**Issue by DelightfulAgony** [tootsuite/mastodon#6792] opened 2018-03-15 22:46 UTC
Hello!
I just thought it would be great if you could pin a column with the local timeline of different instances appart from the one you're on.
As different instances tend towards different interests I think it would be a nice way to find new accounts of your interest without moving instances or creating different accounts for each one.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment] 2018-03-15 22:49
this is a duplicate of #1053, which has lots of discussion on the issue

**Comment by DelightfulAgony** [comment] 2018-03-15 23:00
Thank you @nightpool

**Closed** 2018-03-15 22:59 UTC
