### ISSUE TITLE
Can't delete a user ?

### ISSUE THREAD

**Issue by jhautefeuille** [tootsuite/mastodon#779] opened 2017-04-03 14:46 UTC
How to delete my user login ?

**Comment by tobypinder** [comment] 2017-04-03 18:41
I don't believe the project supports account deletion yet as there is still an issue #109 open on this bug tracker, and with the way federation works it isn't as simple as deleting you from the database. I don't know if there is some manual assistance that a member of the project can provide you or not, all I can recommend is the manual process of removing content and deleting avatars/etc.

**Comment by ashfurrow** [comment] 2017-04-22 05:42
You can try contacting the admin and asking them to suspend your account, which deletes your toots, uploads, avatar. The account stays around preventing someone from taking your old username.

Since this is a duplicate of #109 I'm going to close.

**Closed by ashfurrow** 2017-04-22 05:42 UTC
