### ISSUE TITLE
Rename lists

### ISSUE THREAD

**Issue by kpcyrd** [tootsuite/mastodon#6153] opened 2018-01-02 04:58 UTC
It seems it's currently not possible to rename a list without:
- creating a new list
- add everybody from the old list manually
- delete the old list

It would be really nice if I could just rename the list itself.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mftaff** [comment] 2018-01-04 14:40
Hey, I am relatively new to open source contributing, mind if I have a go at this?

**Comment by kpcyrd** [comment] 2018-01-04 14:56
@mftaff that would be awesome! :)

**Comment by Sylvhem** [comment] 2018-03-02 16:51
This issue is a specific subset of #5915. Should we count it as a duplicate?

**Comment by ThibG** [comment] 2018-05-07 20:40
Duplicate of #5915

**Closed by ThibG** 2018-05-07 20:40 UTC
