### ISSUE TITLE
full-text search on toots (feature request)

### ISSUE THREAD

**Issue by dachary** [tootsuite/mastodon#2637] opened 2017-04-30 07:29 UTC
A full text search on the status of the instance would be very useful. As my the number of toots I posted grows, I have trouble finding my own toots from some time ago ;-)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by rjeffries** [comment] 2017-04-30 13:29
New to GitHub so this may not be appropriate, but I very much desire free text search. Huge value add. Thx.

**Comment by Gargron** [comment] 2017-06-30 15:12
Duplicate of #594

**Closed by Gargron** 2017-06-30 15:12 UTC
Labels: enhancement
