### ISSUE TITLE
Pasting URL's with ampersand results in broken Toots

### ISSUE THREAD

**Issue by alerque** [tootsuite/mastodon#1144] opened 2017-04-07 10:29 UTC
This is possibly related to #826.

Taking a URL with `&` separated URL parameters results in a double-encoding and a useless URL in the posted Toot.

Example of a broken toot: https://mastodon.social/@alerque/1871713

The URL in that toot was originally pasted in the compose box as: https://aur.archlinux.org/packages/?SeB=nd&K=mastodon

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Exagone313** [comment] 2017-04-07 11:46
"Duplicated" issue.

**Comment by wxcafe** [comment] 2017-04-09 16:54
Closing since this is a duplicate of multiple other issues (#689, #826, #1034, etc)

**Closed by wxcafe** 2017-04-09 16:55 UTC
Labels: duplicate
