### ISSUE TITLE
Home doesn't show toots from people I'm following

### ISSUE THREAD

**Issue by hach-que** [tootsuite/mastodon#1354] opened 2017-04-09 15:51 UTC
For some reason, after coming back to mastodon.social after like 2 months, Home doesn't show toots from anyone I'm following anymore unless I unfollow and refollow them.  My account is @hq.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-09 15:57
@hq@mastodon.social I guess? Tagging @Gargron then

**Comment by hach-que** [comment] 2017-04-09 16:00
Yeah, that's the one.  I just went through some of my follows and unfollowed/refollowed so Home had some content.  But at least one other person had this problem as well: https://mastodon.social/@antumbral/1588916

**Comment by Gargron** [comment] 2018-02-13 22:15
Duplicate of solved #5634

**Closed by Gargron** 2018-02-13 22:15 UTC
Labels: question
