### ISSUE TITLE
Feature Request: Trending Topics

### ISSUE THREAD

**Issue by stockermans** [tootsuite/mastodon#1473] opened 2017-04-10 20:01 UTC
It would be essential to have trending topics listings easily accessible for users.

**Comment by davidak** [comment] 2017-04-10 21:23
Yes, would be really nice to see what topics the (mastodon) world currently cares about.

As a workaround you can follow https://mastodon.social/@TrendingBot

**Comment by isati** [comment] 2017-04-10 22:37
Is trendingbot source available?

**Comment by yiskah** [comment] 2017-04-11 03:46
We don't know who runs TrendingBot it was been a great mystery of Mastodon for a long time. It pollutes the tags that are trending with its own posts and we don't know how to stop it, hehe.

in all seriousness, implementing a "trending topics" feature would be difficult to do "right." It would involve some level of tracking and datamining, which most of our users are opposed to and is antithetical to what mastodon promotes itself as. It also could only track what's trending locally if you wanted it to be any degree of accurate, as not all instances are known to any server.

It would really just depend on what you want out of it and what compromises you're willing to make.

**Comment by James-Firth** [comment] 2017-04-11 22:30
I feel like a "Trending Locally" option would be good for an instance admin to be able to toggle on/off. 

That would allow each instance to make the decision whether they were okay with that sort of data-mining.

**Comment by Gargron** [comment] 2017-06-29 22:02
Duplicate of #271

**Closed by Gargron** 2017-06-29 22:02 UTC
Labels: priority - low
