### ISSUE TITLE
Update failed by v3.0.1 to v3.1.0

### ISSUE THREAD

**Issue by tailot** [tootsuite/mastodon#13380] opened 2020-04-02 14:01 UTC
### Expected behaviour

Upgrade successfully.

### Actual behaviour

The system cannot be updated with message:
"Bundler::GemNotFound: Could not find rake-10.3.2 in any of the sources"

### Steps to reproduce the problem

git checkout v3.1.0
bundle install

(I am following the release notes.)

### Specifications

Mastodon version v3.1.0

OS: Ubuntu 18.04

**Comment by ThibG** [comment] 2020-04-02 18:13
I cannot reproduce this. However, 3.1.0 will fail to install because of `httplog` 1.4.1 missing, and 3.1.1 and 3.1.2 because of `sidekiq-unique-jobs-6.0.18` missing.
Hopefully we will soon have a new release fixing that dependency issue.

**Comment by ThibG** [comment] 2020-04-05 13:30
v3.1.3 has been released, you should be able to upgrade straight to it (but please have a look at upgrade notes for intermediate versions as well), so I'm closing

**Closed by ThibG** 2020-04-05 13:30 UTC

**Comment by tailot** [comment] 2020-04-06 08:30
@ThibG Thanks!!! Works well!
