### ISSUE TITLE
Not receiving notifications for new follower approvals 

### ISSUE THREAD

**Issue by vladanghene** [tootsuite/mastodon#771] opened 2017-04-03 11:19 UTC
Set my profile to private.
Tried to follow myself from my newly deployed instance http://mastodonclojure.herokuapp.com , found my valid mastodon.social account, clicked follow (result is Awaiting Approval) --> on mastodon.social I get no notification.

**Comment by ashfurrow** [comment] 2017-04-22 05:44
I'm not aware if this is a bug or if this is a missing feature. Reaching out to @Gargron for clarification. Thanks for opening!

**Comment by Gargron** [comment] 2017-06-29 15:54
Duplicate of #455

**Closed by Gargron** 2017-06-29 15:54 UTC
Labels: question
