### ISSUE TITLE
Reply count not correct

### ISSUE THREAD

**Issue by schiessle** [tootsuite/mastodon#8711] opened 2018-09-17 08:45 UTC
I realized that when I use the Mastodon API to fetch a toot that "replies_count" is not always correct, often the count is lower then the number of actual replies. First I thought that I did something wrong but then I realized that the problem also exists on the web interface. See this toot for example: https://mastodon.social/@bjoern/100148499376257587 There is one replay but the reply count says '0'.

![mastodon](https://user-images.githubusercontent.com/1589737/45613451-b0c60c80-ba66-11e8-8ca3-7758603449e9.png)

**Comment by trwnh** [comment] 2018-09-18 01:36
Duplicate of #8324

**Comment by Gargron** [comment] 2018-09-18 01:52
The screenshot shows the public (static) page so JavaScript updates would not be related. Still possibly related to some layer of caching.

**Comment by schiessle** [comment] 2018-09-18 08:26
@Gargron If I query the API directly with a small script for the toot I get the same result. So I don't think it is a browser caching issue.

**Closed** 2018-10-28 05:42 UTC
Labels: bug
