### ISSUE TITLE
Send emails to moderators (or at least the admin) when a report is filed.

### ISSUE THREAD

**Issue by wavebeem** [tootsuite/mastodon#2240] opened 2017-04-20 21:53 UTC
As far as I can tell there is no email or notification when I knew report is filed, making it hard to respond to moderation reports in a timely manner.

Ideally the instance admin and any number of moderator users would get a notification email when a report is filed.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment] 2017-04-21 08:39
I think this is a duplicate of #1624, closing

**Closed** 2017-04-21 08:40 UTC
Labels: duplicate
