### ISSUE TITLE
GraphQL？

### ISSUE THREAD

**Issue by zzz6519003** [tootsuite/mastodon#13356] opened 2020-03-31 01:08 UTC

**Comment by nightpool** [comment] 2020-03-31 01:11
why?

**Comment by Sasha-Sorokin** [comment] 2020-03-31 11:48
What did you mean with this trendy word?

**Comment by ykzts** [comment] 2020-03-31 13:08
Is this Issue a duplicate of #8035?

**Comment by ykzts** [comment] 2020-04-04 23:00
This issue is closed due to lack of information.  Please comment if necessary.

**Closed by ykzts** 2020-04-04 23:00 UTC
