### ISSUE TITLE
BUG / Look at a report don't work in 1.3.1

### ISSUE THREAD

**Issue by valentin2105** [tootsuite/mastodon#2567] opened 2017-04-28 03:15 UTC
Since the last release (1.3.1), I can't open a report,

I can list all the reports, but can't open any, 

Here is the error :

```
[aac8cb9a-c184-415b-9a46-898c1f46305b]
[aac8cb9a-c184-415b-9a46-898c1f46305b] ActionView::Template::Error (Missing partial authorize_follow/_card with {:locale=>[:fr, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml, :rabl]}. Searched in:
  * "/mastodon/app/views"
  * "/mastodon/vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.0.1/app/views"
  * "/mastodon/vendor/bundle/ruby/2.4.0/gems/doorkeeper-4.2.5/app/views"
  * "/mastodon/vendor/bundle/ruby/2.4.0/gems/devise-4.2.1/app/views"
  * "/mastodon/vendor/bundle/ruby/2.4.0/gems/pghero-1.6.4/app/views"
):
[aac8cb9a-c184-415b-9a46-898c1f46305b]     4: .report-accounts
[aac8cb9a-c184-415b-9a46-898c1f46305b]     5:   .report-accounts__item
[aac8cb9a-c184-415b-9a46-898c1f46305b]     6:     %strong= t('admin.reports.reported_account')
[aac8cb9a-c184-415b-9a46-898c1f46305b]     7:     = render partial: 'authorize_follow/card', locals: { account: @report.target_account }
[aac8cb9a-c184-415b-9a46-898c1f46305b]     8:     = render partial: 'admin/accounts/card', locals: { account: @report.target_account }
[aac8cb9a-c184-415b-9a46-898c1f46305b]     9:   .report-accounts__item
[aac8cb9a-c184-415b-9a46-898c1f46305b]    10:     %strong= t('admin.reports.reported_by')
[aac8cb9a-c184-415b-9a46-898c1f46305b]
[aac8cb9a-c184-415b-9a46-898c1f46305b] app/views/admin/reports/show.html.haml:7:in `_app_views_admin_reports_show_html_haml__549391079573317213_47369153243800'
```

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment] 2017-04-28 03:35
Dupe of https://github.com/tootsuite/mastodon/issues/2551

**Closed** 2017-04-28 08:17 UTC
Labels: duplicate
