### ISSUE TITLE
Upgrade to latest twemoji version

### ISSUE THREAD

**Issue by phildini** [tootsuite/mastodon#5579] opened 2017-10-31 23:31 UTC
There's a whole bunch of new emoji available in the latest twemoji version that it would be really cool to get into Mastodon.

https://github.com/twitter/twemoji/releases/tag/v2.3.0

I confess I have not looked deeply at how we integrate emoji sets to being with, but my hope is that this isn't too difficult. I may try to tackle myself, but if someone has a bead on how to make this happen, great!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by glasnt** [comment] 2017-10-31 23:45
It *looks* like the emoji exist but aren't being picked up by the emoji picker (zombies, etc). Not sure if our instance is running the latest version of mastadon or something of the like, but I'm confused as to why the Unicode 10.0 assets exist, but aren't appearing in emoji picker searches

(Sorry if I've misanalysed this)

**Comment by nightpool** [comment] 2017-11-01 17:54
possibly blocked on https://github.com/iamcal/emoji-data/issues/90

**Comment by phildini** [comment] 2017-11-03 05:18
@nightpool thanks for trying to ping on the upstream emoji-data version.

Would it be a faux-pas to fork and upgrade ourselves, then have mastodon reference the fork?

**Comment by phildini** [comment] 2017-11-05 19:41
@nightpool Given that that repo hasn't been updated since May, I think we should think about forking it into tootsuite (or one of us forking it ourselves and updating it). 

What's the process here? Is there someone I should ask about the right way forward, or "just do it" and file a PR?

**Comment by nightpool** [comment] 2017-11-05 20:03
Well the problem is that it's not a direct dependency of ours—it's
transitive through emoji-mart. We'll have to discuss with them the best way
forward.

**Comment by renatolond** [comment] 2017-12-15 14:18
It seems the version of emoji-data was updated, and emoji-mart seems to have picked it up too. :)

**Comment by marrus-sh** [comment] 2018-06-06 03:59
given that Twemoji 11.0 is out with a bunch of new Emoji, it would be nice if we could get support for them as well ^^;; https://blog.emojipedia.org/twemoji-11-0-emoji-changelog/

**Comment by renatolond** [comment] 2018-06-11 07:40
Hey! I suggest that we close this one (since 2.4.1 fits the op description) and open a new one about the Unicode 11 emojis (or maybe use #7446 for this)

**Closed** 2018-06-11 12:19 UTC
