### ISSUE TITLE
[Feature request] Show profile preview on hover

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#6354] opened 2018-01-25 01:35 UTC
Per @GTCcreations on Twitter: https://twitter.com/GTCCreations/status/956178485265031168

> [A] suggestion would be showing details while hovering the mouse over someone's username.

I believe Twitter does this, and I agree something like this could be useful for Mastodon. https://i.imgur.com/MCLzewh.png

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2019-08-05 09:06
Duplicate of #1471

**Closed by Gargron** 2019-08-05 09:06 UTC
Labels: suggestion, ui
