### ISSUE TITLE
React interface slows down over time due to growing timeline

### ISSUE THREAD

**Issue by kaniini** [tootsuite/mastodon#3078] opened 2017-05-16 04:51 UTC
Hello,

It seems that in recent Mastodon (1.3.3 and git master as well), the interface slows down over time because older toots are not garbage collected from the UI.  This results in the browser containing 10000s of toots in the timeline widget.

It seems to me like the JS side should garbage-collect old toots by using some sort of ring queue, where overflows result in the oldest toot being removed from the widget.

**Comment by nolanlawson** [comment] 2017-05-16 20:17
Is this a duplicate of #2900?

**Comment by sorin-davidoi** [comment] 2017-06-07 22:31
@nolanlawson I guess this can be closed.

**Closed** 2017-07-02 15:11 UTC
