### ISSUE TITLE
Password Recovery broken

### ISSUE THREAD

**Issue by Kuroto** [tootsuite/mastodon#6634] opened 2018-03-05 08:09 UTC
I created a new account on Mastodon and after verified my email I couldn't log in, figured I typed in a wrong password twice (it's early and haven't had coffee), but the password recovery link took me to a broken page.

"We're sorry, but something went wrong on our end. " And the elephant banging on a computer.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ykzts** [comment] 2018-03-05 08:12
duplicate of #6611.

**Closed by ykzts** 2018-03-05 08:12 UTC
Labels: duplicate
