### ISSUE TITLE
PGP Support

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon#4007] opened 2017-06-30 00:56 UTC
Could we have a possibility for linking PGP certificates to Mastodon accounts to allow for signatures on posts, a web of trust, and encryption?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). #

**Comment by benjamincodeWebsite** [comment] 2017-06-30 01:01
This would also aid with #913. If this is approved, I would be happy to help with implementation.

**Comment by eebrown** [comment] 2017-12-31 21:17
This is also discussed on #928. I support for the reasons I list there.

**Comment by nightpool** [comment] 2017-12-31 21:21
duplicate of #928

**Closed by nightpool** 2017-12-31 21:21 UTC
