### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by popcornqueen** [tootsuite/mastodon#2887] opened 2017-05-07 16:05 UTC
[Hello, I would like to ask if it's possible for Mastodon to have polls? I think it would be very interesting especially with the federated timeline. I don't know how to code so I'm just pitching this idea.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment] 2017-05-07 16:18
This is #1629! I love this idea. :D Please feel free to go +1 or comment or whatever you feel like doing. :)

**Comment by kensoh** [comment] 2017-05-08 02:29
Hi Nicole @popcornqueen this is Ken from Mastodon (https://mastodon.social/@kensoh). People normally try to consolidate issues so that it is easier for the developers to track. After clicking on 1629 link, you can click on the thumbs up to vote on that issue.

Someone on the developers team will close this issue and the number of thumbs up is helpful for developers team to gauge which features to implement as higher priority as it reflects users' needs.

**Comment by Cassolotl** [comment] 2017-05-08 14:48
@kensoh Thanks, well-put. :) I'll add that the person who opened the issue can also close it!

**Comment by wxcafe** [comment] 2017-05-09 10:03
As mentionned, this is a duplicate of #1629. Closing 👍

**Closed by wxcafe** 2017-05-09 10:03 UTC
