### ISSUE TITLE
SUGGESTION: Saving space in notification area

### ISSUE THREAD

**Issue by maff1989** [tootsuite/mastodon#5589] opened 2017-11-04 17:29 UTC
Instead of displaying the entire status in the notifications area when somebody boosts/favorites a status, instead link to the status in the notification.

Example: "`So-and-so favorited your <a href="web URL">status</a>`"

Each notification would then mostly only take 1-2 lines of text and allow more notifications to be listed in the designated notification area

**Comment by Technowix** [comment] 2017-11-05 01:31
Would be... well, lose the point of the notification ? if we have to click into each :x

**Comment by greggrossmeier** [comment] 2017-12-14 17:16
I recently had a 500 char toot widely boosted/favorited. It'd be great if we could *merge* these notifications. "Alice, Bob, Claire, Danielle boosted...<full toot>" and same for favorited. Those lists of usernames would be updated upon new boosts/favs.

**Comment by Technowix** [comment] 2017-12-14 17:41
@greggrossmeier I like the idea of same-post notifications being merged ! But we might not mess up the chronological way of displaying thoses, so if someone fav & boost the post, that might get the feature less worthwhile 🤔

**Comment by deutrino** [comment] 2018-01-21 22:47
Duplicate of #1868?

**Comment by nightpool** [comment] 2018-01-21 23:01
dupe of https://github.com/tootsuite/mastodon/issues/1483

**Closed by nightpool** 2018-01-21 23:01 UTC
