### ISSUE TITLE
Pressing "back" can exit Mastodon.

### ISSUE THREAD

**Issue by nikhiljha** [tootsuite/mastodon#9972] opened 2019-02-04 23:41 UTC
### Expected behaviour

Using buttons in the Mastodon UI shouldn't be able to take me outside of Mastodon.

### Actual behaviour

GIF > https://i.imgur.com/uQOarLn.gifv
(For some reason GitHub doesn't let me show gifv, so here we are.)

I go to the website I was previously on.

### Steps to reproduce the problem

0. Have slow computer, go to some website.
1. Open Mastodon in the same tab
2. Click "Local Timeline"
3. Click back twice really fast.
4. You are magically taken to the page you visited in step 0.

### Specifications

Mastodon v2.7.1 on [Fosstodon](https://fosstodon.org/about)
MacOS Safari 12.0.2 (14606.3.4)

**Comment by kyefox** [comment] 2019-02-09 23:12
Seeing it in Chrome 71.0.3578.98 64 bit on Windows 10, also on Mastodon 2.7.1.

**Comment by Gargron** [comment] 2019-08-09 18:39
Duplicate of #946

**Closed by Gargron** 2019-08-09 18:39 UTC
Labels: bug
