### ISSUE TITLE
API: searching for a "direct" toot gives a 50x error page instead of a json error

### ISSUE THREAD

**Issue by Kimik0** [tootsuite/mastodon#3461] opened 2017-05-30 23:13 UTC
I was just testing some API stuff, and tried looking up one of my own toots through the `search?q=<toot url>` endpoint. Because I wasn't signed in and that toot was a "direct" toot, I expected to get an error back. Instead I got a "500 Internal Server Error" page. While debugging my error handling a bit more, I also got a "503 Service Unavailable" page at one point, but I'm not sure what I did different that time.

I think searching by url for toots that are not "public" or "unlisted" should return a proper json error if the client hasn't authorized. I can't tell if it happens for authorized use too (i.e. the user isn't a follower or mentioned), but maybe check that too.
* * * *
- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by unarist** [comment] 2017-06-01 04:56
I've confirmed this bug on 1.4.1 and probably since #2812.

@mjankowski It seems to fail when FetchAtomService returns `nil` due to non 200 response from `tooturl`, but I don't know which should be fixed FetchRemoteResourceService or FetchAtomService. Can you take a look?

**Comment by mjankowski** [comment] 2017-06-01 14:45
Can you provide a little more detail on how to reproduce? Maybe a link to an API request which you think is returning an incorrect response?

**Comment by unarist** [comment] 2017-06-01 14:59
For example, https://mstdn.maud.io/@unarist/2346775 is a "direct" toot. So you can't see this anyway.

Passing this URL to search API returns empty response on 1.3.3.
https://mastodon.cloud/api/v1/search?q=https://mstdn.maud.io/@unarist/2346775

However, it returns 500 Internal Server Error since 1.4.1.
https://mastodon.social/api/v1/search?q=https://mstdn.maud.io/@unarist/2346775

**Closed** 2017-06-06 14:44 UTC
