### ISSUE TITLE
[Feature] Back-Federate - sync users with historical data

### ISSUE THREAD

**Issue by ashleyhull-versent** [tootsuite/mastodon#8331] opened 2018-08-20 23:36 UTC
Hey hey,
I've got a new instance and started getting followed by a bunch of people - and when I click on their account. It's empty. (example below)

Have I misconfigured something or is this by design - If not, could I have the ability as an admin or moderator or even user to "pull" the history of somebody to get access to their past toots on my instance.

Some of the federated users I follow have toots and some dont.. almost none of them have follows/followers tho

![image](https://user-images.githubusercontent.com/17537000/44372023-5bf5ab80-a525-11e8-95bb-7bba63864a2f.png)

**Comment by nightpool** [comment] 2018-08-20 23:41
duplicate of #34

**Closed by nightpool** 2018-08-20 23:41 UTC
