### ISSUE TITLE
Bug: Local only hashtags seems to leak toots

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#13841] opened 2020-05-25 07:42 UTC
<img width="421" alt="image" src="https://user-images.githubusercontent.com/17537000/82790058-f8d53d80-9e9d-11ea-9efa-0af05ae4b88b.png">

### Expected behaviour

Only local toots

### Actual behaviour

VERY rarely local and remote toots

### Steps to reproduce the problem

no idea.

### Specifications
3.1.4

**Comment by shleeable** [comment] 2020-05-28 01:46
<img width="423" alt="image" src="https://user-images.githubusercontent.com/17537000/83089077-ff46fd80-a0c7-11ea-8733-c7d0c75fbe7f.png">

ok.. it seems to replicated by dropping the websocket. it spits out a recent toot.

**Comment by ThibG** [comment] 2020-05-28 13:20
I am unable to reproduce this, but something similar was fixed a few days ago. Is your server up to date?

**Comment by shleeable** [comment] 2020-05-31 09:37
I don't run master. I'm always on stable.

**Comment by ThibG** [comment] 2020-05-31 13:08
Fixed by #13827 then.

**Closed by ThibG** 2020-05-31 13:08 UTC
