### ISSUE TITLE
tootctl media remove-orphans throws 'NoMethodError"

### ISSUE THREAD

**Issue by splacat** [tootsuite/mastodon#13529] opened 2020-04-21 19:48 UTC
Running RAILS_ENV="production" bin/tootctl media remove-orphans throws 'NoMethodError"

### Expected behaviour

Removing orphans without errors.

No errors.

### Actual behaviour

`method_missing': undefined method `datum' 

/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.2/lib/active_model/attribute_methods.rb:430:in `method_missing': undefined method `datum' for #<Import:0x0000000006cdb1c0> (NoMethodError)
Did you mean?  data

### Specifications

git status -> HEAD separat a v3.1.3

**Comment by Gargron** [comment] 2020-04-27 22:24
Duplicate of #13425

**Closed by Gargron** 2020-04-27 22:24 UTC
