### ISSUE TITLE
Inaccurate number of followers

### ISSUE THREAD

**Issue by ismirth** [tootsuite/mastodon#11455] opened 2019-07-31 19:09 UTC
Number of followers indicated as 7 regardless of how many followers someone has. Currently my profile has over 40 followers. I have checked this across multiple phone apps and on the web and the number seven is consistent. Appears to be a back-end problem.

Since you need to have a minimum of 10 followers to show up on the public server list... this might be kicking a lot of people off of that?

I would expect that the number of followers indicated would be accurate based on the number a followers you actually have.

### Steps to reproduce the problem

I have been told by the admin that I contacted that other people have submitted this complaint to them as well but a ticket have not yet been created. I'm not sure how endemic this issue is. Please feel free to look at my profile @todon.nl@bells to see that I have over 40 followers and that the number is only showing up at 7.

### Specifications
I am on Android, and have downloaded different apps to try and it is broken across all of them... And through the browser interface.

**Comment by jeroenpraat** [comment] 2019-08-04 20:39
I found a difference between the number reported on the users profile and on the users account page in the admin interface (see screenshot below).

![Schermafdruk van 2019-08-04 22-25-38](https://user-images.githubusercontent.com/41594439/62428917-f257b880-b707-11e9-9ba8-eefd009624b7.png)
![Schermafdruk van 2019-08-04 22-25-51](https://user-images.githubusercontent.com/41594439/62428916-f257b880-b707-11e9-8396-d637dd595898.png)

This was also reported by https://todon.nl/@lazarski and https://todon.nl/@agaitaarino (see screenshots).

![Schermafdruk van 2019-08-04 22-27-54](https://user-images.githubusercontent.com/41594439/62428933-27fca180-b708-11e9-9513-f6bb3e0f8e75.png)
![Schermafdruk van 2019-08-04 22-28-50](https://user-images.githubusercontent.com/41594439/62428929-27640b00-b708-11e9-843f-e5618079962a.png)
![Schermafdruk van 2019-08-04 22-28-19](https://user-images.githubusercontent.com/41594439/62428930-27fca180-b708-11e9-9c59-d1e02b446793.png)
![Schermafdruk van 2019-08-04 22-28-08](https://user-images.githubusercontent.com/41594439/62428931-27fca180-b708-11e9-98ac-6c5996a90e73.png)

I was able to fix this directly in the database (account_stats table), but there are probably more users affected.

This is all happened after I suspended a user that mass followed a few accounts on Todon.nl. So I think this is a valid bug.

**Comment by Gargron** [comment] 2019-08-05 08:33
Duplicate of #11403

**Closed by Gargron** 2019-08-05 08:33 UTC
Labels: bug
