### ISSUE TITLE
Loading a toot from its URL after deleting causes it to be recreated.

### ISSUE THREAD

**Issue by trwnh** [tootsuite/mastodon#7088] opened 2018-04-09 12:41 UTC
Steps to reproduce:
1) post a toot
2) copy its direct link
3) paste the direct link into a new tab and enter
4) delete the toot from the webapp
5) refresh the tab with the pasted direct link

Expected behavior: the toot should not be found.

Actual behavior: the toot loads fine, and upon refreshing my webapp, the toot reappears on my home timeline and on my profile.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nynhex** [comment] 2018-04-09 13:11
This is most likely a background/service worker causing some lag on the instance.  I'm sure @Gargron can confirm, but I've seen this happen in testing on my instance when I was running into performance issues and not enough threads for workers under a stress test

**Comment by wxcafe** [comment] 2018-04-09 15:43
Yes, the service worker was probably busy deleting it from the DB, but it removed it from the web UI immediately. Not a bug, closing

**Closed by wxcafe** 2018-04-09 15:43 UTC
