### ISSUE TITLE
Username starting with _

### ISSUE THREAD

**Issue by mabe-at** [tootsuite/mastodon#12150] opened 2019-10-11 19:57 UTC
I am running a mastodon instance ...
and "suddenly" (probably some versions ago) my username, which is starting with an underscoe ("_mabe") is "kind of" invalid.

My username was valid, when i have started running my mastodon instance.

What to do?

**Comment by ThibG** [comment] 2019-10-12 08:36
What do you mean by “kind of” invalid?
As far as I know, it should still be valid.

**Comment by mabe-at** [comment] 2019-10-12 08:40
The profile page returns an error.
https://mabe.space/@_mabe

**Comment by ThibG** [comment] 2019-10-12 10:27
Weird. I do not think this is related to the username, as I just created a test account `_bob` which works just fine.

Can you run the following query in `bundle exec rails c`?

```
Account.where(username: '_mabe').pluck(:domain, :uri, :id)
```

**Comment by mabe-at** [comment] 2019-10-12 17:32
This is the result.

```
irb(main):001:0> Account.where(username: '_mabe').pluck(:domain, :uri, :id)
=> [[nil, "", 3]]
```

**Comment by ThibG** [comment] 2019-10-12 17:35
hm… `Account.find(3).suspended_at` maybe?

**Comment by mabe-at** [comment] 2019-10-12 17:36
i```
rb(main):002:0> Account.find(3).suspended_at 
=> nil
```

**Comment by ThibG** [comment] 2019-10-12 18:02
it keeps getting weirder… what does `Account.find_local('_mabe')` return?

**Comment by mabe-at** [comment] 2019-10-12 18:12
```
irb(main):011:0> Account.find_local('_mabe')
=> nil
```

**Comment by ThibG** [comment] 2019-10-12 18:17
Thanks… what about the followings?

`Account.where(username: '_mabe').order(id: :asc).take`
`Account.unscoped.where(username: '_mabe').order(id: :asc).take`
`Account.where(Account.arel_table[:username].lower.eq '_mabe'.to_s.downcase).order(id: :asc).take`
`Account.unscoped.where(Account.arel_table[:username].lower.eq '_mabe'.to_s.downcase).order(id: :asc).take`

**Comment by nightpool** [comment] 2019-10-12 18:22
Broken postgres index? collation issue?

**Comment by mabe-at** [comment] 2019-10-12 18:22
I have registered a new user with username '_test' and this one worked.
Then I have made a db backup and just did this.

```
Account.update(3, :username => 'mabe')
Account.update(3, :username => '_mabe')
```
And now the profile page is working again and also the "admin/settings" can be saved.

**Comment by nightpool** [comment] 2019-10-12 18:23
Yeah, this sounds like postgres index corruption

**Comment by ThibG** [comment] 2019-10-12 18:24
ok I'll assume this is indeed the case and close this issue as not a bug within Mastodon…

**Closed by ThibG** 2019-10-12 18:24 UTC

**Comment by mabe-at** [comment] 2019-10-12 18:25
But thank you for your help!

**Comment by nightpool** [comment] 2019-10-12 18:31
@mabe-at I would suggest running amcheck and rebuilding any indexes that it thinks might be corrupted
