### ISSUE TITLE
Large delay on some toots

### ISSUE THREAD

**Issue by colomar** [tootsuite/mastodon#1523] opened 2017-04-11 09:15 UTC
As you can see on the screenshot, some toots from Jens from 10 hours ago only showed up in my timeline _after_ much newer ones from others. All the people seen in the timeline are on other instances.
It's also not just the sorting that's messed up, I actually could not see the toots before.
![screen shot 2017-04-11 at 10 56 56](https://cloud.githubusercontent.com/assets/11637533/24901547/ba1b0eea-1ea7-11e7-8912-e02495672463.png)
I am on social.tchncs.de, Jens is on mastodon.cloud.

**Comment by wxcafe** [comment] 2017-04-11 09:21
This is because the sidekiq queues of one of the servers are full. Talk to your admin so they check if it theirs, or they can talk to the admin of the remote instance. Since this is not a bug in mastodon the software, I'm closing this issue

**Closed by wxcafe** 2017-04-11 09:21 UTC
Labels: invalid
