### ISSUE TITLE
Encoding::UndefinedConversionError since today's upgrade.

### ISSUE THREAD

**Issue by Aldarone** [tootsuite/mastodon#1136] opened 2017-04-07 07:58 UTC
Hello I am the admin of witches.town and I updated my instance this morning. However, the toots aren't federating anymore, my users can't follow or boost anyone and I'm seeing this error all over the logs :

```
web_1        | 2017-04-07T07:54:55.285964614Z [54648852-d910-4b17-85b0-eeb750093bd8] method=POST path=/api/v1/statuses/120331/favourite format=html controller=Api::V1::StatusesController action=favourite status=500 error='Encoding::UndefinedConversionError: "\xC3" from ASCII-8BIT to UTF-8' duration=66.97 view=0.00 db=11.48
web_1        | 2017-04-07T07:54:55.287485626Z [54648852-d910-4b17-85b0-eeb750093bd8]   
web_1        | 2017-04-07T07:54:55.287554509Z [54648852-d910-4b17-85b0-eeb750093bd8] Encoding::UndefinedConversionError ("\xC3" from ASCII-8BIT to UTF-8):
web_1        | 2017-04-07T07:54:55.287708976Z [54648852-d910-4b17-85b0-eeb750093bd8]   
web_1        | 2017-04-07T07:54:55.287748374Z [54648852-d910-4b17-85b0-eeb750093bd8] app/services/favourite_service.rb:16:in `call'
web_1        | 2017-04-07T07:54:55.287866350Z [54648852-d910-4b17-85b0-eeb750093bd8] app/controllers/api/v1/statuses_controller.rb:95:in `favourite'
```
Do you know how I can fix this ?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Aldarone** [comment] 2017-04-07 08:10
It seems the same issue affect mastodon.social too. I'm reverting 6d6a429af8fe4bd92ed497f401676353fdc603e0 to see if it comes from here.

**Comment by Aldarone** [comment] 2017-04-07 08:21
Yep, that was it.

**Comment by nolanlawson** [comment] 2017-04-07 08:30
Question: is now a good time to start thinking about [semantic versioning](http://semver.org/) for Mastodon? Pulling from master seems very risky, if for no other reason than that various instances could be on various commits of the codebase, making it hard to track down bugs.

Then again, setting up SemVer inherently creates extra maintenance burden for @Gargron and so maybe it wouldn't be possible without more committers. Let us know what we can do to help! 😊

(Context: I maintain https://toot.cafe/)

**Comment by mkody** [comment] 2017-04-07 08:49
I can confirm that `Encoding::UndefinedConversionError ("\xC3" from ASCII-8BIT to UTF-8)` issue was happening on my instance as well.  
But I was able to boost and follow users.

**Comment by hishamhm** [comment] 2017-04-07 08:56
Semantic versioning can be used two ways: 0.x for early stage development or x.y.z for stable development. The x.y.z model is indeed extra burden because of compatibility guarantees, etc. But at this point, with fast-paced updates where everyone is encouraged to just keep upgrading to the latest one, the 0.x model seems more appropriate.

However, [1.0 was tagged already](https://github.com/tootsuite/mastodon/releases). In any case, tagging known-stable commits as "releases" (even if daily and not following semantic versioning: 1.2017.04.07.1 perhaps?) could help instance admins to make it easier to know (a) if they're running the same version of the code and (b) which of two instances are more up-to-date.

**Comment by Gargron** [comment] 2017-04-07 09:12
What I *wanted* was to make semi-big tagged releases (1.0, 1.1, 1.2 etc) and have instance admins pin their installation to a tag. But 1.1 is so outdated now I can understand why people want latest master. Maybe we need a "stable" branch,

**Comment by Gargron** [comment] 2017-04-07 09:19
Anyway, I have pushed a fix for this, it's live on .social and seems to be working. Please confirm and if it's fixed for you also, close issue!

**Comment by ggramaize** [comment] 2017-04-07 09:40
I confirm the fix you pushed solved the issue on my instance. 
The federation jobs now run successfully on sidekiq.

**Comment by Sigafoos** [comment] 2017-04-07 11:03
Shouldn't `master` be the stable branch? Then you can have a `develop` branch that gets code merged in once it's been tested/verified. And instances can run off the bleeding edge code if they want the newest features/to help test.

**Closed** 2017-04-07 12:34 UTC

**Comment by nolanlawson** [comment] 2017-04-07 20:51
`master`/`stable` makes sense to me. Sometimes it's useful to eagerly accept PRs to `master`, test them in dev, and then push to `stable`.

OTOH having some kind of versioning shorthand would be useful for chatting about them on Mastodon itself, e.g. `stable-1.1.0`, `stable-2.0.1`, `stable-3.1.1` or something like that. Maybe a major version bump could indicate that you need to do a database migration or a `bundle install`, a minor version would be a feature add, and a patch would be a bugfix.

FWIW I am tooting about this with the #MastodonAdmins tag.
