### ISSUE TITLE
Filtered languages not always respected

### ISSUE THREAD

**Issue by apricot13** [tootsuite/mastodon#4891] opened 2017-09-11 07:57 UTC
I only have english enabled in my settings but I'm seeing other languages on my local and federated timelines (though I'm not sure if the language filtering should apply on federated or not but I thought I would mention it anyway). This is on mastodon.social if relevant.

<img width="393" alt="screen shot 2017-09-11 at 8 47 20 am" src="https://user-images.githubusercontent.com/649148/30263970-e5bb1352-96ce-11e7-8433-32587e8c4fd6.png">
<img width="244" alt="screen shot 2017-09-11 at 8 47 34 am" src="https://user-images.githubusercontent.com/649148/30263969-e5b6cc5c-96ce-11e7-822e-b94c7cb5ae39.png">

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tlhall** [comment] 2017-09-13 20:34
I also see this behavior with 1.6.0rc5 and 1.4.1.

**Comment by unarist** [comment] 2017-09-14 14:59
Looks like duplicate of #3706.

**Comment by apricot13** [comment] 2017-09-14 16:35
so it is! I did search first though honest! 😅

**Closed** 2017-09-16 13:09 UTC
