### ISSUE TITLE
View feed of public toots from a specific instance

### ISSUE THREAD

**Issue by alexgleason** [tootsuite/mastodon#1481] opened 2017-04-10 21:32 UTC
Users should have the ability to view toots based on the instance they have originated from. I imagine this being similar to a hashtag view. This is valuable since instances can form tight communities or serve a specific purpose.

**Comment by R0ckweb** [comment] 2017-04-10 22:38
Duplicate of #1053 ?

**Comment by wxcafe** [comment] 2017-04-10 23:11
Yep, closing

**Closed by wxcafe** 2017-04-10 23:11 UTC
Labels: duplicate
