### ISSUE TITLE
A collection of issues I found with the new audio player

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#14276] opened 2020-07-09 17:15 UTC
Let me preface this by saying that I like the new audio player, it's pretty and I being able to show artwork. Here's some issues I found while trying it out:

- clicking in the middle of the audio player both plays/ pauses the track and opens the toot in the rightmost column, which doesn't happen with any other media type

- the seek bar is hard to notice if you don't know that it's at the very top of the player. depending on its color it might completely blend in with the background of the toot

- the audio player visualization always stuck at like 25% in the top right of the circle, even when paused or when the volume is turned all the way down. If that is intended for some reason (it shows up in all the screenshots here on github), here's me saying that it's confusing

- the visualization scales with volume, I'm not sure if that should be considered an issue but it looks a lot cooler when the volume is all the way up, so why not have it look like that for any volume > 0?

- the lines from the visualization don't meet perfectly on the right of the circle, idk if that's solvable but it's a bit irritating once you notice it

**Comment by Gargron** [comment] 2020-07-09 18:46
> clicking in the middle of the audio player both plays/ pauses the track and opens the toot in the rightmost column, which doesn't happen with any other media type

I've not been able to reproduce this, does this happen on Firefox or a different browser? It's not intended, obviously...

**Comment by ThibG** [comment] 2020-07-09 21:59
> > clicking in the middle of the audio player both plays/ pauses the track and opens the toot in the rightmost column, which doesn't happen with any other media type
> 
> I've not been able to reproduce this, does this happen on Firefox or a different browser? It's not intended, obviously...

seems like a glitch-soc issue, i'll investigate it later

**Comment by ThibG** [comment] 2020-07-10 11:11
> Let me preface this by saying that I like the new audio player, it's pretty and I being able to show artwork. Here's some issues I found while trying it out:
> 
>     * clicking in the middle of the audio player both plays/ pauses the track and opens the toot in the rightmost column, which doesn't happen with any other media type

glitch-soc bug, should be fixed now (https://github.com/glitch-soc/mastodon/pull/1379)

>     * the seek bar is hard to notice if you don't know that it's at the very top of the player. depending on its color it might completely blend in with the background of the toot

I do agree, but also once you know about it, it 

>     * the audio player visualization always stuck at like 25% in the top right of the circle, even when paused or when the volume is turned all the way down. If that is intended for some reason (it shows up in all the screenshots here on github), here's me saying that it's confusing

That seem intended (that's the whole `_getSize` thing), not sure what was the reasoning for that? Maybe to not make the visualization look “flat” when it hasn't started yet? Or is that leftover code from previous iterations?

>     * the visualization scales with volume, I'm not sure if that should be considered an issue but it looks a lot cooler when the volume is all the way up, so why not have it look like that for any volume > 0?

That seems to be how the Web Audio API works, I wonder if we can do it differently…

>     * the lines from the visualization don't meet perfectly on the right of the circle, idk if that's solvable but it's a bit irritating once you notice it

The code computes a non-integer number of ticks to draw… fixing that… also, some rounding errors may be involved. I will fix that.

**Closed** 2020-07-10 11:57 UTC
