### ISSUE TITLE
Viewing reports broken in v1.3.1

### ISSUE THREAD

**Issue by staticsafe** [tootsuite/mastodon#2551] opened 2017-04-27 23:07 UTC
Clicking through to view an individual report is broken.

Error:

Apr 27 23:04:44 tenforward.social bundle[3099]: [ef60e6e4-0b35-4a1b-8af4-e989ff8576dd] ActionView::Template::Error (Missing partial authorize_follow/_card with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml, :rabl]}. Searched in:
Apr 27 23:04:44 tenforward.social bundle[3099]:   * "/home/mastodon/live/app/views"
Apr 27 23:04:44 tenforward.social bundle[3099]:   * "/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.0.1/app/views"
Apr 27 23:04:44 tenforward.social bundle[3099]:   * "/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/doorkeeper-4.2.5/app/views"
Apr 27 23:04:44 tenforward.social bundle[3099]:   * "/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/devise-4.2.1/app/views"
Apr 27 23:04:44 tenforward.social bundle[3099]:   * "/home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/pghero-1.6.4/app/views"
Apr 27 23:04:44 tenforward.social bundle[3099]: ):
Apr 27 23:04:44 tenforward.social bundle[3099]: [ef60e6e4-0b35-4a1b-8af4-e989ff8576dd]     4: .report-accounts
Apr 27 23:04:44 tenforward.social bundle[3099]: [ef60e6e4-0b35-4a1b-8af4-e989ff8576dd]     5:   .report-accounts__item
Apr 27 23:04:44 tenforward.social bundle[3099]: [ef60e6e4-0b35-4a1b-8af4-e989ff8576dd]     6:     %strong= t('admin.reports.reported_account')
Apr 27 23:04:44 tenforward.social bundle[3099]: [ef60e6e4-0b35-4a1b-8af4-e989ff8576dd]     7:     = render partial: 'authorize_follow/card', locals: { account: @report.target_account }
Apr 27 23:04:44 tenforward.social bundle[3099]: [ef60e6e4-0b35-4a1b-8af4-e989ff8576dd]     8:     = render partial: 'admin/accounts/card', locals: { account: @report.target_account }
Apr 27 23:04:44 tenforward.social bundle[3099]: [ef60e6e4-0b35-4a1b-8af4-e989ff8576dd]     9:   .report-accounts__item
Apr 27 23:04:44 tenforward.social bundle[3099]: [ef60e6e4-0b35-4a1b-8af4-e989ff8576dd]    10:     %strong= t('admin.reports.reported_by')

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment] 2017-04-27 23:10
deplecared with #2545 ?

**Comment by nightpool** [comment] 2017-04-27 23:11
Yes, this looks to be the same root cause as #2545, although YMMV on whether one would consider  it the same bug or not

**Comment by ykzts** [comment] 2017-04-27 23:31
Even if you merge #2546 , do not working?

**Comment by mjankowski** [comment] 2017-04-28 00:57
Fixed in https://github.com/tootsuite/mastodon/commit/074e9612a20fda089eee6a1ac80aefb668e54f59

**Closed by mjankowski** 2017-04-28 00:57 UTC
Labels: bug
