### ISSUE TITLE
After bulk-removing followers, the count shows 0

### ISSUE THREAD

**Issue by michel-slm** [tootsuite/mastodon#11516] opened 2019-08-07 17:24 UTC
After getting 2000+ bot followers from the same instance, I removed all followers from that domain using https://floss.social/relationships?relationship=followed_by

This resets my follower count to 0: https://floss.social/@michel_slm
![Screenshot from 2019-08-07 19-25-31](https://user-images.githubusercontent.com/85603/62643870-371e6200-b949-11e9-918f-71586c7566a1.png)

From the [discussion](https://floss.social/web/statuses/102576736666999633) it appears that once the follower list changes again the number is recalculated, but bulk-removing should also update this count properly.

Mastodon instance version: 2.9.2

**Comment by michel-slm** [comment] 2019-08-08 04:32
There are two new (legitimate) followers on my account, and unfortunately instead of showing the correct total count, now it claims I have two followers.

**Comment by Phroneris** [comment] 2019-08-10 22:22
Same on two servers (aka instances, both v2.9.2 vanilla) where I live.

Affected:
- The number of followers becomes zero
- A victim user is rejected automatically from the directory maybe because of few followers

Not affected (the same as before suspending a spam follower):
- The list of followers show correct members
- Long-following users can see the victim user at their home timeline without re-following

**Comment by angristan** [comment] 2019-08-11 09:50
Duplicate of #1403

**Comment by Phroneris** [comment] 2019-08-11 11:01
You mean #11403

**Comment by Gargron** [comment] 2019-08-11 11:15
Duplicate of #11403, indeed

**Closed by Gargron** 2019-08-11 11:15 UTC
Labels: bug

**Comment by angristan** [comment] 2019-08-11 11:25
Yes, sorry 😅
