### ISSUE TITLE
Edit profile image pickers need cleanup

### ISSUE THREAD

**Issue by CallKathy-1** [tootsuite/mastodon#1304] opened 2017-04-08 23:44 UTC
When editting profile, image pickers imply none has been set up. 
1) Profile image picker implies none has been set during edit - when actually it has been set
2) Header image image picker implies none has been set during edit - when actually it has been set
See screenshot - Mine are both set, but don't show in edit profile
https://www.screencast.com/t/hjye79rcU1ZK

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment] 2017-04-11 12:10
Additionally, there is no option to remove the set pictures and use the defaults.

**Comment by Gargron** [comment] 2017-06-29 19:18
Duplicate of #3220

**Closed by Gargron** 2017-06-29 19:18 UTC
Labels: enhancement, ui
