### ISSUE TITLE
Feature request: Boost with a CW

### ISSUE THREAD

**Issue by codl** [tootsuite/mastodon#2719] opened 2017-05-02 16:40 UTC
Different communities tag different things, it would be useful to have the ability to add a CW to a post while boosting it, when youd like to share it but it isn't appropriately tagged

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JulesTheFairy** [comment] 2017-05-02 22:00
The possibility to tag boosts with CWs would be appreciated by many people I know.

If you are on an instance with stricter rules for CWs, you can't boost a lot of things because of the missing CW.

At the moment you have to copy the link to the toot into a new toot and add a CW, which is pretty annoying.

**Comment by MadDogWulf** [comment] 2017-05-05 17:08
I worry about this somewhat, with quote tweeting from Twitter and Tumblr being intentionally being missing because it makes it too easy to dogpile on a user. And if this is rushed, it might come out with a version that makes it easier for someone to repost something and make it seem like the original poster said something they didn't.
Letting users impersonate one another like that would be unwise.

I agree this feature is necessary, with me wanting to boost flashing images before but unable to because they ain't marked as sensitive. It just needs to be done RIGHT.

From one minute of thinking about it, I ain't saying we gotta do this way it's just what's come to mind.
You make it clear and distinct from the original CW System - You make the text "Wulf boosted and added a content warning" and make the Show More button look different. This is unique to the boost and is not automatically added to any new boosts from this newly CW'd version of the post.

Then, when someone adds a new CW to a post they can only pick from a list of preexisting tags, like Politics, Pornographic, Lewd, Discourse, Money, etc. The ones that come default should be treated like a language file so it can be translated. Different instances can add more but the ones in main branch should translate.

 #1010 solves the problem of how to hide images, anything with CW hides images automatically. This would be a 2-1 punch to one of Mastodon's dumbest changes, the NSFW button explains nothing about functionality, doesn't translate into other languages, and uses very problematic wording such as it is. Much, much worse than "mark image as sensitive"

**Comment by Gargron** [comment] 2017-07-02 14:24
(Essentially) duplicate of #309

**Closed by Gargron** 2017-07-02 14:24 UTC
Labels: enhancement
