### ISSUE TITLE
Add option to exclude replies from Atom feed

### ISSUE THREAD

**Issue by sybrenstuvel** [tootsuite/mastodon#2060] opened 2017-04-18 06:49 UTC
I'm currently using [If-This-Then-That](https://ifttt.com/) (IFTTT) to forward my Mastodon toots to Twitter and Facebook. IFTTT uses the Mastodon Atom feed to get posts to forward. Currently replies to other Mastodon users are also listed in that feed, which results in only my half of a conversation being shown on Twitter/Facebook. I'd be very happy if I could let Mastodon exclude such messages from the Atom feed, and only include non-replies.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment] 2017-04-18 13:06
Can you add any xml-level filters at the IFTTT level?

I believe that reply statuses will have:

        <activity:object-type>http://activitystrea.ms/schema/1.0/comment</activity:object-type>

whereas new statuses will have:

        <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>

**Comment by sybrenstuvel** [comment] 2017-04-18 13:39
That's useful info, thanks.

I tried passing "http://activitystrea.ms/schema/1.0/note" as "keyword" IFTTT responds to, but it doesn't work. My guess is that they only match on content, and not on other tags :(

**Comment by bmann** [comment] 2017-04-19 04:24
This isn't possible with the simplicity of IFTTT RSS/Atom keyword matching.

Someone writing a direct webhook to the IFTTT maker channel with the Mastodon API could have more control over this https://ifttt.com/maker_webhooks. 

I would close this here and continue the discussion in the documentation repo, we are already talking IFTTT there --> https://github.com/tootsuite/documentation/issues/77

**Closed** 2017-04-19 08:38 UTC
Labels: help wanted, question

**Comment by rtvb** [comment] 2017-04-21 04:00
The issue is closed but I feel that it is a genuine request for change. There should be a user feed that excludes replies and boosts so only contain new content.

**Comment by ViViDboarder** [comment] 2017-06-19 17:07
I agree. If by URL one could filter by adding `?object-type=note` or something similar would be quite useful.

Tried to dig through the source, but I'm not super familiar with Rails and can't figure out where the proper code path is.

**Comment by thiagomgd** [comment] 2017-09-17 23:16
I agree. I want to have a feed with only my posts, which aren't replies.

**Comment by husimo** [comment] 2017-11-02 12:31
I agree to. I would be like to be able to hide boosts and replies. thank you

**Comment by Drulac** [comment] 2018-04-02 06:43
I could be really useful
