### ISSUE TITLE
Maximum image attachment size is not configurable

### ISSUE THREAD

**Issue by jmahmood** [tootsuite/mastodon#2252] opened 2017-04-21 08:30 UTC
Hi,

I noticed that the image size used for the media API is not configurable.  

This is set in ./models/media_attachment.rb, specifically here:

  IMAGE_STYLES = { original: '1280x1280>', small: '400x400>' }.freeze

I am making a screenshot generator bot for my own mastodon instance and I often get much larger image files than 1280 x 1280.  Moreover, the term "original" for a resized file is a bit confusing.

I understand there are several work arounds I could do;  increase the size in the source code, or upload directly to a separate location.  

Is this for a specific reason ("We do not want you using the API to store the original files on the Mastodon server") or is it something that may be changed in the future to allow us to configure the file more effectively?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment] 2017-04-21 08:36
couldn't you just change those settings?

**Comment by jmahmood** [comment] 2017-04-21 14:58
As mentioned, I made changes directly in the Ruby file, which is OK for me, but shouldn't these sorts of items be exposed in the administration menu?  

Moreover, 1280 x 1280 is ~1.6 megapixels; it's tiny in a world where even bad phones have 8 megapixel cameras. 

Finally, the image being modified when it is marked in the API as the "Original" file is not the behavior that I would expect.  

I am willing to believe it is a good reason, but I couldn't find it while going through the git history.  Maybe the JavaScript is primed for a certain file size which is why we need to keep it @ that size, or maybe the true original file should be placed directly into a directory that is exposed by Nginx so as to skip the ruby application server entirely.  (I think that is already happening, but it's all I could think of)

**Comment by ashfurrow** [comment] 2017-04-23 20:56
I took a look at this and the original file isn't being saved to S3 as I'd expect to. I imagine the original reason was to save on storage space, but there's [also a cap on file sizes](https://github.com/tootsuite/mastodon/blob/ef5937da1ff2d6caca244439dd9b9b9ed85fb278/app/models/media_attachment.rb#L32) so I'm not sure it's prudent to discard the original.

We could keep the original, replace `original` with something like `large`, and then create a link from the media modal to the original. Does that make sense? I can start working on it if that's the direction we'd like to move in. 

I think with that solution we wouldn't even need the configurable option, since we'd keep the original. Thoughts?

**Comment by Gargron** [comment] 2017-04-24 00:57
The settings are not configurable because we want to ensure that in most cases attachments on one instance can show up fine on another. If one instance allows 20MB uploads while another only 1MB, the experience will be broken. Current setting is a sensible default that works for most cases, and when you need more, I suggest using external hosting (YouTube, Flickr, etc - specialized hosting)

**Comment by ashfurrow** [comment] 2017-04-24 06:56
Gotcha, thanks for following up @Gargron.

@jmahmood it sounds like this is intended behaviour that's not going to be changed. Thanks for opening the issue – I'm sure the answer will be helpful to others. Going to close this issue; if things aren't answered to your satisfaction, please feel free to re-open. Thanks!

**Closed by ashfurrow** 2017-04-24 06:56 UTC
Labels: api, enhancement, priority - medium

**Comment by sftblw** [comment] 2018-04-08 11:51
I think 1280 x 1280 is too small for 8mb limitation... Could it be enlarged to 4096 x 4096 and still limit file size by 8mb as same as usual?

**Comment by jeroenpraat** [comment] 2018-04-21 14:08
@Gargron I agree with your explanation and people can upload it to external sources, but than it would be desirable to implement the following feature request for jpg+png images as well:

https://github.com/tootsuite/mastodon/issues/7031

**Comment by glubsy** [comment] 2018-08-18 13:08
>The settings are not configurable because we want to ensure that in most cases attachments on one instance can show up fine on another

@Gargron then why not allow access from other instances to the resized file, but when the user really needs the original file size, let him access that file somehow, either by tweaking the URL to point to the original file (if stored on its instances) or even better (but that would requite some work) place a button that points to that original file's URL.

**Comment by PandorasFox** [comment] 2018-08-31 20:25
> The settings are not configurable because we want to ensure that in most cases attachments on one instance can show up fine on another. If one instance allows 20MB uploads while another only 1MB, the experience will be broken. Current setting is a sensible default that works for most cases, and when you need more, I suggest using external hosting (YouTube, Flickr, etc - specialized hosting)

Wouldn't the ideal situation then be to standardize upon some dimensions/sizes for federation, but allow instances to do whatever with the 'original' file size limit? ie photography or art focused instances would definitely want originals intact.

**Comment by glubsy** [comment] 2018-08-31 22:48
> but allow instances to do whatever with the 'original' file size limit? ie photography or art focused instances would definitely want originals intact.

Absolutely right.

Pleroma doesn't limit file sizes like Mastodon does, but since both Mastodon and Pleroma instances can be accessed via the Fediverse, the original files will only be retained by Pleroma instances. 

I have looked around the Mastodon source code and couldn't clearly determine how to enforce original file retention (and delivery) on Mastodon, but I have a feeling it's possible somehow...

As it stands right now, I'd rather set up a Pleroma instance instead of a Mastodon instance for that very reason.

**Comment by ronilaukkarinen** [comment] 2022-12-06 14:09
> > The settings are not configurable because we want to ensure that in most cases attachments on one instance can show up fine on another. If one instance allows 20MB uploads while another only 1MB, the experience will be broken. Current setting is a sensible default that works for most cases, and when you need more, I suggest using external hosting (YouTube, Flickr, etc - specialized hosting)
> 
> Wouldn't the ideal situation then be to standardize upon some dimensions/sizes for federation, but allow instances to do whatever with the 'original' file size limit? ie photography or art focused instances would definitely want originals intact.
> 
> I understand the need for having some standards for media for sane federation, but I don't really see why this can't be improved.

Sorry to bump old close issue, but +1 for this. The user should not be responsible of what kind of video is going to be uploaded, the server should do the heavy lifting. Things have changed now that we have lots of non-technical people on Mastodon. If they want to upload 4K videos, the servers should compress them to a size everyone understands. This can and should be improved in some way.

**Comment by ronilaukkarinen** [comment] 2022-12-06 17:19
Just to clarify this, these ideas could work here as well:

1. [**vector-im/element-android:** Re-encode/downscale video before uploading to satisfy max upload size](https://github.com/vector-im/element-android/issues/3016)
2. [**vector-im/element-android:** Video compression crops the videos to 16:9 aspect ratio](https://github.com/vector-im/element-android/issues/5113)

**Comment by fofwisdom** [comment] 2022-12-19 14:24
If the server discards the original image, it should be able to handle the color profile properly too.
Naver, South Korea's top user portal, once used resized images of original size for all BBS and Blogs to reduce image load. This has caused a lot of confusion in society, such as obstructing the understanding of the relationship between OS, images, web browsers, and monitors, and hindering the growth of the market.

**Comment by alexbbrown** [comment] 2022-12-25 16:43
Why is this issue closed? The user of experience of getting and error when uploading a default resolution photo from an iPhone is not good.

I would expect the server to accept any image size used commonly by popular devices, and then resize internally to a size that can be shared across the network.

(Ps: I have no expectation that the original is ever saved. )
