### ISSUE TITLE
Modals are broken in Firefox

### ISSUE THREAD

**Issue by sdukhovni** [tootsuite/mastodon#5559] opened 2017-10-29 07:37 UTC
These are behaviors I've observed in Firefox ESR 52.4.0:

- Click on an image thumbnail to expand the image, then close the expanded image. Then try to delete a toot. This takes me to a completely blank page and I need to reload for the mastodon UI to reappear. The browser console shows `TypeError: n is undefined` along with a stack trace full of ReactJS internals that I can't glean anything useful from.

- Try to delete a toot, then click "cancel" in the "confirm deletion" modal. Then click on an image thumbnail. Instead of an expanded image, I see a modal box resembling the "confirm deletion" modal, but with no text except for the "cancel" button. This doesn't produce any errors in the console.

This only happens in Firefox, not in Chromium. I noticed this while playing with the "doodle" modal from a non-upstreamed branch, but I've reproduced the bug on vanilla v2.0.0 as well. It looks like after you've opened one type of modal, all later modals get replaced with that first type of modal (so if you open the delete modal first, media modals and doodle modals get replaced with messed-up delete modals; if you open the doodle modal first, delete modals and media modals get replaced with doodle modals; if you open the media modal first, later delete modals and doodle modals get replaced with a media modal so messed-up that it breaks React somehow).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment] 2017-10-29 17:12
I installed Firefox 52.0.2esr on Mac and I'm unable to reproduce using the latest master (3e9236b34374c47e01613cb715e26cde97dc65c3).

Firefox 52 is 4 versions behind the latest (54). Can you reproduce in 54 as well?

Or possibly I'm missing something in the steps to reproduce? I did:

1. In Firefox desktop, click on an image in a toot
2. Click outside the image to dismiss the modal
3. Click the "..." on a toot
4. Click "Delete"
5. Click "Delete" in the prompt

**Comment by sdukhovni** [comment] 2017-10-29 18:42
Those steps are correct (you shouldn't even make it as far as the actual delete prompt if the bug is happening). I've just checked Firefox 56 and the bug doesn't occur, so this may be an issue with Firefox rather than mastodon. Firefox ESR 52 is the newest version packaged by Debian...

**Comment by nightpool** [comment] 2017-11-09 16:38
Just ran into a user having this issue on Firefox ESR on NT 6.1

**Comment by Sylvhem** [comment] 2018-01-06 02:05
I can reproduce it with Firefox 52.5.2 ESR on an instance running Mastodon 2.1.0.

As a Firefox 52 user myself, I would like to point out that I sun into that problem quite frequently. It's not just something that happen once in a blue moon.

**Comment by Seipas** [comment] 2018-01-17 18:45
It also happens with the boost confirmation prompt instead of the delete prompt.

Reproduced with TorBrowser 7.0.11 (based on Firefox 52.5.2) on both Linux Mint and Windows 10

(it's been two month this bug annoys me at work XD)

**Comment by ProgVal** [comment] 2018-02-02 05:48
It is still happening on Mastodon v2.1.3. Any news?

**Comment by ProgVal** [comment] 2018-03-24 21:43
Fixed in v2.3.2.

**Comment by Sylvhem** [comment] 2018-03-24 23:03
I confirm. It's been fixed for all kinds of modals.

**Closed** 2018-05-17 16:42 UTC
Labels: browser compatibility, bug, priority - high, requires in depth
