### ISSUE TITLE
[Feature] Allow #hastags in CW's warnings

### ISSUE THREAD

**Issue by DelightfulAgony** [tootsuite/mastodon#6296] opened 2018-01-19 00:47 UTC
It's just a little detail, but I believe it could be cool to allow users include hastags in CW's warnings.
Not much functionality, more like a graphical/detail kind of thing, but I don't think I would be much of an issue to implement it, don't really know if it would.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment] 2018-01-19 01:24
dupe of #699

**Closed by nightpool** 2018-01-19 01:24 UTC

**Comment by nightpool** [comment] 2018-01-19 01:25
>We have attempted to make content warnings contain rich text, including mentions, links and hashtags. However, this meant that content warnings could not be copied into new toots automatically any longer. It is simpler to think of them as a plain text label on top of the actual content.
