### ISSUE TITLE
Add a NOTICE file containing every contributor

### ISSUE THREAD

**Issue by SoniEx2** [tootsuite/mastodon#6643] opened 2018-03-05 20:37 UTC
I don't know if NOTICE files are a thing in the GPL but I really hope they are. This provides a layer of protection against projects that nuke the commit history.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by foxiepaws** [comment] 2018-03-06 06:18
This is a duplicate of https://github.com/tootsuite/mastodon/issues/6629

**Comment by unarist** [comment] 2018-03-10 01:43
Now we have AUTHORS file (https://github.com/tootsuite/mastodon/pull/6685), so this has been resolved?

**Closed** 2018-03-10 02:35 UTC
