### ISSUE TITLE
In-band communications method for admins

### ISSUE THREAD

**Issue by staticsafe** [tootsuite/mastodon#2656] opened 2017-04-30 13:49 UTC
I'm filing this issue to start a discussion on the possible implemention of in-band communications method for admins.

I understand GNU Social !groups were dismissed earlier in this project's life cycle but it may be worth re-considering at this time. 

My ideal would be a group admin messaging system directly via the admin panel.

Either way, I'll present Eliza's points for why I believe this is an important feature:
[](https://mst3k.interlinked.me/users/Elizafox/updates/17766)

* external means just aren't gonna cut it, some people don't want to use it

* few people want to sign up for a dedicated admin instance 

* shouting over a fence like the current way is leading to toxic meta discourse and it's harmful to us in the long run

* an in-band federated way to communicate to admins only is DESPERATELY needed.

* admin badges might be nice

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by staticsafe** [comment] 2017-04-30 14:12
An additional suggestion from Maiyannah Bishop regarding the use of an ActivityVerb for such a feature:

https://plateia.org/notice/82170

It's the way that the software quantifies different types of content.

We have the following ActivityVerbs in postActiv:
ActivityVerb::POST:
ActivityVerb::SHARE:
ActivityVerb::FOLLOW:
ActivityVerb::FRIEND:
ActivityVerb::UNFOLLOW:
ActivityVerb::JOIN:
ActivityVerb::LEAVE:
ActivityVerb::TAG:
ActivityVerb::UNTAG:
ActivityVerb::UPDATE_PROFILE:

If you create a custom one, it will remain fairly secure (as secure as the implementation anyways) because if GS/pA doesn't recognize the activity verb it will just discard it, so servers that don't follow an established protocol here will just not mesh.  We could create one like ActivityVerb::ADMIN_MESSAGE similar to posts but would only be usable and displayed by admins.  I don't think this would be technically difficult.

**Comment by rtucker** [comment] 2017-04-30 14:14
#2657 is essentially a duplicate of this, but without the mention of !group syntax.

**Comment by fsnk** [comment] 2017-05-01 09:53
If this is added, it needs to be possible to disable. 

I do feel like this is trying to solve a "people problem" with a technological solution, looking at the first two reasons for the proposal: "external means just aren't gonna cut it, some people don't want to use it" and "few people want to sign up for a dedicated admin instance"

It's entirely possible those admins who haven't done these things don't want to do them because they don't want to be heavily involved in the meta.

Our about/more page lists an admin contact within Mastodon, and a contact email. If there's an issue with our server, people can contact us via whichever is more appropriate.

It might be nice if the about/more allowed for adding more than one admin, and a "report abuse" link in the contact column. But more than that seems unnecessary. If people wanted to be involved in the back channel discussions, they would join the existing back channels.

**Comment by msappir** [comment] 2017-05-01 10:27
As an admin who's very very interested in being involved in the meta, I can say for myself that isn't necessarily the reason external means don't cut it. I'm constantly on Mastodon on all platforms, setting up whatever needs to be set up to be on top of things on an addition media is a barrier that keeps my involvement pretty low right now.
Developing some kind of channel for admin talk isn't just about making this easier, it's also about creating a more cohesive federation by default. Opt-out would be fine, imho.

**Comment by Gargron** [comment] 2017-06-30 15:16
Essentially duplicate of #139 (admin group)

**Closed by Gargron** 2017-06-30 15:16 UTC
Labels: enhancement
