### ISSUE TITLE
add more freely configurable fields to user profile

### ISSUE THREAD

**Issue by ij0n** [tootsuite/mastodon#1997] opened 2017-04-17 12:19 UTC
This feels like Instagram, where users are severely limited what kind of data they can add to the profile, with the intention of keeping the user on the platform.

I expect from an open platform that I can add as many other social-media profiles, URLs to projects, my personal website, other social media platforms as i like, in a configurable way.

**Comment by wxcafe** [comment] 2017-04-17 15:24
duplicate of #232

**Closed by wxcafe** 2017-04-17 15:24 UTC
