### ISSUE TITLE
Hashtag subscriptions

### ISSUE THREAD

**Issue by Oreolek** [tootsuite/mastodon#1135] opened 2017-04-07 07:50 UTC
A feature request: subscribe to a hashtag. At least all the local toots, so they would be in the "Home" tab too.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment] 2017-04-07 08:44
This is a duplicate of #1096, please close this issue

**Closed** 2017-04-07 10:12 UTC
