### ISSUE TITLE
Mute only a user's boosts.

### ISSUE THREAD

**Issue by Spunkie** [tootsuite/mastodon#1268] opened 2017-04-08 15:08 UTC
It would be useful to be able to mute just the boosts of a user. 

There are some users that have a bit of a boosting addiction but when tooting they provide good content. I would like to be able to mute just their boosting spam.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment] 2017-04-21 13:08
Duplicate of #648!

**Closed** 2017-04-21 19:35 UTC
Labels: enhancement
