### ISSUE TITLE
Mastodon removes metadata and with that authorship/copyright information from images

### ISSUE THREAD

**Issue by OtherSystems** [tootsuite/mastodon#2710] opened 2017-05-02 10:13 UTC
When sharing images on mastodon, mastodon resizes the image but also strips the EXIF metadata from the image. thereby removing relevant elements of the file and remove copyright/authorship/license information of the file. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by bortzmeyer** [comment] 2017-05-02 11:32
Deleting the EXIF metadata is good for privacy: otherwise, people would unknowingly advertise their physical location, and other private information.

**Comment by nightpool** [comment] 2017-05-02 11:39
I have seen nearly no exif data on the internet that INTENTIONALLY
contained authorship information. How many digital artists know about it,
for example? Instead, you should deliberately and actively source every
artwork image you want to post. This helps foster a culture where sources
are expected, which is much more valuable then just relying on a technology
that barely applies to half of a percent of images.

**Comment by OtherSystems** [comment] 2017-05-02 12:05
Outside of that mastodon is still removing copyright data, how does this apply to commonly used meta data with fotos like camera type, lens type, shutter type etc, which is valuable for those interested in photography. This is not privacy sensitive data and is commonly used. GPS data with photos is also commonly used, but is rather privacy sensitive, but removing it, removes the option to the user to willingly share the data.

**Comment by bortzmeyer** [comment] 2017-05-02 13:36
I'm not sure that camera type, lens type, etc is not privacy-sensitive: it could be used to fingerprint a camera, and therefore an user. 

From a privacy point of view, removing "known-dangerous" metadata is risky: other metadata may be problematic as well.

**Comment by BrunoSpy** [comment] 2017-05-02 13:54
My humble point of view : Mastodon is not a photo sharing platform ans as such I do not see an issue if Mastodon strips down Exif Metadata.
Maybe an option in the future would be to allow each user to choose the behaviour (removing metadata as default).

**Comment by gordonzola** [comment] 2017-05-02 13:57
The cool feature would be to allow writing some words (let’s say, 500 chars) with the picture to describe it and put some credit to it :)
(more seriously, EXIF swiping is a great privacy feature, and we already have options to add credits)

**Comment by michipili** [comment] 2017-05-02 13:58
>  fotos like camera type, lens type, shutter type etc, which is valuable for those interested in photography

This is right but as I understand it mastodon is a generalist network. Because of this, I think that the privacy threat resulting from leaving that meta data attached to the image files outweighs the benefit of that same meta data a small subset of users could have.

Furthermore, photography enthusiasts interested in the EXIM data that has been stripped from an image can get in touch with the author of the image on a ad-hoc basis to get this data. If we want to support EXIM data communication for photography enthusiasts , we can [teach them how to share their EXIM data as text](http://stackoverflow.com/questions/26654709/extract-exif-data-as-text-using-imagemagick) – but I am confident that professional photo software can also do this.

**Comment by Madgui** [comment] 2017-05-02 14:09
Some metadata can be dangerous (I think about localization). And the fact that Mastodon promote idea like freedom, anti-censorship, user privacy, and so one ; show us that this question is relevant to the server-side code, and not only the mobile phone client.

**Comment by OtherSystems** [comment] 2017-05-02 14:10
I thought mastodon was a federated network, where admins can cater to their specific audiences and do not need to work towards one specific normalised type of user.

Suggesting people can share meta data as text or on request is I think completely missing the point of usability.

**I'd love to see an option where users can opt-out of the meta-data getting stripped, perhaps configurable per instance.** 

I do not see how micro-blogging would not include photo-sharing, mastodon and similar services definitly gets used as such.

**Comment by nono-gdv** [comment] 2017-05-02 14:10
Well, as a photographer, I intentionally leave metadata intact on my photo, and I would really like an option to tell Mastodon not to strip it. I don't care about copyright fields and I don't use any GPS-enabled camera; OTOH I can't think of any reason technical info such as f-stop or shutter speed should be removed from my files.

**Comment by keltia** [comment] 2017-05-02 14:20
The balance is not always easy to find.  I agree that Mastodon does strip most if not all info because it is meant to be a privacy-enabling platform, not just yet another OStatus instance.  As a photographer, if I want all info to be kept, I'd put the photo on my site or 500px/Flickr/whatever and link to that, much easier.

Most of the pictures I put on a social network do not need all the info and I think Mastodon is fine as it is.
-1

**Comment by Cassolotl** [comment] 2017-05-02 14:36
I vaguely remember a thing in the news a few years back saying that if someone can't find the owner of a photo they should consider it public domain. Stripping the metadata from photos surely means that it's harder to enforce your copyright and assert ownership, as a photographer.

I am against ownership and technical data being removed from photos, and I can also see why folks might want location data to be removed.

So, if it's all or nothing, a setting to toggle it on or off seems appropriate, with it defaulted to stripping the data if Mastodon is overall wanting to ensure privacy by default.

**Comment by bumblebeefr** [comment] 2017-05-02 15:12
The content of the picture itself could be used to fingerprint the user and can contain privacy sensitive user data. Should we remove picture content as well ? Oh wait... no,  we let the user chose if he wants to share it ! Maybe can we do the same with metadata and let the user chose if he wants to keep them ? :wink: 

Don't miss my point, I appreciate that by default mastodon remove automatic metadata (like location) from photos to a better privacy, but I would also appreciate having the choice to keep some metadata when I want it (like those to indicate the picture is under creative commons and not a default copyright). 

So I vote to add an option to allow users to chose if they want to strip(default) or keep metadata when they post pictures. Maybe with some message to explain why those metadata can be dangerous to privacy.

**Comment by pbeyssac** [comment] 2017-05-02 15:27
You can't unleak what has been leaked, hence it's always better for a tool or social network careful with privacy to strip as much metadata as possible. This is considered best practice on many social networks, especially dating sites.

There are specialized tools for claiming authorship of digital content, and Mastodon is not supposed or in a good position to be one of them.

**Comment by Gargron** [comment] 2017-05-02 23:09
>My humble point of view: Mastodon is not a photo sharing platform and as such I do not see an issue if Mastodon strips down EXIF metadata.

This is exactly my position. We strip metadata, we downsize originals to 1280px at most, etc. If you want to share authentic files, you should use a file sharing platform or specialized hosting e.g. youtube for videos, flickr for photos etc.

**Comment by szbalint** [comment] 2017-05-03 08:46
EXIF is just a metadata container, please separate different kinds of data when considering this subject!

EXIF can contain:

- license/author information that should not be stripped
- orientation information to indicate how the image should be displayed, this absolutely shouldn't be stripped!
- photography information like camera model, aperture, iso values etc that are probably not that interesting for a social network to keep around
- geolocation and other private data like camera serial numbers that should definitely be stripped

I think decisions should be made on the specific exif field and not on the "should we strip exif or not" level. Orientation especially is quite important for a nice user experience and has nothing to do with privacy in EXIF.

**Comment by pbeyssac** [comment] 2017-05-03 09:41
> Orientation especially is quite important for a nice user experience and has nothing to do with privacy in EXIF.

You can apply the "rotate" flag before dropping the EXIF data. The "jhead" tool has options for this, -autorot and -norot. It is lossless (uses jpegtran).

**Comment by Gargron** [comment] 2017-05-03 10:03
>orientation information to indicate how the image should be displayed, this absolutely shouldn't be stripped!

Paperclip does autorotate based on this before stripping it out

**Comment by kyzh** [comment] 2017-05-03 10:21
Provided that mastodon is not going to be specialised in photography, but instead is focus on privacy.
Provided that having the possibility to have data leak will inexorably end up with data being leaked.
Provided that some site specialise in photography exist already and have api to embeded images.

Would the solution to enable better integration with 3rd party photography sites and keep the current behaviour?

**Comment by azbulutlu** [comment] 2017-05-03 12:29
@kyzh as an artist, I'd rather still have the option to upload locally. External sites can close down, etc, and we cannot edit the posts.

as for stripping exif content, a solution could be to strip it, but allowing optional writing of title, owner, rights and description on images.That data can be embedded into relevant exif fields the image at the time of posting and also be viewed in alt, description tags etc.  (latter would be also a good accessibility feature)

**Comment by ashfurrow** [comment] 2017-05-11 21:14
It sounds like from @Gargron that this is something that works as intended on Mastodon, and isn't intended to change. I'm going to recommend closing the issue, unless anyone has objections?

**Closed** 2017-05-11 22:26 UTC
Labels: question
