### ISSUE TITLE
Ability to add more panels/tabs

### ISSUE THREAD

**Issue by geir54** [tootsuite/mastodon#351] opened 2016-12-10 11:54 UTC
I would like to be able to add more tabs like you can on tweetdeck

**Comment by swaldie** [comment] 2016-12-15 13:06
Assuming you're talking about columns (like the public timeline/notifications) column, I would say that we consolidate #310 into this since they both are effectively achieving the same goal.

**Comment by geir54** [comment] 2016-12-16 11:00
Yes that's what i meant :)

**Comment by iamale** [comment] 2017-04-06 10:17
Anybody working on this?

**Comment by sirgallifrey** [comment] 2017-04-09 13:51
+ 1 to this, very useful feat. I want to help, but need to get familiar with the project first :P

**Comment by Angristan** [comment] 2017-04-14 16:15
Good idea, we have some spare space...
![screenshot_14-04-2017_b yhjs5u4q](https://cloud.githubusercontent.com/assets/11699655/25048755/58cd619e-213e-11e7-81a4-8cfe89b6292e.png)

**Comment by ashfurrow** [comment] 2017-04-30 14:19
Thanks for opening the issue – definitely agree with your rationale. Now that https://github.com/tootsuite/mastodon/pull/2021 has been merged, the waste of larger screen space may not be as big an issue. Maybe it's time to close this, since the project UI direction has diverged since it was opened?

**Comment by fhemberger** [comment] 2017-04-30 14:28
@ashfurrow Please don't. This issue is not about wasted space.

**Comment by ashfurrow** [comment] 2017-04-30 17:52
You got it 👍

**Comment by black-puppydog** [comment] 2017-05-01 01:15
Since #1079 has been closed as a duplicate of this, I just want to make sure that the "want to *close* most tabs" use case is not forgotten here. And for comparison, here's framapiaf.org on a crappy 1366x720 screen. Not much wasted/empty space. Note that 99% of the time, I only need the timeline tab and possibly the rightmost tab for conversations.
![screenshot at 2017-05-01 03-08-59](https://cloud.githubusercontent.com/assets/189241/25569693/14ff6b7a-2e1c-11e7-8560-f7b52ba9f62f.png)

**Comment by iamale** [comment] 2017-05-01 03:46
@black-puppydog Probably we also need to _reorder_ tabs/columns then as well.

The whole set of things you can do in TweetDeck now, in other words.

**Comment by iamale** [comment] 2017-05-01 03:49
Also, multi-column layout proves way more useful when used in multi-account setting, i. e. when managing a personal and a fan project acct from one PC. Not sure if we need this now for Mastadon, though.

**Comment by spinda** [comment] 2017-05-19 22:22
I find myself wishing for this frequently in order to read the local and federated timelines side-by-side.

**Comment by Gargron** [comment] 2017-05-19 23:34
I'm roadblocked by my choice early on to use react-router. That's why there is a "context" column

**Comment by iamale** [comment] 2017-05-20 12:55
@Gargron Well, you could leave the context column as is but add the ability to add the other columns too? You can even slightly modify the route components so that they can be used as both context and standalone columns.

**Comment by Gargron** [comment] 2017-05-20 15:02
@iamale They can already be used so. The desktop view mounts the compose, home and notification components next to the context column, those are the same components that can be mounted inside the context in mobile view.

**Closed** 2017-06-03 23:39 UTC
Labels: enhancement
