### ISSUE TITLE
Swipe feature on mobile version too sensitive

### ISSUE THREAD

**Issue by ThomasLeister** [tootsuite/mastodon#4038] opened 2017-07-02 14:14 UTC
Hi,

thanks to @sorin-davidoi for the new swipe feature in Mastodon 1.4.7! I like the idea. Unfortunately this feature currently drives me crazy because I constantly change the column view unintentionally when scrolling. :-( In my opinion the trigger for a view change is way too sensitive. 

Maybe there is a way to make it less sensitive? A view change should only be triggered on long-distance swipes, but not on tiny horizontal movements. 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment] 2017-07-02 14:19
Duplicate of #4035, resolved

**Closed by Gargron** 2017-07-02 14:19 UTC
