### ISSUE TITLE
Webapp: Add a 'collapse' button for toots/posts with more than 500 characters

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/mastodon#5477] opened 2017-10-19 20:00 UTC
There are Mastodon instances that offer more than 500 characters for toots. The same with GNU Social and other software in the fediverse.

This breaks the UX in the Mastodon webapp. People have to scroll a lot to skip to the next toot. I like to suggest a button with 'collapse rest of toot' after 500 characters.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment] 2017-10-19 21:57
Duplicate of https://github.com/tootsuite/mastodon/issues/255

**Closed by nolanlawson** 2017-10-19 21:57 UTC
