### ISSUE TITLE
Limit federation

### ISSUE THREAD

**Issue by mrrcollins** [tootsuite/mastodon#1561] opened 2017-04-11 18:11 UTC
I have Mastodon set up for my school district, but I want to limit the federation of it to other K12 schools. Where do I control this?

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Fastidious** [comment] 2017-04-11 18:14
@mrrcollins I do not think it is possible.

**Comment by carlosjs23** [comment] 2017-04-11 18:31
I think, blacklisting instances published in instances.mastodon.xyz and whitelisting instances of the other K12 schools in nginx could be a trick, however not all instances are posted there.

**Comment by Fastidious** [comment] 2017-04-11 18:34
@carlosjs23 @mrrcollins alternatively, if you are going the black/whitelisting route, just setup firewalls and only allow the other schools IP through it.

**Comment by carlosjs23** [comment] 2017-04-11 18:39
@Fastidious I assumed that the instance is being exposed on the internet and not on an internal network, keeping my guess if @mrrcollins does what you mention, internet users will not be able to enter any of the instances.

If users are also expected to enter through the alleged internal network, then he can do as you mention.

In any case, more details about the network are needed.

**Comment by Fastidious** [comment] 2017-04-11 18:42
@carlosjs23 I work for a university. I think @mrrcollins only wants the schools to federate amongst each other (which, by the way, it goes against what the whole federation thing is about, but I digress).

**Comment by carlosjs23** [comment] 2017-04-11 18:47
If it is the case, I agree with you, but not in that it goes against the federation, since I see that he wants to give it a healthy and particular use.

In any case, we must stop guessing and expect clarification from him.

**Comment by mrrcollins** [comment] 2017-04-11 19:03
I'm looking at using Mastodon to teach students K-12 social media usage. As such, it would be nice to keep the server limited to only other K12 instances.

Students would then be able to follow students in other districts, without all of the "complexities" that would arise if it was totally public and federated.

Basically, black list all other instances, and then whitelist specific instances.

**Comment by expenses** [comment] 2017-04-11 23:03
@mrrcollins You can't blacklist all instances at the moment?

**Comment by Fastidious** [comment] 2017-04-11 23:52
Blacklisting instances isn’t fool proof, as instances are popping up left and right now. There is no way to keep it up. Using `iptables` (or similar) to only grant access to the other K-12 schools, and sharing the configuration with those other schools, is the only fool proof method.

**Comment by mrrcollins** [comment] 2017-04-12 00:52
@expenses : I'm new at administering Mastodon, where is the blacklist and whitelist settings?

@Fastidious : If I used a firewall (iptables), wouldn't that block clients from working?

**Comment by expenses** [comment] 2017-04-12 01:05
@mrrcollins I'm not sure, I was just being theoretical.

**Comment by mrrcollins** [comment] 2017-04-12 01:31
@expenses You had me all excited there, because that's exactly what I was hoping existed! Lol!

**Comment by Ragzouken** [comment] 2017-04-12 12:13
ask the admin at awoo.space mb - there is whitelist only

**Comment by wxcafe** [comment] 2017-04-12 17:21
The comment by @Ragzouken is the right answer. The admin at awoo.space is @vahnj@awoo.space. Closing this since the issue is not with mastodon and an answer has been supplied.

**Closed by wxcafe** 2017-04-12 17:21 UTC
