### ISSUE TITLE
Images from some other servers are cropped to 16:9 regardless of local preference

### ISSUE THREAD

**Issue by creideiki** [tootsuite/mastodon#14146] opened 2020-06-26 18:53 UTC
### Expected behaviour

When "Crop images in non-expanded toots to 16x9" is disabled, I expect to see full images in each toot in my timeline.

### Actual behaviour

Since a couple of days ago, on my account on mastodon.social, I see full images for toots posted by accounts on mastodon.social, but for toots from accounts on some other servers the images are cropped to 16:9.

Affected servers I've seen include botsin.space and social.tulsa.ok.us.

### Steps to reproduce the problem

1. Disable "Crop images in non-expanded toots to 16x9".
2. Make sure you are logged in to an account on mastodon.social.
3. View a toot from an affected server containing an image, e.g. https://mastodon.social/web/statuses/104410577796909170
4. Observe that the image is cropped to 16:9.

### Specifications

Firefox 77.0.1 on Gentoo Linux, with an account on mastodon.social.

**Comment by Sasha-Sorokin** [comment] 2020-06-28 21:36
Can reproduce, Chromium 83.0.4103.97.

The media gallery has height of `272.812px`, even in expanded view. Re-uploaded file being displayed correctly :thinking:

**Comment by creideiki** [comment] 2020-06-28 22:35
When I look at mastodon.social's view of a couple of feeds of bot accounts that post images regularly from botsin.space, I see full images up until June 25 01:14 UTC+2, but only cropped images from June 25 01:36 UTC+2 onwards. Did something happen on mastodon.social at European midnight between June 24 and 25? See e.g. (potentially NSFW, CW: drawings of sometimes lightly dressed furry characters) https://mastodon.social/web/accounts/1181888

**Comment by umonaca** [comment] 2020-06-30 12:34
### Expected behaviour

When "Crop images in non-expanded toots to 16x9" is **unchecked**, the images should always show in full size.

### Actual behaviour

Sometimes it shows pics in full size, sometimes it does not.

The ones that does not:
![image](https://user-images.githubusercontent.com/53662960/86117940-ee5e2300-ba9d-11ea-8cfd-8ffbc8b79764.png)

The ones that show in full size:
![image](https://user-images.githubusercontent.com/53662960/86117976-ff0e9900-ba9d-11ea-82e3-3f7bb4450448.png)

These two examples are in Gargron@mastodon.social's profile, showing on mastodon.social.


### Steps to reproduce the problem

On mastodon.social, **uncheck** "Crop images in non-expanded toots to 16x9". Save the settings. 

Open [Gargron's profile](https://mastodon.social/web/accounts/1), then you will see the examples as showing above.

### Specifications

mastodon.social and other servers using the master branch, as of commit ce9ae9aa50cab4de4db5c06f54f4f95d736d68c6

Browser: Firefox 78.0 and Chrome 83.0

**Comment by umonaca** [comment] 2020-06-30 12:45
I have seen this bug on our development server and I think the bug is introduced somewhere after the stable v3.1.4.
However it is hard to pin down the actual commit causing this issue because it only affects new toots with pics.
For the old toots, if one toot is rendered with 16:9, even if I switch to the old version of program, it stills renders as 16:9.
For the new toots, if I switch to the old good version of program, the new incoming toots renders correctly in full size.

So I believe it's the media meta info messed up somewhere after the stable v3.1.4. The old version processed the media meta info correctly, but the new version does not. Then for the new version, the front end react script will not be able to pick up the correct media meta, thus switching to 16:9 (https://github.com/tootsuite/mastodon/blob/ce9ae9aa50cab4de4db5c06f54f4f95d736d68c6/app/javascript/mastodon/components/media_gallery.js#L329)

**Comment by Gargron** [comment] 2020-06-30 13:16
I believe the bug has been fixed in #14133, i.e. it was down to width/height/etc of the image being removed from the `meta` hash. If the issue does not appear for posts on mastodon.social/mastodon.online that are processed today/in the future, then it's done. If you notice it re-appears on new posts, then something is still amiss.

**Comment by umonaca** [comment] 2020-06-30 13:21
I am doing a git-bisect with my development server. Pleroma seems to be causing the trouble for some commit after the stable v3.1.4. It may take a few hours before I know the reason.

**Comment by Gargron** [comment] 2020-06-30 13:22
Please keep in mind any bug fix / appearance will not be retroactive. The meta hash is written when the media attachment is processed. It's a write bug, not a read bug.

**Comment by umonaca** [comment] 2020-06-30 17:54
Yes I've been repeatedly uploading and deleting long images on pleroma to find the commit.
I found something interesting via git-bisect and manual git checkout:

I can confirm that this bug was actually **introduced** from #14133 (commit 662a49dc3f06749936cedd7349092bbe622f0bc6) and **fixed** later in commit 64aac3073340dbc92c33f5f1c6f76dcafa77a450.
So the bug only exists for pics that comes between 6/24 to the day you apply your latest change. As for today the bug is somehow fixed for new pics.

Screenshots:
![image](https://user-images.githubusercontent.com/53662960/86135797-48201680-bab9-11ea-9f9e-9259cffe1eed.png)
![image](https://user-images.githubusercontent.com/53662960/86159676-b0cabb80-bad8-11ea-97c3-c4043835bbd5.png)

**Comment by Gargron** [comment] 2020-06-30 21:31
Good to know, glad that it's fixed :)

**Closed by Gargron** 2020-06-30 21:31 UTC
