### ISSUE TITLE
Search not discoverable on mobile UI

### ISSUE THREAD

**Issue by strk** [tootsuite/mastodon#3545] opened 2017-06-04 06:40 UTC
As a new user, in the home tab I'm told: "You aren't following anyone yet. Visit the public timeline or use search to get started and meet other users."

But there is no "search" to use, that I can find.

This is from Firefox on Android. Even when requesting desktop version. Happens on mastodon.social instance.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by drcable** [comment] 2017-06-04 06:57
The search functionality refers to user search- not a general search of toots. It's at the top of the the toot tab(the little pen on the far left of the top navigation bad)

**Comment by strk** [comment] 2017-06-04 08:00
Found, thanks. Its not intuitive that you have to pretend you want to write something in order to search for users you actually want to read from

**Comment by Cassolotl** [comment] 2018-02-26 23:03
This is a duplicate of *Findability of search field on mobile layout #1206*, I think?

**Comment by renatolond** [comment] 2018-03-08 12:46
I'm seeing some of users of masto.donte complaining again about this after the last change in the mobile layout (the compose becoming a floating button). Even I spent some time looking for it the other day. It would be really nice to have this in a different place, or have it's own icon.

**Comment by Gargron** [comment] 2018-04-08 18:29
Fixed by #7072 and #7077

**Closed by Gargron** 2018-04-08 18:29 UTC
